import React, { useEffect, useState } from 'react';
import {
  ActivityIndicator, BackHandler, Modal, Platform, ScrollView,
  StyleSheet, Text, TouchableOpacity, View,
} from 'react-native';
import { router, useFocusEffect } from 'expo-router';
import { supabase, getSessionUser } from '../lib/supabase';
import { colors } from '../constants/theme';

const NAVY = '#2E5480';
const GOLD = '#C9A227';
const DISCLAIMER = 'This meal plan is generated by Maharaj as a personalised recommendation based on your family profile. It is not a substitute for professional medical or nutritional advice. Please consult a qualified nutritionist, dietician, or physician before making significant dietary changes, especially if any family member has a health condition.';

interface PlanRow {
  id: string;
  period_start: string;
  period_end: string;
  plan_json: any;
  generated_at: string;
}

function formatDate(d: string) {
  const dt = new Date(d);
  return dt.toLocaleDateString('en-GB', { day: 'numeric', month: 'short' });
}

function formatPeriod(start: string, end: string) {
  if (start === end) return formatDate(start);
  return `${formatDate(start)} – ${formatDate(end)}`;
}

const VEGGIE_KW = ['onion','tomato','potato','spinach','cabbage','carrot','pea','bean','capsicum','brinjal','okra','bhindi','gourd','methi','palak','mushroom','corn','garlic','ginger','chili','lemon','coriander','cauliflower','eggplant'];
const PROTEIN_KW = ['chicken','fish','mutton','egg','paneer','tofu','dal','lentil','chickpea','chana','rajma','kidney','moong','toor','urad','soy','prawn','shrimp','matki','moth'];
const SPICE_KW = ['turmeric','cumin','coriander powder','chili powder','garam masala','pepper','cardamom','clove','cinnamon','bay','mustard','fenugreek','hing','masala','sesame'];
const DAIRY_KW = ['milk','curd','yogurt','ghee','butter','cream','cheese','buttermilk','paneer'];

type GroceryCat = 'Vegetables' | 'Protein' | 'Spices' | 'Dairy' | 'Pantry';
function categorise(name: string): GroceryCat {
  const n = name.toLowerCase();
  if (PROTEIN_KW.some(k => n.includes(k))) return 'Protein';
  if (DAIRY_KW.some(k => n.includes(k)))   return 'Dairy';
  if (VEGGIE_KW.some(k => n.includes(k)))  return 'Vegetables';
  if (SPICE_KW.some(k => n.includes(k)))   return 'Spices';
  return 'Pantry';
}
const CAT_ORDER: GroceryCat[] = ['Vegetables', 'Protein', 'Dairy', 'Spices', 'Pantry'];

function buildGroceryFromPlan(plan_json: any): Record<GroceryCat, string[]> {
  const items: Record<string, GroceryCat> = {};
  const days = plan_json?.days ?? [];
  days.forEach((day: any) => {
    ['breakfast','lunch','dinner'].forEach(slot => {
      const slotData = day[slot];
      if (!slotData) return;
      const ingredients: string[] = slotData?.options?.[0]?.ingredients ?? [];
      ingredients.forEach((ing: string) => {
        const name = ing.replace(/^\d+[\w.]*\s*(g|kg|ml|l|tsp|tbsp|cup|cups)?\s*/i, '').trim();
        if (name && name.length > 2) items[name] = categorise(name);
      });
    });
  });
  const grouped = {} as Record<GroceryCat, string[]>;
  CAT_ORDER.forEach(cat => { grouped[cat] = []; });
  Object.entries(items).forEach(([name, cat]) => grouped[cat].push(name));
  return grouped;
}

export default function MyDownloadsModal({ visible, onClose }: { visible: boolean; onClose: () => void }) {
  const [plans, setPlans] = useState<PlanRow[]>([]);
  const [loading, setLoading] = useState(false);
  const [selectedPlan, setSelectedPlan] = useState<PlanRow | null>(null);
  const [view, setView] = useState<'table' | 'plan' | 'shopping'>('table');

  useEffect(() => {
    if (!visible) return;
    setView('table');
    setSelectedPlan(null);
    void loadPlans();
  }, [visible]);

  useEffect(() => {
    if (!visible) return;
    const onBack = () => {
      if (view === 'plan' || view === 'shopping') {
        setView('table');
        return true;
      }
      if (view === 'table') {
        onClose();
        return true;
      }
      return false;
    };
    const sub = BackHandler.addEventListener('hardwareBackPress', onBack);
    return () => sub.remove();
  }, [visible, view]);

  useEffect(() => {
    if (!visible || Platform.OS !== 'web' || typeof window === 'undefined') return;
    window.history.pushState(null, '', window.location.href);
    const onPopState = () => {
      window.history.pushState(null, '', window.location.href);
      if (view === 'plan' || view === 'shopping') {
        setView('table');
      } else {
        onClose();
      }
    };
    window.addEventListener('popstate', onPopState);
    return () => window.removeEventListener('popstate', onPopState);
  }, [visible, view]);

  async function loadPlans() {
    setLoading(true);
    try {
      const user = await getSessionUser();
      if (!user) return;
      const twoMonthsAgo = new Date();
      twoMonthsAgo.setMonth(twoMonthsAgo.getMonth() - 2);
      const { data } = await supabase
        .from('meal_plans')
        .select('id, period_start, period_end, plan_json, generated_at')
        .eq('user_id', user.id)
        .gte('generated_at', twoMonthsAgo.toISOString())
        .order('generated_at', { ascending: false })
        .limit(8);
      setPlans(data ?? []);
    } finally {
      setLoading(false);
    }
  }

  async function downloadPDF(type: 'plan' | 'shopping') {
    if (!selectedPlan) return;
    try {
      const user = await getSessionUser();
      if (!user) return;
      const { data: profile } = await supabase
        .from('profiles')
        .select('family_name, plan_summary_language')
        .eq('id', user.id)
        .maybeSingle();
      const familyName = profile?.family_name || 'Your Family';
      const pdfLang = profile?.plan_summary_language || 'en';
      const days = selectedPlan.plan_json?.days ?? [];
      const dateFrom = selectedPlan.period_start;
      const dateTo = selectedPlan.period_end;
      const postBody = type === 'shopping'
        ? JSON.stringify({ type: 'grocery', familyName, dateFrom, dateTo, content: { categories: CAT_ORDER.filter(cat => buildGroceryFromPlan(selectedPlan.plan_json)[cat]?.length > 0).map(cat => ({ name: cat, items: buildGroceryFromPlan(selectedPlan.plan_json)[cat].map(n => ({ name: n, quantity: '', unit: '' })) })) } })
        : JSON.stringify({ familyName, planData: { days }, dateFrom, dateTo, planSummaryLanguage: pdfLang });
      const response = await fetch('/api/generate-pdf', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: postBody,
      });
      const blob = await response.blob();
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `maharaj-${type}-${dateFrom}.pdf`;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(url);
    } catch {}
  }

  function renderTable() {
    return (
      <View>
        <View style={{ width: 36, height: 4, backgroundColor: 'rgba(27,58,92,0.2)', borderRadius: 2, alignSelf: 'center', marginBottom: 16 }} />
        <Text style={{ fontSize: 15, fontWeight: '700', color: NAVY, marginBottom: 4 }}>My Downloads</Text>
        <Text style={{ fontSize: 12, color: 'rgba(27,58,92,0.5)', marginBottom: 16 }}>Last 8 plans</Text>

        {loading ? (
          <ActivityIndicator color={NAVY} style={{ marginVertical: 24 }} />
        ) : plans.length === 0 ? (
          <Text style={{ fontSize: 13, color: 'rgba(27,58,92,0.5)', textAlign: 'center', paddingVertical: 24 }}>No plans found in the last 2 months.</Text>
        ) : (
          <View>
            <View style={{ flexDirection: 'row', borderBottomWidth: 0.5, borderBottomColor: 'rgba(27,58,92,0.15)', paddingBottom: 8, marginBottom: 4 }}>
              <Text style={{ flex: 2, fontSize: 12, fontWeight: '600', color: 'rgba(27,58,92,0.5)' }}>Plan period</Text>
              <Text style={{ flex: 1, fontSize: 12, fontWeight: '600', color: 'rgba(27,58,92,0.5)', textAlign: 'center' }}>Plan summary</Text>
              <Text style={{ flex: 1, fontSize: 12, fontWeight: '600', color: 'rgba(27,58,92,0.5)', textAlign: 'center' }}>Shopping list</Text>
            </View>
            {plans.map(plan => (
              <View key={plan.id} style={{ flexDirection: 'row', paddingVertical: 12, borderBottomWidth: 0.5, borderBottomColor: 'rgba(27,58,92,0.08)', alignItems: 'center' }}>
                <Text style={{ flex: 2, fontSize: 13, color: NAVY }}>{formatPeriod(plan.period_start, plan.period_end)}</Text>
                <TouchableOpacity style={{ flex: 1, alignItems: 'center' }} onPress={() => { setSelectedPlan(plan); setView('plan'); }}>
                  <Text style={{ fontSize: 12, color: NAVY, fontWeight: '600', textDecorationLine: 'underline' }}>View</Text>
                </TouchableOpacity>
                <TouchableOpacity style={{ flex: 1, alignItems: 'center' }} onPress={() => { setSelectedPlan(plan); setView('shopping'); }}>
                  <Text style={{ fontSize: 12, color: NAVY, fontWeight: '600', textDecorationLine: 'underline' }}>View</Text>
                </TouchableOpacity>
              </View>
            ))}
          </View>
        )}

        <TouchableOpacity
          style={{ borderWidth: 0.5, borderColor: 'rgba(27,58,92,0.15)', borderRadius: 10, padding: 12, alignItems: 'center', marginTop: 16 }}
          onPress={onClose}
        >
          <Text style={{ fontSize: 13, color: 'rgba(27,58,92,0.5)' }}>Close</Text>
        </TouchableOpacity>
      </View>
    );
  }

  function renderPlanView() {
    if (!selectedPlan) return null;
    const days = selectedPlan.plan_json?.days ?? [];
    return (
      <View style={{ flex: 1 }}>
        <View style={{ backgroundColor: NAVY, borderTopLeftRadius: 20, borderTopRightRadius: 20, paddingHorizontal: 16, paddingVertical: 12, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }}>
          <TouchableOpacity onPress={() => setView('table')}>
            <Text style={{ color: 'white', fontSize: 13, fontWeight: '500' }}>Back</Text>
          </TouchableOpacity>
          <Text style={{ color: 'white', fontSize: 14, fontWeight: '700' }}>Plan — {formatDate(selectedPlan.period_start)}</Text>
          <TouchableOpacity onPress={() => downloadPDF('plan')}>
            <Text style={{ color: GOLD, fontSize: 13, fontWeight: '600' }}>Download</Text>
          </TouchableOpacity>
        </View>
        <ScrollView style={{ flex: 1 }} contentContainerStyle={{ padding: 16 }}>
          <View style={{ borderWidth: 0.5, borderColor: 'rgba(27,58,92,0.15)', borderRadius: 10, overflow: 'hidden', marginBottom: 14 }}>
            <View style={{ flexDirection: 'row', backgroundColor: 'rgba(46,84,128,0.06)', paddingVertical: 8 }}>
              <Text style={{ flex: 1, paddingHorizontal: 8, fontSize: 11, fontWeight: '600', color: 'rgba(27,58,92,0.6)' }}>Day</Text>
              <Text style={{ flex: 2, paddingHorizontal: 8, fontSize: 11, fontWeight: '600', color: 'rgba(27,58,92,0.6)' }}>Breakfast</Text>
              <Text style={{ flex: 2, paddingHorizontal: 8, fontSize: 11, fontWeight: '600', color: 'rgba(27,58,92,0.6)' }}>Lunch</Text>
              <Text style={{ flex: 2, paddingHorizontal: 8, fontSize: 11, fontWeight: '600', color: 'rgba(27,58,92,0.6)' }}>Dinner</Text>
            </View>
            {days.map((day: any, i: number) => {
              const breakfast = day?.anatomy?.breakfast?.dishName || day?.breakfast?.options?.[0]?.name || '';
              const lunch = day?.anatomy?.lunch?.curry?.[0]?.dishName || day?.lunch?.options?.[0]?.name || '';
              const dinner = day?.anatomy?.dinner?.curry?.[0]?.dishName || day?.dinner?.options?.[0]?.name || '';
              return (
                <View key={i} style={{ flexDirection: 'row', paddingVertical: 10, borderTopWidth: 0.5, borderTopColor: 'rgba(27,58,92,0.08)' }}>
                  <Text style={{ flex: 1, paddingHorizontal: 8, fontSize: 12, color: NAVY, fontWeight: '600' }}>{day.dayName?.slice(0,3) || day.day?.slice(0,3)}</Text>
                  <Text style={{ flex: 2, paddingHorizontal: 8, fontSize: 11, color: 'rgba(27,58,92,0.8)' }} numberOfLines={2}>{breakfast}</Text>
                  <Text style={{ flex: 2, paddingHorizontal: 8, fontSize: 11, color: 'rgba(27,58,92,0.8)' }} numberOfLines={2}>{lunch}</Text>
                  <Text style={{ flex: 2, paddingHorizontal: 8, fontSize: 11, color: 'rgba(27,58,92,0.8)' }} numberOfLines={2}>{dinner}</Text>
                </View>
              );
            })}
          </View>
          <View style={{ backgroundColor: 'rgba(46,84,128,0.04)', borderWidth: 0.5, borderColor: 'rgba(27,58,92,0.12)', borderRadius: 10, padding: 12 }}>
            <Text style={{ fontSize: 11, color: 'rgba(27,58,92,0.55)', lineHeight: 18 }}>{DISCLAIMER}</Text>
          </View>
          <View style={{ height: 24 }} />
        </ScrollView>
      </View>
    );
  }

  function renderShoppingView() {
    if (!selectedPlan) return null;
    const grocery = buildGroceryFromPlan(selectedPlan.plan_json);
    return (
      <View style={{ flex: 1 }}>
        <View style={{ backgroundColor: NAVY, borderTopLeftRadius: 20, borderTopRightRadius: 20, paddingHorizontal: 16, paddingVertical: 12, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }}>
          <TouchableOpacity onPress={() => setView('table')}>
            <Text style={{ color: 'white', fontSize: 13, fontWeight: '500' }}>Back</Text>
          </TouchableOpacity>
          <Text style={{ color: 'white', fontSize: 14, fontWeight: '700' }}>Shopping list — {formatDate(selectedPlan.period_start)}</Text>
          <TouchableOpacity onPress={() => downloadPDF('shopping')}>
            <Text style={{ color: GOLD, fontSize: 13, fontWeight: '600' }}>Download</Text>
          </TouchableOpacity>
        </View>
        <ScrollView style={{ flex: 1 }} contentContainerStyle={{ padding: 16 }}>
          {CAT_ORDER.map(cat => {
            const items = grocery[cat];
            if (!items?.length) return null;
            return (
              <View key={cat} style={{ marginBottom: 16 }}>
                <Text style={{ fontSize: 11, fontWeight: '700', color: GOLD, letterSpacing: 0.5, marginBottom: 8 }}>{cat.toUpperCase()}</Text>
                {items.map((item, i) => (
                  <View key={i} style={{ flexDirection: 'row', justifyContent: 'space-between', paddingVertical: 6, borderBottomWidth: 0.5, borderBottomColor: 'rgba(27,58,92,0.08)' }}>
                    <Text style={{ fontSize: 13, color: NAVY }}>{item}</Text>
                  </View>
                ))}
              </View>
            );
          })}
          <View style={{ height: 24 }} />
        </ScrollView>
      </View>
    );
  }

  return (
    <Modal visible={visible} transparent animationType="slide" onRequestClose={onClose}>
      <View style={{ flex: 1, backgroundColor: 'rgba(0,0,0,0.45)', justifyContent: 'flex-end' }}>
        <View style={{ backgroundColor: 'white', borderTopLeftRadius: 20, borderTopRightRadius: 20, maxHeight: '85%', overflow: 'hidden' }}>
          {view === 'table' && (
            <ScrollView contentContainerStyle={{ padding: 20 }}>
              {renderTable()}
            </ScrollView>
          )}
          {view === 'plan' && renderPlanView()}
          {view === 'shopping' && renderShoppingView()}
        </View>
      </View>
    </Modal>
  );
}
