interface DishSeed {
  name: string; name_hindi?: string; name_regional?: string;
  cuisine: string[]; meal_type: string[]; dietary: string[];
  health_tags: string[]; occasion: string[]; season: string[];
  ingredients_main: string[]; description: string;
}

export const RAJASTHANI_DISHES: DishSeed[] = [
// ═══ Rajput Non-Veg (40) ═══
{ name:'Jungli Maas', name_hindi:'जंगली मांस', cuisine:['Rajasthani'], meal_type:['dinner'], dietary:['non-vegetarian','mutton'], health_tags:['protein'], occasion:['guest','hunting feast'], season:['winter'], ingredients_main:['mutton','red chilli','ghee','salt'], description:'Wild-style mutton — Rajput shikar recipe, just meat, chilli, ghee and salt, primal simplicity from hunting camps' },
{ name:'Soola', name_hindi:'सूला', cuisine:['Rajasthani'], meal_type:['dinner'], dietary:['non-vegetarian','mutton'], health_tags:['protein'], occasion:['festive','guest'], season:['winter'], ingredients_main:['mutton leg','red chilli','garlic','yogurt','ghee'], description:'Skewered grilled mutton — whole leg on iron rod over open flame, Rajput outdoor feast cooking' },
{ name:'Khad Murgh', name_hindi:'खड मुर्ग़', cuisine:['Rajasthani'], meal_type:['dinner'], dietary:['non-vegetarian','chicken'], health_tags:['protein'], occasion:['guest','festive'], season:['winter'], ingredients_main:['whole chicken','red chilli','garlic','yogurt','wheat dough','ghee'], description:'Pit-cooked chicken — whole bird sealed in dough, buried in desert sand pit with hot coals, Thar Desert barbecue' },
{ name:'Shikari Murgh', cuisine:['Rajasthani'], meal_type:['dinner'], dietary:['non-vegetarian','chicken'], health_tags:['protein'], occasion:['guest'], season:['winter'], ingredients_main:['chicken','mustard oil','red chilli','garlic','onion','whole spices'], description:'Hunter-style chicken — bold Rajput preparation, minimal spices, maximum heat, the shikar tradition continues' },
{ name:'Mutton Kaleji', name_hindi:'मटन कलेजी', cuisine:['Rajasthani','Mughlai'], meal_type:['dinner'], dietary:['non-vegetarian','mutton'], health_tags:['protein','iron'], occasion:['everyday'], season:['all'], ingredients_main:['goat liver','onion','ginger-garlic','green chilli','garam masala'], description:'Goat liver fry — iron-rich offal dish, quick-cooked Rajput style, strong flavoured and nutritious' },
{ name:'Murgh Rajasthani', cuisine:['Rajasthani'], meal_type:['dinner'], dietary:['non-vegetarian','chicken'], health_tags:['protein'], occasion:['everyday'], season:['all'], ingredients_main:['chicken','yogurt','onion','garlic','Mathania chilli','cumin'], description:'Rajasthani home-style chicken — yogurt-based, Mathania chillies for colour, everyday non-veg in Rajput households' },
// ═══ Marwadi Veg Mains (60) ═══
{ name:'Gatte ki Khichdi', name_hindi:'गट्टे की खिचड़ी', cuisine:['Rajasthani'], meal_type:['lunch'], dietary:['vegetarian'], health_tags:['protein','comfort'], occasion:['everyday'], season:['all'], ingredients_main:['gram flour dumplings','rice','moong dal','cumin','mustard seeds','ghee'], description:'Gram flour dumplings in rice — one-pot Marwadi comfort meal, gatte cooked right in the khichdi' },
{ name:'Rajasthani Kadhi', name_hindi:'राजस्थानी कढ़ी', cuisine:['Rajasthani'], meal_type:['lunch'], dietary:['vegetarian'], health_tags:['probiotic','comfort'], occasion:['everyday'], season:['all'], ingredients_main:['yogurt','gram flour','cumin','mustard oil','red chilli','hing'], description:'Rajasthani yogurt curry — thicker than Gujarati, tangier than Punjabi, mustard oil tempering distinguishes it' },
{ name:'Pakodi Kadhi Rajasthani', cuisine:['Rajasthani'], meal_type:['lunch'], dietary:['vegetarian'], health_tags:['probiotic','protein'], occasion:['everyday'], season:['all'], ingredients_main:['yogurt','gram flour','onion pakodi','cumin','mustard seeds'], description:'Kadhi with onion fritters — Rajasthani version with crispy pakodi floating in tangy yogurt curry' },
{ name:'Besan Gatte ka Pulao', cuisine:['Rajasthani'], meal_type:['lunch'], dietary:['vegetarian'], health_tags:['protein','energy'], occasion:['festive'], season:['all'], ingredients_main:['basmati rice','gram flour dumplings','ghee','cumin','whole spices'], description:'Gram flour dumpling rice — festive Marwadi one-pot, gatte studded through fragrant ghee rice' },
{ name:'Ker Sangri ki Sabzi', name_hindi:'केर सांगरी', cuisine:['Rajasthani'], meal_type:['lunch','dinner'], dietary:['vegetarian'], health_tags:['fibre','desert food'], occasion:['everyday'], season:['summer'], ingredients_main:['ker berries','sangri beans','dried red chilli','mustard oil','amchur'], description:'Desert berry and bean fry — unique to Thar Desert, dried and reconstituted, tangy and intensely flavoured' },
{ name:'Panchkuta', name_hindi:'पंचकूटा', cuisine:['Rajasthani'], meal_type:['lunch'], dietary:['vegetarian'], health_tags:['fibre','desert food','revival'], occasion:['festive'], season:['all'], ingredients_main:['ker','sangri','kachri','kumatiya','gunda','mustard oil'], description:'Five dried desert vegetables — ancient Rajasthani famine food turned festive, each vegetable foraged from the Thar' },
{ name:'Raab', name_hindi:'राब', cuisine:['Rajasthani'], meal_type:['breakfast','snack'], dietary:['vegetarian'], health_tags:['energy','iron','comfort'], occasion:['everyday','postpartum'], season:['winter'], ingredients_main:['bajra flour','ghee','jaggery','water'], description:'Millet porridge drink from Rajasthan — warming winter drink given to new mothers, just bajra-ghee-jaggery boiled in water' },
{ name:'Bajra Soyta', name_hindi:'बाजरे का सोयता', cuisine:['Rajasthani'], meal_type:['dinner'], dietary:['vegetarian'], health_tags:['fibre','iron','energy'], occasion:['everyday'], season:['winter'], ingredients_main:['bajra flour','buttermilk','cumin','mustard oil','green chilli'], description:'Bajra porridge in buttermilk — Rajasthani desert dinner, millet flour cooked in chaas, cooling despite being winter food' },
{ name:'Missi Roti', name_hindi:'मिस्सी रोटी', cuisine:['Rajasthani','Punjabi'], meal_type:['breakfast','lunch'], dietary:['vegetarian'], health_tags:['protein','fibre'], occasion:['everyday'], season:['all'], ingredients_main:['gram flour','wheat flour','onion','cumin','coriander','ajwain'], description:'Gram flour flatbread — protein-rich mixed flour roti, speckled with onion and spices, Rajasthani-Punjabi shared heritage' },
{ name:'Khoba Roti', name_hindi:'खोबा रोटी', cuisine:['Rajasthani'], meal_type:['lunch','dinner'], dietary:['vegetarian'], health_tags:['energy'], occasion:['everyday'], season:['all'], ingredients_main:['wheat flour','ghee','cumin','onion'], description:'Decorative dimpled flatbread — thick roti with finger-pressed hollows filled with ghee, Rajasthani artisan bread' },
{ name:'Makki ka Dhokla', cuisine:['Rajasthani'], meal_type:['breakfast','snack'], dietary:['vegetarian'], health_tags:['fibre'], occasion:['everyday'], season:['winter'], ingredients_main:['cornmeal','yogurt','cumin','mustard seeds','green chilli'], description:'Corn dhokla from Rajasthan — steamed cornmeal cake, different from Gujarati besan dhokla, winter breakfast' },
{ name:'Mogri ki Sabzi', cuisine:['Rajasthani'], meal_type:['lunch'], dietary:['vegetarian'], health_tags:['fibre','desert food'], occasion:['everyday'], season:['all'], ingredients_main:['dried mogri','mustard oil','cumin','red chilli','hing'], description:'Dried radish pods vegetable — Thar Desert preserved food, sun-dried and reconstituted, tangy and unique' },
{ name:'Kumatiya Sabzi', cuisine:['Rajasthani'], meal_type:['lunch'], dietary:['vegetarian'], health_tags:['fibre','desert food','revival'], occasion:['festive'], season:['all'], ingredients_main:['dried kumatiya berries','mustard oil','cumin','red chilli','amchur'], description:'Dried wild berry vegetable — foraged from the desert, part of the legendary panchkuta five-vegetable mix' },
// ═══ Street Food / Snacks (30) ═══
{ name:'Pyaaz Kachori Jaipur', name_hindi:'प्याज़ कचौरी', cuisine:['Rajasthani'], meal_type:['breakfast','snack'], dietary:['vegetarian'], health_tags:['energy'], occasion:['everyday','street food'], season:['all'], ingredients_main:['wheat flour','onion','coriander','fennel','cumin','oil'], description:'Onion-filled flaky pastry — Jaipur morning essential, served at every street corner with tamarind-coriander chutney' },
{ name:'Mirchi Bada Jodhpur', name_hindi:'मिर्ची बड़ा', cuisine:['Rajasthani'], meal_type:['snack','breakfast'], dietary:['vegetarian'], health_tags:['spicy','energy'], occasion:['street food','everyday'], season:['monsoon'], ingredients_main:['green chilli','potato','gram flour','spices','oil'], description:'Stuffed chilli fritters — Jodhpur street food legend, big green chillies with potato stuffing in crispy batter' },
{ name:'Mawa Kachori Jodhpur', name_hindi:'मावा कचौरी', cuisine:['Rajasthani'], meal_type:['dessert','snack'], dietary:['vegetarian'], health_tags:['rich','celebration'], occasion:['festive'], season:['winter'], ingredients_main:['maida','khoya','sugar syrup','cardamom','pistachios','saffron'], description:'Sweet khoya-filled fried pastry — Jodhpur famous sweet, crispy shell with rich mawa filling soaked in syrup' },
{ name:'Bikaneri Bhujia', name_hindi:'बीकानेरी भुजिया', cuisine:['Rajasthani'], meal_type:['snack'], dietary:['vegetarian'], health_tags:['crispy'], occasion:['everyday'], season:['all'], ingredients_main:['moth bean flour','gram flour','pepper','cloves','oil'], description:'Thin spiced noodle namkeen from Bikaner — India most famous packaged snack, originated from this desert city' },
{ name:'Kanji Vada', name_hindi:'कांजी वड़ा', cuisine:['Rajasthani'], meal_type:['snack'], dietary:['vegetarian'], health_tags:['probiotic','digestive'], occasion:['Holi'], season:['spring'], ingredients_main:['moong dal','mustard seeds','hing','black carrot','mustard','water'], description:'Fermented mustard-water lentil dumplings — Rajasthani Holi specialty, tangy probiotic drink with floating vada' },
{ name:'Boondi', name_hindi:'बूंदी', cuisine:['Rajasthani'], meal_type:['snack','dessert'], dietary:['vegetarian'], health_tags:['versatile'], occasion:['festive','everyday'], season:['all'], ingredients_main:['gram flour','sugar syrup','ghee','oil'], description:'Tiny gram flour pearls — fried and either sweetened or salted, base for ladoo, raita, and standalone namkeen' },
{ name:'Motichur Ladoo', name_hindi:'मोतीचूर लाडू', cuisine:['Rajasthani','Punjabi'], meal_type:['dessert'], dietary:['vegetarian'], health_tags:['celebration'], occasion:['wedding','festive'], season:['all'], ingredients_main:['gram flour','sugar syrup','ghee','cardamom','pistachios','saffron'], description:'Finest boondi ladoo — ultrafine gram flour drops bound with syrup, the Indian wedding sweet par excellence' },
{ name:'Boondi Ladoo', name_hindi:'बूंदी लाडू', cuisine:['Rajasthani'], meal_type:['dessert'], dietary:['vegetarian'], health_tags:['celebration'], occasion:['festive','temple'], season:['all'], ingredients_main:['gram flour','sugar syrup','ghee','cardamom','raisins'], description:'Standard boondi sweet balls — coarser than motichur, temple prasad and festival sweet across Rajasthan' },
{ name:'Balushahi', name_hindi:'बालूशाही', cuisine:['Rajasthani','UP'], meal_type:['dessert'], dietary:['vegetarian'], health_tags:['energy'], occasion:['festive'], season:['all'], ingredients_main:['maida','yogurt','ghee','sugar syrup','cardamom'], description:'Flaky soaked pastry — Rajasthani-UP sweet, crispy layers soaked in sugar syrup, not as sweet as jalebi' },
{ name:'Dilkushar', cuisine:['Rajasthani'], meal_type:['dessert'], dietary:['vegetarian'], health_tags:['revival'], occasion:['festive'], season:['all'], ingredients_main:['maida','ghee','sugar','cardamom','pistachios'], description:'Heart-pleaser pastry — forgotten Rajasthani sweet being revived, flaky layered pastry with cardamom-pistachio' },
// ═══ Desserts / Sweets (30) ═══
{ name:'Ghevar Jaipur', name_hindi:'घेवर', cuisine:['Rajasthani'], meal_type:['dessert'], dietary:['vegetarian'], health_tags:['celebration'], occasion:['Teej','Rakhi'], season:['monsoon'], ingredients_main:['maida','ghee','sugar syrup','saffron','milk','pistachios'], description:'Disc-shaped honeycomb sweet from Jaipur — batter poured into hot ghee creates the holes, Teej and Rakhi essential' },
{ name:'Malpua Rajasthani', name_hindi:'मालपुआ', cuisine:['Rajasthani'], meal_type:['dessert'], dietary:['vegetarian'], health_tags:['energy'], occasion:['Holi','festive'], season:['all'], ingredients_main:['maida','milk','sugar syrup','fennel','cardamom','ghee'], description:'Sweet fried pancakes from Pushkar — soaked in syrup, served with rabri, Rajasthani Holi essential' },
{ name:'Moong Dal Halwa Rajasthani', name_hindi:'मूंग दाल हलवा', cuisine:['Rajasthani'], meal_type:['dessert'], dietary:['vegetarian'], health_tags:['protein','rich'], occasion:['wedding','winter'], season:['winter'], ingredients_main:['moong dal','ghee','sugar','milk','cardamom','almonds','saffron'], description:'Moong lentil fudge — Rajasthani wedding sweet, slow-fried in ghee for hours until deep golden, impossibly rich' },
{ name:'Churma', name_hindi:'चूरमा', cuisine:['Rajasthani'], meal_type:['dessert'], dietary:['vegetarian'], health_tags:['energy'], occasion:['festive','everyday'], season:['winter'], ingredients_main:['wheat flour','ghee','jaggery','cardamom'], description:'Crumbled wheat sweet — the third pillar of dal-baati-churma, baked baati crushed and mixed with ghee and jaggery' },
{ name:'Gaund ke Ladoo', name_hindi:'गौंद के लड्डू', cuisine:['Rajasthani'], meal_type:['dessert','snack'], dietary:['vegetarian'], health_tags:['warming','postpartum'], occasion:['winter','postpartum'], season:['winter'], ingredients_main:['edible gum','wheat flour','ghee','sugar','almonds','coconut'], description:'Edible gum ladoo — winter warming sweet given to new mothers in Rajasthan, rich with ghee and dry fruits' },
{ name:'Atte ke Ladoo', name_hindi:'आटे के लड्डू', cuisine:['Rajasthani','Punjabi'], meal_type:['dessert'], dietary:['vegetarian'], health_tags:['energy'], occasion:['everyday','festive'], season:['winter'], ingredients_main:['wheat flour','ghee','sugar','cardamom','almonds'], description:'Wheat flour ladoo — simplest Rajasthani sweet, roasted atta with ghee and sugar, winter energy balls' },
{ name:'Mawa Ladoo', name_hindi:'मावा लाडू', cuisine:['Rajasthani'], meal_type:['dessert'], dietary:['vegetarian'], health_tags:['calcium','rich'], occasion:['festive'], season:['all'], ingredients_main:['khoya','sugar','cardamom','pistachios','saffron'], description:'Khoya fudge balls — rich milk-solid ladoo, Rajasthani festival sweet, dense and aromatic' },
{ name:'Kalakand Rajasthani', name_hindi:'कलाकंद', cuisine:['Rajasthani'], meal_type:['dessert'], dietary:['vegetarian'], health_tags:['calcium'], occasion:['festive'], season:['all'], ingredients_main:['milk','sugar','lemon','cardamom','pistachios'], description:'Milk cake from Alwar — grainy reduced milk sweet, Alwar speciality, moist and crumbly texture' },
{ name:'Imarti', name_hindi:'इमारती', cuisine:['Rajasthani','UP'], meal_type:['dessert'], dietary:['vegetarian'], health_tags:['energy'], occasion:['festive','Diwali'], season:['all'], ingredients_main:['urad dal flour','sugar syrup','saffron','ghee'], description:'Flower-shaped fried sweet — more elaborate than jalebi, made from urad dal batter, crispier and more fragrant' },
{ name:'Doodh Jalebi', cuisine:['Rajasthani'], meal_type:['dessert'], dietary:['vegetarian'], health_tags:['calcium','rich'], occasion:['festive'], season:['all'], ingredients_main:['maida','sugar syrup','saffron','milk','cardamom','pistachios'], description:'Jalebi soaked in sweetened milk — Rajasthani upgrade of jalebi, hot spirals dropped into cold saffron milk' },
{ name:'Makhania Lassi', name_hindi:'मखनिया लस्सी', cuisine:['Rajasthani'], meal_type:['snack'], dietary:['vegetarian'], health_tags:['probiotic','cooling'], occasion:['everyday'], season:['summer'], ingredients_main:['yogurt','cream','sugar','cardamom','saffron','rose water'], description:'Creamy Rajasthani lassi from Jaipur — thicker and richer than Punjabi lassi, with a scoop of malai on top' },
{ name:'Thandai Rajasthani', name_hindi:'ठंडाई', cuisine:['Rajasthani'], meal_type:['snack'], dietary:['vegetarian'], health_tags:['cooling','festive'], occasion:['Holi','summer'], season:['summer'], ingredients_main:['milk','almonds','fennel','melon seeds','saffron','rose petals','sugar'], description:'Spiced nut milk from Rajasthan — Holi celebration drink, stone-ground nut paste in cold milk, traditionally with bhang' },
// ═══ Jain Rajasthani (30) ═══
{ name:'Jain Gatte ki Sabzi', cuisine:['Jain','Rajasthani'], meal_type:['lunch','dinner'], dietary:['jain'], health_tags:['protein'], occasion:['everyday'], season:['all'], ingredients_main:['gram flour','yogurt','mustard oil','hing','cumin','red chilli'], description:'Gram flour dumplings in yogurt — Jain Rajasthani classic, hing replaces onion-garlic, equally rich and tangy' },
{ name:'Jain Panchmel Dal Rajasthani', cuisine:['Jain','Rajasthani'], meal_type:['lunch','dinner'], dietary:['jain'], health_tags:['protein'], occasion:['everyday','festive'], season:['all'], ingredients_main:['toor dal','chana dal','moong dal','urad dal','masoor dal','hing','ghee','cumin'], description:'Five-lentil dal, Jain Marwadi — hing provides the depth, ghee tempering, served at every Jain Marwadi feast' },
{ name:'Jain Ker Sangri', cuisine:['Jain','Rajasthani'], meal_type:['lunch'], dietary:['jain'], health_tags:['fibre','desert food'], occasion:['everyday'], season:['summer'], ingredients_main:['ker berries','sangri beans','hing','mustard oil','amchur','red chilli'], description:'Desert berry and bean, Jain version — hing replaces garlic, same tangy desert flavour, Jain Marwadi staple' },
{ name:'Jain Gatte ki Khichdi', cuisine:['Jain','Rajasthani'], meal_type:['lunch'], dietary:['jain'], health_tags:['protein','comfort'], occasion:['everyday'], season:['all'], ingredients_main:['gram flour dumplings','rice','moong dal','hing','cumin','ghee'], description:'Gatte khichdi, Jain version — one-pot Marwadi comfort with hing instead of onion-garlic' },
{ name:'Jain Rajasthani Kadhi', cuisine:['Jain','Rajasthani'], meal_type:['lunch'], dietary:['jain'], health_tags:['probiotic'], occasion:['everyday'], season:['all'], ingredients_main:['yogurt','gram flour','hing','cumin','red chilli','mustard oil'], description:'Yogurt curry, Jain Rajasthani — thick and tangy, hing tempering, no onion-garlic, everyday thali component' },
{ name:'Jain Bajra Khichdi', cuisine:['Jain','Rajasthani'], meal_type:['dinner'], dietary:['jain'], health_tags:['fibre','iron'], occasion:['everyday'], season:['winter'], ingredients_main:['bajra','moong dal','ghee','cumin','hing','turmeric'], description:'Pearl millet khichdi, Jain — winter Marwadi dinner with hing, served with ghee and jaggery' },
{ name:'Jain Missi Roti', cuisine:['Jain','Rajasthani'], meal_type:['breakfast'], dietary:['jain'], health_tags:['protein'], occasion:['everyday'], season:['all'], ingredients_main:['gram flour','wheat flour','hing','cumin','coriander','ajwain'], description:'Gram flour flatbread, Jain — no onion, hing and ajwain for flavour, protein-rich daily bread' },
{ name:'Jain Papad ki Sabzi', cuisine:['Jain','Rajasthani'], meal_type:['lunch','dinner'], dietary:['jain'], health_tags:['quick'], occasion:['everyday'], season:['all'], ingredients_main:['papad','yogurt','cumin','hing','turmeric','mustard oil'], description:'Papad curry, Jain version — crushed papad in yogurt gravy with hing, desert ingenuity without onion-garlic' },
{ name:'Jain Churma Ladoo', cuisine:['Jain','Rajasthani'], meal_type:['dessert'], dietary:['jain'], health_tags:['energy'], occasion:['festive'], season:['winter'], ingredients_main:['wheat flour','ghee','jaggery','cardamom','sesame'], description:'Crushed wheat balls, Jain — baked and crumbled with ghee-jaggery, festive Marwadi Jain sweet' },
{ name:'Jain Moong Dal Halwa', cuisine:['Jain','Rajasthani'], meal_type:['dessert'], dietary:['jain'], health_tags:['protein','rich'], occasion:['wedding','winter'], season:['winter'], ingredients_main:['moong dal','ghee','sugar','milk','cardamom','almonds','saffron'], description:'Moong lentil fudge, Jain — hours of slow frying in ghee, Jain Marwadi wedding sweet, impossibly rich' },
];
