require('dotenv').config();
const { createClient } = require('@supabase/supabase-js');

const client = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL,
  process.env.SUPABASE_SERVICE_ROLE_KEY,
);

// ─── 65 Kerala dishes ─────────────────────────────────────────────────────────
// Distribution: 14 breakfast | 16 lunch_curry | 14 dinner_curry |
//               10 veg_side | 5 rice | 3 bread | 2 raita | 1 snack

// ─── 50 Street Food dishes ────────────────────────────────────────────────────
// Distribution: 5 breakfast | 5 lunch_curry | 40 snack
// ALL Street Food dishes carry is_street: true

const dishes = [

  // ══════════════════════════════════════════════════════════════════════════════
  // KERALA  (65)
  // ══════════════════════════════════════════════════════════════════════════════

  // ── BREAKFAST (14) ──────────────────────────────────────────────────────────

  {
    name: 'Appam',
    name_hindi: 'अप्पम',
    name_regional: 'അപ്പം',
    description: 'Fermented rice batter poured into a wok to create a thin lacy edge with a soft spongy centre — Kerala most iconic breakfast.',
    cuisine: ['Kerala'],
    region: 'SOUTH',
    slot: ['breakfast'],
    is_veg: true, is_vegan: true, is_jain: true, is_fasting: false, is_street: false,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Idiyappam',
    name_hindi: 'इडियाप्पम',
    name_regional: 'ഇടിയപ്പം',
    description: 'Fine rice noodles pressed through a mould into delicate discs, steamed and served with coconut milk or egg curry.',
    cuisine: ['Kerala'],
    region: 'SOUTH',
    slot: ['breakfast'],
    is_veg: true, is_vegan: true, is_jain: true, is_fasting: false, is_street: false,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Puttu',
    name_hindi: 'पुट्टू',
    name_regional: 'പുട്ട്',
    description: 'Steamed cylinder of layered rice flour and fresh coconut cooked in a bamboo or metal mould — eaten with kadala curry or banana.',
    cuisine: ['Kerala'],
    region: 'SOUTH',
    slot: ['breakfast'],
    is_veg: true, is_vegan: true, is_jain: true, is_fasting: false, is_street: false,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Palappam',
    name_hindi: 'पालअप्पम',
    name_regional: 'പാലപ്പം',
    description: 'Bowl-shaped fermented rice pancake with a thick soft centre and thin crispy edges, cooked in coconut milk — a Kerala Christian staple.',
    cuisine: ['Kerala'],
    region: 'SOUTH',
    slot: ['breakfast'],
    is_veg: true, is_vegan: true, is_jain: true, is_fasting: false, is_street: false,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Vellayappam',
    name_hindi: 'वेल्लयप्पम',
    name_regional: 'വെള്ളയപ്പം',
    description: 'Thick white fermented rice pancake slightly puffed and spongy — softer and larger than appam, a Kerala everyday breakfast.',
    cuisine: ['Kerala'],
    region: 'SOUTH',
    slot: ['breakfast'],
    is_veg: true, is_vegan: true, is_jain: true, is_fasting: false, is_street: false,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Kallappam',
    name_hindi: 'कल्लप्पम',
    name_regional: 'കള്ളപ്പം',
    description: 'Rice pancake fermented with toddy (palm wine) giving a distinct tang and airy texture — a traditional Kerala breakfast.',
    cuisine: ['Kerala'],
    region: 'SOUTH',
    slot: ['breakfast'],
    is_veg: true, is_vegan: true, is_jain: true, is_fasting: false, is_street: false,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Kerala Parotta',
    name_hindi: 'केरला परोटा',
    name_regional: 'കേരള പൊറോട്ട',
    description: 'Flaky layered flatbread made from maida, beaten and folded repeatedly to create soft coin-like layers — served with beef or chicken curry.',
    cuisine: ['Kerala'],
    region: 'SOUTH',
    slot: ['breakfast'],
    is_veg: true, is_vegan: false, is_jain: true, is_fasting: false, is_street: true,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Wheat Puttu',
    name_hindi: 'गेहूं पुट्टू',
    name_regional: 'ഗോതമ്പ് പുട്ട്',
    description: 'Steamed cylinder of wheat flour and coconut — a healthier everyday variant of the classic rice puttu.',
    cuisine: ['Kerala'],
    region: 'SOUTH',
    slot: ['breakfast'],
    is_veg: true, is_vegan: true, is_jain: true, is_fasting: false, is_street: false,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Rava Puttu',
    name_hindi: 'रवा पुट्टू',
    name_regional: 'റവ പുട്ട്',
    description: 'Steamed semolina and coconut cylinder — a quicker no-soak alternative to rice puttu, popular in Kerala households.',
    cuisine: ['Kerala'],
    region: 'SOUTH',
    slot: ['breakfast'],
    is_veg: true, is_vegan: true, is_jain: true, is_fasting: false, is_street: false,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Rice Rava Upma',
    name_hindi: 'राइस रवा उपमा',
    name_regional: 'ഗോതമ്പ് ഉപ്പുമാവ്',
    description: 'Broken rice cooked with mustard seeds, curry leaves, and coconut in the Kerala style — a light and quick weekday morning breakfast.',
    cuisine: ['Kerala'],
    region: 'SOUTH',
    slot: ['breakfast'],
    is_veg: true, is_vegan: true, is_jain: false, is_fasting: false, is_street: false,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Semiya Upma',
    name_hindi: 'सेमिया उपमा',
    name_regional: 'സേമ്യ ഉപ്പുമാവ്',
    description: 'Roasted vermicelli cooked with mustard seeds, curry leaves, green chilli, and coconut — a quick Kerala morning breakfast.',
    cuisine: ['Kerala'],
    region: 'SOUTH',
    slot: ['breakfast'],
    is_veg: true, is_vegan: false, is_jain: false, is_fasting: false, is_street: false,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Kerala Egg Roast',
    name_hindi: 'केरला एग रोस्ट',
    name_regional: 'മുട്ട റോസ്റ്റ്',
    description: 'Hard-boiled eggs slow-roasted in a caramelised shallot-tomato masala with Malabar spices — the classic appam and parotta companion.',
    cuisine: ['Kerala'],
    region: 'SOUTH',
    slot: ['breakfast'],
    is_veg: false, is_vegan: false, is_jain: false, is_fasting: false, is_street: false,
    is_non_veg_type: 'egg', allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Rava Dosa',
    name_hindi: 'रवा डोसा',
    name_regional: 'റവ ദോശ',
    description: 'Thin and crispy semolina crepe with onion, green chilli, and peppercorns — a quick no-ferment Kerala breakfast.',
    cuisine: ['Kerala'],
    region: 'SOUTH',
    slot: ['breakfast'],
    is_veg: true, is_vegan: false, is_jain: false, is_fasting: false, is_street: false,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Bread Omelette',
    name_hindi: 'ब्रेड ऑमलेट',
    name_regional: 'ബ്രഡ് ഓംലെറ്റ്',
    description: 'Spiced egg omelette sandwiched between buttered bread slices on a hot griddle — a Kerala roadside breakfast staple.',
    cuisine: ['Kerala'],
    region: 'SOUTH',
    slot: ['breakfast'],
    is_veg: false, is_vegan: false, is_jain: false, is_fasting: false, is_street: true,
    is_non_veg_type: 'egg', allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },

  // ── LUNCH CURRY (16) ────────────────────────────────────────────────────────

  {
    name: 'Avial',
    name_hindi: 'अवियल',
    name_regional: 'അവിയൽ',
    description: 'Mixed seasonal vegetables cooked in coconut and cumin paste, finished with yogurt and coconut oil — a Kerala Onam thali centrepiece.',
    cuisine: ['Kerala'],
    region: 'SOUTH',
    slot: ['lunch_curry'],
    is_veg: true, is_vegan: false, is_jain: false, is_fasting: false, is_street: false,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday', 'festival'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Olan',
    name_hindi: 'ओलान',
    name_regional: 'ഓലൻ',
    description: 'Ash gourd and black-eyed peas simmered in thin coconut milk with green chilli and coconut oil — a subtle, cooling Kerala Onam dish.',
    cuisine: ['Kerala'],
    region: 'SOUTH',
    slot: ['lunch_curry'],
    is_veg: true, is_vegan: true, is_jain: true, is_fasting: false, is_street: false,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday', 'festival'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Erissery',
    name_hindi: 'एरिसरी',
    name_regional: 'എരിശ്ശേരി',
    description: 'Pumpkin and lentils cooked in coconut paste, topped with fried coconut and mustard seeds — a classic Kerala sadya dish.',
    cuisine: ['Kerala'],
    region: 'SOUTH',
    slot: ['lunch_curry'],
    is_veg: true, is_vegan: true, is_jain: true, is_fasting: false, is_street: false,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday', 'festival'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Kerala Sambar',
    name_hindi: 'केरला सांभर',
    name_regional: 'കേരള സാമ്പാർ',
    description: 'Toor dal and shallot curry tempered with coconut oil and curry leaves — thinner and less tangy than Tamil sambar, served over rice.',
    cuisine: ['Kerala'],
    region: 'SOUTH',
    slot: ['lunch_curry'],
    is_veg: true, is_vegan: true, is_jain: false, is_fasting: false, is_street: false,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Rasam',
    name_hindi: 'रसम',
    name_regional: 'രസം',
    description: 'Thin peppery tamarind-tomato soup with garlic and rasam powder — drunk as a digestive or poured over rice at the end of a Kerala meal.',
    cuisine: ['Kerala'],
    region: 'SOUTH',
    slot: ['lunch_curry'],
    is_veg: true, is_vegan: true, is_jain: false, is_fasting: false, is_street: false,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Kadala Curry',
    name_hindi: 'कडाला करी',
    name_regional: 'കടല കറി',
    description: 'Black chickpeas cooked in a roasted coconut and shallot masala — the traditional accompaniment for puttu and appam.',
    cuisine: ['Kerala'],
    region: 'SOUTH',
    slot: ['lunch_curry'],
    is_veg: true, is_vegan: true, is_jain: false, is_fasting: false, is_street: false,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Ulli Theeyal',
    name_hindi: 'उल्ली थीयाल',
    name_regional: 'ഉള്ളി തീയൽ',
    description: 'Shallots simmered in a roasted coconut-tamarind-spice gravy — one of the most flavourful and aromatic Kerala curries.',
    cuisine: ['Kerala'],
    region: 'SOUTH',
    slot: ['lunch_curry'],
    is_veg: true, is_vegan: true, is_jain: false, is_fasting: false, is_street: false,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Karimeen Pollichathu',
    name_hindi: 'करीमीन पोल्लिचातु',
    name_regional: 'കരിമീൻ പൊള്ളിച്ചത്',
    description: 'Pearl spot fish marinated in red masala, wrapped in banana leaf and pan-roasted — the signature dish of Kerala backwaters.',
    cuisine: ['Kerala'],
    region: 'SOUTH',
    slot: ['lunch_curry'],
    is_veg: false, is_vegan: false, is_jain: false, is_fasting: false, is_street: false,
    is_non_veg_type: 'fish', allowed_days: [], occasion: ['party', 'everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Kerala Fish Curry',
    name_hindi: 'केरला फिश करी',
    name_regional: 'മീൻ കറി',
    description: 'Fresh fish in a fiery red coconut milk curry with kudampuli (Gamboge) — the everyday Kerala fish curry eaten over matta rice.',
    cuisine: ['Kerala'],
    region: 'SOUTH',
    slot: ['lunch_curry'],
    is_veg: false, is_vegan: false, is_jain: false, is_fasting: false, is_street: false,
    is_non_veg_type: 'fish', allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Prawn Moilee',
    name_hindi: 'प्रॉन मोइली',
    name_regional: 'ചെമ്മീൻ മൊയ്ലി',
    description: 'Prawns in a delicate golden coconut milk curry with turmeric and green chilli — a mild and aromatic Kerala Christian preparation.',
    cuisine: ['Kerala'],
    region: 'SOUTH',
    slot: ['lunch_curry'],
    is_veg: false, is_vegan: false, is_jain: false, is_fasting: false, is_street: false,
    is_non_veg_type: 'prawn', allowed_days: [], occasion: ['everyday', 'party'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Chicken Stew',
    name_hindi: 'चिकन स्टू',
    name_regional: 'ചിക്കൻ സ്റ്റൂ',
    description: 'Chicken simmered in a delicately spiced thin coconut milk stew with potatoes and whole spices — the classic appam companion.',
    cuisine: ['Kerala'],
    region: 'SOUTH',
    slot: ['lunch_curry'],
    is_veg: false, is_vegan: false, is_jain: false, is_fasting: false, is_street: false,
    is_non_veg_type: 'chicken', allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Kootu Curry',
    name_hindi: 'कूटु करी',
    name_regional: 'കൂട്ടുകറി',
    description: 'Black chickpeas and raw banana cooked in coconut paste with toasted coconut — an essential sadya dish for Onam and Vishu.',
    cuisine: ['Kerala'],
    region: 'SOUTH',
    slot: ['lunch_curry'],
    is_veg: true, is_vegan: true, is_jain: false, is_fasting: false, is_street: false,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday', 'festival'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Parippu Curry',
    name_hindi: 'परिप्पु करी',
    name_regional: 'പരിപ്പ് കറി',
    description: 'Moong dal cooked with coconut milk and turmeric, finished with a mustard-curry leaf coconut oil tempering — first course of the sadya.',
    cuisine: ['Kerala'],
    region: 'SOUTH',
    slot: ['lunch_curry'],
    is_veg: true, is_vegan: true, is_jain: true, is_fasting: false, is_street: false,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday', 'festival'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Pineapple Pachadi',
    name_hindi: 'अनानास पचड़ी',
    name_regional: 'കൈതച്ചക്ക പച്ചടി',
    description: 'Fresh pineapple cooked in coconut paste and stirred into yogurt with a mustard tempering — a sweet-tangy sadya side.',
    cuisine: ['Kerala'],
    region: 'SOUTH',
    slot: ['lunch_curry'],
    is_veg: true, is_vegan: false, is_jain: true, is_fasting: false, is_street: false,
    is_non_veg_type: null, allowed_days: [], occasion: ['festival', 'everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Moru Kachiyathu',
    name_hindi: 'मोरू काचियाथु',
    name_regional: 'മോരു കാച്ചിയത്',
    description: 'Spiced and tempered thin buttermilk curry with green chilli, ginger, and curry leaves — poured over rice as the cooling last course of sadya.',
    cuisine: ['Kerala'],
    region: 'SOUTH',
    slot: ['lunch_curry'],
    is_veg: true, is_vegan: false, is_jain: true, is_fasting: false, is_street: false,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday', 'festival'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Meen Vattichathu',
    name_hindi: 'मीन वट्टिचाथु',
    name_regional: 'മീൻ വറ്റിച്ചത്',
    description: 'Sour Kerala fish curry cooked dry with kudampuli, red chilli, and shallots in a clay pot until the gravy thickens to a bold coating.',
    cuisine: ['Kerala'],
    region: 'SOUTH',
    slot: ['lunch_curry'],
    is_veg: false, is_vegan: false, is_jain: false, is_fasting: false, is_street: false,
    is_non_veg_type: 'fish', allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },

  // ── DINNER CURRY (14) ───────────────────────────────────────────────────────

  {
    name: 'Kerala Mutton Curry',
    name_hindi: 'केरला मटन करी',
    name_regional: 'ആട്ടിൻ കറി',
    description: 'Mutton slow-cooked in a roasted coconut and Malabar spice gravy with shallots and coconut oil — a Kerala Sunday dinner.',
    cuisine: ['Kerala'],
    region: 'SOUTH',
    slot: ['dinner_curry'],
    is_veg: false, is_vegan: false, is_jain: false, is_fasting: false, is_street: false,
    is_non_veg_type: 'mutton', allowed_days: [], occasion: ['everyday', 'party'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Kerala Beef Fry',
    name_hindi: 'केरला बीफ फ्राय',
    name_regional: 'ബീഫ് ഉലർത്തിയത്',
    description: 'Beef cooked with shallots, curry leaves, black pepper, and coconut pieces until dry and caramelised — an iconic Kerala Christian dish.',
    cuisine: ['Kerala'],
    region: 'SOUTH',
    slot: ['dinner_curry'],
    is_veg: false, is_vegan: false, is_jain: false, is_fasting: false, is_street: false,
    is_non_veg_type: 'beef', allowed_days: [], occasion: ['everyday', 'party'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Kerala Duck Roast',
    name_hindi: 'केरला डक रोस्ट',
    name_regional: 'താറാവ് റോസ്റ്റ്',
    description: 'Duck slow-roasted in a dark shallot-coconut masala with whole spices — a prized Kerala Christian feast dish served with appam.',
    cuisine: ['Kerala'],
    region: 'SOUTH',
    slot: ['dinner_curry'],
    is_veg: false, is_vegan: false, is_jain: false, is_fasting: false, is_street: false,
    is_non_veg_type: 'duck', allowed_days: [], occasion: ['party', 'everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Kerala Crab Curry',
    name_hindi: 'केरला क्रैब करी',
    name_regional: 'ഞണ്ട് കറി',
    description: 'Mud crab cooked in a rich coconut milk and roasted coconut masala with Malabar spices — a coastal Kerala delicacy.',
    cuisine: ['Kerala'],
    region: 'SOUTH',
    slot: ['dinner_curry'],
    is_veg: false, is_vegan: false, is_jain: false, is_fasting: false, is_street: false,
    is_non_veg_type: 'seafood', allowed_days: [], occasion: ['party', 'everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Prawn Thoran',
    name_hindi: 'प्रॉन थोरन',
    name_regional: 'ചെമ്മീൻ തോരൻ',
    description: 'Prawns stir-fried dry with freshly grated coconut, turmeric, green chilli, and curry leaves — a quick Kerala coastal dinner side.',
    cuisine: ['Kerala'],
    region: 'SOUTH',
    slot: ['dinner_curry'],
    is_veg: false, is_vegan: false, is_jain: false, is_fasting: false, is_street: false,
    is_non_veg_type: 'prawn', allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Meen Peera',
    name_hindi: 'मीन पीरा',
    name_regional: 'മീൻ പീര',
    description: 'Small fish cooked dry with freshly grated coconut, shallots, and kudampuli — a flavourful everyday Kerala home dinner.',
    cuisine: ['Kerala'],
    region: 'SOUTH',
    slot: ['dinner_curry'],
    is_veg: false, is_vegan: false, is_jain: false, is_fasting: false, is_street: false,
    is_non_veg_type: 'fish', allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Chicken Roast Kerala',
    name_hindi: 'केरला चिकन रोस्ट',
    name_regional: 'ചിക്കൻ റോസ്റ്റ്',
    description: 'Chicken roasted in a dark caramelised shallot-tomato masala until the oil separates — a bold spiced Kerala dinner classic.',
    cuisine: ['Kerala'],
    region: 'SOUTH',
    slot: ['dinner_curry'],
    is_veg: false, is_vegan: false, is_jain: false, is_fasting: false, is_street: false,
    is_non_veg_type: 'chicken', allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Cabbage Thoran',
    name_hindi: 'कैबेज थोरन',
    name_regional: 'കാബേജ് തോരൻ',
    description: 'Finely shredded cabbage stir-fried with freshly grated coconut, mustard seeds, and curry leaves — a crisp everyday Kerala side.',
    cuisine: ['Kerala'],
    region: 'SOUTH',
    slot: ['dinner_curry'],
    is_veg: true, is_vegan: true, is_jain: true, is_fasting: false, is_street: false,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Kumbalanga Moru Curry',
    name_hindi: 'कुम्बलंगा मोरू करी',
    name_regional: 'കുമ്പളങ്ങ മോരുകറി',
    description: 'Ash gourd cooked in a seasoned coconut-buttermilk curry — a cooling and digestive Kerala dinner dish.',
    cuisine: ['Kerala'],
    region: 'SOUTH',
    slot: ['dinner_curry'],
    is_veg: true, is_vegan: false, is_jain: true, is_fasting: false, is_street: false,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Pavakka Theeyal',
    name_hindi: 'पावक्का थीयाल',
    name_regional: 'പാവക്ക തീയൽ',
    description: 'Bitter gourd in a deeply roasted coconut, tamarind, and chilli gravy — intense, bitter-tangy, a robustly flavoured Kerala curry.',
    cuisine: ['Kerala'],
    region: 'SOUTH',
    slot: ['dinner_curry'],
    is_veg: true, is_vegan: true, is_jain: false, is_fasting: false, is_street: false,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Koottukari',
    name_hindi: 'कूट्टुकरी',
    name_regional: 'കൂട്ടുകറി',
    description: 'Mixed vegetables and yam cooked with roasted coconut and whole spices — a hearty and complex Kerala vegetarian dinner curry.',
    cuisine: ['Kerala'],
    region: 'SOUTH',
    slot: ['dinner_curry'],
    is_veg: true, is_vegan: true, is_jain: false, is_fasting: false, is_street: false,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Muringakka Curry',
    name_hindi: 'मुरिंगक्का करी',
    name_regional: 'മുരിങ്ങക്ക കറി',
    description: 'Drumstick in a coconut milk and shallot gravy tempered with mustard and curry leaves — a classic everyday Kerala dinner.',
    cuisine: ['Kerala'],
    region: 'SOUTH',
    slot: ['dinner_curry'],
    is_veg: true, is_vegan: true, is_jain: false, is_fasting: false, is_street: false,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Mathanga Erissery',
    name_hindi: 'माथंगा एरिसरी',
    name_regional: 'മത്തങ്ങ എരിശ്ശേരി',
    description: 'Yellow pumpkin and lentils cooked in coconut paste, topped with roasted grated coconut — a sweet and nutty Kerala dinner preparation.',
    cuisine: ['Kerala'],
    region: 'SOUTH',
    slot: ['dinner_curry'],
    is_veg: true, is_vegan: true, is_jain: true, is_fasting: false, is_street: false,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Cheera Kootu',
    name_hindi: 'चीरा कूटु',
    name_regional: 'ചീര കൂട്ടൻ',
    description: 'Red amaranth or spinach cooked with moong dal and coconut paste — a nutritious, lightly spiced Kerala dinner dish.',
    cuisine: ['Kerala'],
    region: 'SOUTH',
    slot: ['dinner_curry'],
    is_veg: true, is_vegan: true, is_jain: true, is_fasting: false, is_street: false,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },

  // ── VEG SIDE (10) ───────────────────────────────────────────────────────────

  {
    name: 'Beans Thoran',
    name_hindi: 'बीन्स थोरन',
    name_regional: 'ബീൻസ് തോരൻ',
    description: 'Finely chopped French beans stir-fried with grated coconut, mustard, turmeric, and curry leaves — a crisp Kerala dry side.',
    cuisine: ['Kerala'],
    region: 'SOUTH',
    slot: ['veg_side'],
    is_veg: true, is_vegan: true, is_jain: true, is_fasting: false, is_street: false,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Carrot Thoran',
    name_hindi: 'गाजर थोरन',
    name_regional: 'കാരറ്റ് തോരൻ',
    description: 'Grated carrot stir-fried with coconut, mustard seeds, and curry leaves — a sweet, crunchy everyday Kerala vegetable side.',
    cuisine: ['Kerala'],
    region: 'SOUTH',
    slot: ['veg_side'],
    is_veg: true, is_vegan: true, is_jain: false, is_fasting: false, is_street: false,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Banana Flower Thoran',
    name_hindi: 'केले के फूल थोरन',
    name_regional: 'വാഴപ്പൂ തോരൻ',
    description: 'Banana blossom stir-fried with coconut, shallots, and turmeric — a mildly astringent, nutritious Kerala side dish.',
    cuisine: ['Kerala'],
    region: 'SOUTH',
    slot: ['veg_side'],
    is_veg: true, is_vegan: true, is_jain: false, is_fasting: false, is_street: false,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Cheera Thoran',
    name_hindi: 'चीरा थोरन',
    name_regional: 'ചീര തോരൻ',
    description: 'Red amaranth leaves wilted and tossed with freshly grated coconut and a mustard-curry leaf tempering in coconut oil.',
    cuisine: ['Kerala'],
    region: 'SOUTH',
    slot: ['veg_side'],
    is_veg: true, is_vegan: true, is_jain: true, is_fasting: false, is_street: false,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Drumstick Thoran',
    name_hindi: 'ड्रमस्टिक थोरन',
    name_regional: 'മുരിങ്ങ തോരൻ',
    description: 'Drumstick pieces stir-fried with coconut paste, turmeric, and curry leaves — a nutritious, earthy Kerala side dish.',
    cuisine: ['Kerala'],
    region: 'SOUTH',
    slot: ['veg_side'],
    is_veg: true, is_vegan: true, is_jain: true, is_fasting: false, is_street: false,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Beetroot Thoran',
    name_hindi: 'बीटरूट थोरन',
    name_regional: 'ബീറ്റ്റൂട്ട് തോരൻ',
    description: 'Grated beetroot stir-fried with coconut, mustard seeds, and curry leaves — a vivid crimson Kerala side with earthy sweetness.',
    cuisine: ['Kerala'],
    region: 'SOUTH',
    slot: ['veg_side'],
    is_veg: true, is_vegan: true, is_jain: false, is_fasting: false, is_street: false,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Raw Banana Mezhukkupuratti',
    name_hindi: 'कच्चे केले मेझुक्कुपुरट्टी',
    name_regional: 'കായ മേഴുക്കുപുരട്ടി',
    description: 'Raw banana slices pan-fried with shallots, turmeric, and coconut oil — a classic dry side from the Kerala sadya spread.',
    cuisine: ['Kerala'],
    region: 'SOUTH',
    slot: ['veg_side'],
    is_veg: true, is_vegan: true, is_jain: false, is_fasting: false, is_street: false,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday', 'festival'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Chena Mezhukkupuratti',
    name_hindi: 'चेना मेझुक्कुपुरट्टी',
    name_regional: 'ചേന മേഴുക്കുപുരട്ടി',
    description: 'Elephant yam cooked with shallots, garlic, and coconut oil until lightly crisp — a robust and earthy Kerala everyday side.',
    cuisine: ['Kerala'],
    region: 'SOUTH',
    slot: ['veg_side'],
    is_veg: true, is_vegan: true, is_jain: false, is_fasting: false, is_street: false,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Achinga Payar Thoran',
    name_hindi: 'अचिंगा पायर थोरन',
    name_regional: 'അച്ചിങ്ങ പയർ തോരൻ',
    description: 'Long yard beans cut and stir-fried with coconut, mustard seeds, and turmeric — a fibre-rich Kerala everyday vegetable side.',
    cuisine: ['Kerala'],
    region: 'SOUTH',
    slot: ['veg_side'],
    is_veg: true, is_vegan: true, is_jain: true, is_fasting: false, is_street: false,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Raw Mango Curry',
    name_hindi: 'कच्चे आम की करी',
    name_regional: 'മാങ്ങ കറി',
    description: 'Raw mango simmered in a coconut milk and spice gravy — a tangy, seasonal Kerala side that uses the sourness of unripe mango.',
    cuisine: ['Kerala'],
    region: 'SOUTH',
    slot: ['veg_side'],
    is_veg: true, is_vegan: true, is_jain: true, is_fasting: false, is_street: false,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },

  // ── RICE (5) ────────────────────────────────────────────────────────────────

  {
    name: 'Matta Rice',
    name_hindi: 'माट्टा राइस',
    name_regional: 'മട്ട അരി',
    description: 'Kerala parboiled red rice steamed until soft — the everyday staple of Kerala, nutty, high in fibre, eaten with all curries.',
    cuisine: ['Kerala'],
    region: 'SOUTH',
    slot: ['rice'],
    is_veg: true, is_vegan: true, is_jain: true, is_fasting: false, is_street: false,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Nei Choru',
    name_hindi: 'नेई चोरु',
    name_regional: 'നെയ് ചോറ്',
    description: 'Fragrant Malabar ghee rice cooked with whole spices, fried onion, and cashews — served with meat curry at weddings and feasts.',
    cuisine: ['Kerala'],
    region: 'SOUTH',
    slot: ['rice'],
    is_veg: true, is_vegan: false, is_jain: false, is_fasting: false, is_street: false,
    is_non_veg_type: null, allowed_days: [], occasion: ['party', 'festival'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Thalassery Chicken Biryani',
    name_hindi: 'तलस्सेरी चिकन बिरयानी',
    name_regional: 'തലശ്ശേരി ബിരിയാണി',
    description: 'Fragrant Malabar biryani with Kaima rice, chicken, and an aromatic spice blend unique to Thalassery — Kerala most distinctive biryani.',
    cuisine: ['Kerala'],
    region: 'SOUTH',
    slot: ['rice'],
    is_veg: false, is_vegan: false, is_jain: false, is_fasting: false, is_street: false,
    is_non_veg_type: 'chicken', allowed_days: [], occasion: ['party', 'everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Kanji',
    name_hindi: 'काँजी',
    name_regional: 'കഞ്ഞി',
    description: 'Thin rice porridge cooked until soupy with ginger and salt — the Kerala comfort food for illness, fasting, and early mornings.',
    cuisine: ['Kerala'],
    region: 'SOUTH',
    slot: ['rice'],
    is_veg: true, is_vegan: true, is_jain: true, is_fasting: true, is_street: false,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Chemmeen Pulao',
    name_hindi: 'चेम्मीन पुलाव',
    name_regional: 'ചെമ്മീൻ പുലാവ്',
    description: 'Kaima rice cooked with marinated prawns, coconut milk, and Malabar spices — a coastal Kerala prawn rice for special occasions.',
    cuisine: ['Kerala'],
    region: 'SOUTH',
    slot: ['rice'],
    is_veg: false, is_vegan: false, is_jain: false, is_fasting: false, is_street: false,
    is_non_veg_type: 'prawn', allowed_days: [], occasion: ['party', 'everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },

  // ── BREAD (3) ───────────────────────────────────────────────────────────────

  {
    name: 'Pathiri',
    name_hindi: 'पाथिरी',
    name_regional: 'പത്തിരി',
    description: 'Thin unleavened rice flour flatbread from Malabar — soft, white, and slightly smoky, eaten with chicken or fish curry.',
    cuisine: ['Kerala'],
    region: 'SOUTH',
    slot: ['bread'],
    is_veg: true, is_vegan: true, is_jain: true, is_fasting: false, is_street: false,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Orotti',
    name_hindi: 'ओरोट्टी',
    name_regional: 'ഒറോട്ടി',
    description: 'Thick rice and coconut flatbread from Kerala — denser and chewier than pathiri, eaten with spicy meat or fish curry.',
    cuisine: ['Kerala'],
    region: 'SOUTH',
    slot: ['bread'],
    is_veg: true, is_vegan: true, is_jain: true, is_fasting: false, is_street: false,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Nei Pathiri',
    name_hindi: 'नेई पाथिरी',
    name_regional: 'നെയ് പത്തിരി',
    description: 'Rice flour flatbread shallow-fried in ghee until golden and crisp — a festive Malabar Muslim bread for Eid and weddings.',
    cuisine: ['Kerala'],
    region: 'SOUTH',
    slot: ['bread'],
    is_veg: true, is_vegan: false, is_jain: true, is_fasting: false, is_street: false,
    is_non_veg_type: null, allowed_days: [], occasion: ['festival', 'party'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },

  // ── RAITA (2) ───────────────────────────────────────────────────────────────

  {
    name: 'Vellarikka Kichadi',
    name_hindi: 'वेल्लरिक्का किचाड़ी',
    name_regional: 'വെള്ളരിക്ക കിച്ചടി',
    description: 'Grated cucumber stirred into yogurt with a coconut paste and mustard seed tempering — a cool, refreshing Kerala sadya side.',
    cuisine: ['Kerala'],
    region: 'SOUTH',
    slot: ['raita'],
    is_veg: true, is_vegan: false, is_jain: true, is_fasting: false, is_street: false,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday', 'festival'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Beetroot Pachadi',
    name_hindi: 'बीटरूट पचड़ी',
    name_regional: 'ബീറ്റ്റൂട്ട് പച്ചടി',
    description: 'Grated beetroot cooked in coconut paste and folded into yogurt with a mustard tempering — a vibrant crimson Kerala raita.',
    cuisine: ['Kerala'],
    region: 'SOUTH',
    slot: ['raita'],
    is_veg: true, is_vegan: false, is_jain: false, is_fasting: false, is_street: false,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday', 'festival'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },

  // ── SNACK (1) ───────────────────────────────────────────────────────────────

  {
    name: 'Unniyappam',
    name_hindi: 'उन्नियप्पम',
    name_regional: 'ഉണ്ണിയപ്പം',
    description: 'Small deep-fried sweet rice and banana pancakes cooked in a special cast-iron mould — a Kerala temple prasad and evening snack.',
    cuisine: ['Kerala'],
    region: 'SOUTH',
    slot: ['snack'],
    is_veg: true, is_vegan: true, is_jain: true, is_fasting: false, is_street: false,
    is_non_veg_type: null, allowed_days: [], occasion: ['festival', 'everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },

  // ══════════════════════════════════════════════════════════════════════════════
  // STREET FOOD  (50)   — ALL dishes carry is_street: true
  // ══════════════════════════════════════════════════════════════════════════════

  // ── BREAKFAST (5) ───────────────────────────────────────────────────────────

  {
    name: 'Vada Pav',
    name_hindi: 'वड़ा पाव',
    name_regional: null,
    description: 'Deep-fried spiced potato dumpling sandwiched in a soft pav with green and tamarind chutneys — Mumbai working-class street icon.',
    cuisine: ['Street Food'],
    region: 'PAN_INDIA',
    slot: ['breakfast'],
    is_veg: true, is_vegan: true, is_jain: false, is_fasting: false, is_street: true,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Chole Kulche',
    name_hindi: 'छोले कुलचे',
    name_regional: null,
    description: 'Tangy spiced chickpeas served with soft leavened kulcha bread — the defining street breakfast of Delhi roadside carts.',
    cuisine: ['Street Food'],
    region: 'PAN_INDIA',
    slot: ['breakfast'],
    is_veg: true, is_vegan: false, is_jain: false, is_fasting: false, is_street: true,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Indore Poha',
    name_hindi: 'इंदौर पोहा',
    name_regional: null,
    description: 'Flattened rice cooked with onion, mustard, and turmeric, topped with sev, pomegranate, and a squeeze of lemon — the Indore street morning.',
    cuisine: ['Street Food'],
    region: 'PAN_INDIA',
    slot: ['breakfast'],
    is_veg: true, is_vegan: true, is_jain: false, is_fasting: false, is_street: true,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Urad Dal Kachori',
    name_hindi: 'उड़द दाल कचौरी',
    name_regional: null,
    description: 'Crispy deep-fried pastry stuffed with spiced urad dal, served with aloo sabzi and chutneys — a North Indian street breakfast staple.',
    cuisine: ['Street Food'],
    region: 'PAN_INDIA',
    slot: ['breakfast'],
    is_veg: true, is_vegan: true, is_jain: false, is_fasting: false, is_street: true,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Egg Bhurji Pav',
    name_hindi: 'एग भुर्जी पाव',
    name_regional: null,
    description: 'Spiced scrambled eggs cooked with onion, tomato, and green chilli on a hot tawa, served with buttered pav — a pan-India street breakfast.',
    cuisine: ['Street Food'],
    region: 'PAN_INDIA',
    slot: ['breakfast'],
    is_veg: false, is_vegan: false, is_jain: false, is_fasting: false, is_street: true,
    is_non_veg_type: 'egg', allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },

  // ── LUNCH_CURRY (5) ─────────────────────────────────────────────────────────

  {
    name: 'Pav Bhaji',
    name_hindi: 'पाव भाजी',
    name_regional: null,
    description: 'Spiced mixed vegetable mash cooked on a large iron tawa with generous butter, served with soft toasted pav — Mumbai street lunch king.',
    cuisine: ['Street Food'],
    region: 'PAN_INDIA',
    slot: ['lunch_curry'],
    is_veg: true, is_vegan: false, is_jain: false, is_fasting: false, is_street: true,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Tawa Pulao',
    name_hindi: 'तवा पुलाव',
    name_regional: null,
    description: 'Leftover rice stir-fried on a tawa with pav bhaji masala, vegetables, and butter — a Mumbai street lunch staple born from excess.',
    cuisine: ['Street Food'],
    region: 'PAN_INDIA',
    slot: ['lunch_curry'],
    is_veg: true, is_vegan: false, is_jain: false, is_fasting: false, is_street: true,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Vegetable Kathi Roll',
    name_hindi: 'वेजिटेबल काठी रोल',
    name_regional: null,
    description: 'Spiced paneer and vegetable filling wrapped in a flaky egg-brushed paratha — a Kolkata Kathi roll adapted for pan-India street markets.',
    cuisine: ['Street Food'],
    region: 'PAN_INDIA',
    slot: ['lunch_curry'],
    is_veg: true, is_vegan: false, is_jain: false, is_fasting: false, is_street: true,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Bombay Toast Sandwich',
    name_hindi: 'बॉम्बे टोस्ट सैंडविच',
    name_regional: null,
    description: 'Multi-layer grilled sandwich with green chutney, potato, cucumber, tomato, and cheese pressed on a griddle — Mumbai street lunch.',
    cuisine: ['Street Food'],
    region: 'PAN_INDIA',
    slot: ['lunch_curry'],
    is_veg: true, is_vegan: false, is_jain: false, is_fasting: false, is_street: true,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Chicken Frankie',
    name_hindi: 'चिकन फ्रैंकी',
    name_regional: null,
    description: 'Spiced chicken tikka wrapped in a soft paratha with onion, lemon, and chilli sauce — Mumbai Frankie chain origin, now pan-India.',
    cuisine: ['Street Food'],
    region: 'PAN_INDIA',
    slot: ['lunch_curry'],
    is_veg: false, is_vegan: false, is_jain: false, is_fasting: false, is_street: true,
    is_non_veg_type: 'chicken', allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },

  // ── SNACK (40) ──────────────────────────────────────────────────────────────

  {
    name: 'Pani Puri',
    name_hindi: 'पानी पुरी',
    name_regional: null,
    description: 'Hollow crispy puris filled with spiced potato and chickpea, dipped in cold tangy mint-tamarind water — India most beloved street snack.',
    cuisine: ['Street Food'],
    region: 'PAN_INDIA',
    slot: ['snack'],
    is_veg: true, is_vegan: true, is_jain: false, is_fasting: false, is_street: true,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Bhel Puri',
    name_hindi: 'भेल पूरी',
    name_regional: null,
    description: 'Puffed rice tossed with tomato, onion, raw mango, tamarind chutney, and sev — Mumbai Marine Drive snack, sour-sweet-spicy.',
    cuisine: ['Street Food'],
    region: 'PAN_INDIA',
    slot: ['snack'],
    is_veg: true, is_vegan: true, is_jain: false, is_fasting: false, is_street: true,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Sev Puri',
    name_hindi: 'सेव पूरी',
    name_regional: null,
    description: 'Flat puris topped with diced potato, onion, tamarind chutney, green chutney, and a mountain of thin sev — a Mumbai chaat classic.',
    cuisine: ['Street Food'],
    region: 'PAN_INDIA',
    slot: ['snack'],
    is_veg: true, is_vegan: true, is_jain: false, is_fasting: false, is_street: true,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Dahi Puri',
    name_hindi: 'दही पुरी',
    name_regional: null,
    description: 'Hollow puris filled with potato and chickpea, topped with sweetened yogurt, tamarind chutney, and sev — Mumbai street chaat.',
    cuisine: ['Street Food'],
    region: 'PAN_INDIA',
    slot: ['snack'],
    is_veg: true, is_vegan: false, is_jain: false, is_fasting: false, is_street: true,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Dahi Bhalla',
    name_hindi: 'दही भल्ला',
    name_regional: null,
    description: 'Soaked urad dal dumplings smothered in cold spiced yogurt with tamarind chutney, cumin powder, and raisins — Old Delhi street staple.',
    cuisine: ['Street Food'],
    region: 'PAN_INDIA',
    slot: ['snack'],
    is_veg: true, is_vegan: false, is_jain: false, is_fasting: false, is_street: true,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday', 'festival'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Aloo Tikki',
    name_hindi: 'आलू टिक्की',
    name_regional: null,
    description: 'Shallow-fried spiced potato patties served with chutneys, yogurt, and chole — an everyday North Indian street snack.',
    cuisine: ['Street Food'],
    region: 'PAN_INDIA',
    slot: ['snack'],
    is_veg: true, is_vegan: false, is_jain: false, is_fasting: false, is_street: true,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Samosa',
    name_hindi: 'समोसा',
    name_regional: null,
    description: 'Crispy deep-fried pastry filled with spiced potato and peas — the most universal Indian street snack, found across every city and town.',
    cuisine: ['Street Food'],
    region: 'PAN_INDIA',
    slot: ['snack'],
    is_veg: true, is_vegan: true, is_jain: false, is_fasting: false, is_street: true,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Raj Kachori',
    name_hindi: 'राज कचौरी',
    name_regional: null,
    description: 'Giant crispy kachori shell filled with potato, sprouts, yogurt, tamarind, and sev — Delhi street food royalty.',
    cuisine: ['Street Food'],
    region: 'PAN_INDIA',
    slot: ['snack'],
    is_veg: true, is_vegan: false, is_jain: false, is_fasting: false, is_street: true,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Jalebi',
    name_hindi: 'जलेबी',
    name_regional: null,
    description: 'Fermented batter piped in spirals and deep-fried, then soaked in saffron-scented sugar syrup — the golden crispy street sweet of India.',
    cuisine: ['Street Food'],
    region: 'PAN_INDIA',
    slot: ['snack'],
    is_veg: true, is_vegan: true, is_jain: true, is_fasting: false, is_street: true,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday', 'festival'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Ragda Pattice',
    name_hindi: 'रगड़ा पैटीस',
    name_regional: null,
    description: 'Crispy potato patties topped with dried white pea curry, tamarind chutney, and sev — a complete Mumbai street meal-snack.',
    cuisine: ['Street Food'],
    region: 'PAN_INDIA',
    slot: ['snack'],
    is_veg: true, is_vegan: true, is_jain: false, is_fasting: false, is_street: true,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Puchka',
    name_hindi: 'पुचका',
    name_regional: null,
    description: "Kolkata's version of pani puri — filled with spiced potato and tamarind water flavoured with black salt, the crunchiest variant.",
    cuisine: ['Street Food'],
    region: 'PAN_INDIA',
    slot: ['snack'],
    is_veg: true, is_vegan: true, is_jain: false, is_fasting: false, is_street: true,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Jhalmuri',
    name_hindi: 'झालमुरी',
    name_regional: null,
    description: 'Puffed rice tossed by hand with mustard oil, raw onion, green chilli, raw mango, and chanachur — Kolkata park snack, no two same.',
    cuisine: ['Street Food'],
    region: 'PAN_INDIA',
    slot: ['snack'],
    is_veg: true, is_vegan: true, is_jain: false, is_fasting: false, is_street: true,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Papdi Chaat',
    name_hindi: 'पापड़ी चाट',
    name_regional: null,
    description: 'Crispy fried wafers layered with boiled potato, chickpea, yogurt, tamarind, green chutney, and sev — Chandni Chowk chaat at its finest.',
    cuisine: ['Street Food'],
    region: 'PAN_INDIA',
    slot: ['snack'],
    is_veg: true, is_vegan: false, is_jain: false, is_fasting: false, is_street: true,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Masala Puri',
    name_hindi: 'मसाला पुरी',
    name_regional: null,
    description: 'Fried puris crushed and topped with a spiced green pea masala, onion, and chutneys — the signature street snack of Bangalore.',
    cuisine: ['Street Food'],
    region: 'PAN_INDIA',
    slot: ['snack'],
    is_veg: true, is_vegan: true, is_jain: false, is_fasting: false, is_street: true,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Mirchi Bajji',
    name_hindi: 'मिर्ची भजी',
    name_regional: null,
    description: 'Large banana peppers or green chillies dipped in spiced gram flour batter and deep-fried — a popular snack across Andhra and Maharashtra.',
    cuisine: ['Street Food'],
    region: 'PAN_INDIA',
    slot: ['snack'],
    is_veg: true, is_vegan: true, is_jain: false, is_fasting: false, is_street: true,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Bread Pakoda',
    name_hindi: 'ब्रेड पकोड़ा',
    name_regional: null,
    description: 'Bread slices stuffed with spiced potato, dipped in gram flour batter and deep-fried — a hearty North Indian street snack.',
    cuisine: ['Street Food'],
    region: 'PAN_INDIA',
    slot: ['snack'],
    is_veg: true, is_vegan: true, is_jain: false, is_fasting: false, is_street: true,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Pyaz Kachori',
    name_hindi: 'प्याज़ कचौरी',
    name_regional: null,
    description: 'Jodhpuri deep-fried pastry with a crispy shell filled with caramelised spiced onion — a Rajasthan morning street snack.',
    cuisine: ['Street Food'],
    region: 'PAN_INDIA',
    slot: ['snack'],
    is_veg: true, is_vegan: true, is_jain: false, is_fasting: false, is_street: true,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Mawa Kachori',
    name_hindi: 'मावा कचौरी',
    name_regional: null,
    description: 'Deep-fried flaky pastry filled with sweetened khoya and dry fruits, soaked in sugar syrup — Jodhpur exclusive festival sweet snack.',
    cuisine: ['Street Food'],
    region: 'PAN_INDIA',
    slot: ['snack'],
    is_veg: true, is_vegan: false, is_jain: false, is_fasting: false, is_street: true,
    is_non_veg_type: null, allowed_days: [], occasion: ['festival', 'everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Onion Bhajiya',
    name_hindi: 'प्याज़ भजिया',
    name_regional: null,
    description: 'Thinly sliced onion rings coated in spiced gram flour batter and deep-fried crispy — the monsoon snack of every Indian street stall.',
    cuisine: ['Street Food'],
    region: 'PAN_INDIA',
    slot: ['snack'],
    is_veg: true, is_vegan: true, is_jain: false, is_fasting: false, is_street: true,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Bhutta',
    name_hindi: 'भुट्टा',
    name_regional: null,
    description: 'Corn cob roasted on live coals, rubbed with lemon, red chilli, and black salt — the simplest and most elemental Indian street snack.',
    cuisine: ['Street Food'],
    region: 'PAN_INDIA',
    slot: ['snack'],
    is_veg: true, is_vegan: true, is_jain: true, is_fasting: true, is_street: true,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Corn Bhel',
    name_hindi: 'कॉर्न भेल',
    name_regional: null,
    description: 'Boiled sweet corn tossed with onion, tomato, chilli, lemon juice, and chaat masala — a Mumbai street cart snack popular at beaches.',
    cuisine: ['Street Food'],
    region: 'PAN_INDIA',
    slot: ['snack'],
    is_veg: true, is_vegan: true, is_jain: true, is_fasting: false, is_street: true,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Aloo Chaat',
    name_hindi: 'आलू चाट',
    name_regional: null,
    description: 'Crispy fried potato pieces tossed with yogurt, tamarind chutney, cumin, and chaat masala — a tangy, addictive street snack.',
    cuisine: ['Street Food'],
    region: 'PAN_INDIA',
    slot: ['snack'],
    is_veg: true, is_vegan: false, is_jain: false, is_fasting: false, is_street: true,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Ram Ladoo',
    name_hindi: 'राम लड्डू',
    name_regional: null,
    description: 'Tiny crispy fried moong dal balls served with shredded white radish and tangy green chutney — a Delhi-exclusive street snack.',
    cuisine: ['Street Food'],
    region: 'PAN_INDIA',
    slot: ['snack'],
    is_veg: true, is_vegan: true, is_jain: false, is_fasting: false, is_street: true,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Daulat ki Chaat',
    name_hindi: 'दौलत की चाट',
    name_regional: null,
    description: 'Light-as-air chilled milk foam set overnight in winter dew, topped with saffron and pistachios — Old Delhi winter-only street dessert.',
    cuisine: ['Street Food'],
    region: 'PAN_INDIA',
    slot: ['snack'],
    is_veg: true, is_vegan: false, is_jain: true, is_fasting: false, is_street: true,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Kulfi',
    name_hindi: 'कुल्फी',
    name_regional: null,
    description: 'Dense slow-frozen Indian ice cream made from reduced milk with cardamom, saffron, and pistachios — the original sub-continental frozen dessert.',
    cuisine: ['Street Food'],
    region: 'PAN_INDIA',
    slot: ['snack'],
    is_veg: true, is_vegan: false, is_jain: true, is_fasting: false, is_street: true,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Keema Pav',
    name_hindi: 'कीमा पाव',
    name_regional: null,
    description: 'Spiced minced mutton served with soft buttered pav — an Irani café and street staple of Mumbai and Pune.',
    cuisine: ['Street Food'],
    region: 'PAN_INDIA',
    slot: ['snack'],
    is_veg: false, is_vegan: false, is_jain: false, is_fasting: false, is_street: true,
    is_non_veg_type: 'mutton', allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Chicken Tikka Roll',
    name_hindi: 'चिकन टिक्का रोल',
    name_regional: null,
    description: 'Tandoor-charred chicken tikka wrapped in a flaky paratha with green chutney, onion, and chaat masala — a pan-India street roll.',
    cuisine: ['Street Food'],
    region: 'PAN_INDIA',
    slot: ['snack'],
    is_veg: false, is_vegan: false, is_jain: false, is_fasting: false, is_street: true,
    is_non_veg_type: 'chicken', allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Momo',
    name_hindi: 'मोमो',
    name_regional: null,
    description: 'Steamed or fried Tibetan-origin dumplings filled with spiced vegetables or chicken, served with fiery red chutney — pan-India street staple.',
    cuisine: ['Street Food'],
    region: 'PAN_INDIA',
    slot: ['snack'],
    is_veg: true, is_vegan: false, is_jain: false, is_fasting: false, is_street: true,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Chilli Chicken',
    name_hindi: 'चिली चिकन',
    name_regional: null,
    description: 'Crispy fried chicken tossed in a tangy soy-garlic-green chilli sauce — Indian-Chinese street food born in Kolkata, now everywhere.',
    cuisine: ['Street Food'],
    region: 'PAN_INDIA',
    slot: ['snack'],
    is_veg: false, is_vegan: false, is_jain: false, is_fasting: false, is_street: true,
    is_non_veg_type: 'chicken', allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Hakka Noodles',
    name_hindi: 'हक्का नूडल्स',
    name_regional: null,
    description: 'Stir-fried noodles with vegetables, soy sauce, and green chilli — Indo-Chinese street food sold from every Schezwan cart across India.',
    cuisine: ['Street Food'],
    region: 'PAN_INDIA',
    slot: ['snack'],
    is_veg: true, is_vegan: true, is_jain: false, is_fasting: false, is_street: true,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Medu Vada',
    name_hindi: 'मेदू वड़ा',
    name_regional: null,
    description: 'Crispy fried urad dal donuts with a soft interior, served with sambar and coconut chutney — a South Indian street breakfast snack.',
    cuisine: ['Street Food'],
    region: 'PAN_INDIA',
    slot: ['snack'],
    is_veg: true, is_vegan: true, is_jain: false, is_fasting: false, is_street: true,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Mysore Bonda',
    name_hindi: 'मैसूर बोंडा',
    name_regional: null,
    description: 'Soft deep-fried maida balls with a slightly tangy batter — a Bangalore street snack served with coconut chutney and sambar.',
    cuisine: ['Street Food'],
    region: 'PAN_INDIA',
    slot: ['snack'],
    is_veg: true, is_vegan: true, is_jain: false, is_fasting: false, is_street: true,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Batata Bhajia',
    name_hindi: 'बटाटा भजिया',
    name_regional: null,
    description: 'Thin sliced potato rounds coated in spiced gram flour batter and deep-fried until golden — a Gujarati and Mumbai street staple.',
    cuisine: ['Street Food'],
    region: 'PAN_INDIA',
    slot: ['snack'],
    is_veg: true, is_vegan: true, is_jain: false, is_fasting: false, is_street: true,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Litti Chokha',
    name_hindi: 'लिट्टी चोखा',
    name_regional: null,
    description: 'Charcoal-roasted wheat balls filled with spiced sattu, served with smoky roasted aubergine chokha — Bihar and Jharkhand street soul food.',
    cuisine: ['Street Food'],
    region: 'PAN_INDIA',
    slot: ['snack'],
    is_veg: true, is_vegan: true, is_jain: false, is_fasting: false, is_street: true,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Ghugni',
    name_hindi: 'घुघनी',
    name_regional: null,
    description: 'Spiced dried yellow pea curry topped with raw onion, green chilli, coconut, and tamarind — Bengal and Odisha street snack staple.',
    cuisine: ['Street Food'],
    region: 'PAN_INDIA',
    slot: ['snack'],
    is_veg: true, is_vegan: true, is_jain: false, is_fasting: false, is_street: true,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Egg Roll',
    name_hindi: 'एग रोल',
    name_regional: null,
    description: 'Egg omelette cooked directly on a paratha, rolled with spiced chicken or vegetables, onion, and green chutney — Kolkata street staple.',
    cuisine: ['Street Food'],
    region: 'PAN_INDIA',
    slot: ['snack'],
    is_veg: false, is_vegan: false, is_jain: false, is_fasting: false, is_street: true,
    is_non_veg_type: 'egg', allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Mutton Kathi Roll',
    name_hindi: 'मटन काठी रोल',
    name_regional: null,
    description: "Slow-cooked mutton wrapped in a flaky paratha with raw onion, lemon, and chilli — the original Kolkata Nizam's street roll.",
    cuisine: ['Street Food'],
    region: 'PAN_INDIA',
    slot: ['snack'],
    is_veg: false, is_vegan: false, is_jain: false, is_fasting: false, is_street: true,
    is_non_veg_type: 'mutton', allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Poha Chivda',
    name_hindi: 'पोहा चिवड़ा',
    name_regional: null,
    description: 'Crispy flattened rice tossed with peanuts, curry leaves, mustard seeds, turmeric, and sugar — a light and addictive Indian street snack mix.',
    cuisine: ['Street Food'],
    region: 'PAN_INDIA',
    slot: ['snack'],
    is_veg: true, is_vegan: true, is_jain: false, is_fasting: false, is_street: true,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Aloo Bonda',
    name_hindi: 'आलू बोंडा',
    name_regional: null,
    description: 'Spiced mashed potato balls coated in gram flour batter and deep-fried — the South Indian street counterpart to the Maharashtrian vada.',
    cuisine: ['Street Food'],
    region: 'PAN_INDIA',
    slot: ['snack'],
    is_veg: true, is_vegan: true, is_jain: false, is_fasting: false, is_street: true,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Dal Kachori',
    name_hindi: 'दाल कचौरी',
    name_regional: null,
    description: 'Crispy deep-fried pastry filled with coarse moong dal and Rajasthani spices — a classic street snack from Rajasthan and UP.',
    cuisine: ['Street Food'],
    region: 'PAN_INDIA',
    slot: ['snack'],
    is_veg: true, is_vegan: true, is_jain: false, is_fasting: false, is_street: true,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
];

// ─── Seed ─────────────────────────────────────────────────────────────────────

async function seed() {
  const BATCH_SIZE = 20;
  let totalInserted = 0;
  let totalErrors = 0;

  const kerala = dishes.filter(d => d.cuisine?.includes('Kerala'));
  const street = dishes.filter(d => d.cuisine?.includes('Street Food'));

  console.log(`\nSeeding ${dishes.length} dishes (Kerala: ${kerala.length} | Street Food: ${street.length})\n`);

  for (let i = 0; i < dishes.length; i += BATCH_SIZE) {
    const batch = dishes.slice(i, i + BATCH_SIZE);
    const batchNum = Math.floor(i / BATCH_SIZE) + 1;

    const { error } = await client.from('dishes').insert(batch);

    if (error) {
      console.error(`  Batch ${batchNum} ERROR: ${error.message}`);
      totalErrors += batch.length;
    } else {
      totalInserted += batch.length;
      console.log(`  Batch ${batchNum}: inserted ${batch.length} dishes (running total: ${totalInserted})`);
    }
  }

  console.log(`\nDone. Inserted: ${totalInserted} | Errors: ${totalErrors}\n`);

  // ── Verification ─────────────────────────────────────────────────────────────

  console.log('Verification query:');
  console.log("  SELECT cuisine[1] as cuisine, COUNT(*) FROM dishes WHERE cuisine && ARRAY['Kerala','Street Food'] GROUP BY cuisine[1];\n");

  const { data: keralaRows, error: keralaErr } = await client
    .from('dishes')
    .select('cuisine')
    .contains('cuisine', ['Kerala']);

  const { data: streetRows, error: streetErr } = await client
    .from('dishes')
    .select('cuisine')
    .contains('cuisine', ['Street Food']);

  if (keralaErr || streetErr) {
    console.error('Verification error:', keralaErr?.message ?? streetErr?.message);
    return;
  }

  const counts: Record<string, number> = {
    Kerala: (keralaRows || []).length,
    'Street Food': (streetRows || []).length,
  };

  // ── Audit table ──────────────────────────────────────────────────────────────

  const generated: Record<string, number> = {
    Kerala: kerala.length,
    'Street Food': street.length,
  };

  console.log('┌──────────────┬──────────────────┬─────────────────┬────────┐');
  console.log('│ Cuisine      │ Dishes generated │ Dishes inserted │ Errors │');
  console.log('├──────────────┼──────────────────┼─────────────────┼────────┤');

  for (const cuisine of ['Kerala', 'Street Food']) {
    const gen = generated[cuisine];
    const ins = counts[cuisine] ?? 0;
    const err = gen - ins;
    console.log(
      `│ ${cuisine.padEnd(12)} │ ${String(gen).padEnd(16)} │ ${String(ins).padEnd(15)} │ ${String(err).padEnd(6)} │`,
    );
  }

  console.log('├──────────────┼──────────────────┼─────────────────┼────────┤');
  const totalGen = generated['Kerala'] + generated['Street Food'];
  const totalIns = counts['Kerala'] + counts['Street Food'];
  console.log(
    `│ ${'TOTAL'.padEnd(12)} │ ${String(totalGen).padEnd(16)} │ ${String(totalIns).padEnd(15)} │ ${String(totalGen - totalIns).padEnd(6)} │`,
  );
  console.log('└──────────────┴──────────────────┴─────────────────┴────────┘');
}

seed().catch(console.error);
