// seed-v2-malvani.ts
// 50 Malvani dishes: 10 breakfast | 12 lunch_curry | 12 dinner_curry | 8 veg_side | 4 rice | 2 bread | 2 raita

import { createClient } from '@supabase/supabase-js';
require('dotenv').config();

const supabase = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL!,
  process.env.SUPABASE_SERVICE_ROLE_KEY!
);

const dishes = [
  // ── BREAKFAST (10) ──────────────────────────────────────────────
  {
    name: 'Ghavan',
    name_regional: 'Ghavan',
    description: 'Thin rice flour crepe, Malvani style with coconut',
    cuisine: ['Malvani'],
    region: 'Konkan',
    slot: ['breakfast'],
    is_veg: true,
    is_vegan: true,
    is_jain: false,
    is_fasting: false,
    is_street: false,
    occasion: ['everyday'],
    health_tags: ['light', 'gluten-free'],
  },
  {
    name: 'Amboli',
    name_regional: 'Amboli',
    description: 'Fermented rice and urad dal pancake, spongy and soft',
    cuisine: ['Malvani'],
    region: 'Konkan',
    slot: ['breakfast'],
    is_veg: true,
    is_vegan: true,
    is_jain: false,
    is_fasting: false,
    is_street: false,
    occasion: ['everyday'],
    health_tags: ['fermented', 'probiotic'],
  },
  {
    name: 'Ukdiche Modak',
    name_regional: 'Ukdiche Modak',
    description: 'Steamed rice modak with coconut-jaggery filling',
    cuisine: ['Malvani'],
    region: 'Konkan',
    slot: ['breakfast'],
    is_veg: true,
    is_vegan: true,
    is_jain: false,
    is_fasting: false,
    is_street: false,
    occasion: ['ganesh-chaturthi', 'festival'],
    health_tags: ['festive', 'steamed'],
  },
  {
    name: 'Pej',
    name_regional: 'Pej',
    description: 'Thin rice porridge, Malvani breakfast staple',
    cuisine: ['Malvani'],
    region: 'Konkan',
    slot: ['breakfast'],
    is_veg: true,
    is_vegan: true,
    is_jain: false,
    is_fasting: true,
    is_street: false,
    occasion: ['everyday'],
    health_tags: ['light', 'easy-digest'],
  },
  {
    name: 'Malvani Poha',
    name_regional: 'Malvani Poha',
    description: 'Flattened rice with coconut, curry leaves and mustard',
    cuisine: ['Malvani'],
    region: 'Konkan',
    slot: ['breakfast'],
    is_veg: true,
    is_vegan: true,
    is_jain: false,
    is_fasting: false,
    is_street: false,
    occasion: ['everyday'],
    health_tags: ['light', 'quick'],
  },
  {
    name: 'Neer Dosa',
    name_regional: 'Neer Dosa',
    description: 'Thin watery rice batter crepe, delicate and lacy',
    cuisine: ['Malvani', 'Konkani'],
    region: 'Konkan',
    slot: ['breakfast'],
    is_veg: true,
    is_vegan: true,
    is_jain: false,
    is_fasting: false,
    is_street: false,
    occasion: ['everyday'],
    health_tags: ['light', 'gluten-free'],
  },
  {
    name: 'Sabudana Khichdi Malvani',
    name_regional: 'Sabudana Khichdi',
    description: 'Tapioca pearls with peanuts and green chilli, fasting-friendly',
    cuisine: ['Malvani'],
    region: 'Konkan',
    slot: ['breakfast'],
    is_veg: true,
    is_vegan: false,
    is_jain: false,
    is_fasting: true,
    is_street: false,
    occasion: ['everyday', 'fast'],
    health_tags: ['fasting', 'energising'],
  },
  {
    name: 'Rava Upma Malvani',
    name_regional: 'Rava Upma',
    description: 'Semolina upma tempered with curry leaves and coconut',
    cuisine: ['Malvani'],
    region: 'Konkan',
    slot: ['breakfast'],
    is_veg: true,
    is_vegan: false,
    is_jain: false,
    is_fasting: false,
    is_street: false,
    occasion: ['everyday'],
    health_tags: ['quick', 'filling'],
  },
  {
    name: 'Idli with Malvani Chutney',
    name_regional: 'Idli',
    description: 'Steamed rice cakes served with spiced coconut chutney',
    cuisine: ['Malvani'],
    region: 'Konkan',
    slot: ['breakfast'],
    is_veg: true,
    is_vegan: true,
    is_jain: false,
    is_fasting: false,
    is_street: false,
    occasion: ['everyday'],
    health_tags: ['fermented', 'probiotic', 'light'],
  },
  {
    name: 'Shevai',
    name_regional: 'Shevai',
    description: 'Hand-pressed rice noodles, steamed and served with coconut milk',
    cuisine: ['Malvani', 'Konkani'],
    region: 'Konkan',
    slot: ['breakfast'],
    is_veg: true,
    is_vegan: true,
    is_jain: false,
    is_fasting: false,
    is_street: false,
    occasion: ['everyday'],
    health_tags: ['light', 'gluten-free'],
  },

  // ── LUNCH CURRY (12) ────────────────────────────────────────────
  {
    name: 'Malvani Kombdi Rassa',
    name_regional: 'Kombdi Rassa',
    description: 'Fiery Malvani chicken curry with freshly ground coconut masala',
    cuisine: ['Malvani'],
    region: 'Konkan',
    slot: ['lunch_curry'],
    is_veg: false,
    is_vegan: false,
    is_jain: false,
    is_fasting: false,
    is_street: false,
    is_non_veg_type: 'chicken',
    allowed_days: ['Sunday'],
    occasion: ['everyday', 'sunday-special'],
    health_tags: ['protein-rich', 'spicy'],
  },
  {
    name: 'Malvani Mutton Rassa',
    name_regional: 'Mutton Rassa',
    description: 'Slow-cooked mutton in Malvani masala, rich and aromatic',
    cuisine: ['Malvani'],
    region: 'Konkan',
    slot: ['lunch_curry'],
    is_veg: false,
    is_vegan: false,
    is_jain: false,
    is_fasting: false,
    is_street: false,
    is_non_veg_type: 'mutton',
    allowed_days: ['Sunday'],
    occasion: ['sunday-special', 'festive'],
    health_tags: ['protein-rich', 'spicy'],
  },
  {
    name: 'Kolambi Masala Malvani',
    name_regional: 'Kolambi Masala',
    description: 'Malvani prawn curry with kokum and freshly grated coconut',
    cuisine: ['Malvani'],
    region: 'Konkan',
    slot: ['lunch_curry'],
    is_veg: false,
    is_vegan: false,
    is_jain: false,
    is_fasting: false,
    is_street: false,
    is_non_veg_type: 'prawn',
    occasion: ['everyday'],
    health_tags: ['seafood', 'coastal'],
  },
  {
    name: 'Surmai Curry Malvani',
    name_regional: 'Surmai Curry',
    description: 'King fish curry in bold Malvani coconut-red chilli gravy',
    cuisine: ['Malvani'],
    region: 'Konkan',
    slot: ['lunch_curry'],
    is_veg: false,
    is_vegan: false,
    is_jain: false,
    is_fasting: false,
    is_street: false,
    is_non_veg_type: 'fish',
    occasion: ['everyday'],
    health_tags: ['seafood', 'omega-3'],
  },
  {
    name: 'Bangda Masala Malvani',
    name_regional: 'Bangda Masala',
    description: 'Mackerel in Malvani masala, tangy and robust',
    cuisine: ['Malvani'],
    region: 'Konkan',
    slot: ['lunch_curry'],
    is_veg: false,
    is_vegan: false,
    is_jain: false,
    is_fasting: false,
    is_street: false,
    is_non_veg_type: 'fish',
    occasion: ['everyday'],
    health_tags: ['seafood', 'omega-3'],
  },
  {
    name: 'Malvani Egg Curry',
    name_regional: 'Anda Masala Malvani',
    description: 'Boiled eggs simmered in spicy Malvani coconut gravy',
    cuisine: ['Malvani'],
    region: 'Konkan',
    slot: ['lunch_curry'],
    is_veg: false,
    is_vegan: false,
    is_jain: false,
    is_fasting: false,
    is_street: false,
    is_non_veg_type: 'egg',
    occasion: ['everyday'],
    health_tags: ['protein-rich'],
  },
  {
    name: 'Dalimbi Usal',
    name_regional: 'Dalimbi Usal',
    description: 'Field beans cooked with coconut and Malvani spices',
    cuisine: ['Malvani'],
    region: 'Konkan',
    slot: ['lunch_curry'],
    is_veg: true,
    is_vegan: true,
    is_jain: false,
    is_fasting: false,
    is_street: false,
    occasion: ['everyday'],
    health_tags: ['protein-rich', 'fibre-rich'],
  },
  {
    name: 'Kala Watana Usal',
    name_regional: 'Kala Vatana Usal',
    description: 'Black peas cooked with coconut masala, a Malvani staple',
    cuisine: ['Malvani'],
    region: 'Konkan',
    slot: ['lunch_curry'],
    is_veg: true,
    is_vegan: true,
    is_jain: false,
    is_fasting: false,
    is_street: false,
    occasion: ['everyday'],
    health_tags: ['protein-rich', 'fibre-rich'],
  },
  {
    name: 'Moong Dal Malvani',
    name_regional: 'Moong Dal',
    description: 'Green moong dal tempered with coconut and Malvani spices',
    cuisine: ['Malvani'],
    region: 'Konkan',
    slot: ['lunch_curry'],
    is_veg: true,
    is_vegan: true,
    is_jain: false,
    is_fasting: false,
    is_street: false,
    occasion: ['everyday'],
    health_tags: ['light', 'protein-rich'],
  },
  {
    name: 'Solkadhi',
    name_regional: 'Sol Kadhi',
    description: 'Kokum and coconut milk digestive drink, cooling and tangy',
    cuisine: ['Malvani', 'Konkani'],
    region: 'Konkan',
    slot: ['lunch_curry'],
    is_veg: true,
    is_vegan: true,
    is_jain: false,
    is_fasting: false,
    is_street: false,
    occasion: ['everyday'],
    health_tags: ['probiotic', 'cooling', 'digestive'],
  },
  {
    name: 'Tisrya Masala Malvani',
    name_regional: 'Tisrya Masala',
    description: 'Clams cooked in freshly ground Malvani coconut masala',
    cuisine: ['Malvani'],
    region: 'Konkan',
    slot: ['lunch_curry'],
    is_veg: false,
    is_vegan: false,
    is_jain: false,
    is_fasting: false,
    is_street: false,
    is_non_veg_type: 'shellfish',
    occasion: ['everyday'],
    health_tags: ['seafood', 'coastal'],
  },
  {
    name: 'Rawas Curry Malvani',
    name_regional: 'Rawas Curry',
    description: 'Indian salmon in Malvani red coconut gravy',
    cuisine: ['Malvani'],
    region: 'Konkan',
    slot: ['lunch_curry'],
    is_veg: false,
    is_vegan: false,
    is_jain: false,
    is_fasting: false,
    is_street: false,
    is_non_veg_type: 'fish',
    occasion: ['everyday'],
    health_tags: ['seafood', 'omega-3', 'protein-rich'],
  },

  // ── DINNER CURRY (12) ────────────────────────────────────────────
  {
    name: 'Bangda Fry Malvani',
    name_regional: 'Bangda Tawa Fry',
    description: 'Mackerel marinated in Malvani masala and tawa-fried',
    cuisine: ['Malvani'],
    region: 'Konkan',
    slot: ['dinner_curry'],
    is_veg: false,
    is_vegan: false,
    is_jain: false,
    is_fasting: false,
    is_street: false,
    is_non_veg_type: 'fish',
    occasion: ['everyday'],
    health_tags: ['seafood', 'omega-3'],
  },
  {
    name: 'Kolambi Sukhe Malvani',
    name_regional: 'Kolambi Sukhe',
    description: 'Dry prawn stir-fry with Malvani spices and fresh coconut',
    cuisine: ['Malvani'],
    region: 'Konkan',
    slot: ['dinner_curry'],
    is_veg: false,
    is_vegan: false,
    is_jain: false,
    is_fasting: false,
    is_street: false,
    is_non_veg_type: 'prawn',
    occasion: ['everyday'],
    health_tags: ['seafood', 'protein-rich'],
  },
  {
    name: 'Surmai Tawa Fry',
    name_regional: 'Surmai Tawa Fry',
    description: 'King fish pan-fried in Malvani red chilli marinade',
    cuisine: ['Malvani'],
    region: 'Konkan',
    slot: ['dinner_curry'],
    is_veg: false,
    is_vegan: false,
    is_jain: false,
    is_fasting: false,
    is_street: false,
    is_non_veg_type: 'fish',
    occasion: ['everyday'],
    health_tags: ['seafood', 'omega-3'],
  },
  {
    name: 'Kande Pohe Malvani',
    name_regional: 'Kande Pohe',
    description: 'Spiced poha with onion and Malvani coconut finish',
    cuisine: ['Malvani'],
    region: 'Konkan',
    slot: ['dinner_curry'],
    is_veg: true,
    is_vegan: true,
    is_jain: false,
    is_fasting: false,
    is_street: false,
    occasion: ['everyday'],
    health_tags: ['light', 'quick'],
  },
  {
    name: 'Matki Usal Malvani',
    name_regional: 'Matki Usal',
    description: 'Moth beans cooked with freshly grated coconut and spices',
    cuisine: ['Malvani'],
    region: 'Konkan',
    slot: ['dinner_curry'],
    is_veg: true,
    is_vegan: true,
    is_jain: false,
    is_fasting: false,
    is_street: false,
    occasion: ['everyday'],
    health_tags: ['protein-rich', 'fibre-rich'],
  },
  {
    name: 'Egg Bhurji Malvani',
    name_regional: 'Anda Bhurji',
    description: 'Scrambled eggs with onion, tomato and Malvani spices',
    cuisine: ['Malvani'],
    region: 'Konkan',
    slot: ['dinner_curry'],
    is_veg: false,
    is_vegan: false,
    is_jain: false,
    is_fasting: false,
    is_street: false,
    is_non_veg_type: 'egg',
    occasion: ['everyday'],
    health_tags: ['protein-rich', 'quick'],
  },
  {
    name: 'Jawla Sukhe',
    name_regional: 'Jawla Sukhe',
    description: 'Dried shrimp stir-fry with coconut and Malvani masala',
    cuisine: ['Malvani'],
    region: 'Konkan',
    slot: ['dinner_curry'],
    is_veg: false,
    is_vegan: false,
    is_jain: false,
    is_fasting: false,
    is_street: false,
    is_non_veg_type: 'prawn',
    occasion: ['everyday'],
    health_tags: ['seafood', 'coastal'],
  },
  {
    name: 'Tambdi Bhaji Malvani',
    name_regional: 'Tambdi Bhaji',
    description: 'Red amaranth stir-fry with garlic and coconut',
    cuisine: ['Malvani'],
    region: 'Konkan',
    slot: ['dinner_curry'],
    is_veg: true,
    is_vegan: true,
    is_jain: false,
    is_fasting: false,
    is_street: false,
    occasion: ['everyday'],
    health_tags: ['iron-rich', 'light'],
  },
  {
    name: 'Chicken Malvani Dry',
    name_regional: 'Chicken Sukha Malvani',
    description: 'Dry chicken preparation with Malvani masala and coconut',
    cuisine: ['Malvani'],
    region: 'Konkan',
    slot: ['dinner_curry'],
    is_veg: false,
    is_vegan: false,
    is_jain: false,
    is_fasting: false,
    is_street: false,
    is_non_veg_type: 'chicken',
    occasion: ['everyday'],
    health_tags: ['protein-rich', 'spicy'],
  },
  {
    name: 'Varan Malvani',
    name_regional: 'Varan',
    description: 'Simple toor dal with turmeric and ghee, comfort dinner',
    cuisine: ['Malvani'],
    region: 'Konkan',
    slot: ['dinner_curry'],
    is_veg: true,
    is_vegan: false,
    is_jain: false,
    is_fasting: false,
    is_street: false,
    occasion: ['everyday'],
    health_tags: ['light', 'protein-rich', 'comfort'],
  },
  {
    name: 'Pomfret Masala Malvani',
    name_regional: 'Paplet Masala',
    description: 'Pomfret stuffed and cooked in Malvani masala',
    cuisine: ['Malvani'],
    region: 'Konkan',
    slot: ['dinner_curry'],
    is_veg: false,
    is_vegan: false,
    is_jain: false,
    is_fasting: false,
    is_street: false,
    is_non_veg_type: 'fish',
    occasion: ['everyday'],
    health_tags: ['seafood', 'omega-3'],
  },
  {
    name: 'Kala Chana Usal Malvani',
    name_regional: 'Kala Chana Usal',
    description: 'Black chickpeas cooked with coconut and Malvani spices',
    cuisine: ['Malvani'],
    region: 'Konkan',
    slot: ['dinner_curry'],
    is_veg: true,
    is_vegan: true,
    is_jain: false,
    is_fasting: false,
    is_street: false,
    occasion: ['everyday'],
    health_tags: ['protein-rich', 'fibre-rich'],
  },

  // ── VEG SIDE (8) ────────────────────────────────────────────────
  {
    name: 'Batata Sukhe Malvani',
    name_regional: 'Batata Sukhe',
    description: 'Dry potato stir-fry with Malvani masala and coconut',
    cuisine: ['Malvani'],
    region: 'Konkan',
    slot: ['veg_side'],
    is_veg: true,
    is_vegan: true,
    is_jain: false,
    is_fasting: false,
    is_street: false,
    occasion: ['everyday'],
    health_tags: ['filling'],
  },
  {
    name: 'Vaingem Sukhe Malvani',
    name_regional: 'Vaingem Sukhe',
    description: 'Brinjal stir-fry with coconut and red chilli',
    cuisine: ['Malvani'],
    region: 'Konkan',
    slot: ['veg_side'],
    is_veg: true,
    is_vegan: true,
    is_jain: false,
    is_fasting: false,
    is_street: false,
    occasion: ['everyday'],
    health_tags: ['antioxidant'],
  },
  {
    name: 'Kadgi Chakko Malvani',
    name_regional: 'Kadgi Chakko',
    description: 'Raw jackfruit dry curry with coconut and Malvani spices',
    cuisine: ['Malvani'],
    region: 'Konkan',
    slot: ['veg_side'],
    is_veg: true,
    is_vegan: true,
    is_jain: false,
    is_fasting: false,
    is_street: false,
    occasion: ['everyday'],
    health_tags: ['fibre-rich'],
  },
  {
    name: 'Bhende Sukhe Malvani',
    name_regional: 'Bhende Sukhe',
    description: 'Okra stir-fry with fresh coconut and spices',
    cuisine: ['Malvani'],
    region: 'Konkan',
    slot: ['veg_side'],
    is_veg: true,
    is_vegan: true,
    is_jain: false,
    is_fasting: false,
    is_street: false,
    occasion: ['everyday'],
    health_tags: ['fibre-rich'],
  },
  {
    name: 'Tendla Sukhe Malvani',
    name_regional: 'Tendla Sukhe',
    description: 'Ivy gourd stir-fry with mustard and coconut',
    cuisine: ['Malvani'],
    region: 'Konkan',
    slot: ['veg_side'],
    is_veg: true,
    is_vegan: true,
    is_jain: false,
    is_fasting: false,
    is_street: false,
    occasion: ['everyday'],
    health_tags: ['light', 'diabetic-friendly'],
  },
  {
    name: 'Dudhi Sabzi Malvani',
    name_regional: 'Dugdhi Bhaji',
    description: 'Bottle gourd cooked with coconut milk and mild spices',
    cuisine: ['Malvani'],
    region: 'Konkan',
    slot: ['veg_side'],
    is_veg: true,
    is_vegan: true,
    is_jain: false,
    is_fasting: false,
    is_street: false,
    occasion: ['everyday'],
    health_tags: ['light', 'easy-digest'],
  },
  {
    name: 'Koshimbir Malvani',
    name_regional: 'Koshimbir',
    description: 'Fresh cucumber and raw mango salad with coconut',
    cuisine: ['Malvani'],
    region: 'Konkan',
    slot: ['veg_side'],
    is_veg: true,
    is_vegan: true,
    is_jain: false,
    is_fasting: false,
    is_street: false,
    occasion: ['everyday'],
    health_tags: ['raw', 'cooling', 'probiotic'],
  },
  {
    name: 'Fanasachi Bhaji Malvani',
    name_regional: 'Fanasachi Bhaji',
    description: 'Raw jackfruit sabzi cooked Malvani style with garam masala',
    cuisine: ['Malvani'],
    region: 'Konkan',
    slot: ['veg_side'],
    is_veg: true,
    is_vegan: true,
    is_jain: false,
    is_fasting: false,
    is_street: false,
    occasion: ['everyday'],
    health_tags: ['fibre-rich'],
  },

  // ── RICE (4) ────────────────────────────────────────────────────
  {
    name: 'Ukde Sheeth',
    name_regional: 'Ukde Sheeth',
    description: 'Parboiled red rice, Malvani table staple',
    cuisine: ['Malvani'],
    region: 'Konkan',
    slot: ['rice'],
    is_veg: true,
    is_vegan: true,
    is_jain: false,
    is_fasting: false,
    is_street: false,
    occasion: ['everyday'],
    health_tags: ['whole-grain', 'fibre-rich'],
  },
  {
    name: 'Kolambi Bhaat Malvani',
    name_regional: 'Kolambi Bhaat',
    description: 'Prawn rice cooked in Malvani spices, Sunday special',
    cuisine: ['Malvani'],
    region: 'Konkan',
    slot: ['rice'],
    is_veg: false,
    is_vegan: false,
    is_jain: false,
    is_fasting: false,
    is_street: false,
    is_non_veg_type: 'prawn',
    allowed_days: ['Sunday'],
    occasion: ['sunday-special'],
    health_tags: ['protein-rich', 'seafood'],
  },
  {
    name: 'Malvani Masale Bhaat',
    name_regional: 'Masale Bhaat',
    description: 'Spiced rice with vegetables and Malvani masala',
    cuisine: ['Malvani'],
    region: 'Konkan',
    slot: ['rice'],
    is_veg: true,
    is_vegan: true,
    is_jain: false,
    is_fasting: false,
    is_street: false,
    occasion: ['everyday'],
    health_tags: ['one-pot'],
  },
  {
    name: 'Coconut Rice Malvani',
    name_regional: 'Nariyal Bhaat',
    description: 'Steamed rice tempered with coconut, curry leaves and mustard',
    cuisine: ['Malvani'],
    region: 'Konkan',
    slot: ['rice'],
    is_veg: true,
    is_vegan: true,
    is_jain: false,
    is_fasting: false,
    is_street: false,
    occasion: ['everyday'],
    health_tags: ['light', 'aromatic'],
  },

  // ── BREAD (2) ────────────────────────────────────────────────────
  {
    name: 'Malvani Bhakri',
    name_regional: 'Tandulacha Bhakri',
    description: 'Rice flour flatbread, Malvani staple for fish curries',
    cuisine: ['Malvani'],
    region: 'Konkan',
    slot: ['bread'],
    is_veg: true,
    is_vegan: true,
    is_jain: false,
    is_fasting: false,
    is_street: false,
    occasion: ['everyday'],
    health_tags: ['gluten-free'],
  },
  {
    name: 'Vade Malvani',
    name_regional: 'Vade',
    description: 'Deep-fried rice flour puri, served with kala vatana rassa',
    cuisine: ['Malvani'],
    region: 'Konkan',
    slot: ['bread'],
    is_veg: true,
    is_vegan: true,
    is_jain: false,
    is_fasting: false,
    is_street: true,
    occasion: ['everyday', 'festival'],
    health_tags: ['festive'],
  },

  // ── RAITA (2) ────────────────────────────────────────────────────
  {
    name: 'Sol Kadhi Malvani',
    name_regional: 'Sol Kadhi',
    description: 'Kokum coconut milk digestive drink, cooling and pink',
    cuisine: ['Malvani'],
    region: 'Konkan',
    slot: ['raita'],
    is_veg: true,
    is_vegan: true,
    is_jain: false,
    is_fasting: false,
    is_street: false,
    occasion: ['everyday'],
    health_tags: ['probiotic', 'cooling', 'digestive'],
  },
  {
    name: 'Kakdi Koshimbir',
    name_regional: 'Kakdi Koshimbir',
    description: 'Cucumber raita with yoghurt, coconut and mustard tempering',
    cuisine: ['Malvani'],
    region: 'Konkan',
    slot: ['raita'],
    is_veg: true,
    is_vegan: false,
    is_jain: false,
    is_fasting: false,
    is_street: false,
    occasion: ['everyday'],
    health_tags: ['probiotic', 'cooling'],
  },
];

async function seed() {
  console.log(`Seeding ${dishes.length} Malvani dishes into Supabase...\n`);
  const BATCH = 20;
  let total = 0;
  let errors = 0;

  for (let i = 0; i < dishes.length; i += BATCH) {
    const batch = dishes.slice(i, i + BATCH);
    const { error } = await supabase.from('dishes').insert(batch);
    if (error) {
      console.error(`  Batch ${Math.floor(i / BATCH) + 1} error:`, error.message);
      errors++;
    } else {
      total += batch.length;
      console.log(`  Batch ${Math.floor(i / BATCH) + 1}: inserted ${batch.length} dishes (running total: ${total})`);
    }
  }

  console.log(`\nDone. Inserted: ${total} | Errors: ${errors}`);

  // Verification
  const { data, error } = await supabase
    .from('dishes')
    .select('slot')
    .eq('region', 'Konkan')
    .contains('cuisine', ['Malvani']);

  if (!error && data) {
    const counts: Record<string, number> = {};
    for (const row of data) {
      for (const s of row.slot as string[]) {
        counts[s] = (counts[s] || 0) + 1;
      }
    }
    console.log('\nVerification — Malvani dishes by slot:\n');
    for (const [slot, count] of Object.entries(counts).sort()) {
      console.log(`  ${slot.padEnd(16)} ${count}`);
    }
    console.log(`\n  Total rows inserted: ${data.length}`);
  }
}

seed().catch(console.error);
