require('dotenv').config();
const { createClient } = require('@supabase/supabase-js');

const client = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL,
  process.env.SUPABASE_SERVICE_ROLE_KEY,
);

// ─── 60 Maharashtrian dishes ──────────────────────────────────────────────────
// Distribution: 15 breakfast | 15 lunch_curry | 10 dinner_curry |
//               8 veg_side | 4 rice | 4 bread | 2 raita | 2 snack

const dishes = [

  // ── BREAKFAST (15) ──────────────────────────────────────────────────────────

  {
    name: 'Kande Pohe',
    name_hindi: 'कांदे पोहे',
    name_regional: 'कांदे पोहे',
    description: 'Flattened rice tossed with onion, mustard seeds, turmeric, and fresh coriander — the quintessential Maharashtrian morning staple.',
    cuisine: ['Maharashtrian'],
    region: 'WEST',
    slot: ['breakfast'],
    is_veg: true, is_vegan: true, is_jain: false, is_fasting: false, is_street: false,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Dadpe Pohe',
    name_hindi: null,
    name_regional: 'दडपे पोहे',
    description: 'Raw uncooked flattened rice tossed with fresh grated coconut, green chilli, lemon, and pomegranate — a no-fire Konkan breakfast.',
    cuisine: ['Maharashtrian'],
    region: 'WEST',
    slot: ['breakfast'],
    is_veg: true, is_vegan: true, is_jain: false, is_fasting: false, is_street: false,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Sabudana Khichdi',
    name_hindi: 'साबूदाना खिचड़ी',
    name_regional: 'साबुदाणा खिचडी',
    description: 'Sago pearls cooked with peanuts, green chilli, and cumin — the standard Maharashtrian Ekadashi and Navratri fasting breakfast.',
    cuisine: ['Maharashtrian'],
    region: 'WEST',
    slot: ['breakfast'],
    is_veg: true, is_vegan: false, is_jain: false, is_fasting: true, is_street: false,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Sabudana Vada',
    name_hindi: 'साबूदाना वड़ा',
    name_regional: 'साबुदाणा वडा',
    description: 'Crispy deep-fried sago and potato patties spiced with green chilli and peanuts — a Maharashtrian fasting snack sold outside temples.',
    cuisine: ['Maharashtrian'],
    region: 'WEST',
    slot: ['breakfast'],
    is_veg: true, is_vegan: false, is_jain: false, is_fasting: true, is_street: true,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Thalipeeth',
    name_hindi: 'थालीपीठ',
    name_regional: 'थालीपीठ',
    description: 'Multi-grain flatbread made from roasted bhajani flour with onion, coriander, and cumin — served with white butter and thecha.',
    cuisine: ['Maharashtrian'],
    region: 'WEST',
    slot: ['breakfast'],
    is_veg: true, is_vegan: false, is_jain: false, is_fasting: false, is_street: false,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Amboli',
    name_hindi: null,
    name_regional: 'आंबोळी',
    description: 'Thick fermented rice and urad dal pancake from Konkan Maharashtra — spongy and slightly sour, eaten with coconut chutney or usal.',
    cuisine: ['Maharashtrian'],
    region: 'WEST',
    slot: ['breakfast'],
    is_veg: true, is_vegan: true, is_jain: false, is_fasting: false, is_street: false,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Ghavan',
    name_hindi: null,
    name_regional: 'घावन',
    description: 'Paper-thin rice flour crepe made with coconut milk and cumin — a Konkan Maharashtrian breakfast eaten with fresh coconut chutney.',
    cuisine: ['Maharashtrian'],
    region: 'WEST',
    slot: ['breakfast'],
    is_veg: true, is_vegan: true, is_jain: true, is_fasting: false, is_street: false,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Misal Pav',
    name_hindi: 'मिसल पाव',
    name_regional: 'मिसळ पाव',
    description: 'Sprouted moth bean curry topped with farsan, onion, and lemon served with soft pav — Pune and Nashik street food eaten as breakfast.',
    cuisine: ['Maharashtrian'],
    region: 'WEST',
    slot: ['breakfast'],
    is_veg: true, is_vegan: false, is_jain: false, is_fasting: false, is_street: true,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Batata Vada',
    name_hindi: 'बटाटा वड़ा',
    name_regional: 'बटाटा वडा',
    description: 'Spiced mashed potato filling coated in gram flour batter and deep-fried — the filling inside a vada pav, also eaten standalone.',
    cuisine: ['Maharashtrian'],
    region: 'WEST',
    slot: ['breakfast'],
    is_veg: true, is_vegan: true, is_jain: false, is_fasting: false, is_street: true,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Upma',
    name_hindi: 'उपमा',
    name_regional: 'उपमा',
    description: 'Semolina porridge tempered with mustard seeds, curry leaves, green chilli, and vegetables — a standard weekday Maharashtrian breakfast.',
    cuisine: ['Maharashtrian'],
    region: 'WEST',
    slot: ['breakfast'],
    is_veg: true, is_vegan: false, is_jain: false, is_fasting: false, is_street: false,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Rava Sheera',
    name_hindi: 'रवा शीरा',
    name_regional: 'रवा शीरा',
    description: 'Semolina sweet pudding made with ghee, sugar, cardamom, and cashews — offered as prasad and eaten as festive or fasting breakfast.',
    cuisine: ['Maharashtrian'],
    region: 'WEST',
    slot: ['breakfast'],
    is_veg: true, is_vegan: false, is_jain: true, is_fasting: true, is_street: false,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday', 'festival'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Tarri Poha',
    name_hindi: null,
    name_regional: 'तर्री पोहा',
    description: 'Plain poha drenched in a fiery spiced onion-tomato gravy called tarri — a Nagpur breakfast street staple with chana and sev on top.',
    cuisine: ['Maharashtrian'],
    region: 'WEST',
    slot: ['breakfast'],
    is_veg: true, is_vegan: false, is_jain: false, is_fasting: false, is_street: true,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Anda Bhurji Pav',
    name_hindi: 'अंडा भुर्जी पाव',
    name_regional: 'अंडा भुर्जी पाव',
    description: 'Spiced scrambled eggs cooked with onion, tomato, and green chilli served with soft pav — Mumbai morning street staple.',
    cuisine: ['Maharashtrian'],
    region: 'WEST',
    slot: ['breakfast'],
    is_veg: false, is_vegan: false, is_jain: false, is_fasting: false, is_street: true,
    is_non_veg_type: 'egg', allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Appe',
    name_hindi: null,
    name_regional: 'आप्पे',
    description: 'Small round dumplings made from fermented rice and urad dal batter cooked in a special mould pan — light Maharashtrian breakfast.',
    cuisine: ['Maharashtrian'],
    region: 'WEST',
    slot: ['breakfast'],
    is_veg: true, is_vegan: true, is_jain: false, is_fasting: false, is_street: false,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Matki Usal',
    name_hindi: null,
    name_regional: 'मटकी उसळ',
    description: 'Sprouted moth bean curry tempered with mustard, asafoetida, and goda masala — a protein-rich Maharashtrian breakfast or side.',
    cuisine: ['Maharashtrian'],
    region: 'WEST',
    slot: ['breakfast'],
    is_veg: true, is_vegan: true, is_jain: false, is_fasting: false, is_street: false,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },

  // ── LUNCH CURRY (15) ────────────────────────────────────────────────────────

  {
    name: 'Varan',
    name_hindi: 'वरण',
    name_regional: 'वरण',
    description: 'Plain cooked toor dal seasoned with turmeric and finished with ghee — the most basic and sacred Maharashtrian dal eaten over steamed rice.',
    cuisine: ['Maharashtrian'],
    region: 'WEST',
    slot: ['lunch_curry'],
    is_veg: true, is_vegan: false, is_jain: false, is_fasting: false, is_street: false,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Katachi Amti',
    name_hindi: null,
    name_regional: 'कटाची आमटी',
    description: 'Tangy sweet spiced chana dal soup made from the cooking water of chana — a Pune Brahmin festival dal served with puran poli.',
    cuisine: ['Maharashtrian'],
    region: 'WEST',
    slot: ['lunch_curry'],
    is_veg: true, is_vegan: false, is_jain: false, is_fasting: false, is_street: false,
    is_non_veg_type: null, allowed_days: [], occasion: ['festival'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Pithla',
    name_hindi: 'पिठलं',
    name_regional: 'पिठलं',
    description: 'Thick gram flour curry cooked with onion, garlic, green chilli, and turmeric — the working-class Maharashtrian staple eaten with bhakri.',
    cuisine: ['Maharashtrian'],
    region: 'WEST',
    slot: ['lunch_curry'],
    is_veg: true, is_vegan: true, is_jain: false, is_fasting: false, is_street: false,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Bharli Vangi',
    name_hindi: 'भरली वांगी',
    name_regional: 'भरली वांगी',
    description: 'Small brinjals stuffed with a roasted coconut, peanut, and sesame masala then cooked in a tangy gravy — a Maharashtrian celebration dish.',
    cuisine: ['Maharashtrian'],
    region: 'WEST',
    slot: ['lunch_curry'],
    is_veg: true, is_vegan: true, is_jain: false, is_fasting: false, is_street: false,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday', 'party'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Kala Chana Amti',
    name_hindi: null,
    name_regional: 'काळ्या वाटाण्याची आमटी',
    description: 'Black chickpea curry with tamarind, jaggery, and goda masala — a hearty Maharashtrian dal eaten on regular weekdays.',
    cuisine: ['Maharashtrian'],
    region: 'WEST',
    slot: ['lunch_curry'],
    is_veg: true, is_vegan: true, is_jain: false, is_fasting: false, is_street: false,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Moong Dal Amti',
    name_hindi: null,
    name_regional: 'मुगाची आमटी',
    description: 'Maharashtrian split moong dal curry tempered with mustard, asafoetida, and fresh coconut — light and digestive, eaten with rice.',
    cuisine: ['Maharashtrian'],
    region: 'WEST',
    slot: ['lunch_curry'],
    is_veg: true, is_vegan: false, is_jain: false, is_fasting: false, is_street: false,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Chavali Amti',
    name_hindi: null,
    name_regional: 'चवळीची आमटी',
    description: 'Black-eyed pea curry cooked with coconut, tamarind, and goda masala — an everyday Maharashtrian protein dal.',
    cuisine: ['Maharashtrian'],
    region: 'WEST',
    slot: ['lunch_curry'],
    is_veg: true, is_vegan: true, is_jain: false, is_fasting: false, is_street: false,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Misal',
    name_hindi: 'मिसळ',
    name_regional: 'मिसळ',
    description: 'Spicy sprouted mixed lentil curry topped with farsan, onion, and lemon — eaten as a standalone Maharashtrian lunch dish without pav.',
    cuisine: ['Maharashtrian'],
    region: 'WEST',
    slot: ['lunch_curry'],
    is_veg: true, is_vegan: false, is_jain: false, is_fasting: false, is_street: false,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Kolhapuri Tambda Rassa',
    name_hindi: null,
    name_regional: 'तांबडा रस्सा',
    description: 'Fiery thin red mutton curry from Kolhapur made with dry coconut and house-ground red masala — traditionally served as Sunday special with bhakri.',
    cuisine: ['Maharashtrian'],
    region: 'WEST',
    slot: ['lunch_curry'],
    is_veg: false, is_vegan: false, is_jain: false, is_fasting: false, is_street: false,
    is_non_veg_type: 'mutton', allowed_days: ['Sunday'], occasion: ['everyday', 'party'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Kolhapuri Pandhara Rassa',
    name_hindi: null,
    name_regional: 'पांढरा रस्सा',
    description: 'Mild white mutton curry from Kolhapur with coconut milk, white pepper, and poppy seeds — paired with tambda rassa on Sunday meals.',
    cuisine: ['Maharashtrian'],
    region: 'WEST',
    slot: ['lunch_curry'],
    is_veg: false, is_vegan: false, is_jain: false, is_fasting: false, is_street: false,
    is_non_veg_type: 'mutton', allowed_days: ['Sunday'], occasion: ['everyday', 'party'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Saoji Chicken',
    name_hindi: null,
    name_regional: 'साओजी चिकन',
    description: 'Nagpur-style chicken curry in an intensely spiced 30-ingredient Saoji masala — the spiciest chicken curry in Maharashtra.',
    cuisine: ['Maharashtrian'],
    region: 'WEST',
    slot: ['lunch_curry'],
    is_veg: false, is_vegan: false, is_jain: false, is_fasting: false, is_street: false,
    is_non_veg_type: 'chicken', allowed_days: [], occasion: ['everyday', 'party'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Kolhapuri Chicken',
    name_hindi: null,
    name_regional: 'कोल्हापुरी चिकन',
    description: 'Chicken cooked in the signature Kolhapuri red masala with dry coconut, onion, and garlic — bold, deeply spiced Deccan curry.',
    cuisine: ['Maharashtrian'],
    region: 'WEST',
    slot: ['lunch_curry'],
    is_veg: false, is_vegan: false, is_jain: false, is_fasting: false, is_street: false,
    is_non_veg_type: 'chicken', allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Bangda Masala',
    name_hindi: 'बांगडा मसाला',
    name_regional: 'बांगडा मसाला',
    description: 'Mackerel cooked in a coconut-kokum-based Maharashtrian red masala — an everyday Konkan fish curry eaten with steamed rice.',
    cuisine: ['Maharashtrian'],
    region: 'WEST',
    slot: ['lunch_curry'],
    is_veg: false, is_vegan: false, is_jain: false, is_fasting: false, is_street: false,
    is_non_veg_type: 'fish', allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Kolambi Masala',
    name_hindi: 'कोळंबी मसाला',
    name_regional: 'कोळंबी मसाला',
    description: 'Prawns cooked in a fresh coconut and kokum gravy with Maharashtrian spices — a Konkan coastal prawn curry served with ukde sheeth.',
    cuisine: ['Maharashtrian'],
    region: 'WEST',
    slot: ['lunch_curry'],
    is_veg: false, is_vegan: false, is_jain: false, is_fasting: false, is_street: false,
    is_non_veg_type: 'prawn', allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Tisrya Masala',
    name_hindi: null,
    name_regional: 'तिसऱ्या मसाला',
    description: 'Clams cooked in coconut milk, kokum, and Konkan masala — a seasonal Maharashtrian coastal delicacy eaten with steamed rice.',
    cuisine: ['Maharashtrian'],
    region: 'WEST',
    slot: ['lunch_curry'],
    is_veg: false, is_vegan: false, is_jain: false, is_fasting: false, is_street: false,
    is_non_veg_type: 'fish', allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },

  // ── DINNER CURRY (10) ───────────────────────────────────────────────────────

  {
    name: 'Moong Dal Varan',
    name_hindi: null,
    name_regional: 'मुगाचे वरण',
    description: 'Light split moong dal cooked simply with turmeric and finished with a mustard-curry leaf tadka — a gentle Maharashtrian dinner dal.',
    cuisine: ['Maharashtrian'],
    region: 'WEST',
    slot: ['dinner_curry'],
    is_veg: true, is_vegan: false, is_jain: false, is_fasting: false, is_street: false,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Masoor Dal Tadka',
    name_hindi: 'मसूर दाल तड़का',
    name_regional: null,
    description: 'Red lentil curry tempered with ghee, garlic, dried red chilli, and cumin — a quick and comforting weeknight Maharashtrian dinner dal.',
    cuisine: ['Maharashtrian'],
    region: 'WEST',
    slot: ['dinner_curry'],
    is_veg: true, is_vegan: false, is_jain: false, is_fasting: false, is_street: false,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Hirva Vatana Usal',
    name_hindi: null,
    name_regional: 'हिरव्या वाटाण्याची उसळ',
    description: 'Fresh green peas cooked with coconut, goda masala, and a tempering of mustard and asafoetida — a seasonal Maharashtrian winter curry.',
    cuisine: ['Maharashtrian'],
    region: 'WEST',
    slot: ['dinner_curry'],
    is_veg: true, is_vegan: true, is_jain: false, is_fasting: false, is_street: false,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Dalimbi Usal',
    name_hindi: null,
    name_regional: 'दालिंब्याची उसळ',
    description: 'Field bean (vaal) curry cooked with coconut and Maharashtrian goda masala — a hearty dal unique to the Konkan and Deccan belt.',
    cuisine: ['Maharashtrian'],
    region: 'WEST',
    slot: ['dinner_curry'],
    is_veg: true, is_vegan: true, is_jain: false, is_fasting: false, is_street: false,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Vaangi Bharta',
    name_hindi: 'बैंगन भर्ता',
    name_regional: 'वांग्याचे भरीत',
    description: 'Smoky roasted brinjal mashed with onion, garlic, green chilli, and coriander — a rustic Maharashtrian fire-roasted preparation.',
    cuisine: ['Maharashtrian'],
    region: 'WEST',
    slot: ['dinner_curry'],
    is_veg: true, is_vegan: true, is_jain: false, is_fasting: false, is_street: false,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Chicken Rassa',
    name_hindi: 'चिकन रस्सा',
    name_regional: 'चिकन रस्सा',
    description: 'Everyday Maharashtrian chicken curry in a thin coconut-onion gravy spiced with goda masala — lighter than Kolhapuri, served with bhakri.',
    cuisine: ['Maharashtrian'],
    region: 'WEST',
    slot: ['dinner_curry'],
    is_veg: false, is_vegan: false, is_jain: false, is_fasting: false, is_street: false,
    is_non_veg_type: 'chicken', allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Mutton Rassa',
    name_hindi: 'मटण रस्सा',
    name_regional: 'मटण रस्सा',
    description: 'Slow-cooked mutton curry in a coconut and onion-based Maharashtrian gravy spiced with goda masala — a Sunday dinner centrepiece.',
    cuisine: ['Maharashtrian'],
    region: 'WEST',
    slot: ['dinner_curry'],
    is_veg: false, is_vegan: false, is_jain: false, is_fasting: false, is_street: false,
    is_non_veg_type: 'mutton', allowed_days: ['Sunday'], occasion: ['everyday', 'party'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Surmai Masala',
    name_hindi: 'सुरमई मसाला',
    name_regional: 'सुरमई मसाला',
    description: 'Kingfish steaks cooked in a thick coconut-onion Maharashtrian masala — the prized everyday fish curry of the Konkan coast.',
    cuisine: ['Maharashtrian'],
    region: 'WEST',
    slot: ['dinner_curry'],
    is_veg: false, is_vegan: false, is_jain: false, is_fasting: false, is_street: false,
    is_non_veg_type: 'fish', allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Kolambi Sukke',
    name_hindi: null,
    name_regional: 'कोळंबी सुक्के',
    description: 'Dry prawn preparation tossed with fresh coconut, Maharashtrian spices, and kokum — served as a side with steamed rice and dal.',
    cuisine: ['Maharashtrian'],
    region: 'WEST',
    slot: ['dinner_curry'],
    is_veg: false, is_vegan: false, is_jain: false, is_fasting: false, is_street: false,
    is_non_veg_type: 'prawn', allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Anda Curry',
    name_hindi: 'अंडा करी',
    name_regional: 'अंड्याचा रस्सा',
    description: 'Hard-boiled eggs simmered in a spiced Maharashtrian onion-tomato gravy with coconut milk — a quick weeknight dinner curry.',
    cuisine: ['Maharashtrian'],
    region: 'WEST',
    slot: ['dinner_curry'],
    is_veg: false, is_vegan: false, is_jain: false, is_fasting: false, is_street: false,
    is_non_veg_type: 'egg', allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },

  // ── VEG SIDE (8) ────────────────────────────────────────────────────────────

  {
    name: 'Bhendi Bhaji',
    name_hindi: 'भिंडी भाजी',
    name_regional: 'भेंडी भाजी',
    description: 'Dry okra stir-fry with mustard seeds, turmeric, and a touch of coconut — an everyday Maharashtrian vegetable side dish.',
    cuisine: ['Maharashtrian'],
    region: 'WEST',
    slot: ['veg_side'],
    is_veg: true, is_vegan: true, is_jain: false, is_fasting: false, is_street: false,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Batata Bhaji',
    name_hindi: 'आलू भाजी',
    name_regional: 'बटाट्याची भाजी',
    description: 'Dry potato preparation with mustard seeds, turmeric, curry leaves, and green chilli — a simple Maharashtrian everyday vegetable side.',
    cuisine: ['Maharashtrian'],
    region: 'WEST',
    slot: ['veg_side'],
    is_veg: true, is_vegan: true, is_jain: false, is_fasting: false, is_street: false,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Vaangi Batata Bhaji',
    name_hindi: null,
    name_regional: 'वांगी बटाटा भाजी',
    description: 'Brinjal and potato cooked together with goda masala and fresh coconut — a popular Maharashtrian everyday side dish.',
    cuisine: ['Maharashtrian'],
    region: 'WEST',
    slot: ['veg_side'],
    is_veg: true, is_vegan: true, is_jain: false, is_fasting: false, is_street: false,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Tendli Bhaji',
    name_hindi: 'टिंडा भाजी',
    name_regional: 'तोंडलीची भाजी',
    description: 'Ivy gourd dry stir-fry with mustard, turmeric, and grated coconut — a Maharashtrian coastal Konkan favourite vegetable side.',
    cuisine: ['Maharashtrian'],
    region: 'WEST',
    slot: ['veg_side'],
    is_veg: true, is_vegan: true, is_jain: false, is_fasting: false, is_street: false,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Dudhi Bhaji',
    name_hindi: 'लौकी की सब्ज़ी',
    name_regional: 'दुधी भाजी',
    description: 'Bottle gourd cooked with chana dal, mustard, and fresh coconut — a light and digestive Maharashtrian vegetable side.',
    cuisine: ['Maharashtrian'],
    region: 'WEST',
    slot: ['veg_side'],
    is_veg: true, is_vegan: true, is_jain: false, is_fasting: false, is_street: false,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Methi Bhaji',
    name_hindi: 'मेथी भाजी',
    name_regional: 'मेथीची भाजी',
    description: 'Fresh fenugreek leaves stir-fried with garlic, green chilli, and a pinch of jaggery to balance bitterness — a Maharashtrian winter side.',
    cuisine: ['Maharashtrian'],
    region: 'WEST',
    slot: ['veg_side'],
    is_veg: true, is_vegan: true, is_jain: false, is_fasting: false, is_street: false,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Shevgyachi Bhaji',
    name_hindi: 'सहजन की सब्ज़ी',
    name_regional: 'शेवग्याची भाजी',
    description: 'Drumstick pieces cooked with chana dal, tomato, and Maharashtrian spices — a nutritious and everyday Konkan-Deccan side dish.',
    cuisine: ['Maharashtrian'],
    region: 'WEST',
    slot: ['veg_side'],
    is_veg: true, is_vegan: true, is_jain: false, is_fasting: false, is_street: false,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Shepu Bhaji',
    name_hindi: 'सोवा भाजी',
    name_regional: 'शेपूची भाजी',
    description: 'Fresh dill leaves stir-fried with moong dal, mustard, and coconut — a distinctly aromatic and healthy Maharashtrian vegetable side.',
    cuisine: ['Maharashtrian'],
    region: 'WEST',
    slot: ['veg_side'],
    is_veg: true, is_vegan: true, is_jain: false, is_fasting: false, is_street: false,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },

  // ── RICE (4) ────────────────────────────────────────────────────────────────

  {
    name: 'Ukde Sheeth',
    name_hindi: null,
    name_regional: 'उकड शीत',
    description: 'Plain steamed Maharashtrian parboiled (ukde) rice — the traditional red rice of the Konkan belt eaten at every meal.',
    cuisine: ['Maharashtrian'],
    region: 'WEST',
    slot: ['rice'],
    is_veg: true, is_vegan: true, is_jain: true, is_fasting: false, is_street: false,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Vangi Bhaat',
    name_hindi: 'बैंगन भात',
    name_regional: 'वांगी भात',
    description: 'Brinjal rice cooked with peanuts, sesame, and goda masala — a Maharashtrian one-pot meal popular as a lunchbox rice.',
    cuisine: ['Maharashtrian'],
    region: 'WEST',
    slot: ['rice'],
    is_veg: true, is_vegan: true, is_jain: false, is_fasting: false, is_street: false,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Masale Bhaat',
    name_hindi: null,
    name_regional: 'मसाले भात',
    description: 'Spiced mixed vegetable rice fragrant with goda masala, coconut, and peanuts — a Maharashtrian festive rice richer than vangi bhaat.',
    cuisine: ['Maharashtrian'],
    region: 'WEST',
    slot: ['rice'],
    is_veg: true, is_vegan: false, is_jain: false, is_fasting: false, is_street: false,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday', 'festival'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Dadhi Bhaat',
    name_hindi: 'दही चावल',
    name_regional: 'दह्याचा भात',
    description: 'Curd rice Maharashtrian style with a tempering of mustard seeds and curry leaves — a cooling end to a spiced Maharashtrian meal.',
    cuisine: ['Maharashtrian'],
    region: 'WEST',
    slot: ['rice'],
    is_veg: true, is_vegan: false, is_jain: false, is_fasting: false, is_street: false,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },

  // ── BREAD (4) ───────────────────────────────────────────────────────────────

  {
    name: 'Jowar Bhakri',
    name_hindi: 'ज्वार की रोटी',
    name_regional: 'जोंधळ्याची भाकरी',
    description: 'Thick sorghum millet flatbread hand-patted and cooked on a tawa — the staple bread of the Deccan Maharashtrian farmer.',
    cuisine: ['Maharashtrian'],
    region: 'WEST',
    slot: ['bread'],
    is_veg: true, is_vegan: true, is_jain: true, is_fasting: false, is_street: false,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Nachni Bhakri',
    name_hindi: 'रागी रोटी',
    name_regional: 'नाचणीची भाकरी',
    description: 'Finger millet flatbread rich in calcium and iron — a Maharashtrian everyday bread darker and denser than jowar bhakri.',
    cuisine: ['Maharashtrian'],
    region: 'WEST',
    slot: ['bread'],
    is_veg: true, is_vegan: true, is_jain: true, is_fasting: false, is_street: false,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Bajri Bhakri',
    name_hindi: 'बाजरे की रोटी',
    name_regional: 'बाजरीची भाकरी',
    description: 'Pearl millet flatbread eaten with pithla, thecha, and white butter — a winter Maharashtrian staple particularly in Vidarbha and Marathwada.',
    cuisine: ['Maharashtrian'],
    region: 'WEST',
    slot: ['bread'],
    is_veg: true, is_vegan: true, is_jain: true, is_fasting: false, is_street: false,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Puran Poli',
    name_hindi: 'पूरण पोली',
    name_regional: 'पुरण पोळी',
    description: 'Sweet flatbread stuffed with chana dal and jaggery filling, cooked in ghee — Maharashtra most beloved festival bread served at Holi and Gudi Padwa.',
    cuisine: ['Maharashtrian'],
    region: 'WEST',
    slot: ['bread'],
    is_veg: true, is_vegan: false, is_jain: false, is_fasting: false, is_street: false,
    is_non_veg_type: null, allowed_days: [], occasion: ['festival'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },

  // ── RAITA (2) ───────────────────────────────────────────────────────────────

  {
    name: 'Kakdi Koshimbir',
    name_hindi: null,
    name_regional: 'काकडीची कोशिंबीर',
    description: 'Grated cucumber mixed with yogurt, roasted peanuts, grated coconut, and a mustard-green chilli tempering — the classic Maharashtrian raita.',
    cuisine: ['Maharashtrian'],
    region: 'WEST',
    slot: ['raita'],
    is_veg: true, is_vegan: false, is_jain: true, is_fasting: false, is_street: false,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Tomato Koshimbir',
    name_hindi: null,
    name_regional: 'टोमॅटोची कोशिंबीर',
    description: 'Chopped tomato salad tossed with fresh coconut, green chilli, coriander, and a mustard seed tadka — a Maharashtrian fresh accompaniment.',
    cuisine: ['Maharashtrian'],
    region: 'WEST',
    slot: ['raita'],
    is_veg: true, is_vegan: true, is_jain: false, is_fasting: false, is_street: false,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },

  // ── SNACK (2) ───────────────────────────────────────────────────────────────

  {
    name: 'Chakli',
    name_hindi: 'चकली',
    name_regional: 'चकली',
    description: 'Crispy spiral deep-fried snack made from rice flour, gram flour, and sesame seeds — a Maharashtrian Diwali faral staple.',
    cuisine: ['Maharashtrian'],
    region: 'WEST',
    slot: ['snack'],
    is_veg: true, is_vegan: true, is_jain: false, is_fasting: false, is_street: false,
    is_non_veg_type: null, allowed_days: [], occasion: ['festival', 'everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Kothimbir Vadi',
    name_hindi: null,
    name_regional: 'कोथिंबीर वडी',
    description: 'Coriander leaf and gram flour squares steamed then pan-fried golden — a uniquely Maharashtrian snack with a herby, nutty flavour.',
    cuisine: ['Maharashtrian'],
    region: 'WEST',
    slot: ['snack'],
    is_veg: true, is_vegan: true, is_jain: false, is_fasting: false, is_street: false,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
];

// ─── Seed ─────────────────────────────────────────────────────────────────────

async function seed() {
  console.log(`\nSeeding ${dishes.length} Maharashtrian dishes into Supabase...\n`);

  const BATCH_SIZE = 20;
  let totalInserted = 0;
  let totalErrors = 0;

  for (let i = 0; i < dishes.length; i += BATCH_SIZE) {
    const batch = dishes.slice(i, i + BATCH_SIZE);
    const batchNum = Math.floor(i / BATCH_SIZE) + 1;

    const { error } = await client.from('dishes').insert(batch);

    if (error) {
      console.error(`  Batch ${batchNum} ERROR: ${error.message}`);
      totalErrors += batch.length;
    } else {
      totalInserted += batch.length;
      console.log(`  Batch ${batchNum}: inserted ${batch.length} dishes (running total: ${totalInserted})`);
    }
  }

  console.log(`\nDone. Inserted: ${totalInserted} | Errors: ${totalErrors}\n`);

  // ── Verification ─────────────────────────────────────────────────────────────
  console.log('Verification — Maharashtrian dishes by slot:\n');

  const { data: rows, error: verifyErr } = await client
    .from('dishes')
    .select('slot')
    .contains('cuisine', ['Maharashtrian']);

  if (verifyErr) {
    console.error('Verification error:', verifyErr.message);
    return;
  }

  const counts: Record<string, number> = {};
  (rows || []).forEach((r: { slot: string[] }) => {
    r.slot.forEach((s: string) => {
      counts[s] = (counts[s] || 0) + 1;
    });
  });

  const total = Object.values(counts).reduce((a, b) => a + b, 0);
  Object.entries(counts)
    .sort(([a], [b]) => a.localeCompare(b))
    .forEach(([slot, count]) => {
      console.log(`  ${slot.padEnd(16)} ${count}`);
    });
  console.log(`  ${'TOTAL'.padEnd(16)} ${total}`);
}

seed().catch(console.error);
