interface DishSeed { name: string; name_hindi?: string; name_regional?: string; cuisine: string[]; meal_type: string[]; dietary: string[]; health_tags: string[]; occasion: string[]; season: string[]; ingredients_main: string[]; description: string; }

export const STREET_FOOD_DISHES: DishSeed[] = [
// ═══ MUMBAI STREET (25) ═══
{ name:'Frankie Mumbai', cuisine:['Mumbai','Street Food'], meal_type:['snack','lunch'], dietary:['vegetarian'], health_tags:['energy'], occasion:['street food','everyday'], season:['all'], ingredients_main:['roti','paneer','onion','capsicum','schezwan sauce','green chutney'], description:'Mumbai street wrap — thinner than kati roll, paneer or chicken rolled in roomali-thin roti with schezwan, invented by Tibbs Frankie' },
{ name:'Bombay Sandwich', cuisine:['Mumbai','Street Food'], meal_type:['snack'], dietary:['vegetarian'], health_tags:['light'], occasion:['street food','everyday'], season:['all'], ingredients_main:['bread','potato','cucumber','beetroot','chutney','butter','chaat masala'], description:'Mumbai sandwich — triple-decker with green chutney, thin sliced veg, toasted on coal press, found at every Mumbai street corner' },
{ name:'Toast Sandwich Mumbai', cuisine:['Mumbai','Street Food'], meal_type:['snack'], dietary:['vegetarian'], health_tags:['energy'], occasion:['street food'], season:['all'], ingredients_main:['bread','butter','potato','onion','chutney','cheese','chaat masala'], description:'Grilled cheese sandwich Mumbai — coal-pressed with butter on both sides, melty cheese inside, Mumbai office-goer lunch' },
{ name:'Tawa Pulao Mumbai', cuisine:['Mumbai','Street Food'], meal_type:['dinner'], dietary:['vegetarian'], health_tags:['energy'], occasion:['street food','everyday'], season:['all'], ingredients_main:['rice','mixed vegetables','pav bhaji masala','butter','onion','capsicum','lemon'], description:'Griddle-tossed rice — pav bhaji masala rice, Mumbai invention, leftover vegetables from pav bhaji stall tossed with rice' },
{ name:'Keema Pav Mumbai', cuisine:['Mumbai','Street Food'], meal_type:['dinner','snack'], dietary:['non-vegetarian','mutton'], health_tags:['protein'], occasion:['street food','everyday'], season:['all'], ingredients_main:['mutton mince','pav','onion','ginger-garlic','green peas','garam masala'], description:'Spiced mince with bread — Irani cafe staple, dry keema scooped with soft pav, the non-veg comfort of Mumbai streets' },
{ name:'Bun Maska Irani', cuisine:['Mumbai','Street Food'], meal_type:['breakfast','snack'], dietary:['vegetarian'], health_tags:['comfort'], occasion:['street food','everyday'], season:['all'], ingredients_main:['bun','butter'], description:'Buttered bun at Irani cafe — simplest Mumbai comfort, soft bun slathered with butter, dunked in Irani chai, Parsi cafe culture icon' },
{ name:'Irani Chai Mumbai', cuisine:['Mumbai','Street Food'], meal_type:['snack'], dietary:['vegetarian'], health_tags:['comfort'], occasion:['street food','everyday'], season:['all'], ingredients_main:['tea leaves','full cream milk','sugar'], description:'Irani cafe tea — milkier and thicker than regular chai, condensed milk gives it body, served in glass cups at Parsi-Irani cafes' },
{ name:'Jumbo Vada Pav', cuisine:['Mumbai','Street Food'], meal_type:['snack','lunch'], dietary:['vegetarian'], health_tags:['energy'], occasion:['street food'], season:['all'], ingredients_main:['large potato vada','jumbo pav','garlic chutney','dry chutney','green chilli'], description:'Oversized vada pav — the XXL version, bigger vada, bigger pav, extra chutneys, Mumbai street food extravagance' },
// ═══ DELHI STREET (20) ═══
{ name:'Paranthe Wali Gali Aloo', cuisine:['Delhi','Street Food'], meal_type:['breakfast'], dietary:['vegetarian'], health_tags:['energy'], occasion:['street food'], season:['all'], ingredients_main:['wheat flour','potato','ghee','pickle','curd','sabzi'], description:'Aloo paratha from THE Paranthe Wali Gali — Old Delhi parathas fried in ghee since 1875, served with 8 accompaniments' },
{ name:'Paranthe Wali Gali Rabdi', cuisine:['Delhi','Street Food'], meal_type:['breakfast','dessert'], dietary:['vegetarian'], health_tags:['rich'], occasion:['street food'], season:['all'], ingredients_main:['wheat flour','rabdi','ghee','sugar','cardamom'], description:'Rabdi paratha — sweet version from Paranthe Wali Gali, stuffed with thick reduced milk, fried and served with more rabdi on top' },
{ name:'Nihari Delhi Street', cuisine:['Delhi','Street Food','Mughlai'], meal_type:['breakfast','dinner'], dietary:['non-vegetarian','mutton'], health_tags:['protein','iron'], occasion:['street food','winter'], season:['winter'], ingredients_main:['mutton shank','wheat flour','ginger','lime','fried onion','naan'], description:'Bone marrow stew from Jama Masjid — eaten at 5am by Dilli wallahs, overnight slow-cook, the marrow is scooped with naan' },
{ name:'Seekh Kebab Delhi Street', cuisine:['Delhi','Street Food','Mughlai'], meal_type:['snack','dinner'], dietary:['non-vegetarian','mutton'], health_tags:['protein'], occasion:['street food'], season:['all'], ingredients_main:['mutton mince','onion','green chilli','coriander','garam masala'], description:'Minced meat skewers from Old Delhi — charcoal-grilled at Jama Masjid stalls, smoky and spiced, served with rumali roti' },
{ name:'Korma Delhi Street', cuisine:['Delhi','Street Food','Mughlai'], meal_type:['dinner'], dietary:['non-vegetarian','mutton'], health_tags:['protein','rich'], occasion:['street food','Eid'], season:['all'], ingredients_main:['mutton','cashew','yogurt','cream','whole spices','saffron'], description:'Street korma from Matia Mahal — rich cream-nut gravy, the same recipe for decades, Old Delhi Muslim quarter speciality' },
{ name:'Samosa Delhi', cuisine:['Delhi','Street Food'], meal_type:['snack'], dietary:['vegetarian'], health_tags:['energy'], occasion:['street food','everyday'], season:['all'], ingredients_main:['maida','potato','peas','cumin','coriander','green chilli','oil'], description:'Delhi samosa — larger and crunchier than other cities, potato-pea filling with strong cumin, served with two chutneys' },
{ name:'Jalebi Delhi', cuisine:['Delhi','Street Food'], meal_type:['dessert','breakfast'], dietary:['vegetarian'], health_tags:['energy'], occasion:['street food','festive'], season:['all'], ingredients_main:['maida','sugar syrup','saffron','ghee'], description:'Hot jalebi from Old Delhi — fried fresh at 6am, eaten with rabdi or plain, the morning sweet of Chandni Chowk' },
// ═══ HYDERABAD STREET (12) ═══
{ name:'Lukhmi Hyderabadi', cuisine:['Hyderabad','Street Food'], meal_type:['snack'], dietary:['non-vegetarian','mutton'], health_tags:['protein'], occasion:['street food','Eid'], season:['all'], ingredients_main:['maida','mutton mince','onion','mint','whole spices','oil'], description:'Hyderabadi meat puff — square fried pastry with spiced keema, served at every bakery and Eid gathering, Nizam-era snack' },
{ name:'Osmania Biscuit', cuisine:['Hyderabad','Street Food'], meal_type:['snack'], dietary:['vegetarian'], health_tags:['comfort'], occasion:['street food','everyday'], season:['all'], ingredients_main:['maida','sugar','ghee','cardamom','vanilla'], description:'Hyderabad signature biscuit — crumbly, not too sweet, dunked in Irani chai at Karachi Bakery, the Hyderabadi tea biscuit' },
{ name:'Irani Chai Hyderabad', cuisine:['Hyderabad','Street Food'], meal_type:['snack'], dietary:['vegetarian'], health_tags:['comfort'], occasion:['street food','everyday'], season:['all'], ingredients_main:['tea','condensed milk','sugar'], description:'Hyderabadi Irani chai — thicker than Mumbai version, served in tiny glass cups with Osmania biscuit, every Hyderabadi morning ritual' },
{ name:'Mirchi Bajji Hyderabad', cuisine:['Hyderabad','Street Food'], meal_type:['snack'], dietary:['vegetarian'], health_tags:['spicy'], occasion:['street food','monsoon'], season:['monsoon'], ingredients_main:['large green chilli','gram flour','onion','rice flour','oil'], description:'Stuffed chilli fritter — Hyderabad version, larger chillies than Jodhpur mirchi bada, onion-stuffed and batter-fried' },
// ═══ SOUTH INDIAN STREET (15) ═══
{ name:'Masala Dosa Street', cuisine:['South Indian','Street Food'], meal_type:['breakfast','snack'], dietary:['vegetarian'], health_tags:['probiotic'], occasion:['street food','everyday'], season:['all'], ingredients_main:['rice batter','urad dal','potato masala','onion','mustard seeds','ghee'], description:'Street masala dosa — thinner and crispier than home version, made on giant tawa, folded around turmeric-potato filling, available 24/7' },
{ name:'Kari Dosa', cuisine:['Tamil Nadu','Street Food'], meal_type:['dinner'], dietary:['non-vegetarian','mutton'], health_tags:['protein'], occasion:['street food'], season:['all'], ingredients_main:['dosa batter','mutton mince','egg','onion','curry leaves'], description:'Meat dosa — Tamil street food, dosa spread with spiced keema and egg, late-night Chennai and Madurai speciality' },
{ name:'Bonda Soup', cuisine:['South Indian','Street Food'], meal_type:['snack'], dietary:['vegetarian'], health_tags:['comfort'], occasion:['street food'], season:['monsoon','winter'], ingredients_main:['urad dal bonda','spicy rasam soup','onion','coriander'], description:'Vada dunked in rasam — South Indian street comfort, crispy bonda dropped into hot pepper rasam, drunk from a glass' },
{ name:'Mangalore Buns', cuisine:['Mangalorean','Street Food'], meal_type:['breakfast','snack'], dietary:['vegetarian'], health_tags:['energy'], occasion:['street food','everyday'], season:['all'], ingredients_main:['maida','ripe banana','sugar','yogurt','oil'], description:'Sweet banana puri from Mangalore — banana sweetened dough fried into puffy rounds, unique street breakfast of coastal Karnataka' },
{ name:'Churumuri', cuisine:['Karnataka','Street Food'], meal_type:['snack'], dietary:['vegetarian'], health_tags:['light'], occasion:['street food','evening'], season:['all'], ingredients_main:['puffed rice','onion','carrot','peanuts','lemon','green chilli','coconut oil'], description:'Karnataka bhel — puffed rice tossed with coconut oil instead of mustard oil, the Bangalore and Mysore evening street snack' },
// ═══ GUJARAT STREET (10) ═══
{ name:'Locho Surat Street', cuisine:['Gujarati','Street Food'], meal_type:['breakfast','snack'], dietary:['vegetarian'], health_tags:['light'], occasion:['street food'], season:['all'], ingredients_main:['gram flour','ginger','green chilli','oil','sev','coriander'], description:'Surat street breakfast — soft steamed gram flour cake topped with sev, eaten from newspaper at roadside stalls since the 1960s' },
{ name:'Surti Bhajiya Street', cuisine:['Gujarati','Street Food'], meal_type:['snack'], dietary:['vegetarian'], health_tags:['comfort'], occasion:['street food','monsoon'], season:['monsoon'], ingredients_main:['gram flour','various vegetables','green chilli','oil'], description:'Surat mixed fritters — 15+ varieties of bhajiya at each Surti stall, from methi to mirchi to banana, the monsoon chai companion' },
{ name:'Tikha Gathiya', cuisine:['Gujarati','Street Food'], meal_type:['snack'], dietary:['vegetarian'], health_tags:['spicy'], occasion:['street food','everyday'], season:['all'], ingredients_main:['gram flour','pepper','cloves','oil'], description:'Spicy gram flour sticks — the peppery gathiya variant, Rajkot street snack, spicier than regular gathiya' },
// ═══ PAN-INDIA STREET (15) ═══
{ name:'Pani Puri Pan-India', cuisine:['Street Food'], meal_type:['snack'], dietary:['vegetarian'], health_tags:['light'], occasion:['street food','evening'], season:['all'], ingredients_main:['semolina puris','potato','chickpea','tamarind water','mint water','black salt'], description:'The universal Indian street food — called Puchka in Kolkata, Golgappa in Delhi, Gupchup in Odisha, Pani Puri in Mumbai, one dish many names' },
{ name:'Samosa Pan-India', cuisine:['Street Food'], meal_type:['snack'], dietary:['vegetarian'], health_tags:['energy'], occasion:['street food','everyday'], season:['all'], ingredients_main:['maida','potato','peas','cumin','coriander','oil'], description:'The triangular pastry found everywhere — from Kashmir to Kanyakumari, every city has its own size and filling, the most ubiquitous Indian snack' },
{ name:'Kachori Pan-India', cuisine:['Street Food'], meal_type:['snack','breakfast'], dietary:['vegetarian'], health_tags:['energy'], occasion:['street food'], season:['all'], ingredients_main:['maida','moong dal','cumin','fennel','oil'], description:'Stuffed fried sphere — every region has its own kachori, dal kachori is the most common, morning street breakfast across North and West India' },
{ name:'Bhutta Masala', cuisine:['Street Food'], meal_type:['snack'], dietary:['vegetarian'], health_tags:['fibre'], occasion:['street food','monsoon'], season:['monsoon'], ingredients_main:['corn on cob','lemon','red chilli','salt','butter'], description:'Roasted corn on the cob — charcoal-grilled, rubbed with lemon-chilli-salt-butter, the monsoon evening snack of every Indian city' },
{ name:'Masala Mungfali', cuisine:['Street Food'], meal_type:['snack'], dietary:['vegetarian'], health_tags:['protein'], occasion:['street food','winter'], season:['winter'], ingredients_main:['roasted peanuts','salt','red chilli','chaat masala','lemon'], description:'Spiced roasted peanuts — the cheapest street snack in India, paper cones of hot peanuts sold at every traffic signal in winter' },
{ name:'Kulfi Street', cuisine:['Street Food'], meal_type:['dessert'], dietary:['vegetarian'], health_tags:['calcium'], occasion:['street food','summer'], season:['summer'], ingredients_main:['milk','sugar','cardamom','pistachios','saffron'], description:'Indian ice cream from the cart — denser than Western ice cream, frozen in conical moulds, kulfi-wallah cycles through every neighbourhood in summer' },
{ name:'Chai Tapri', cuisine:['Street Food'], meal_type:['snack'], dietary:['vegetarian'], health_tags:['antioxidant','comfort'], occasion:['street food','everyday'], season:['all'], ingredients_main:['tea leaves','milk','sugar','ginger','cardamom'], description:'Roadside chai — the 10-rupee cup that fuels India, boiled hard with milk and sugar, served in glass or kulhad, the social glue of the nation' },
];
