interface DishSeed {
  name: string; name_hindi?: string; name_regional?: string;
  cuisine: string[]; meal_type: string[]; dietary: string[];
  health_tags: string[]; occasion: string[]; season: string[];
  ingredients_main: string[]; description: string;
}

export const MAHARASHTRIAN_DISHES: DishSeed[] = [
// ── Pune Brahmin / Everyday (60) ──
{ name:'Varan Bhaat', name_hindi:'वरण भात', cuisine:['Maharashtrian'], meal_type:['lunch','dinner'], dietary:['vegetarian'], health_tags:['comfort','protein'], occasion:['everyday'], season:['all'], ingredients_main:['toor dal','rice','ghee','turmeric','hing'], description:'Plain toor dal over steamed rice with ghee — the most basic Maharashtrian meal, Pune Brahmin comfort food, everyday simplicity' },
{ name:'Katachi Amti', name_hindi:'कटाची आमटी', cuisine:['Maharashtrian'], meal_type:['lunch'], dietary:['vegetarian'], health_tags:['protein'], occasion:['festive','Ganesh Chaturthi'], season:['all'], ingredients_main:['chana dal','jaggery','tamarind','kokum','cumin','mustard seeds'], description:'Sweet-sour gram dal soup — Pune festival special served with puran poli, tangy and warming' },
{ name:'Golyachi Amti', name_hindi:'गोळ्याची आमटी', cuisine:['Maharashtrian'], meal_type:['lunch'], dietary:['vegetarian'], health_tags:['protein'], occasion:['everyday'], season:['all'], ingredients_main:['toor dal','kokum','jaggery','goda masala','coconut','hing'], description:'Kokum-flavoured dal — Konkan Brahmin style, tangier than varan, sour pink kokum gives the signature colour' },
{ name:'Pithla Bhakri', name_hindi:'पिठला भाकरी', cuisine:['Maharashtrian'], meal_type:['lunch','dinner'], dietary:['vegetarian'], health_tags:['protein','quick'], occasion:['everyday'], season:['all'], ingredients_main:['gram flour','onion','garlic','green chilli','turmeric','jowar flour'], description:'Thick gram flour curry with millet flatbread — working-class Maharashtrian staple, 10-minute meal, deeply satisfying' },
{ name:'Zunka Bhakri', name_hindi:'झुणका भाकरी', cuisine:['Maharashtrian','Vidarbha'], meal_type:['lunch','dinner'], dietary:['vegetarian'], health_tags:['protein'], occasion:['everyday'], season:['all'], ingredients_main:['gram flour','onion','garlic','green chilli','jowar flour','oil'], description:'Dry gram flour crumble with millet bread — dryer than pithla, Vidarbha-Marathwada working-class identity dish' },
{ name:'Thalipeeth', name_hindi:'थालीपीठ', cuisine:['Maharashtrian'], meal_type:['breakfast','dinner'], dietary:['vegetarian'], health_tags:['multi-grain','fibre'], occasion:['everyday'], season:['all'], ingredients_main:['bhajani flour','onion','coriander','cumin','oil','butter'], description:'Multi-grain flatbread from Maharashtra — special bhajani flour of roasted grains, served with butter and thecha' },
{ name:'Hirva Thecha', name_hindi:'हिरवा ठेचा', cuisine:['Maharashtrian'], meal_type:['snack','condiment'], dietary:['vegetarian'], health_tags:['spicy'], occasion:['everyday'], season:['all'], ingredients_main:['green chilli','garlic','peanuts','salt','oil'], description:'Green chilli-garlic chutney pounded in mortar — Maharashtra table essential, raw heat with garlic punch' },
{ name:'Lal Thecha', name_hindi:'लाल ठेचा', cuisine:['Maharashtrian'], meal_type:['condiment'], dietary:['vegetarian'], health_tags:['spicy'], occasion:['everyday'], season:['all'], ingredients_main:['dry red chilli','garlic','oil','salt'], description:'Red chilli-garlic chutney — hotter cousin of hirva thecha, Vidarbha style, coarsely pounded' },
{ name:'Shengdana Thecha', name_hindi:'शेंगदाणा ठेचा', cuisine:['Maharashtrian'], meal_type:['condiment'], dietary:['vegetarian'], health_tags:['protein'], occasion:['everyday'], season:['all'], ingredients_main:['peanuts','garlic','dry red chilli','salt','oil'], description:'Peanut-garlic chutney — Maharashtrian protein-rich condiment, coarsely ground, pairs with bhakri' },
{ name:'Vangi Bhaat', name_hindi:'वांगी भात', cuisine:['Maharashtrian'], meal_type:['lunch'], dietary:['vegetarian'], health_tags:['fibre'], occasion:['everyday','lunchbox'], season:['all'], ingredients_main:['rice','brinjal','peanuts','sesame','goda masala','coconut'], description:'Brinjal rice — Maharashtrian one-pot meal, spiced with goda masala, great for lunchbox' },
{ name:'Masale Bhaat', name_hindi:'मसाले भात', cuisine:['Maharashtrian'], meal_type:['lunch'], dietary:['vegetarian'], health_tags:['energy'], occasion:['festive','everyday'], season:['all'], ingredients_main:['rice','mixed vegetables','goda masala','coconut','peanuts','ghee'], description:'Spiced vegetable rice — Maharashtrian celebration rice, fragrant with goda masala, richer than vangi bhaat' },
// ── Kolhapuri (40) ──
{ name:'Kolhapuri Tambda Rassa', name_hindi:'कोल्हापुरी तांबडा रस्सा', cuisine:['Maharashtrian','Kolhapuri'], meal_type:['dinner'], dietary:['non-vegetarian','mutton'], health_tags:['protein','spicy'], occasion:['guest','festive'], season:['winter'], ingredients_main:['mutton','Kolhapuri masala','dry coconut','onion','garlic','red chilli'], description:'Fiery red mutton curry — Kolhapur signature, thin red gravy made with dry coconut, served with bhakri at midnight' },
{ name:'Kolhapuri Pandhara Rassa', name_hindi:'कोल्हापुरी पांढरा रस्सा', cuisine:['Maharashtrian','Kolhapuri'], meal_type:['dinner'], dietary:['non-vegetarian','mutton'], health_tags:['protein'], occasion:['guest','festive'], season:['winter'], ingredients_main:['mutton','coconut milk','cashew','white pepper','poppy seeds','cinnamon'], description:'White mutton curry — Kolhapur mild counterpart to tambda rassa, creamy coconut-cashew base, paired together' },
{ name:'Kolhapuri Chicken Rassa', cuisine:['Maharashtrian','Kolhapuri'], meal_type:['lunch','dinner'], dietary:['non-vegetarian','chicken'], health_tags:['protein','spicy'], occasion:['everyday'], season:['all'], ingredients_main:['chicken','Kolhapuri masala','onion','coconut','garlic','ginger'], description:'Kolhapuri chicken in red gravy — spicier than standard chicken curry, the Kolhapur chilli blend is legendary' },
{ name:'Kolhapuri Usal', cuisine:['Maharashtrian','Kolhapuri'], meal_type:['breakfast','lunch'], dietary:['vegetarian'], health_tags:['protein','spicy'], occasion:['everyday'], season:['all'], ingredients_main:['sprouted matki','Kolhapuri masala','onion','garlic','coconut'], description:'Spicy sprouted moth bean curry — Kolhapur breakfast with pav, fiercer spice level than Pune misal' },
{ name:'Kolhapuri Egg Masala', cuisine:['Maharashtrian','Kolhapuri'], meal_type:['lunch','dinner'], dietary:['non-vegetarian','egg'], health_tags:['protein','spicy'], occasion:['everyday'], season:['all'], ingredients_main:['eggs','Kolhapuri masala','onion','coconut','garlic'], description:'Eggs in Kolhapuri red masala — quick fiery Kolhapuri non-veg, eggs in the signature red gravy' },
// ── Vidarbha / Nagpur (40) ──
{ name:'Saoji Chicken', cuisine:['Maharashtrian','Vidarbha'], meal_type:['dinner'], dietary:['non-vegetarian','chicken'], health_tags:['protein','spicy'], occasion:['everyday','guest'], season:['all'], ingredients_main:['chicken','Saoji masala','onion','garlic','poppy seeds','coconut','sesame'], description:'Nagpur Saoji chicken — the spiciest chicken curry in Maharashtra, 30+ spice Saoji masala, a Nagpur truck-stop legend' },
{ name:'Saoji Mutton', cuisine:['Maharashtrian','Vidarbha'], meal_type:['dinner'], dietary:['non-vegetarian','mutton'], health_tags:['protein','spicy','iron'], occasion:['weekend','guest'], season:['winter'], ingredients_main:['mutton','Saoji masala','onion','garlic','poppy seeds','dry coconut'], description:'Nagpur Saoji mutton — slow-cooked in the legendary 30-spice Saoji masala, Vidarbha pride' },
{ name:'Tarri Poha', cuisine:['Maharashtrian','Vidarbha'], meal_type:['breakfast'], dietary:['vegetarian'], health_tags:['spicy','light'], occasion:['everyday','street food'], season:['all'], ingredients_main:['flattened rice','onion','spicy tarri gravy','sev','coriander','lemon'], description:'Poha with spicy gravy — Nagpur breakfast speciality, plain poha drenched in fiery onion-tomato tarri' },
{ name:'Nagpuri Saoji Rassa Mutton', cuisine:['Maharashtrian','Vidarbha'], meal_type:['dinner'], dietary:['non-vegetarian','mutton'], health_tags:['protein','spicy'], occasion:['guest'], season:['winter'], ingredients_main:['mutton','dry coconut','poppy seeds','sesame','onion','garlic','Saoji masala'], description:'Nagpur mutton rassa — thinner gravy than Kolhapuri, more coconut-poppy seed base, Vidarbha identity dish' },
{ name:'Varhadi Chicken', cuisine:['Maharashtrian','Vidarbha'], meal_type:['dinner'], dietary:['non-vegetarian','chicken'], health_tags:['protein'], occasion:['everyday'], season:['all'], ingredients_main:['chicken','til chutney','onion','garlic','dry coconut','sesame'], description:'Varhadi-style chicken — sesame and dry coconut based, distinct from Kolhapuri, Vidarbha region everyday non-veg' },
// ── Konkan Coast (40) ──
{ name:'Bangda Fry', name_hindi:'बांगडा फ्राई', cuisine:['Maharashtrian','Konkan'], meal_type:['dinner','snack'], dietary:['non-vegetarian','fish'], health_tags:['protein','omega-3'], occasion:['everyday'], season:['all'], ingredients_main:['mackerel','turmeric','red chilli','salt','oil'], description:'Pan-fried mackerel — everyday Konkan fish, simple turmeric-chilli rub, fried crispy on tawa' },
{ name:'Bombil Fry', name_hindi:'बोंबील फ्राई', cuisine:['Maharashtrian','Konkan','Mumbai'], meal_type:['dinner','snack'], dietary:['non-vegetarian','fish'], health_tags:['protein'], occasion:['everyday'], season:['all'], ingredients_main:['Bombay duck','semolina','turmeric','red chilli','oil'], description:'Fried Bombay duck — Mumbai-Konkan speciality, semolina-coated crispy fish, melts in mouth' },
{ name:'Kolbi Masala', name_hindi:'कोळंबी मसाला', cuisine:['Maharashtrian','Konkan'], meal_type:['lunch','dinner'], dietary:['non-vegetarian','fish'], health_tags:['protein'], occasion:['everyday'], season:['all'], ingredients_main:['prawns','coconut','kokum','onion','garlic','red chilli'], description:'Prawn masala Konkan style — coconut-kokum base, tangy and spicy, served with rice' },
{ name:'Tisrya Masala', name_hindi:'तिसऱ्या मसाला', cuisine:['Maharashtrian','Konkan'], meal_type:['dinner'], dietary:['non-vegetarian','fish'], health_tags:['protein','iron'], occasion:['everyday','guest'], season:['monsoon'], ingredients_main:['clams','coconut','kokum','garlic','red chilli','ginger'], description:'Clam masala — Konkan coastal delicacy, tiny clams in coconut-kokum gravy, monsoon seasonal' },
{ name:'Koli Fish Curry', cuisine:['Maharashtrian','Mumbai'], meal_type:['lunch'], dietary:['non-vegetarian','fish'], health_tags:['protein','omega-3'], occasion:['everyday'], season:['all'], ingredients_main:['fish','coconut','kokum','onion','garlic','red chilli','turmeric'], description:'Koli fishing community curry — Mumbai native fish curry, coconut-kokum base, eaten by original Mumbaikars' },
{ name:'Sol Kadhi', name_hindi:'सोल कढ़ी', cuisine:['Maharashtrian','Konkan'], meal_type:['lunch'], dietary:['vegetarian'], health_tags:['digestive','cooling'], occasion:['everyday'], season:['summer'], ingredients_main:['kokum','coconut milk','garlic','green chilli','cumin','coriander'], description:'Pink kokum-coconut digestive drink — served after meals in Konkan homes, cooling and tangy, aids digestion' },
// ── Mumbai Street Food (30) ──
{ name:'Vada Pav Mumbai', cuisine:['Maharashtrian','Mumbai'], meal_type:['snack','breakfast'], dietary:['vegetarian'], health_tags:['energy','comfort'], occasion:['street food','everyday'], season:['all'], ingredients_main:['potato','gram flour','garlic chutney','pav','dry garlic chutney','green chilli'], description:'Mumbai vada pav — the city common man meal, spiced potato dumpling in bread with three chutneys' },
{ name:'Pav Bhaji Mumbai', cuisine:['Maharashtrian','Mumbai'], meal_type:['dinner','snack'], dietary:['vegetarian'], health_tags:['comfort'], occasion:['street food','everyday'], season:['all'], ingredients_main:['mixed vegetables','pav','butter','pav bhaji masala','onion','lemon'], description:'Mumbai tawa bhaji — mashed vegetables with river of butter on griddle, served with soft buttered pav' },
{ name:'Ragda Pattice', cuisine:['Maharashtrian','Mumbai'], meal_type:['snack','street food'], dietary:['vegetarian'], health_tags:['protein'], occasion:['street food','evening'], season:['all'], ingredients_main:['dried peas','potato patties','tamarind chutney','green chutney','sev','onion'], description:'Potato patties in pea curry — Mumbai chaat, crispy tikkis drowned in ragda and chutneys' },
{ name:'Bhel Puri Mumbai', cuisine:['Maharashtrian','Mumbai'], meal_type:['snack'], dietary:['vegetarian'], health_tags:['light'], occasion:['street food','evening'], season:['all'], ingredients_main:['puffed rice','sev','onion','tomato','coriander','tamarind chutney','green chutney'], description:'Mumbai puffed rice chaat — Chowpatty beach evening essential, tossed fresh on the spot' },
// ── Marathwada (20) ──
{ name:'Jowar Bhakri Thecha', cuisine:['Maharashtrian','Marathwada'], meal_type:['lunch','dinner'], dietary:['vegetarian'], health_tags:['fibre'], occasion:['everyday'], season:['all'], ingredients_main:['jowar flour','green chilli','garlic','peanuts','oil'], description:'Sorghum flatbread with pounded chutney — Marathwada daily meal, thick jowar bhakri with raw green thecha' },
{ name:'Shengdana Chutney Bhakri', cuisine:['Maharashtrian','Marathwada'], meal_type:['lunch'], dietary:['vegetarian'], health_tags:['protein'], occasion:['everyday'], season:['all'], ingredients_main:['jowar flour','peanuts','dry coconut','garlic','red chilli'], description:'Bhakri with dry peanut chutney — Marathwada farmer lunch, peanut-coconut dry chutney with millet bread' },
{ name:'Harbharyachi Usal', cuisine:['Maharashtrian','Marathwada'], meal_type:['lunch'], dietary:['vegetarian'], health_tags:['protein','fibre'], occasion:['everyday'], season:['all'], ingredients_main:['black chickpea','onion','garlic','goda masala','coconut'], description:'Black chickpea curry — hearty Marathwada usal, earthier than standard chana, served with bhakri' },
// ── Sweets & Festival (30) ──
{ name:'Ukdiche Modak', name_hindi:'उकडीचे मोदक', cuisine:['Maharashtrian'], meal_type:['dessert'], dietary:['vegetarian'], health_tags:['celebration'], occasion:['Ganesh Chaturthi'], season:['monsoon'], ingredients_main:['rice flour','coconut','jaggery','cardamom','nutmeg','ghee'], description:'Steamed sweet dumplings — the most sacred Ganesh Chaturthi offering, hand-shaped rice shells with coconut-jaggery filling' },
{ name:'Talniche Modak', name_hindi:'तळणीचे मोदक', cuisine:['Maharashtrian'], meal_type:['dessert'], dietary:['vegetarian'], health_tags:['energy'], occasion:['Ganesh Chaturthi'], season:['monsoon'], ingredients_main:['maida','coconut','jaggery','cardamom','ghee'], description:'Deep-fried modak — the crispy cousin of ukdiche modak, also offered to Ganpati, crunchier shell' },
{ name:'Karanji', name_hindi:'करंजी', cuisine:['Maharashtrian'], meal_type:['dessert'], dietary:['vegetarian'], health_tags:['energy'], occasion:['Diwali'], season:['all'], ingredients_main:['maida','coconut','sugar','cardamom','poppy seeds','ghee'], description:'Crescent-shaped sweet pastry — Maharashtrian Diwali faral essential, coconut-poppy seed filling' },
{ name:'Shankarpali', name_hindi:'शंकरपाळी', cuisine:['Maharashtrian'], meal_type:['snack','dessert'], dietary:['vegetarian'], health_tags:['energy'], occasion:['Diwali'], season:['all'], ingredients_main:['maida','sugar','ghee','milk','cardamom'], description:'Sweet diamond crackers — every Maharashtrian Diwali box has these, crunchy and mildly sweet' },
{ name:'Chakli', name_hindi:'चकली', cuisine:['Maharashtrian'], meal_type:['snack'], dietary:['vegetarian'], health_tags:['crispy'], occasion:['Diwali'], season:['all'], ingredients_main:['rice flour','gram flour','cumin','sesame','hing','oil'], description:'Spiral crispy snack — Diwali faral icon, pressed through a mould into hot oil, every shape tells the maker' },
{ name:'Chivda Poha', cuisine:['Maharashtrian'], meal_type:['snack'], dietary:['vegetarian'], health_tags:['light'], occasion:['Diwali','everyday'], season:['all'], ingredients_main:['thin poha','peanuts','raisins','curry leaves','turmeric','sugar','oil'], description:'Puffed rice snack mix — Maharashtrian Diwali namkeen, lighter than Gujarati chevdo' },
{ name:'Kothimbir Vadi', name_hindi:'कोथिंबीर वडी', cuisine:['Maharashtrian'], meal_type:['snack'], dietary:['vegetarian'], health_tags:['iron'], occasion:['everyday'], season:['all'], ingredients_main:['coriander leaves','gram flour','sesame','peanuts','ginger','green chilli'], description:'Coriander leaf fritters — steamed then pan-fried, green and herby, unique Maharashtrian snack' },
{ name:'Puran Poli', name_hindi:'पुरण पोळी', cuisine:['Maharashtrian'], meal_type:['dessert'], dietary:['vegetarian'], health_tags:['energy','celebration'], occasion:['Ganesh Chaturthi','Holi','Gudi Padwa'], season:['all'], ingredients_main:['wheat flour','chana dal','jaggery','cardamom','ghee','nutmeg'], description:'Sweet stuffed flatbread — Maharashtra festive bread for every major festival, the taste of celebration itself' },
{ name:'Amboli', name_hindi:'आंबोली', cuisine:['Maharashtrian','Konkan'], meal_type:['breakfast'], dietary:['vegetarian'], health_tags:['probiotic'], occasion:['everyday'], season:['all'], ingredients_main:['rice flour','urad dal','onion','cumin','coconut'], description:'Fermented rice pancake — Konkan breakfast, thicker than dosa, spongy and slightly sour, eaten with coconut chutney' },
{ name:'Ghavan', name_hindi:'घावन', cuisine:['Maharashtrian','Konkan'], meal_type:['breakfast'], dietary:['vegetarian'], health_tags:['light'], occasion:['everyday'], season:['all'], ingredients_main:['rice flour','coconut milk','cumin'], description:'Paper-thin rice crepe — Konkan breakfast, as thin as neer dosa, served with coconut chutney or usal' },
{ name:'Nachni Bhakri', cuisine:['Maharashtrian'], meal_type:['breakfast','dinner'], dietary:['vegetarian'], health_tags:['calcium','iron'], occasion:['everyday'], season:['all'], ingredients_main:['ragi flour','salt'], description:'Finger millet flatbread — calcium-rich Maharashtrian daily bread, darker and denser than jowar bhakri' },
];
