require('dotenv').config();
const { createClient } = require('@supabase/supabase-js');

const client = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL,
  process.env.SUPABASE_SERVICE_ROLE_KEY,
);

// ─── 60 Tamil Nadu dishes ─────────────────────────────────────────────────────
// Distribution: 14 breakfast | 15 lunch_curry | 12 dinner_curry |
//               10 veg_side | 4 rice | 2 bread | 2 raita | 1 snack

const dishes = [

  // ── BREAKFAST (14) ──────────────────────────────────────────────────────────

  {
    name: 'Idli',
    name_hindi: 'इडली',
    name_regional: 'இட்லி',
    description: 'Soft steamed cakes made from fermented rice and urad dal batter — the quintessential Tamil Nadu morning staple served with sambar and chutneys.',
    cuisine: ['Tamil Nadu'],
    region: 'SOUTH',
    slot: ['breakfast'],
    is_veg: true, is_vegan: true, is_jain: true, is_fasting: false, is_street: false,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Dosa',
    name_hindi: 'डोसा',
    name_regional: 'தோசை',
    description: 'Thin crispy crepe made from fermented rice and lentil batter, cooked on a cast-iron griddle and served with coconut chutney and sambar.',
    cuisine: ['Tamil Nadu'],
    region: 'SOUTH',
    slot: ['breakfast'],
    is_veg: true, is_vegan: true, is_jain: true, is_fasting: false, is_street: false,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Masala Dosa',
    name_hindi: 'मसाला डोसा',
    name_regional: 'மசால தோசை',
    description: 'Golden crispy dosa stuffed with a spiced potato and onion filling, served with coconut chutney, tomato chutney and sambar.',
    cuisine: ['Tamil Nadu'],
    region: 'SOUTH',
    slot: ['breakfast'],
    is_veg: true, is_vegan: true, is_jain: false, is_fasting: false, is_street: false,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Rava Dosa',
    name_hindi: 'रवा डोसा',
    name_regional: 'ரவா தோசை',
    description: 'Instant lacy crepe made from semolina, rice flour and all-purpose flour, scattered with onion, green chilli and curry leaves — crispy and quick.',
    cuisine: ['Tamil Nadu'],
    region: 'SOUTH',
    slot: ['breakfast'],
    is_veg: true, is_vegan: true, is_jain: false, is_fasting: false, is_street: false,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Ven Pongal',
    name_hindi: 'वेन पोंगल',
    name_regional: 'வெண் பொங்கல்',
    description: 'Savory porridge of rice and moong dal cooked together with black pepper, cumin and ghee — a Tamil temple food eaten for breakfast on most days.',
    cuisine: ['Tamil Nadu'],
    region: 'SOUTH',
    slot: ['breakfast'],
    is_veg: true, is_vegan: false, is_jain: true, is_fasting: false, is_street: false,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: ['protein'],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Upma',
    name_hindi: 'उपमा',
    name_regional: 'உப்பமா',
    description: 'Semolina cooked with onion, mustard seeds, curry leaves, ginger and mixed vegetables — a simple Tamil breakfast prepared in under twenty minutes.',
    cuisine: ['Tamil Nadu'],
    region: 'SOUTH',
    slot: ['breakfast'],
    is_veg: true, is_vegan: true, is_jain: false, is_fasting: false, is_street: false,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Idiyappam',
    name_hindi: 'इडियप्पम',
    name_regional: 'இடியாப்பம்',
    description: 'Delicate steamed string hoppers pressed from rice flour dough, served with coconut milk, egg curry or vegetable stew.',
    cuisine: ['Tamil Nadu'],
    region: 'SOUTH',
    slot: ['breakfast'],
    is_veg: true, is_vegan: true, is_jain: true, is_fasting: false, is_street: false,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Appam',
    name_hindi: 'अप्पम',
    name_regional: 'அப்பம்',
    description: 'Lacy fermented rice flour pancake with a soft spongy center and crispy thin edges, served with coconut milk or stew.',
    cuisine: ['Tamil Nadu'],
    region: 'SOUTH',
    slot: ['breakfast'],
    is_veg: true, is_vegan: true, is_jain: true, is_fasting: false, is_street: false,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Pesarattu',
    name_hindi: 'पेसरट्टू',
    name_regional: 'பசரட்டு',
    description: 'Crispy crepe made from whole green moong batter with ginger and green chilli — protein-rich and naturally gluten-free.',
    cuisine: ['Tamil Nadu'],
    region: 'SOUTH',
    slot: ['breakfast'],
    is_veg: true, is_vegan: true, is_jain: true, is_fasting: false, is_street: false,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: ['protein', 'low-gi'],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Medu Vada',
    name_hindi: 'मेदु वड़ा',
    name_regional: 'மெதுவடை',
    description: 'Deep-fried crispy urad dal doughnut with a soft interior, flavoured with black pepper, cumin and curry leaves — served with coconut chutney and sambar.',
    cuisine: ['Tamil Nadu'],
    region: 'SOUTH',
    slot: ['breakfast'],
    is_veg: true, is_vegan: true, is_jain: true, is_fasting: false, is_street: false,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: ['protein'],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Oothappam',
    name_hindi: 'उत्तपम',
    name_regional: 'உத்தாப்பம்',
    description: 'Thick soft pancake made from fermented rice-lentil batter, topped with onion, tomato, green chilli and coriander before pan-frying.',
    cuisine: ['Tamil Nadu'],
    region: 'SOUTH',
    slot: ['breakfast'],
    is_veg: true, is_vegan: true, is_jain: false, is_fasting: false, is_street: false,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Semiya Upma',
    name_hindi: 'सेमिया उपमा',
    name_regional: 'சேமியா உப்பமா',
    description: 'Vermicelli cooked with mustard seeds, onion, green chilli and vegetables in a light tempering of oil — a quick Tamil breakfast.',
    cuisine: ['Tamil Nadu'],
    region: 'SOUTH',
    slot: ['breakfast'],
    is_veg: true, is_vegan: true, is_jain: false, is_fasting: false, is_street: false,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Kuzhi Paniyaram',
    name_hindi: null,
    name_regional: 'குழி பணியாரம்',
    description: 'Small dumplings made from leftover idli-dosa batter cooked in a special cast-iron mould until golden outside and soft inside, served with chutneys.',
    cuisine: ['Tamil Nadu'],
    region: 'SOUTH',
    slot: ['breakfast'],
    is_veg: true, is_vegan: true, is_jain: false, is_fasting: false, is_street: false,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Wheat Rava Upma',
    name_hindi: 'गेहूं रवा उपमा',
    name_regional: null,
    description: 'Broken wheat cooked with onion, green chilli, ginger and vegetables — a fibre-rich healthy Tamil breakfast.',
    cuisine: ['Tamil Nadu'],
    region: 'SOUTH',
    slot: ['breakfast'],
    is_veg: true, is_vegan: true, is_jain: false, is_fasting: false, is_street: false,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: ['fibre', 'low-gi'],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },

  // ── LUNCH CURRY (15) ─────────────────────────────────────────────────────────

  {
    name: 'Sambar',
    name_hindi: 'सांभर',
    name_regional: 'சாம்பார்',
    description: 'Tangy lentil and vegetable stew spiced with sambar powder and tamarind — the cornerstone of every Tamil Nadu lunch.',
    cuisine: ['Tamil Nadu'],
    region: 'SOUTH',
    slot: ['lunch_curry'],
    is_veg: true, is_vegan: true, is_jain: false, is_fasting: false, is_street: false,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: ['protein', 'fibre'],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Rasam',
    name_hindi: 'रसम',
    name_regional: 'ரசம்',
    description: 'Thin peppery tamarind broth with tomato, garlic and spices — drunk as a digestive soup or mixed with rice in Tamil meals.',
    cuisine: ['Tamil Nadu'],
    region: 'SOUTH',
    slot: ['lunch_curry'],
    is_veg: true, is_vegan: true, is_jain: false, is_fasting: false, is_street: false,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: ['light'],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Chettinad Chicken Curry',
    name_hindi: 'चेट्टीनाड चिकन करी',
    name_regional: 'செட்டிநாடு கோழி குழம்பு',
    description: 'Fiery aromatic chicken curry from the Chettinad region made with freshly ground spices including kalpasi, marathi mokku and star anise.',
    cuisine: ['Tamil Nadu'],
    region: 'SOUTH',
    slot: ['lunch_curry'],
    is_veg: false, is_vegan: false, is_jain: false, is_fasting: false, is_street: false,
    is_non_veg_type: 'chicken', allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Puli Kuzhambu',
    name_hindi: null,
    name_regional: 'புளி குழம்பு',
    description: 'Bold tamarind-based curry with shallots, small brinjal and a complex spice base — the definitive Tamil sour kuzhambu eaten with rice.',
    cuisine: ['Tamil Nadu'],
    region: 'SOUTH',
    slot: ['lunch_curry'],
    is_veg: true, is_vegan: true, is_jain: false, is_fasting: false, is_street: false,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Meen Kuzhambu',
    name_hindi: 'मछली करी',
    name_regional: 'மீன் குழம்பு',
    description: 'Tangy tamarind fish curry with shallots, tomato and a freshly ground coconut-spice base — a must at every Tamil non-veg lunch.',
    cuisine: ['Tamil Nadu'],
    region: 'SOUTH',
    slot: ['lunch_curry'],
    is_veg: false, is_vegan: false, is_jain: false, is_fasting: false, is_street: false,
    is_non_veg_type: 'fish', allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Vendakkai Sambar',
    name_hindi: 'भिंडी सांभर',
    name_regional: 'வெண்டைக்காய் சாம்பார்',
    description: 'Classic Tamil sambar with crispy fried okra added to the lentil-tamarind base — the okra lends a mild sweetness and body to the stew.',
    cuisine: ['Tamil Nadu'],
    region: 'SOUTH',
    slot: ['lunch_curry'],
    is_veg: true, is_vegan: true, is_jain: false, is_fasting: false, is_street: false,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: ['fibre'],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Paruppu Kuzhambu',
    name_hindi: null,
    name_regional: 'பருப்பு குழம்பு',
    description: 'Thick lentil curry cooked with tomato, shallots and ground coconut spice paste — a comforting everyday Tamil kuzhambu.',
    cuisine: ['Tamil Nadu'],
    region: 'SOUTH',
    slot: ['lunch_curry'],
    is_veg: true, is_vegan: true, is_jain: false, is_fasting: false, is_street: false,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: ['protein'],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Mutton Chettinad',
    name_hindi: 'चेट्टीनाड मटन',
    name_regional: 'செட்டிநாடு ஆட்டுக்கறி',
    description: 'Slow-cooked Chettinad mutton curry with a powerhouse of whole spices, kalpasi, dagad phool and fresh coconut paste.',
    cuisine: ['Tamil Nadu'],
    region: 'SOUTH',
    slot: ['lunch_curry'],
    is_veg: false, is_vegan: false, is_jain: false, is_fasting: false, is_street: false,
    is_non_veg_type: 'mutton', allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Prawn Masala Tamil Style',
    name_hindi: 'झींगा मसाला',
    name_regional: 'இறால் மசாலா',
    description: 'Spicy prawn dry masala with shallots, tomato, fennel and fresh-ground Chettinad spice blend — best eaten with rice and rasam.',
    cuisine: ['Tamil Nadu'],
    region: 'SOUTH',
    slot: ['lunch_curry'],
    is_veg: false, is_vegan: false, is_jain: false, is_fasting: false, is_street: false,
    is_non_veg_type: 'prawn', allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Egg Curry Chettinad',
    name_hindi: 'अंडा करी',
    name_regional: 'முட்டை குழம்பு',
    description: 'Hard-boiled eggs simmered in a Chettinad-spiced onion-tomato gravy with coconut paste and kalpasi.',
    cuisine: ['Tamil Nadu'],
    region: 'SOUTH',
    slot: ['lunch_curry'],
    is_veg: false, is_vegan: false, is_jain: false, is_fasting: false, is_street: false,
    is_non_veg_type: 'egg', allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Kootu',
    name_hindi: null,
    name_regional: 'கூட்டு',
    description: 'Thick semi-dry curry of vegetables and lentils cooked with a fresh coconut and cumin paste — a mild, protein-rich Tamil side curry.',
    cuisine: ['Tamil Nadu'],
    region: 'SOUTH',
    slot: ['lunch_curry'],
    is_veg: true, is_vegan: true, is_jain: false, is_fasting: false, is_street: false,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: ['protein', 'fibre'],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Mor Kuzhambu',
    name_hindi: null,
    name_regional: 'மோர் குழம்பு',
    description: 'Buttermilk curry tempered with mustard seeds, curry leaves and spiced with a fresh coconut-turmeric paste — cooling and digestive.',
    cuisine: ['Tamil Nadu'],
    region: 'SOUTH',
    slot: ['lunch_curry'],
    is_veg: true, is_vegan: false, is_jain: true, is_fasting: false, is_street: false,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: ['light'],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Vatha Kuzhambu',
    name_hindi: null,
    name_regional: 'வத்த குழம்பு',
    description: 'Intensely sour shallot-tamarind curry with sun-dried manathakkali or sundakkai vathal — a deep-flavoured Tamil kuzhambu.',
    cuisine: ['Tamil Nadu'],
    region: 'SOUTH',
    slot: ['lunch_curry'],
    is_veg: true, is_vegan: true, is_jain: false, is_fasting: false, is_street: false,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Nanjilnadu Fish Curry',
    name_hindi: null,
    name_regional: 'நஞ்சில்நாடு மீன் குழம்பு',
    description: 'Kerala-border style fish curry from the Nanjil Nadu region made with raw mango, shallots and freshly ground coconut and chilli paste.',
    cuisine: ['Tamil Nadu'],
    region: 'SOUTH',
    slot: ['lunch_curry'],
    is_veg: false, is_vegan: false, is_jain: false, is_fasting: false, is_street: false,
    is_non_veg_type: 'fish', allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Avial',
    name_hindi: 'अवियल',
    name_regional: 'அவியல்',
    description: 'Mixed vegetable preparation in a coconut-yogurt gravy with green chilli and cumin — a classic Tamil-Kerala border dish cooked with zero oil.',
    cuisine: ['Tamil Nadu'],
    region: 'SOUTH',
    slot: ['lunch_curry'],
    is_veg: true, is_vegan: false, is_jain: false, is_fasting: false, is_street: false,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: ['light'],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },

  // ── DINNER CURRY (12) ────────────────────────────────────────────────────────

  {
    name: 'Dal Tadka Tamil Style',
    name_hindi: 'दाल तड़का',
    name_regional: null,
    description: 'Toor dal finished with a strong Tamil tadka of mustard, dried red chilli, curry leaves and garlic — lighter and more aromatic than the North Indian version.',
    cuisine: ['Tamil Nadu'],
    region: 'SOUTH',
    slot: ['dinner_curry'],
    is_veg: true, is_vegan: true, is_jain: false, is_fasting: false, is_street: false,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: ['protein'],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Chicken Varuval',
    name_hindi: 'चिकन वरुवल',
    name_regional: 'சிக்கன் வறுவல்',
    description: 'Dry-roasted chicken tossed with fennel, black pepper and shallots until the masala coats every piece — a Tamil dry chicken preparation.',
    cuisine: ['Tamil Nadu'],
    region: 'SOUTH',
    slot: ['dinner_curry'],
    is_veg: false, is_vegan: false, is_jain: false, is_fasting: false, is_street: false,
    is_non_veg_type: 'chicken', allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Chettinad Pepper Chicken',
    name_hindi: 'चेट्टीनाड पेपर चिकन',
    name_regional: 'மிளகு கோழி',
    description: 'Chicken marinated in black pepper and fennel, then slow-cooked in a dark onion-tomato gravy — the definitive Chettinad pepper preparation.',
    cuisine: ['Tamil Nadu'],
    region: 'SOUTH',
    slot: ['dinner_curry'],
    is_veg: false, is_vegan: false, is_jain: false, is_fasting: false, is_street: false,
    is_non_veg_type: 'chicken', allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Mutton Kola Urundai',
    name_hindi: 'मटन कोला उरुंदई',
    name_regional: 'மட்டன் கோல உருண்டை',
    description: 'Chettinad mutton keema balls deep fried with raw rice, coconut and spices — served as an appetiser or with rice and kuzhambu.',
    cuisine: ['Tamil Nadu'],
    region: 'SOUTH',
    slot: ['dinner_curry'],
    is_veg: false, is_vegan: false, is_jain: false, is_fasting: false, is_street: false,
    is_non_veg_type: 'mutton', allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Meen Varuval',
    name_hindi: 'मछली फ्राई',
    name_regional: 'மீன் வறுவல்',
    description: 'Fish fillets marinated in turmeric, chilli and tamarind then shallow-fried until crispy — a Tamil classic eaten with rice and sambar.',
    cuisine: ['Tamil Nadu'],
    region: 'SOUTH',
    slot: ['dinner_curry'],
    is_veg: false, is_vegan: false, is_jain: false, is_fasting: false, is_street: false,
    is_non_veg_type: 'fish', allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Prawn Thokku',
    name_hindi: 'झींगा थोक्कू',
    name_regional: 'இறால் தொக்கு',
    description: 'Prawn cooked down in a thick, intensely spiced onion-tomato masala until the oil separates — a bold Tamil prawn preparation.',
    cuisine: ['Tamil Nadu'],
    region: 'SOUTH',
    slot: ['dinner_curry'],
    is_veg: false, is_vegan: false, is_jain: false, is_fasting: false, is_street: false,
    is_non_veg_type: 'prawn', allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Chicken Chukka',
    name_hindi: 'चिकन चुक्का',
    name_regional: 'சிக்கன் சுக்கா',
    description: 'Bone-in chicken dry-roasted with shallots, fennel seeds and freshly ground Chettinad masala until dark and aromatic.',
    cuisine: ['Tamil Nadu'],
    region: 'SOUTH',
    slot: ['dinner_curry'],
    is_veg: false, is_vegan: false, is_jain: false, is_fasting: false, is_street: false,
    is_non_veg_type: 'chicken', allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Crab Masala Tamil Style',
    name_hindi: 'केकड़ा मसाला',
    name_regional: 'நண்டு மசாலா',
    description: 'Whole blue swimmer crab cooked in a fiery Chettinad spice gravy with shallots, coconut and freshly pounded spices.',
    cuisine: ['Tamil Nadu'],
    region: 'SOUTH',
    slot: ['dinner_curry'],
    is_veg: false, is_vegan: false, is_jain: false, is_fasting: false, is_street: false,
    is_non_veg_type: 'seafood', allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Poricha Kuzhambu',
    name_hindi: null,
    name_regional: 'பொரிச்ச குழம்பு',
    description: 'Mixed vegetable curry ground with fresh coconut, cumin and pepper without any tamarind — a gentle, nutty Tamil kuzhambu.',
    cuisine: ['Tamil Nadu'],
    region: 'SOUTH',
    slot: ['dinner_curry'],
    is_veg: true, is_vegan: true, is_jain: false, is_fasting: false, is_street: false,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: ['light'],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Milagu Kuzhambu',
    name_hindi: null,
    name_regional: 'மிளகு குழம்பு',
    description: 'Pepper-dominant kuzhambu cooked with shallots and tamarind — known for its digestive properties and traditionally eaten in the monsoon season.',
    cuisine: ['Tamil Nadu'],
    region: 'SOUTH',
    slot: ['dinner_curry'],
    is_veg: true, is_vegan: true, is_jain: false, is_fasting: false, is_street: false,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: ['light'],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Kathirikai Gothsu',
    name_hindi: 'बैंगन गोथसू',
    name_regional: 'கத்திரிக்காய் கோதசு',
    description: 'Roasted and mashed brinjal cooked with tamarind, shallots and mustard tempering — a semi-liquid side dish for pongal and idli.',
    cuisine: ['Tamil Nadu'],
    region: 'SOUTH',
    slot: ['dinner_curry'],
    is_veg: true, is_vegan: true, is_jain: false, is_fasting: false, is_street: false,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Thenga Araitha Kuzhambu',
    name_hindi: null,
    name_regional: 'தேங்காய் அரைத்த குழம்பு',
    description: 'Tamarind kuzhambu enriched with freshly ground coconut and a mix of coriander and cumin — a subtler, creamier Tamil curry.',
    cuisine: ['Tamil Nadu'],
    region: 'SOUTH',
    slot: ['dinner_curry'],
    is_veg: true, is_vegan: true, is_jain: false, is_fasting: false, is_street: false,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },

  // ── VEG SIDE (10) ────────────────────────────────────────────────────────────

  {
    name: 'Beans Poriyal',
    name_hindi: 'बीन्स पोरियल',
    name_regional: 'பீன்ஸ் பொரியல்',
    description: 'French beans stir-fried with mustard seeds, dried red chilli, curry leaves and fresh grated coconut — the classic Tamil poriyal.',
    cuisine: ['Tamil Nadu'],
    region: 'SOUTH',
    slot: ['veg_side'],
    is_veg: true, is_vegan: true, is_jain: true, is_fasting: false, is_street: false,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: ['fibre'],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Cabbage Poriyal',
    name_hindi: 'पत्तागोभी पोरियल',
    name_regional: 'கோஸ் பொரியல்',
    description: 'Shredded cabbage tossed with mustard seeds, curry leaves, green chilli and coconut — a staple Tamil vegetable side.',
    cuisine: ['Tamil Nadu'],
    region: 'SOUTH',
    slot: ['veg_side'],
    is_veg: true, is_vegan: true, is_jain: true, is_fasting: false, is_street: false,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: ['fibre'],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Vazhakkai Poriyal',
    name_hindi: 'कच्चा केला पोरियल',
    name_regional: 'வாழைக்காய் பொரியல்',
    description: 'Raw unripe banana slices stir-fried with mustard, cumin and fresh coconut — a starchy, mildly flavoured Tamil side dish.',
    cuisine: ['Tamil Nadu'],
    region: 'SOUTH',
    slot: ['veg_side'],
    is_veg: true, is_vegan: true, is_jain: true, is_fasting: false, is_street: false,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Pavakkai Poriyal',
    name_hindi: 'करेला पोरियल',
    name_regional: 'பாவக்காய் பொரியல்',
    description: 'Bitter gourd sliced and stir-fried with mustard, dried red chilli and coconut — a medicinal Tamil vegetable side that aids digestion.',
    cuisine: ['Tamil Nadu'],
    region: 'SOUTH',
    slot: ['veg_side'],
    is_veg: true, is_vegan: true, is_jain: true, is_fasting: false, is_street: false,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: ['low-gi', 'diabetic-friendly'],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Kovakkai Poriyal',
    name_hindi: 'तिंडोरा पोरियल',
    name_regional: 'கோவக்காய் பொரியல்',
    description: 'Tindora (ivy gourd) sliced and tossed with mustard, urad dal, dried chilli and coconut — a delicate everyday Tamil poriyal.',
    cuisine: ['Tamil Nadu'],
    region: 'SOUTH',
    slot: ['veg_side'],
    is_veg: true, is_vegan: true, is_jain: true, is_fasting: false, is_street: false,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Murungakkai Stir Fry',
    name_hindi: 'सहजन फ्राई',
    name_regional: 'முருங்கைக்காய் வறுவல்',
    description: 'Drumstick pieces sauteed with onion, turmeric and chilli powder — eaten for its iron content and distinctive earthy flavour.',
    cuisine: ['Tamil Nadu'],
    region: 'SOUTH',
    slot: ['veg_side'],
    is_veg: true, is_vegan: true, is_jain: false, is_fasting: false, is_street: false,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: ['iron-rich'],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Keerai Masiyal',
    name_hindi: 'साग मसियाल',
    name_regional: 'கீரை மசியல்',
    description: 'Spinach or mulai keerai mashed with garlic, green chilli and a light cumin tempering — a simple iron-rich Tamil greens preparation.',
    cuisine: ['Tamil Nadu'],
    region: 'SOUTH',
    slot: ['veg_side'],
    is_veg: true, is_vegan: true, is_jain: false, is_fasting: false, is_street: false,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: ['iron-rich'],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Kothavarangai Poriyal',
    name_hindi: 'ग्वार फली पोरियल',
    name_regional: 'கொத்தவரங்காய் பொரியல்',
    description: 'Cluster beans stir-fried with mustard seeds, urad dal, dried red chilli and coconut — slightly bitter and highly nutritious.',
    cuisine: ['Tamil Nadu'],
    region: 'SOUTH',
    slot: ['veg_side'],
    is_veg: true, is_vegan: true, is_jain: true, is_fasting: false, is_street: false,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: ['fibre', 'low-gi'],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Vazhaipoo Poriyal',
    name_hindi: 'केले के फूल पोरियल',
    name_regional: 'வாழைப்பூ பொரியல்',
    description: 'Banana flower cleaned and cooked with mustard, coconut and a mild spice base — a labour-intensive but deeply nutritious Tamil side dish.',
    cuisine: ['Tamil Nadu'],
    region: 'SOUTH',
    slot: ['veg_side'],
    is_veg: true, is_vegan: true, is_jain: true, is_fasting: false, is_street: false,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: ['iron-rich', 'fibre'],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Brinjal Gothsu',
    name_hindi: 'बैंगन गोथसू',
    name_regional: 'கத்திரிக்காய் கொதசு',
    description: 'Smoked brinjal cooked to a semi-liquid relish with shallots, tamarind and mustard — eaten as a side dish with idli, pongal or rice.',
    cuisine: ['Tamil Nadu'],
    region: 'SOUTH',
    slot: ['veg_side'],
    is_veg: true, is_vegan: true, is_jain: false, is_fasting: false, is_street: false,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },

  // ── RICE (4) ─────────────────────────────────────────────────────────────────

  {
    name: 'Lemon Rice',
    name_hindi: 'नींबू चावल',
    name_regional: 'எலுமிச்சை சாதம்',
    description: 'Cooked rice tempered with mustard, peanuts, dried red chilli, curry leaves and fresh lemon juice — a classic Tamil temple offering.',
    cuisine: ['Tamil Nadu'],
    region: 'SOUTH',
    slot: ['rice'],
    is_veg: true, is_vegan: true, is_jain: true, is_fasting: false, is_street: false,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Puliyodarai',
    name_hindi: 'इमली चावल',
    name_regional: 'புளியோதரை',
    description: 'Rice mixed with a freshly made tamarind-spice paste with peanuts, sesame and curry leaves — a temple prasad staple across Tamil Nadu.',
    cuisine: ['Tamil Nadu'],
    region: 'SOUTH',
    slot: ['rice'],
    is_veg: true, is_vegan: true, is_jain: true, is_fasting: false, is_street: false,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Thayir Sadam',
    name_hindi: 'दही चावल',
    name_regional: 'தயிர் சாதம்',
    description: 'Cooked rice mixed with yogurt and a light tempering of mustard, ginger and pomegranate — the last course of every Tamil meal.',
    cuisine: ['Tamil Nadu'],
    region: 'SOUTH',
    slot: ['rice'],
    is_veg: true, is_vegan: false, is_jain: true, is_fasting: false, is_street: false,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: ['probiotic', 'light'],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Coconut Rice Tamil Style',
    name_hindi: 'नारियल चावल',
    name_regional: 'தேங்காய் சாதம்',
    description: 'Rice tossed with fresh grated coconut, mustard, urad dal, dried red chilli and curry leaves — a festival rice from Tamil Nadu.',
    cuisine: ['Tamil Nadu'],
    region: 'SOUTH',
    slot: ['rice'],
    is_veg: true, is_vegan: true, is_jain: true, is_fasting: false, is_street: false,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },

  // ── BREAD (2) ────────────────────────────────────────────────────────────────

  {
    name: 'Parotta',
    name_hindi: 'पोरोटा',
    name_regional: 'பரோட்டா',
    description: 'Layered flaky flatbread made by folding and coiling maida dough repeatedly, then griddled with oil — best eaten with salna or chicken curry.',
    cuisine: ['Tamil Nadu'],
    region: 'SOUTH',
    slot: ['bread'],
    is_veg: true, is_vegan: false, is_jain: true, is_fasting: false, is_street: false,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Poori Tamil Style',
    name_hindi: 'पूरी',
    name_regional: 'பூரி',
    description: 'Deep-fried puffed wheat bread served with potato masala or chana — a beloved Tamil weekend breakfast and festive bread.',
    cuisine: ['Tamil Nadu'],
    region: 'SOUTH',
    slot: ['bread'],
    is_veg: true, is_vegan: true, is_jain: true, is_fasting: false, is_street: false,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },

  // ── RAITA (2) ────────────────────────────────────────────────────────────────

  {
    name: 'Cucumber Pachadi',
    name_hindi: 'खीरा पचड़ी',
    name_regional: 'வேலரிக்காய் பச்சடி',
    description: 'Fresh cucumber mixed with yogurt and tempered with mustard seeds and green chilli — a cooling Tamil raita served alongside rice meals.',
    cuisine: ['Tamil Nadu'],
    region: 'SOUTH',
    slot: ['raita'],
    is_veg: true, is_vegan: false, is_jain: true, is_fasting: false, is_street: false,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: ['cooling', 'probiotic'],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Pineapple Pachadi',
    name_hindi: 'अनानास पचड़ी',
    name_regional: 'அன்னாசி பச்சடி',
    description: 'Ripe pineapple cooked briefly with yogurt, coconut and a mustard tempering — a sweet-sour Tamil pachadi served at weddings and festivals.',
    cuisine: ['Tamil Nadu'],
    region: 'SOUTH',
    slot: ['raita'],
    is_veg: true, is_vegan: false, is_jain: true, is_fasting: false, is_street: false,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },

  // ── SNACK (1) ────────────────────────────────────────────────────────────────

  {
    name: 'Murukku',
    name_hindi: 'मुरुक्कू',
    name_regional: 'முறுக்கு',
    description: 'Crispy deep-fried rice flour and urad dal snack pressed through a star mould into spiral shapes — the iconic Tamil Diwali and everyday snack.',
    cuisine: ['Tamil Nadu'],
    region: 'SOUTH',
    slot: ['snack'],
    is_veg: true, is_vegan: true, is_jain: true, is_fasting: false, is_street: false,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },

];

// ─── Seed function ─────────────────────────────────────────────────────────────

async function seed() {
  const BATCH_SIZE = 20;
  let totalInserted = 0;
  let totalErrors   = 0;

  const tamilnadu = dishes.filter(d => d.cuisine?.includes('Tamil Nadu'));
  console.log(`\nSeeding ${dishes.length} dishes (Tamil Nadu: ${tamilnadu.length})\n`);

  for (let i = 0; i < dishes.length; i += BATCH_SIZE) {
    const batch = dishes.slice(i, i + BATCH_SIZE);
    const { error } = await client.from('dishes').insert(batch);
    if (error) {
      console.error(`  Batch ${Math.floor(i / BATCH_SIZE) + 1} ERROR:`, error.message);
      totalErrors += batch.length;
    } else {
      totalInserted += batch.length;
      console.log(`  Batch ${Math.floor(i / BATCH_SIZE) + 1}: inserted ${batch.length} dishes (running total: ${totalInserted})`);
    }
  }

  console.log(`\nDone. Inserted: ${totalInserted} | Errors: ${totalErrors}`);
  console.log('\nVerification query:');
  console.log("  SELECT cuisine[1] as cuisine, COUNT(*) FROM dishes WHERE cuisine @> ARRAY['Tamil Nadu'] GROUP BY cuisine[1];");

  // Verify via API
  const { data: rows } = await client.from('dishes').select('cuisine').contains('cuisine', ['Tamil Nadu']);
  const tn = (rows ?? []).length;

  console.log('\n' + '┌' + '─'.repeat(16) + '┬' + '─'.repeat(18) + '┬' + '─'.repeat(17) + '┬' + '─'.repeat(8) + '┐');
  console.log('│ ' + 'Cuisine'.padEnd(14) + ' │ ' + 'Dishes generated'.padEnd(16) + ' │ ' + 'Dishes inserted'.padEnd(15) + ' │ ' + 'Errors'.padEnd(6) + ' │');
  console.log('├' + '─'.repeat(16) + '┼' + '─'.repeat(18) + '┼' + '─'.repeat(17) + '┼' + '─'.repeat(8) + '┤');
  console.log('│ ' + 'Tamil Nadu'.padEnd(14) + ' │ ' + String(tamilnadu.length).padEnd(16) + ' │ ' + String(tn).padEnd(15) + ' │ ' + String(totalErrors).padEnd(6) + ' │');
  console.log('├' + '─'.repeat(16) + '┼' + '─'.repeat(18) + '┼' + '─'.repeat(17) + '┼' + '─'.repeat(8) + '┤');
  console.log('│ ' + 'TOTAL'.padEnd(14) + ' │ ' + String(dishes.length).padEnd(16) + ' │ ' + String(totalInserted).padEnd(15) + ' │ ' + String(totalErrors).padEnd(6) + ' │');
  console.log('└' + '─'.repeat(16) + '┴' + '─'.repeat(18) + '┴' + '─'.repeat(17) + '┴' + '─'.repeat(8) + '┘');
}

seed().catch(console.error);
