require('dotenv').config();
const { createClient } = require('@supabase/supabase-js');

const client = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL,
  process.env.SUPABASE_SERVICE_ROLE_KEY,
);

// ─── 70 Punjabi dishes ────────────────────────────────────────────────────────
// Distribution: 15 breakfast | 18 lunch_curry | 15 dinner_curry |
//               10 veg_side | 5 rice | 4 bread | 2 raita | 1 snack

// ─── 60 Gujarati dishes ───────────────────────────────────────────────────────
// Distribution: 12 breakfast | 15 lunch_curry | 12 dinner_curry |
//               10 veg_side | 5 rice | 3 bread | 2 raita | 1 snack

const dishes = [

  // ══════════════════════════════════════════════════════════════════════════════
  // PUNJABI  (70)
  // ══════════════════════════════════════════════════════════════════════════════

  // ── BREAKFAST (15) ───────────────────────────────────────────────────────────

  {
    name: 'Aloo Paratha',
    name_hindi: 'आलू पराठा',
    name_regional: null,
    description: 'Whole-wheat flatbread stuffed with spiced mashed potato, roasted on a tawa with ghee — the undisputed king of Punjabi breakfast.',
    cuisine: ['Punjabi'],
    region: 'NORTH',
    slot: ['breakfast'],
    is_veg: true, is_vegan: false, is_jain: false, is_fasting: false, is_street: false,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Gobi Paratha',
    name_hindi: 'गोभी पराठा',
    name_regional: null,
    description: 'Wheat flatbread filled with grated spiced cauliflower, cooked in ghee — a Punjabi winter morning staple.',
    cuisine: ['Punjabi'],
    region: 'NORTH',
    slot: ['breakfast'],
    is_veg: true, is_vegan: false, is_jain: true, is_fasting: false, is_street: false,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Paneer Paratha',
    name_hindi: 'पनीर पराठा',
    name_regional: null,
    description: 'Wheat flatbread stuffed with crumbled cottage cheese spiced with green chilli and cumin — a protein-rich Punjabi breakfast.',
    cuisine: ['Punjabi'],
    region: 'NORTH',
    slot: ['breakfast'],
    is_veg: true, is_vegan: false, is_jain: true, is_fasting: false, is_street: false,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Mooli Paratha',
    name_hindi: 'मूली पराठा',
    name_regional: null,
    description: 'Flatbread stuffed with grated white radish, ajwain, and green chilli — a peppery Punjabi winter breakfast served with pickles.',
    cuisine: ['Punjabi'],
    region: 'NORTH',
    slot: ['breakfast'],
    is_veg: true, is_vegan: false, is_jain: false, is_fasting: false, is_street: false,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Pyaz Paratha',
    name_hindi: 'प्याज़ पराठा',
    name_regional: null,
    description: 'Flatbread stuffed with raw onion, green chilli, and coriander — quick to make and sharp in flavour, a Punjabi roadside breakfast.',
    cuisine: ['Punjabi'],
    region: 'NORTH',
    slot: ['breakfast'],
    is_veg: true, is_vegan: false, is_jain: false, is_fasting: false, is_street: false,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Methi Paratha',
    name_hindi: 'मेथी पराठा',
    name_regional: null,
    description: 'Fenugreek leaves kneaded into whole-wheat dough and cooked with ghee — an iron-rich Punjabi winter breakfast.',
    cuisine: ['Punjabi'],
    region: 'NORTH',
    slot: ['breakfast'],
    is_veg: true, is_vegan: false, is_jain: true, is_fasting: false, is_street: false,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Dahi Paratha',
    name_hindi: 'दही पराठा',
    name_regional: null,
    description: 'Soft flatbread with yogurt kneaded into the dough, creating a tender layered result — a mild everyday Punjabi breakfast.',
    cuisine: ['Punjabi'],
    region: 'NORTH',
    slot: ['breakfast'],
    is_veg: true, is_vegan: false, is_jain: true, is_fasting: false, is_street: false,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Amritsari Kulcha',
    name_hindi: 'अमृतसरी कुलचा',
    name_regional: null,
    description: 'Leavened bread stuffed with spiced potato and onion, baked in a tandoor and finished with butter — Amritsar street breakfast icon.',
    cuisine: ['Punjabi'],
    region: 'NORTH',
    slot: ['breakfast'],
    is_veg: true, is_vegan: false, is_jain: false, is_fasting: false, is_street: true,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Chole Bhature',
    name_hindi: 'छोले भटूरे',
    name_regional: null,
    description: 'Spiced chickpea curry paired with deep-fried leavened bread — the most iconic Punjabi brunch and street food combination.',
    cuisine: ['Punjabi'],
    region: 'NORTH',
    slot: ['breakfast'],
    is_veg: true, is_vegan: false, is_jain: false, is_fasting: false, is_street: true,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Puri Aloo',
    name_hindi: 'पूरी आलू',
    name_regional: null,
    description: 'Deep-fried wheat puffs served with a runny spiced potato curry — a beloved Punjabi Sunday morning ritual.',
    cuisine: ['Punjabi'],
    region: 'NORTH',
    slot: ['breakfast'],
    is_veg: true, is_vegan: false, is_jain: false, is_fasting: false, is_street: false,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Sweet Lassi',
    name_hindi: 'मीठी लस्सी',
    name_regional: null,
    description: 'Thick chilled yogurt drink sweetened with sugar, topped with a layer of cream — the classic Punjabi breakfast cooler.',
    cuisine: ['Punjabi'],
    region: 'NORTH',
    slot: ['breakfast'],
    is_veg: true, is_vegan: false, is_jain: true, is_fasting: true, is_street: true,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Makhan Roti',
    name_hindi: 'मक्खन रोटी',
    name_regional: null,
    description: 'Fresh whole-wheat flatbread slathered with white butter — the simplest and most comforting Punjabi everyday breakfast.',
    cuisine: ['Punjabi'],
    region: 'NORTH',
    slot: ['breakfast'],
    is_veg: true, is_vegan: false, is_jain: true, is_fasting: false, is_street: false,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Anda Bhurji',
    name_hindi: 'अंडा भुर्जी',
    name_regional: null,
    description: 'Scrambled eggs cooked with onion, tomato, green chilli, and fresh coriander — a quick and protein-rich Punjabi breakfast.',
    cuisine: ['Punjabi'],
    region: 'NORTH',
    slot: ['breakfast'],
    is_veg: false, is_vegan: false, is_jain: false, is_fasting: false, is_street: true,
    is_non_veg_type: 'egg', allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Bedmi Poori',
    name_hindi: 'बेड़मी पूरी',
    name_regional: null,
    description: 'Deep-fried puffed bread stuffed with spiced urad dal — a hearty Punjabi and Delhi morning street food served with aloo sabzi.',
    cuisine: ['Punjabi'],
    region: 'NORTH',
    slot: ['breakfast'],
    is_veg: true, is_vegan: true, is_jain: false, is_fasting: false, is_street: true,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Tandoori Paratha',
    name_hindi: 'तंदूरी पराठा',
    name_regional: null,
    description: 'Flaky wheat flatbread cooked directly on the walls of a clay tandoor, blistered and chewy — eaten with dal or pickles.',
    cuisine: ['Punjabi'],
    region: 'NORTH',
    slot: ['breakfast'],
    is_veg: true, is_vegan: false, is_jain: true, is_fasting: false, is_street: false,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },

  // ── LUNCH CURRY (18) ────────────────────────────────────────────────────────

  {
    name: 'Dal Makhani',
    name_hindi: 'दाल मखनी',
    name_regional: null,
    description: 'Whole black lentils slow-cooked overnight with rajma, butter, and cream — the richest and most iconic Punjabi dal.',
    cuisine: ['Punjabi'],
    region: 'NORTH',
    slot: ['lunch_curry'],
    is_veg: true, is_vegan: false, is_jain: false, is_fasting: false, is_street: false,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday', 'party'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Sarson da Saag',
    name_hindi: 'सरसों दा साग',
    name_regional: null,
    description: 'Slow-cooked mustard and spinach greens mash finished with a generous knob of white butter — Punjab winter soul food.',
    cuisine: ['Punjabi'],
    region: 'NORTH',
    slot: ['lunch_curry'],
    is_veg: true, is_vegan: false, is_jain: false, is_fasting: false, is_street: false,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Rajma Masala',
    name_hindi: 'राजमा मसाला',
    name_regional: null,
    description: 'Red kidney beans simmered in a thick onion-tomato gravy with whole spices — the beloved Punjabi comfort food eaten over rice.',
    cuisine: ['Punjabi'],
    region: 'NORTH',
    slot: ['lunch_curry'],
    is_veg: true, is_vegan: false, is_jain: false, is_fasting: false, is_street: false,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Punjabi Chole',
    name_hindi: 'पंजाबी छोले',
    name_regional: null,
    description: 'Chickpeas cooked with tea-darkened gravy, dried pomegranate seeds, and a punchy chole masala — bold, tangy, and hearty.',
    cuisine: ['Punjabi'],
    region: 'NORTH',
    slot: ['lunch_curry'],
    is_veg: true, is_vegan: true, is_jain: false, is_fasting: false, is_street: false,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Paneer Butter Masala',
    name_hindi: 'पनीर बटर मसाला',
    name_regional: null,
    description: 'Cottage cheese cubes in a rich buttery tomato-cream gravy with kasuri methi — a Punjabi restaurant classic loved nationwide.',
    cuisine: ['Punjabi'],
    region: 'NORTH',
    slot: ['lunch_curry'],
    is_veg: true, is_vegan: false, is_jain: false, is_fasting: false, is_street: false,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday', 'party'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Matar Paneer',
    name_hindi: 'मटर पनीर',
    name_regional: null,
    description: 'Green peas and cottage cheese in a spiced tomato-onion gravy — an everyday Punjabi household curry.',
    cuisine: ['Punjabi'],
    region: 'NORTH',
    slot: ['lunch_curry'],
    is_veg: true, is_vegan: false, is_jain: false, is_fasting: false, is_street: false,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Palak Paneer',
    name_hindi: 'पालक पनीर',
    name_regional: null,
    description: 'Cottage cheese cubes folded into a smooth spiced spinach puree — one of the most recognisable Punjabi vegetarian curries.',
    cuisine: ['Punjabi'],
    region: 'NORTH',
    slot: ['lunch_curry'],
    is_veg: true, is_vegan: false, is_jain: false, is_fasting: false, is_street: false,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Butter Chicken',
    name_hindi: 'बटर चिकन',
    name_regional: null,
    description: 'Tandoor-roasted chicken simmered in a velvety butter-tomato-cream sauce with kasuri methi — invented in Delhi, loved worldwide.',
    cuisine: ['Punjabi'],
    region: 'NORTH',
    slot: ['lunch_curry'],
    is_veg: false, is_vegan: false, is_jain: false, is_fasting: false, is_street: false,
    is_non_veg_type: 'chicken', allowed_days: [], occasion: ['everyday', 'party'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Chicken Tikka Masala',
    name_hindi: 'चिकन टिक्का मसाला',
    name_regional: null,
    description: 'Marinated tandoori chicken tikka simmered in a spiced onion-tomato gravy — a quintessential Punjabi restaurant showpiece.',
    cuisine: ['Punjabi'],
    region: 'NORTH',
    slot: ['lunch_curry'],
    is_veg: false, is_vegan: false, is_jain: false, is_fasting: false, is_street: false,
    is_non_veg_type: 'chicken', allowed_days: [], occasion: ['everyday', 'party'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Keema Matar',
    name_hindi: 'कीमा मटर',
    name_regional: null,
    description: 'Minced mutton cooked with green peas, onion, ginger-garlic, and garam masala — a quick and hearty Punjabi non-veg weekday lunch.',
    cuisine: ['Punjabi'],
    region: 'NORTH',
    slot: ['lunch_curry'],
    is_veg: false, is_vegan: false, is_jain: false, is_fasting: false, is_street: false,
    is_non_veg_type: 'mutton', allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Amritsari Fish Curry',
    name_hindi: 'अमृतसरी मछली करी',
    name_regional: null,
    description: 'River fish cooked in a tangy mustard-oil-based Punjabi gravy with ajwain and dried mango — a robust Amritsari home-style curry.',
    cuisine: ['Punjabi'],
    region: 'NORTH',
    slot: ['lunch_curry'],
    is_veg: false, is_vegan: false, is_jain: false, is_fasting: false, is_street: false,
    is_non_veg_type: 'fish', allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Aloo Matar',
    name_hindi: 'आलू मटर',
    name_regional: null,
    description: 'Potato and green pea curry in a simple onion-tomato masala — a reliable everyday Punjabi lunch.',
    cuisine: ['Punjabi'],
    region: 'NORTH',
    slot: ['lunch_curry'],
    is_veg: true, is_vegan: true, is_jain: false, is_fasting: false, is_street: false,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Kadhai Paneer',
    name_hindi: 'कढ़ाई पनीर',
    name_regional: null,
    description: 'Cottage cheese and capsicum tossed in coarsely ground coriander-tomato masala in a wok — a bold, fragrant Punjabi dhaba staple.',
    cuisine: ['Punjabi'],
    region: 'NORTH',
    slot: ['lunch_curry'],
    is_veg: true, is_vegan: false, is_jain: false, is_fasting: false, is_street: false,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Shahi Paneer',
    name_hindi: 'शाही पनीर',
    name_regional: null,
    description: 'Cottage cheese in a royal cashew-cream-tomato gravy with whole aromatic spices — a rich Punjabi party curry.',
    cuisine: ['Punjabi'],
    region: 'NORTH',
    slot: ['lunch_curry'],
    is_veg: true, is_vegan: false, is_jain: false, is_fasting: false, is_street: false,
    is_non_veg_type: null, allowed_days: [], occasion: ['party', 'everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Chana Dal Tadka',
    name_hindi: 'चना दाल तड़का',
    name_regional: null,
    description: 'Split Bengal gram simmered until soft and finished with a fiery ghee tempering of garlic, dried chillies, and cumin.',
    cuisine: ['Punjabi'],
    region: 'NORTH',
    slot: ['lunch_curry'],
    is_veg: true, is_vegan: false, is_jain: false, is_fasting: false, is_street: false,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Langar Dal',
    name_hindi: 'लंगर दाल',
    name_regional: null,
    description: 'Chana and urad dal slow-cooked in large pots with onion, tomato, and ghee — the sacred dal served at Sikh Gurudwaras.',
    cuisine: ['Punjabi'],
    region: 'NORTH',
    slot: ['lunch_curry'],
    is_veg: true, is_vegan: false, is_jain: false, is_fasting: false, is_street: false,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Mixed Vegetable Curry',
    name_hindi: 'मिक्स सब्ज़ी',
    name_regional: null,
    description: 'Seasonal vegetables cooked together in a Punjabi masala gravy with onion, tomato, ginger, and garlic — an everyday home curry.',
    cuisine: ['Punjabi'],
    region: 'NORTH',
    slot: ['lunch_curry'],
    is_veg: true, is_vegan: false, is_jain: false, is_fasting: false, is_street: false,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Saag Aloo',
    name_hindi: 'साग आलू',
    name_regional: null,
    description: 'Spinach and potato cooked together in a mustard-oil-based Punjabi masala with garlic — a robust winter lunch curry.',
    cuisine: ['Punjabi'],
    region: 'NORTH',
    slot: ['lunch_curry'],
    is_veg: true, is_vegan: true, is_jain: false, is_fasting: false, is_street: false,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },

  // ── DINNER CURRY (15) ───────────────────────────────────────────────────────

  {
    name: 'Dal Tadka',
    name_hindi: 'दाल तड़का',
    name_regional: null,
    description: 'Yellow toor or arhar dal finished with a crackling ghee tempering of cumin, dried chilli, and garlic — the definitive dhaba dal.',
    cuisine: ['Punjabi'],
    region: 'NORTH',
    slot: ['dinner_curry'],
    is_veg: true, is_vegan: false, is_jain: false, is_fasting: false, is_street: false,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Pindi Chole',
    name_hindi: 'पिंडी छोले',
    name_regional: null,
    description: 'Rawalpindi-style dark chickpeas cooked with tea bags for colour, pomegranate seeds for tang — drier and bolder than regular chole.',
    cuisine: ['Punjabi'],
    region: 'NORTH',
    slot: ['dinner_curry'],
    is_veg: true, is_vegan: true, is_jain: false, is_fasting: false, is_street: false,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Malai Kofta',
    name_hindi: 'मलाई कोफ़्ता',
    name_regional: null,
    description: 'Fried paneer and potato dumplings served in a rich cashew-cream-tomato gravy — a Punjabi celebration vegetarian centrepiece.',
    cuisine: ['Punjabi'],
    region: 'NORTH',
    slot: ['dinner_curry'],
    is_veg: true, is_vegan: false, is_jain: false, is_fasting: false, is_street: false,
    is_non_veg_type: null, allowed_days: [], occasion: ['party', 'everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Paneer Tikka Masala',
    name_hindi: 'पनीर टिक्का मसाला',
    name_regional: null,
    description: 'Tandoor-charred marinated paneer cubes simmered in a spiced onion-tomato gravy — a smoky, bold Punjabi dinner curry.',
    cuisine: ['Punjabi'],
    region: 'NORTH',
    slot: ['dinner_curry'],
    is_veg: true, is_vegan: false, is_jain: false, is_fasting: false, is_street: false,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday', 'party'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Sarson Chicken',
    name_hindi: 'सरसों चिकन',
    name_regional: null,
    description: 'Chicken marinated and cooked in a mustard-based Punjabi gravy with sharp mustard seeds and green chilli — bold and earthy.',
    cuisine: ['Punjabi'],
    region: 'NORTH',
    slot: ['dinner_curry'],
    is_veg: false, is_vegan: false, is_jain: false, is_fasting: false, is_street: false,
    is_non_veg_type: 'chicken', allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Mutton Rogan Josh',
    name_hindi: 'मटन रोगन जोश',
    name_regional: null,
    description: 'Slow-cooked mutton in a fiery Kashmiri red gravy with whole spices — widely adopted in Punjabi homes as a special dinner.',
    cuisine: ['Punjabi'],
    region: 'NORTH',
    slot: ['dinner_curry'],
    is_veg: false, is_vegan: false, is_jain: false, is_fasting: false, is_street: false,
    is_non_veg_type: 'mutton', allowed_days: [], occasion: ['everyday', 'party'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Kadhai Chicken',
    name_hindi: 'कढ़ाई चिकन',
    name_regional: null,
    description: 'Chicken tossed with capsicum, tomato, and coarsely ground kadhai masala in a wok — a staple Punjabi dhaba dinner.',
    cuisine: ['Punjabi'],
    region: 'NORTH',
    slot: ['dinner_curry'],
    is_veg: false, is_vegan: false, is_jain: false, is_fasting: false, is_street: false,
    is_non_veg_type: 'chicken', allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Punjabi Chicken Curry',
    name_hindi: 'पंजाबी चिकन करी',
    name_regional: null,
    description: 'Bone-in chicken simmered in a rich onion-tomato-yogurt gravy with Punjabi garam masala — a hearty everyday home dinner.',
    cuisine: ['Punjabi'],
    region: 'NORTH',
    slot: ['dinner_curry'],
    is_veg: false, is_vegan: false, is_jain: false, is_fasting: false, is_street: false,
    is_non_veg_type: 'chicken', allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Aloo Gobi',
    name_hindi: 'आलू गोभी',
    name_regional: null,
    description: 'Potato and cauliflower cooked dry with cumin, turmeric, and green chilli — a simple, aromatic Punjabi dinner vegetable curry.',
    cuisine: ['Punjabi'],
    region: 'NORTH',
    slot: ['dinner_curry'],
    is_veg: true, is_vegan: true, is_jain: false, is_fasting: false, is_street: false,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Lauki Chana Dal',
    name_hindi: 'लौकी चना दाल',
    name_regional: null,
    description: 'Bottle gourd cooked with split Bengal gram in a light Punjabi tempering — a gentle, nutritious weeknight dinner.',
    cuisine: ['Punjabi'],
    region: 'NORTH',
    slot: ['dinner_curry'],
    is_veg: true, is_vegan: true, is_jain: false, is_fasting: false, is_street: false,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Matar Mushroom',
    name_hindi: 'मटर मशरूम',
    name_regional: null,
    description: 'Green peas and button mushrooms in a spiced onion-tomato gravy — a popular Punjabi vegetarian dinner curry.',
    cuisine: ['Punjabi'],
    region: 'NORTH',
    slot: ['dinner_curry'],
    is_veg: true, is_vegan: true, is_jain: false, is_fasting: false, is_street: false,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Palak Kofta',
    name_hindi: 'पालक कोफ़्ता',
    name_regional: null,
    description: 'Soft fried spinach and paneer dumplings simmered in a spiced spinach-tomato gravy — a rich Punjabi winter dinner.',
    cuisine: ['Punjabi'],
    region: 'NORTH',
    slot: ['dinner_curry'],
    is_veg: true, is_vegan: false, is_jain: false, is_fasting: false, is_street: false,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Paneer Do Pyaza',
    name_hindi: 'पनीर दो प्याज़ा',
    name_regional: null,
    description: 'Cottage cheese cooked with a double dose of onions — once in the gravy, once fried — giving a sweet-spicy Punjabi dinner curry.',
    cuisine: ['Punjabi'],
    region: 'NORTH',
    slot: ['dinner_curry'],
    is_veg: true, is_vegan: false, is_jain: false, is_fasting: false, is_street: false,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Aloo Baingan',
    name_hindi: 'आलू बैंगन',
    name_regional: null,
    description: 'Potato and brinjal cooked together in a dry mustard-oil Punjabi masala — a rustic, earthy dinner sabzi.',
    cuisine: ['Punjabi'],
    region: 'NORTH',
    slot: ['dinner_curry'],
    is_veg: true, is_vegan: true, is_jain: false, is_fasting: false, is_street: false,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Kadhi Pakora',
    name_hindi: 'कढ़ी पकोड़ा',
    name_regional: null,
    description: 'Onion and gram flour fritters floating in a tangy fenugreek-spiced yogurt curry — a quintessential Punjabi monsoon dinner.',
    cuisine: ['Punjabi'],
    region: 'NORTH',
    slot: ['dinner_curry'],
    is_veg: true, is_vegan: false, is_jain: false, is_fasting: false, is_street: false,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },

  // ── VEG SIDE (10) ───────────────────────────────────────────────────────────

  {
    name: 'Bhindi Masala',
    name_hindi: 'भिंडी मसाला',
    name_regional: null,
    description: 'Okra stir-fried with onion, tomato, and dry spices until crispy — an everyday Punjabi dry vegetable side.',
    cuisine: ['Punjabi'],
    region: 'NORTH',
    slot: ['veg_side'],
    is_veg: true, is_vegan: true, is_jain: false, is_fasting: false, is_street: false,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Tinda Masala',
    name_hindi: 'टिंडा मसाला',
    name_regional: null,
    description: 'Apple gourd cooked with onion, tomato, and Punjabi spices — a mild, everyday summer vegetable side.',
    cuisine: ['Punjabi'],
    region: 'NORTH',
    slot: ['veg_side'],
    is_veg: true, is_vegan: true, is_jain: false, is_fasting: false, is_street: false,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Lauki Ki Sabzi',
    name_hindi: 'लौकी की सब्ज़ी',
    name_regional: null,
    description: 'Bottle gourd cooked in a simple Punjabi onion-tomato masala — a light and digestive everyday vegetable side.',
    cuisine: ['Punjabi'],
    region: 'NORTH',
    slot: ['veg_side'],
    is_veg: true, is_vegan: true, is_jain: false, is_fasting: false, is_street: false,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Gajar Matar',
    name_hindi: 'गाजर मटर',
    name_regional: null,
    description: 'Carrots and green peas stir-fried with cumin, ginger, and Punjabi spices — a colourful winter vegetable side.',
    cuisine: ['Punjabi'],
    region: 'NORTH',
    slot: ['veg_side'],
    is_veg: true, is_vegan: true, is_jain: false, is_fasting: false, is_street: false,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Methi Aloo',
    name_hindi: 'मेथी आलू',
    name_regional: null,
    description: 'Diced potato stir-fried with fresh fenugreek leaves, garlic, and Punjabi spices — a bitter-earthy winter side dish.',
    cuisine: ['Punjabi'],
    region: 'NORTH',
    slot: ['veg_side'],
    is_veg: true, is_vegan: true, is_jain: false, is_fasting: false, is_street: false,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Karela Masala',
    name_hindi: 'करेला मसाला',
    name_regional: null,
    description: 'Bitter gourd stir-fried with onion, dried mango powder, and spices until caramelised — a prized Punjabi digestive side.',
    cuisine: ['Punjabi'],
    region: 'NORTH',
    slot: ['veg_side'],
    is_veg: true, is_vegan: true, is_jain: false, is_fasting: false, is_street: false,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Kathal Sabzi',
    name_hindi: 'कटहल सब्ज़ी',
    name_regional: null,
    description: 'Raw jackfruit cooked with onion, garlic, and whole Punjabi spices — a meaty-textured vegetarian side eaten with roti.',
    cuisine: ['Punjabi'],
    region: 'NORTH',
    slot: ['veg_side'],
    is_veg: true, is_vegan: true, is_jain: false, is_fasting: false, is_street: false,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Arbi Masala',
    name_hindi: 'अरबी मसाला',
    name_regional: null,
    description: 'Taro cooked in a dry Punjabi spice mix with ajwain and dried mango — a nutty, earthy monsoon vegetable side.',
    cuisine: ['Punjabi'],
    region: 'NORTH',
    slot: ['veg_side'],
    is_veg: true, is_vegan: true, is_jain: false, is_fasting: false, is_street: false,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Kaddu Ki Sabzi',
    name_hindi: 'कद्दू की सब्ज़ी',
    name_regional: null,
    description: 'Pumpkin cooked with mustard seeds, dry red chilli, and a pinch of jaggery — a sweet-spiced Punjabi everyday side.',
    cuisine: ['Punjabi'],
    region: 'NORTH',
    slot: ['veg_side'],
    is_veg: true, is_vegan: true, is_jain: false, is_fasting: false, is_street: false,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Mushroom Masala',
    name_hindi: 'मशरूम मसाला',
    name_regional: null,
    description: 'Button mushrooms tossed in a bold Punjabi onion-tomato-capsicum masala — a quick and flavourful vegetable side.',
    cuisine: ['Punjabi'],
    region: 'NORTH',
    slot: ['veg_side'],
    is_veg: true, is_vegan: true, is_jain: false, is_fasting: false, is_street: false,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },

  // ── RICE (5) ────────────────────────────────────────────────────────────────

  {
    name: 'Jeera Rice',
    name_hindi: 'जीरा चावल',
    name_regional: null,
    description: 'Basmati rice tempered with cumin seeds and ghee — the simplest and most fragrant Punjabi accompaniment rice.',
    cuisine: ['Punjabi'],
    region: 'NORTH',
    slot: ['rice'],
    is_veg: true, is_vegan: false, is_jain: true, is_fasting: false, is_street: false,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Matar Pulao',
    name_hindi: 'मटर पुलाव',
    name_regional: null,
    description: 'Basmati rice cooked with green peas, whole spices, and onion — a fragrant and light Punjabi lunch rice.',
    cuisine: ['Punjabi'],
    region: 'NORTH',
    slot: ['rice'],
    is_veg: true, is_vegan: false, is_jain: false, is_fasting: false, is_street: false,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Rajma Chawal',
    name_hindi: 'राजमा चावल',
    name_regional: null,
    description: 'Red kidney bean curry served over plain steamed rice — the most comforting Punjabi meal combination.',
    cuisine: ['Punjabi'],
    region: 'NORTH',
    slot: ['rice'],
    is_veg: true, is_vegan: false, is_jain: false, is_fasting: false, is_street: false,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Chicken Biryani',
    name_hindi: 'चिकन बिरयानी',
    name_regional: null,
    description: 'Aromatic basmati rice layered with marinated chicken, fried onions, and whole spices — the Punjabi-style dum biryani.',
    cuisine: ['Punjabi'],
    region: 'NORTH',
    slot: ['rice'],
    is_veg: false, is_vegan: false, is_jain: false, is_fasting: false, is_street: false,
    is_non_veg_type: 'chicken', allowed_days: [], occasion: ['party', 'everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Vegetable Pulao',
    name_hindi: 'सब्ज़ी पुलाव',
    name_regional: null,
    description: 'Basmati rice cooked with mixed seasonal vegetables and whole spices — a simple, everyday Punjabi one-pot rice.',
    cuisine: ['Punjabi'],
    region: 'NORTH',
    slot: ['rice'],
    is_veg: true, is_vegan: false, is_jain: false, is_fasting: false, is_street: false,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },

  // ── BREAD (4) ───────────────────────────────────────────────────────────────

  {
    name: 'Tandoori Roti',
    name_hindi: 'तंदूरी रोटी',
    name_regional: null,
    description: 'Whole-wheat flatbread slapped onto the walls of a clay tandoor and cooked on intense heat — slightly charred and chewy.',
    cuisine: ['Punjabi'],
    region: 'NORTH',
    slot: ['bread'],
    is_veg: true, is_vegan: true, is_jain: true, is_fasting: false, is_street: false,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Lachha Paratha',
    name_hindi: 'लच्छा पराठा',
    name_regional: null,
    description: 'Multi-layered flaky wheat bread created by spiralling and pressing the dough — crispy, buttery, a Punjabi restaurant classic.',
    cuisine: ['Punjabi'],
    region: 'NORTH',
    slot: ['bread'],
    is_veg: true, is_vegan: false, is_jain: true, is_fasting: false, is_street: false,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Garlic Naan',
    name_hindi: 'गार्लिक नान',
    name_regional: null,
    description: 'Leavened bread baked in a tandoor and brushed with garlic butter and fresh coriander — a Punjabi dhaba favourite.',
    cuisine: ['Punjabi'],
    region: 'NORTH',
    slot: ['bread'],
    is_veg: true, is_vegan: false, is_jain: false, is_fasting: false, is_street: false,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Butter Naan',
    name_hindi: 'बटर नान',
    name_regional: null,
    description: 'Soft leavened tandoor bread finished with a generous smear of butter — the most ordered bread at any Punjabi restaurant.',
    cuisine: ['Punjabi'],
    region: 'NORTH',
    slot: ['bread'],
    is_veg: true, is_vegan: false, is_jain: true, is_fasting: false, is_street: false,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },

  // ── RAITA (2) ───────────────────────────────────────────────────────────────

  {
    name: 'Boondi Raita',
    name_hindi: 'बूंदी रायता',
    name_regional: null,
    description: 'Crispy gram flour pearls soaked in chilled seasoned yogurt with roasted cumin and dried mint — a classic Punjabi side.',
    cuisine: ['Punjabi'],
    region: 'NORTH',
    slot: ['raita'],
    is_veg: true, is_vegan: false, is_jain: true, is_fasting: false, is_street: false,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Pudina Raita',
    name_hindi: 'पुदीना रायता',
    name_regional: null,
    description: 'Chilled yogurt blended with fresh mint, green chilli, and roasted cumin — a refreshing Punjabi accompaniment for biryanis and parathas.',
    cuisine: ['Punjabi'],
    region: 'NORTH',
    slot: ['raita'],
    is_veg: true, is_vegan: false, is_jain: true, is_fasting: false, is_street: false,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },

  // ── SNACK (1) ───────────────────────────────────────────────────────────────

  {
    name: 'Amritsari Aloo Tikki',
    name_hindi: 'अमृतसरी आलू टिक्की',
    name_regional: null,
    description: 'Mashed potato patties stuffed with spiced chana, fried crisp on a tawa, and topped with chutneys — Amritsar street snack.',
    cuisine: ['Punjabi'],
    region: 'NORTH',
    slot: ['snack'],
    is_veg: true, is_vegan: false, is_jain: false, is_fasting: false, is_street: true,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },

  // ══════════════════════════════════════════════════════════════════════════════
  // GUJARATI  (60)
  // ══════════════════════════════════════════════════════════════════════════════

  // ── BREAKFAST (12) ──────────────────────────────────────────────────────────

  {
    name: 'Khaman Dhokla',
    name_hindi: 'खमन ढोकला',
    name_regional: 'ખમણ ઢોકળા',
    description: 'Soft steamed chickpea flour cake tempered with mustard seeds, curry leaves, and green chilli — the most beloved Gujarati snack-breakfast.',
    cuisine: ['Gujarati'],
    region: 'WEST',
    slot: ['breakfast'],
    is_veg: true, is_vegan: true, is_jain: true, is_fasting: false, is_street: true,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Rava Dhokla',
    name_hindi: 'रवा ढोकला',
    name_regional: 'રવા ઢોકળા',
    description: 'Quick semolina steamed cake with yogurt and ginger — a no-fermentation Gujarati breakfast ready in under 30 minutes.',
    cuisine: ['Gujarati'],
    region: 'WEST',
    slot: ['breakfast'],
    is_veg: true, is_vegan: false, is_jain: true, is_fasting: false, is_street: false,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Khandvi',
    name_hindi: 'खांडवी',
    name_regional: 'ખાંડવી',
    description: 'Thin rolls of cooked gram flour and buttermilk tempered with mustard and coconut — a delicate, melt-in-mouth Gujarati breakfast.',
    cuisine: ['Gujarati'],
    region: 'WEST',
    slot: ['breakfast'],
    is_veg: true, is_vegan: false, is_jain: true, is_fasting: false, is_street: false,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Thepla',
    name_hindi: 'थेपला',
    name_regional: 'થેપલા',
    description: 'Thin spiced wheat flatbread with turmeric, yogurt, and sesame — the iconic Gujarati travel food that stays fresh for days.',
    cuisine: ['Gujarati'],
    region: 'WEST',
    slot: ['breakfast'],
    is_veg: true, is_vegan: false, is_jain: true, is_fasting: false, is_street: false,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Methi Thepla',
    name_hindi: 'मेथी थेपला',
    name_regional: 'મેથી થેપલા',
    description: 'Fenugreek-laced thin flatbread with wheat flour, yogurt, and sesame — the iron-rich winter variant of the classic Gujarati thepla.',
    cuisine: ['Gujarati'],
    region: 'WEST',
    slot: ['breakfast'],
    is_veg: true, is_vegan: false, is_jain: true, is_fasting: false, is_street: false,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Batata Poha',
    name_hindi: 'बटाटा पोहा',
    name_regional: 'બટાટા પોહા',
    description: 'Flattened rice tossed with potato, peanuts, mustard seeds, and turmeric with a hint of sweetness — the Gujarati morning poha.',
    cuisine: ['Gujarati'],
    region: 'WEST',
    slot: ['breakfast'],
    is_veg: true, is_vegan: true, is_jain: false, is_fasting: false, is_street: false,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Fafda with Jalebi',
    name_hindi: 'फाफड़ा जलेबी',
    name_regional: 'ફાફડા જલેબી',
    description: 'Crispy gram flour strips paired with hot sugar-syrup jalebis — the quintessential Gujarati Sunday morning ritual.',
    cuisine: ['Gujarati'],
    region: 'WEST',
    slot: ['breakfast'],
    is_veg: true, is_vegan: false, is_jain: false, is_fasting: false, is_street: true,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Nylon Gathiya',
    name_hindi: 'नायलॉन गाठिया',
    name_regional: 'નાયલોન ગાઠિયા',
    description: 'Extra-fine and crispy gram flour sticks with black pepper from Rajkot — the softer, more refined version of regular gathiya.',
    cuisine: ['Gujarati'],
    region: 'WEST',
    slot: ['breakfast'],
    is_veg: true, is_vegan: true, is_jain: false, is_fasting: false, is_street: true,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Bajra Rotla',
    name_hindi: 'बाजरा रोटला',
    name_regional: 'બાજરા રોટલા',
    description: 'Thick hand-patted pearl millet flatbread cooked on an inverted tawa — a Kathiyawadi staple eaten with ghee and jaggery.',
    cuisine: ['Gujarati'],
    region: 'WEST',
    slot: ['breakfast'],
    is_veg: true, is_vegan: true, is_jain: true, is_fasting: false, is_street: false,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Steamed Muthiya',
    name_hindi: 'स्टीम्ड मुठिया',
    name_regional: 'મૂઠિયા',
    description: 'Steamed fenugreek and wheat flour dumplings tempered with mustard and sesame — a light, healthy Gujarati breakfast bite.',
    cuisine: ['Gujarati'],
    region: 'WEST',
    slot: ['breakfast'],
    is_veg: true, is_vegan: true, is_jain: false, is_fasting: false, is_street: false,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Moong Dal Chila',
    name_hindi: 'मूंग दाल चीला',
    name_regional: 'મૂંગ દાળ ચીલા',
    description: 'Thin savoury crepes made from soaked ground moong dal with ginger and green chilli — a protein-rich Gujarati breakfast.',
    cuisine: ['Gujarati'],
    region: 'WEST',
    slot: ['breakfast'],
    is_veg: true, is_vegan: true, is_jain: true, is_fasting: false, is_street: false,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Sev Khamani',
    name_hindi: 'सेव खामणी',
    name_regional: 'સેવ ખામણી',
    description: 'Crumbled khaman dhokla tossed with tempering, topped with sev and pomegranate — a sweet-tangy Surat street breakfast.',
    cuisine: ['Gujarati'],
    region: 'WEST',
    slot: ['breakfast'],
    is_veg: true, is_vegan: false, is_jain: false, is_fasting: false, is_street: true,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },

  // ── LUNCH CURRY (15) ────────────────────────────────────────────────────────

  {
    name: 'Undhiyu',
    name_hindi: 'उंधियू',
    name_regional: 'ઉંધિયુ',
    description: 'Seasonal winter vegetables and fenugreek muthiya slow-cooked in an earthen pot with coconut-coriander masala — Gujarat most celebrated dish.',
    cuisine: ['Gujarati'],
    region: 'WEST',
    slot: ['lunch_curry'],
    is_veg: true, is_vegan: true, is_jain: false, is_fasting: false, is_street: false,
    is_non_veg_type: null, allowed_days: [], occasion: ['festival', 'everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Gujarati Toor Dal',
    name_hindi: 'गुजराती तूर दाल',
    name_regional: 'ગુજરાતી તૂર દાળ',
    description: 'Split pigeon pea dal with jaggery, tamarind, and tomato in a perfectly balanced sweet-sour-spiced Gujarati preparation.',
    cuisine: ['Gujarati'],
    region: 'WEST',
    slot: ['lunch_curry'],
    is_veg: true, is_vegan: false, is_jain: true, is_fasting: false, is_street: false,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Gujarati Kadhi',
    name_hindi: 'गुजराती कढ़ी',
    name_regional: 'ગુજરાતી કઢી',
    description: 'Thin sweet-sour yogurt and gram flour curry with mustard, curry leaves, and dried chilli — sweeter and lighter than Punjabi kadhi.',
    cuisine: ['Gujarati'],
    region: 'WEST',
    slot: ['lunch_curry'],
    is_veg: true, is_vegan: false, is_jain: true, is_fasting: false, is_street: false,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Ringna nu Shaak',
    name_hindi: 'रिंगना नू शाक',
    name_regional: 'રીંગણ નો શાક',
    description: 'Brinjal stuffed with a peanut-sesame-jaggery-coconut masala cooked in a sweet-tangy Gujarati gravy.',
    cuisine: ['Gujarati'],
    region: 'WEST',
    slot: ['lunch_curry'],
    is_veg: true, is_vegan: true, is_jain: false, is_fasting: false, is_street: false,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Sev Tameta nu Shaak',
    name_hindi: 'सेव टमेटा नू शाक',
    name_regional: 'સેવ ટામેટા નો શાક',
    description: 'Tangy tomato curry topped with crispy sev — a 15-minute Gujarati sabzi balancing sweetness, sourness, and crunch.',
    cuisine: ['Gujarati'],
    region: 'WEST',
    slot: ['lunch_curry'],
    is_veg: true, is_vegan: true, is_jain: false, is_fasting: false, is_street: false,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Dudhi Chana Dal',
    name_hindi: 'दूधी चना दाल',
    name_regional: 'દૂધી ચણાદાળ',
    description: 'Bottle gourd cooked with split Bengal gram in a Gujarati masala with mustard and curry leaves — a comforting everyday dal-vegetable.',
    cuisine: ['Gujarati'],
    region: 'WEST',
    slot: ['lunch_curry'],
    is_veg: true, is_vegan: true, is_jain: false, is_fasting: false, is_street: false,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Valor Papdi nu Shaak',
    name_hindi: 'वालोर पापड़ी नू शाक',
    name_regional: 'વાલોળ પાપડી નો શાક',
    description: 'Hyacinth flat beans cooked with peanuts, jaggery, and coconut in a Gujarati winter curry.',
    cuisine: ['Gujarati'],
    region: 'WEST',
    slot: ['lunch_curry'],
    is_veg: true, is_vegan: true, is_jain: false, is_fasting: false, is_street: false,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Methi Muthiya nu Shaak',
    name_hindi: 'मेथी मुठिया नू शाक',
    name_regional: 'મેથી મૂઠિયા નો શાક',
    description: 'Steamed fenugreek dumplings simmered in a sweet-tangy yogurt and tomato gravy — a uniquely Gujarati curry.',
    cuisine: ['Gujarati'],
    region: 'WEST',
    slot: ['lunch_curry'],
    is_veg: true, is_vegan: false, is_jain: false, is_fasting: false, is_street: false,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Batata Tameta nu Shaak',
    name_hindi: 'बटाटा टमेटा नू शाक',
    name_regional: 'બટાટા ટામેટા નો શાક',
    description: 'Potato and tomato cooked in a sweet-spicy Gujarati masala with mustard and jaggery — a quick everyday home curry.',
    cuisine: ['Gujarati'],
    region: 'WEST',
    slot: ['lunch_curry'],
    is_veg: true, is_vegan: true, is_jain: false, is_fasting: false, is_street: false,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Kala Chana Shaak',
    name_hindi: 'काला चना शाक',
    name_regional: 'કાળા ચણા નો શાક',
    description: 'Black chickpeas cooked in a Gujarati dry masala with coconut, mustard seeds, and lemon — a protein-rich everyday curry.',
    cuisine: ['Gujarati'],
    region: 'WEST',
    slot: ['lunch_curry'],
    is_veg: true, is_vegan: true, is_jain: false, is_fasting: false, is_street: false,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Turiya Patra nu Shaak',
    name_hindi: 'तुरिया पात्रा नू शाक',
    name_regional: 'તૂરિયા પાત્રા નો શાક',
    description: 'Ridge gourd cooked with colocasia leaf rolls (patra) in a tangy Gujarati masala — a clever double-vegetable preparation.',
    cuisine: ['Gujarati'],
    region: 'WEST',
    slot: ['lunch_curry'],
    is_veg: true, is_vegan: true, is_jain: false, is_fasting: false, is_street: false,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Surati Papdi Lilva',
    name_hindi: 'सूरती पापड़ी लिलवा',
    name_regional: 'સૂરતી પાપડી લિલ્વા',
    description: 'Fresh flat beans and pigeon peas cooked in a coconut-jaggery Surati masala — a highly seasonal Gujarati winter delicacy.',
    cuisine: ['Gujarati'],
    region: 'WEST',
    slot: ['lunch_curry'],
    is_veg: true, is_vegan: true, is_jain: false, is_fasting: false, is_street: false,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Osaman',
    name_hindi: 'ओसमान',
    name_regional: 'ઓસામણ',
    description: 'Light clear toor dal broth with jaggery, lemon, and mustard tempering — a digestive Gujarati dal drunk as soup or poured over rice.',
    cuisine: ['Gujarati'],
    region: 'WEST',
    slot: ['lunch_curry'],
    is_veg: true, is_vegan: false, is_jain: true, is_fasting: false, is_street: false,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Dal Dhokli',
    name_hindi: 'दाल ढोकली',
    name_regional: 'દાળ ઢોકળી',
    description: 'Spiced wheat flour dumplings simmered in sweet-tangy toor dal with peanuts and ghee — the ultimate Gujarati one-pot comfort meal.',
    cuisine: ['Gujarati'],
    region: 'WEST',
    slot: ['lunch_curry'],
    is_veg: true, is_vegan: false, is_jain: false, is_fasting: false, is_street: false,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Trevti Dal',
    name_hindi: 'त्रेवटी दाल',
    name_regional: 'ત્રેવટી દાળ',
    description: 'Three-lentil Gujarati dal of toor, moong, and chana with jaggery, lemon, and ghee tempering — a rich festive thali dal.',
    cuisine: ['Gujarati'],
    region: 'WEST',
    slot: ['lunch_curry'],
    is_veg: true, is_vegan: false, is_jain: false, is_fasting: false, is_street: false,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday', 'festival'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },

  // ── DINNER CURRY (12) ───────────────────────────────────────────────────────

  {
    name: 'Vaghareli Dal',
    name_hindi: 'वघारेली दाल',
    name_regional: 'વઘારેલી દાળ',
    description: 'Leftover toor dal tempered with ghee, mustard, dried red chilli, and curry leaves — a simple Gujarati weeknight dinner dal.',
    cuisine: ['Gujarati'],
    region: 'WEST',
    slot: ['dinner_curry'],
    is_veg: true, is_vegan: false, is_jain: true, is_fasting: false, is_street: false,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Doodhi Kofta Curry',
    name_hindi: 'दूधी कोफ्ता करी',
    name_regional: 'દૂધી કોફ્તા',
    description: 'Fried bottle gourd dumplings simmered in a spiced tomato-yogurt Gujarati gravy — a light but satisfying dinner.',
    cuisine: ['Gujarati'],
    region: 'WEST',
    slot: ['dinner_curry'],
    is_veg: true, is_vegan: false, is_jain: false, is_fasting: false, is_street: false,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Fansi nu Shaak',
    name_hindi: 'फान्सी नू शाक',
    name_regional: 'ફ્રેન્ચ બીન્સ નો શાક',
    description: 'French beans cooked with grated coconut, mustard seeds, and jaggery — a classic Gujarati dry dinner vegetable.',
    cuisine: ['Gujarati'],
    region: 'WEST',
    slot: ['dinner_curry'],
    is_veg: true, is_vegan: true, is_jain: false, is_fasting: false, is_street: false,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Suran Shaak',
    name_hindi: 'सूरन शाक',
    name_regional: 'સૂરણ નો શાક',
    description: 'Elephant yam cooked in a tangy Gujarati tamarind-jaggery masala — a robust, earthy dinner curry.',
    cuisine: ['Gujarati'],
    region: 'WEST',
    slot: ['dinner_curry'],
    is_veg: true, is_vegan: true, is_jain: false, is_fasting: false, is_street: false,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Parval Masala',
    name_hindi: 'परवल मसाला',
    name_regional: 'પરવળ નો શાક',
    description: 'Pointed gourd stuffed with a peanut-coconut masala and cooked in a sweet-spicy Gujarati curry.',
    cuisine: ['Gujarati'],
    region: 'WEST',
    slot: ['dinner_curry'],
    is_veg: true, is_vegan: true, is_jain: false, is_fasting: false, is_street: false,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Mixed Dal Tadka',
    name_hindi: 'मिक्स दाल तड़का',
    name_regional: 'મિક્સ દાળ',
    description: 'A blend of toor, moong, and masoor dal tempered with garlic, cumin, and dried chilli — a wholesome everyday Gujarati dinner dal.',
    cuisine: ['Gujarati'],
    region: 'WEST',
    slot: ['dinner_curry'],
    is_veg: true, is_vegan: false, is_jain: false, is_fasting: false, is_street: false,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Lilva Kachori nu Shaak',
    name_hindi: 'लिलवा कचोरी नू शाक',
    name_regional: 'લિલ્વા કચોરી નો શાક',
    description: 'Fresh pigeon pea kachoris simmered in a tangy Gujarati tomato gravy — a winter-seasonal Surat dinner speciality.',
    cuisine: ['Gujarati'],
    region: 'WEST',
    slot: ['dinner_curry'],
    is_veg: true, is_vegan: false, is_jain: false, is_fasting: false, is_street: false,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Gujarati Chicken Curry',
    name_hindi: 'गुजराती चिकन करी',
    name_regional: 'ગુજરાતી ચિકન કરી',
    description: 'Bone-in chicken in a coconut-peanut Gujarati masala with jaggery and curry leaves — the coastal Gujarati non-veg curry.',
    cuisine: ['Gujarati'],
    region: 'WEST',
    slot: ['dinner_curry'],
    is_veg: false, is_vegan: false, is_jain: false, is_fasting: false, is_street: false,
    is_non_veg_type: 'chicken', allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Surti Mutton Curry',
    name_hindi: 'सूरती मटन करी',
    name_regional: 'સૂરતી મટન કરી',
    description: 'Mutton slow-cooked in a Surti onion-coconut gravy with Gujarati spices — a bold non-veg dish from Surat.',
    cuisine: ['Gujarati'],
    region: 'WEST',
    slot: ['dinner_curry'],
    is_veg: false, is_vegan: false, is_jain: false, is_fasting: false, is_street: false,
    is_non_veg_type: 'mutton', allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Surti Fish Curry',
    name_hindi: 'सूरती मछली करी',
    name_regional: 'સૂરતી માછળી કરી',
    description: 'River or sea fish cooked in a kokum-coconut Surati gravy with Gujarati masala — a coastal Surat dinner staple.',
    cuisine: ['Gujarati'],
    region: 'WEST',
    slot: ['dinner_curry'],
    is_veg: false, is_vegan: false, is_jain: false, is_fasting: false, is_street: false,
    is_non_veg_type: 'fish', allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Egg Curry Gujarati Style',
    name_hindi: 'अंडा करी गुजराती स्टाइल',
    name_regional: null,
    description: 'Hard-boiled eggs simmered in a sweet-spicy Gujarati onion-tomato gravy with coconut and mustard tempering.',
    cuisine: ['Gujarati'],
    region: 'WEST',
    slot: ['dinner_curry'],
    is_veg: false, is_vegan: false, is_jain: false, is_fasting: false, is_street: false,
    is_non_veg_type: 'egg', allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Prawn Masala Surati',
    name_hindi: 'सूरती प्रॉन मसाला',
    name_regional: 'સૂરતી ઝીંગા મસાલા',
    description: 'Prawns cooked in a tangy coconut-kokum Surati masala — a prized seafood curry from the coastal belt of South Gujarat.',
    cuisine: ['Gujarati'],
    region: 'WEST',
    slot: ['dinner_curry'],
    is_veg: false, is_vegan: false, is_jain: false, is_fasting: false, is_street: false,
    is_non_veg_type: 'prawn', allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },

  // ── VEG SIDE (10) ───────────────────────────────────────────────────────────

  {
    name: 'Bhindi nu Shaak',
    name_hindi: 'भिंडी नू शाक',
    name_regional: 'ભીંડા નો શાક',
    description: 'Okra stir-fried with mustard seeds, turmeric, and sesame in Gujarati style — a crispy, mildly sweet everyday vegetable side.',
    cuisine: ['Gujarati'],
    region: 'WEST',
    slot: ['veg_side'],
    is_veg: true, is_vegan: true, is_jain: false, is_fasting: false, is_street: false,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Kobi nu Shaak',
    name_hindi: 'कोबी नू शाक',
    name_regional: 'કોબી નો શાક',
    description: 'Cabbage stir-fried with mustard seeds, green chilli, turmeric, and a pinch of sugar — a crisp and quick Gujarati side.',
    cuisine: ['Gujarati'],
    region: 'WEST',
    slot: ['veg_side'],
    is_veg: true, is_vegan: true, is_jain: true, is_fasting: false, is_street: false,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Gajar nu Shaak',
    name_hindi: 'गाजर नू शाक',
    name_regional: 'ગાજર નો શાક',
    description: 'Carrot cooked with peanuts, sesame, mustard, and jaggery in a dry Gujarati preparation — a sweet-nutty winter side.',
    cuisine: ['Gujarati'],
    region: 'WEST',
    slot: ['veg_side'],
    is_veg: true, is_vegan: true, is_jain: false, is_fasting: false, is_street: false,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Guar Phali nu Shaak',
    name_hindi: 'गुआर फली नू शाक',
    name_regional: 'ગુવાર ફળી નો શાક',
    description: 'Cluster beans stir-fried with coconut, mustard, and jaggery — a slightly bitter, crunchy Gujarati monsoon vegetable side.',
    cuisine: ['Gujarati'],
    region: 'WEST',
    slot: ['veg_side'],
    is_veg: true, is_vegan: true, is_jain: false, is_fasting: false, is_street: false,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Tindori nu Shaak',
    name_hindi: 'तिंडोरी नू शाक',
    name_regional: 'ટીંડોળા નો શાક',
    description: 'Ivy gourd sliced and stir-fried with peanuts, sesame, and Gujarati spices — a crunchy, everyday vegetable side.',
    cuisine: ['Gujarati'],
    region: 'WEST',
    slot: ['veg_side'],
    is_veg: true, is_vegan: true, is_jain: false, is_fasting: false, is_street: false,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Galka nu Shaak',
    name_hindi: 'गलका नू शाक',
    name_regional: 'ગળ઼કા નો શાક',
    description: 'Ridge gourd cooked with peanuts, mustard, and coconut in a light Gujarati masala — a mild and digestive everyday side.',
    cuisine: ['Gujarati'],
    region: 'WEST',
    slot: ['veg_side'],
    is_veg: true, is_vegan: true, is_jain: false, is_fasting: false, is_street: false,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Ravaiya',
    name_hindi: 'रवैया',
    name_regional: 'રવૈયા',
    description: 'Baby brinjals stuffed with a sweet-spicy peanut-coconut masala and pan-cooked — a quintessential Gujarati festive side dish.',
    cuisine: ['Gujarati'],
    region: 'WEST',
    slot: ['veg_side'],
    is_veg: true, is_vegan: true, is_jain: false, is_fasting: false, is_street: false,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday', 'festival'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Corn nu Shaak',
    name_hindi: 'कॉर्न नू शाक',
    name_regional: 'મકાઈ નો શાક',
    description: 'Fresh corn kernels stir-fried with coconut, green chilli, mustard, and jaggery — a sweet, crunchy Gujarati side.',
    cuisine: ['Gujarati'],
    region: 'WEST',
    slot: ['veg_side'],
    is_veg: true, is_vegan: true, is_jain: true, is_fasting: false, is_street: false,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Lasaniya Batata',
    name_hindi: 'लसनिया बटाटा',
    name_regional: 'લસણિયા બટેટા',
    description: 'Baby potatoes cooked with crushed garlic, peanuts, sesame, and a Kathiyawadi spice blend — spicy and robustly flavoured.',
    cuisine: ['Gujarati'],
    region: 'WEST',
    slot: ['veg_side'],
    is_veg: true, is_vegan: true, is_jain: false, is_fasting: false, is_street: false,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Mogri nu Shaak',
    name_hindi: 'मोगरी नू शाक',
    name_regional: 'મોગરી નો શાક',
    description: 'Radish seed pods stir-fried with mustard, sesame, and green chilli — a seasonal winter side unique to Gujarati homes.',
    cuisine: ['Gujarati'],
    region: 'WEST',
    slot: ['veg_side'],
    is_veg: true, is_vegan: true, is_jain: false, is_fasting: false, is_street: false,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },

  // ── RICE (5) ────────────────────────────────────────────────────────────────

  {
    name: 'Gujarati Khichdi',
    name_hindi: 'गुजराती खिचड़ी',
    name_regional: 'ગુજરાતી ખીચડી',
    description: 'Rice and moong dal cooked together until soft with turmeric and ghee — Gujarat comfort food served with kadhi and papad.',
    cuisine: ['Gujarati'],
    region: 'WEST',
    slot: ['rice'],
    is_veg: true, is_vegan: false, is_jain: true, is_fasting: false, is_street: false,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Vagharela Chawal',
    name_hindi: 'वघारेला चावल',
    name_regional: 'વઘારેલા ભાત',
    description: 'Leftover rice tempered with mustard seeds, curry leaves, green chilli, and peanuts — a quick Gujarati everyday rice.',
    cuisine: ['Gujarati'],
    region: 'WEST',
    slot: ['rice'],
    is_veg: true, is_vegan: true, is_jain: false, is_fasting: false, is_street: false,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Masala Bhat',
    name_hindi: 'मसाला भात',
    name_regional: 'મસાલા ભાત',
    description: 'Spiced rice cooked with mixed vegetables, peanuts, and Gujarati masala — a festive one-pot rice richer than pulao.',
    cuisine: ['Gujarati'],
    region: 'WEST',
    slot: ['rice'],
    is_veg: true, is_vegan: false, is_jain: false, is_fasting: false, is_street: false,
    is_non_veg_type: null, allowed_days: [], occasion: ['festival', 'everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Toor Dal Khichdi',
    name_hindi: 'तूर दाल खिचड़ी',
    name_regional: 'તૂર દાળ ખીચડી',
    description: 'Rice and split pigeon peas cooked to a thick porridge with ghee and whole spices — a deeply nourishing Gujarati sick-day rice.',
    cuisine: ['Gujarati'],
    region: 'WEST',
    slot: ['rice'],
    is_veg: true, is_vegan: false, is_jain: true, is_fasting: false, is_street: false,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Vangi Bhat Gujarati',
    name_hindi: 'वांगी भात गुजराती',
    name_regional: 'રીંગણ ભાત',
    description: 'Basmati rice cooked with brinjal, peanuts, sesame, and Gujarati spices — a flavourful everyday one-pot lunch rice.',
    cuisine: ['Gujarati'],
    region: 'WEST',
    slot: ['rice'],
    is_veg: true, is_vegan: true, is_jain: false, is_fasting: false, is_street: false,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },

  // ── BREAD (3) ───────────────────────────────────────────────────────────────

  {
    name: 'Jowar Rotla',
    name_hindi: 'जोवार रोटला',
    name_regional: 'જુવાર રોટલા',
    description: 'Thick sorghum millet flatbread hand-patted and cooked on a tawa — a staple Kathiyawadi dinner bread eaten with ghee.',
    cuisine: ['Gujarati'],
    region: 'WEST',
    slot: ['bread'],
    is_veg: true, is_vegan: true, is_jain: true, is_fasting: false, is_street: false,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Bhakri',
    name_hindi: 'भाकरी',
    name_regional: 'ભાખરી',
    description: 'Thick and crispy wheat flatbread harder than a phulka — crumbled into kadhi or buttermilk, a staple Gujarati bread.',
    cuisine: ['Gujarati'],
    region: 'WEST',
    slot: ['bread'],
    is_veg: true, is_vegan: true, is_jain: true, is_fasting: false, is_street: false,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Ghau na Rotla',
    name_hindi: 'घऊ ना रोटला',
    name_regional: 'ઘઉ ના રોટલા',
    description: 'Thick whole-wheat flatbread cooked on a tawa and finished on open flame — the everyday Gujarati bread eaten with dal and shaak.',
    cuisine: ['Gujarati'],
    region: 'WEST',
    slot: ['bread'],
    is_veg: true, is_vegan: true, is_jain: true, is_fasting: false, is_street: false,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },

  // ── RAITA (2) ───────────────────────────────────────────────────────────────

  {
    name: 'Kachumber Raita',
    name_hindi: 'कचूम्बर रायता',
    name_regional: 'કચૂમ્બર રાઈતા',
    description: 'Diced cucumber, tomato, and onion folded into seasoned yogurt with roasted cumin — a refreshing Gujarati thali accompaniment.',
    cuisine: ['Gujarati'],
    region: 'WEST',
    slot: ['raita'],
    is_veg: true, is_vegan: false, is_jain: false, is_fasting: false, is_street: false,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
  {
    name: 'Lauki Raita',
    name_hindi: 'लौकी रायता',
    name_regional: 'દૂધી રાઈતા',
    description: 'Grated bottle gourd mixed with yogurt, roasted cumin, and fresh coriander — a cooling and light Gujarati raita.',
    cuisine: ['Gujarati'],
    region: 'WEST',
    slot: ['raita'],
    is_veg: true, is_vegan: false, is_jain: true, is_fasting: false, is_street: false,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },

  // ── SNACK (1) ───────────────────────────────────────────────────────────────

  {
    name: 'Dabeli',
    name_hindi: 'दाबेली',
    name_regional: 'દાબેલી',
    description: 'Spiced potato filling in a soft pav with pomegranate seeds, peanuts, sev, and dabeli masala — invented in Mandvi, Kutch street icon.',
    cuisine: ['Gujarati'],
    region: 'WEST',
    slot: ['snack'],
    is_veg: true, is_vegan: false, is_jain: false, is_fasting: false, is_street: true,
    is_non_veg_type: null, allowed_days: [], occasion: ['everyday'], health_tags: [],
    is_verified: false, is_banned: false, chef_id: null, chef_verified: false,
  },
];

// ─── Seed ─────────────────────────────────────────────────────────────────────

async function seed() {
  const BATCH_SIZE = 20;
  let totalInserted = 0;
  let totalErrors = 0;

  const punjabi = dishes.filter(d => d.cuisine.includes('Punjabi'));
  const gujarati = dishes.filter(d => d.cuisine.includes('Gujarati'));

  console.log(`\nSeeding ${dishes.length} dishes (Punjabi: ${punjabi.length} | Gujarati: ${gujarati.length})\n`);

  for (let i = 0; i < dishes.length; i += BATCH_SIZE) {
    const batch = dishes.slice(i, i + BATCH_SIZE);
    const batchNum = Math.floor(i / BATCH_SIZE) + 1;

    const { error } = await client.from('dishes').insert(batch);

    if (error) {
      console.error(`  Batch ${batchNum} ERROR: ${error.message}`);
      totalErrors += batch.length;
    } else {
      totalInserted += batch.length;
      console.log(`  Batch ${batchNum}: inserted ${batch.length} dishes (running total: ${totalInserted})`);
    }
  }

  console.log(`\nDone. Inserted: ${totalInserted} | Errors: ${totalErrors}\n`);

  // ── Verification ─────────────────────────────────────────────────────────────

  console.log('Verification query:');
  console.log("  SELECT cuisine, COUNT(*) FROM dishes WHERE cuisine && ARRAY['Punjabi','Gujarati'] GROUP BY cuisine ORDER BY cuisine;\n");

  const { data: rows, error: verifyErr } = await client
    .from('dishes')
    .select('cuisine')
    .or('cuisine.cs.{"Punjabi"},cuisine.cs.{"Gujarati"}');

  if (verifyErr) {
    console.error('Verification error:', verifyErr.message);
    return;
  }

  const counts: Record<string, number> = {};
  (rows || []).forEach((r: { cuisine: string[] }) => {
    r.cuisine.forEach((c: string) => {
      if (c === 'Punjabi' || c === 'Gujarati') {
        counts[c] = (counts[c] || 0) + 1;
      }
    });
  });

  // ── Audit table ──────────────────────────────────────────────────────────────

  const generated: Record<string, number> = { Punjabi: punjabi.length, Gujarati: gujarati.length };

  console.log('┌─────────────┬──────────────────┬─────────────────┬────────┐');
  console.log('│ Cuisine     │ Dishes generated │ Dishes inserted │ Errors │');
  console.log('├─────────────┼──────────────────┼─────────────────┼────────┤');

  for (const cuisine of ['Punjabi', 'Gujarati']) {
    const gen = generated[cuisine];
    const ins = counts[cuisine] ?? 0;
    const err = gen - ins;
    console.log(
      `│ ${cuisine.padEnd(11)} │ ${String(gen).padEnd(16)} │ ${String(ins).padEnd(15)} │ ${String(err).padEnd(6)} │`,
    );
  }

  console.log('├─────────────┼──────────────────┼─────────────────┼────────┤');
  const totalGen = generated['Punjabi'] + generated['Gujarati'];
  const totalIns = (counts['Punjabi'] ?? 0) + (counts['Gujarati'] ?? 0);
  console.log(
    `│ ${'TOTAL'.padEnd(11)} │ ${String(totalGen).padEnd(16)} │ ${String(totalIns).padEnd(15)} │ ${String(totalGen - totalIns).padEnd(6)} │`,
  );
  console.log('└─────────────┴──────────────────┴─────────────────┴────────┘');
}

seed().catch(console.error);
