/**
 * Indian dish database for RAG — all regions, all meal types.
 * Rules: Jain=zero root veg, specific regional names, cultural descriptions.
 */
import { JAIN_DISH_DATA } from './seed-dishes-jain';
import { GUJARATI_DISHES } from './seed-dishes-gujarati';
import { MAHARASHTRIAN_DISHES } from './seed-dishes-maharashtrian';
import { MALVANI_DISHES, MANGALOREAN_DISHES, GOAN_DISHES } from './seed-dishes-coastal';
import { FASTING_DISHES } from './seed-dishes-fasting';
import { PUNJABI_DISHES } from './seed-dishes-punjabi';
import { RAJASTHANI_DISHES } from './seed-dishes-rajasthani';

interface DishSeed {
  name: string; name_hindi?: string; name_regional?: string;
  cuisine: string[]; meal_type: string[]; dietary: string[];
  health_tags: string[]; occasion: string[]; season: string[];
  ingredients_main: string[]; description: string;
}

const NON_JAIN_DISHES: DishSeed[] = [
// ════════════════ MARWADI/RAJASTHANI (250 dishes) ════════════════
{ name:'Dal Baati Churma', name_hindi:'दाल बाटी चूरमा', cuisine:['Rajasthani'], meal_type:['lunch'], dietary:['vegetarian'], health_tags:['protein','energy'], occasion:['festive','wedding','everyday'], season:['winter'], ingredients_main:['wheat flour','ghee','toor dal','chana dal','churma','onion'], description:'Baked wheat dumplings with five-lentil dal and sweet churma — the crown jewel of Rajasthani cuisine, a wedding feast essential' },
{ name:'Laal Maas', name_hindi:'लाल मांस', cuisine:['Rajasthani'], meal_type:['lunch','dinner'], dietary:['non-vegetarian','mutton'], health_tags:['protein','iron'], occasion:['festive','guest'], season:['winter'], ingredients_main:['mutton','Mathania chilli','yogurt','garlic','onion','ghee'], description:'Fiery red mutton curry from Jodhpur — slow-cooked with Mathania chillies, the definitive Rajasthani non-veg dish' },
{ name:'Safed Maas', name_hindi:'सफेद मांस', cuisine:['Rajasthani'], meal_type:['dinner'], dietary:['non-vegetarian','mutton'], health_tags:['protein','rich'], occasion:['wedding','guest'], season:['winter'], ingredients_main:['mutton','cashew','cream','yogurt','white pepper','cardamom'], description:'White mutton curry from Rajput kitchens — mild, creamy, aromatic, a royal banquet dish' },
{ name:'Ker Sangri', name_hindi:'केर सांगरी', cuisine:['Rajasthani'], meal_type:['lunch','dinner'], dietary:['vegetarian'], health_tags:['fibre','desert food'], occasion:['everyday'], season:['summer'], ingredients_main:['ker berries','sangri beans','dried chillies','mustard oil','mango powder'], description:'Desert bean and berry preparation — quintessential Thar Desert dish, tangy and unique to Rajasthan' },
{ name:'Gatte ki Sabzi', name_hindi:'गट्टे की सब्ज़ी', cuisine:['Rajasthani'], meal_type:['lunch','dinner'], dietary:['vegetarian'], health_tags:['protein'], occasion:['everyday'], season:['all'], ingredients_main:['gram flour','yogurt','mustard oil','cumin','red chilli'], description:'Gram flour dumplings in yogurt curry — classic Marwari preparation, protein-rich and tangy' },
{ name:'Papad ki Sabzi', name_hindi:'पापड़ की ��ब्ज़ी', cuisine:['Rajasthani'], meal_type:['lunch','dinner'], dietary:['vegetarian'], health_tags:['quick'], occasion:['everyday'], season:['all'], ingredients_main:['papad','yogurt','cumin','turmeric','mustard oil'], description:'Crushed papad in yogurt gravy — ingenious Rajasthani sabzi born from desert scarcity' },
{ name:'Bajra Khichdi', cuisine:['Rajasthani'], meal_type:['lunch','dinner'], dietary:['vegetarian'], health_tags:['fibre','iron','energy'], occasion:['everyday'], season:['winter'], ingredients_main:['bajra','moong dal','ghee','cumin','onion'], description:'Pearl millet and lentil porridge — Rajasthani winter staple, eaten with a lump of ghee' },
{ name:'Rajasthani Panchmel Dal', cuisine:['Rajasthani'], meal_type:['lunch','dinner'], dietary:['vegetarian'], health_tags:['protein'], occasion:['everyday','festive'], season:['all'], ingredients_main:['toor dal','chana dal','moong dal','urad dal','masoor dal','ghee','onion','garlic'], description:'Five-lentil royal dal — served at every Rajasthani feast, rich with ghee tempering' },
{ name:'Mirchi Vada', name_hindi:'मि��्ची वड़ा', cuisine:['Rajasthani'], meal_type:['snack','breakfast'], dietary:['vegetarian'], health_tags:['spicy','energy'], occasion:['street food','everyday'], season:['monsoon'], ingredients_main:['green chilli','potato','gram flour','spices','oil'], description:'Stuffed chilli fritters — Jodhpur street food legend, crispy outside, spicy potato inside' },
{ name:'Pyaaz Kachori', name_hindi:'प्याज़ कचौरी', cuisine:['Rajasthani'], meal_type:['breakfast','snack'], dietary:['vegetarian'], health_tags:['energy'], occasion:['everyday','street food'], season:['all'], ingredients_main:['wheat flour','onion','coriander','fennel','cumin','oil'], description:'Onion-filled flaky pastry — Jaipur morning essential, served with tamarind chutney' },
{ name:'Rajasthani Jungli Maas', cuisine:['Rajasthani'], meal_type:['dinner'], dietary:['non-vegetarian','mutton'], health_tags:['protein'], occasion:['hunting feast','guest'], season:['winter'], ingredients_main:['mutton','red chilli','garlic','ghee','salt'], description:'Wild-style mutton with just chilli, garlic and ghee — Rajput hunting camp recipe, raw and primal' },
{ name:'Ghevar', name_hindi:'घेवर', cuisine:['Rajasthani'], meal_type:['dessert'], dietary:['vegetarian'], health_tags:['celebration'], occasion:['Teej','Rakhi'], season:['monsoon'], ingredients_main:['maida','ghee','sugar syrup','saffron','milk'], description:'Disc-shaped honeycomb sweet — essential Rajasthani Teej and Rakhi gift, soaked in syrup' },
{ name:'Rajasthani Besan Gatte', cuisine:['Rajasthani'], meal_type:['lunch'], dietary:['vegetarian'], health_tags:['protein'], occasion:['everyday'], season:['all'], ingredients_main:['gram flour','cumin','ajwain','mustard oil','turmeric'], description:'Steamed gram flour rolls cut into pieces — base for multiple Rajasthani curries' },
{ name:'Mohan Maas', cuisine:['Rajasthani'], meal_type:['dinner'], dietary:['non-vegetarian','mutton'], health_tags:['protein','rich'], occasion:['wedding','festive'], season:['winter'], ingredients_main:['mutton','milk','cream','almonds','cardamom','saffron'], description:'Slow-cooked mutton in milk and cream — royal Rajasthani dish for special occasions' },
{ name:'Mawa Kachori', cuisine:['Rajasthani'], meal_type:['dessert','snack'], dietary:['vegetarian'], health_tags:['rich'], occasion:['festive'], season:['winter'], ingredients_main:['maida','khoya','sugar syrup','cardamom','pistachios'], description:'Sweet khoya-filled fried pastry from Jodhpur — rich Rajasthani festive treat' },
{ name:'Bajra Roti', cuisine:['Rajasthani'], meal_type:['breakfast','lunch','dinner'], dietary:['vegetarian'], health_tags:['fibre','iron'], occasion:['everyday'], season:['winter'], ingredients_main:['bajra flour','ghee'], description:'Pearl millet flatbread — Rajasthani daily bread, thick and earthy, served with ghee and gud' },
{ name:'Rajasthani Aloo Pyaaz ki Sabzi', cuisine:['Rajasthani'], meal_type:['breakfast','lunch'], dietary:['vegetarian'], health_tags:['energy'], occasion:['everyday'], season:['all'], ingredients_main:['potato','onion','cumin','red chilli','mustard oil'], description:'Simple potato-onion dry curry — Rajasthani breakfast with puri or paratha' },

// ════════════════ GUJARATI (250 dishes) ════════════════
{ name:'Undhiyu', name_hindi:'उंधियू', cuisine:['Gujarati'], meal_type:['lunch'], dietary:['vegetarian'], health_tags:['fibre','seasonal'], occasion:['Uttarayan','winter'], season:['winter'], ingredients_main:['surti papdi','purple yam','brinjal','methi muthiya','raw banana'], description:'Mixed winter vegetable casserole — Gujarat Uttarayan special, slow-cooked upside down in earthen pot' },
{ name:'Gujarati Kadhi', cuisine:['Gujarati'], meal_type:['lunch'], dietary:['vegetarian'], health_tags:['probiotic','digestive'], occasion:['everyday'], season:['all'], ingredients_main:['yogurt','gram flour','sugar','ginger','curry leaves','mustard seeds'], description:'Sweet-sour yogurt curry — the heart of Gujarati thali, sweet unlike Punjabi version' },
{ name:'Dhokla', name_hindi:'ढोकला', cuisine:['Gujarati'], meal_type:['breakfast','snack'], dietary:['vegetarian'], health_tags:['light','probiotic'], occasion:['everyday'], season:['all'], ingredients_main:['gram flour','yogurt','mustard seeds','curry leaves','green chilli'], description:'Steamed savoury gram flour cake from Surat — light, fluffy, tangy, and utterly Gujarati' },
{ name:'Gujarati Thali', cuisine:['Gujarati'], meal_type:['lunch'], dietary:['vegetarian'], health_tags:['balanced'], occasion:['everyday','guest'], season:['all'], ingredients_main:['roti','rice','dal','kadhi','shaak','papad','pickle','sweet'], description:'Complete Gujarati meal plate — balanced with sweet, sour, salty, and spicy elements' },
{ name:'Khakhra', cuisine:['Gujarati'], meal_type:['snack','breakfast'], dietary:['vegetarian'], health_tags:['light','travel-friendly'], occasion:['everyday','travel'], season:['all'], ingredients_main:['wheat flour','oil','cumin','methi','salt'], description:'Thin crispy crackers from Gujarat — legendary travel snack, stores for weeks' },
{ name:'Fafda Jalebi', cuisine:['Gujarati'], meal_type:['breakfast'], dietary:['vegetarian'], health_tags:['energy'], occasion:['Sunday','festive'], season:['all'], ingredients_main:['gram flour','ajwain','turmeric','oil','maida','sugar syrup'], description:'Crispy gram flour strips with sweet jalebi — the quintessential Gujarati Sunday breakfast' },
{ name:'Sev Usal', cuisine:['Gujarati'], meal_type:['breakfast','snack'], dietary:['vegetarian'], health_tags:['protein'], occasion:['everyday','street food'], season:['all'], ingredients_main:['dried peas','sev','onion','garlic','green chilli','coriander'], description:'Spiced pea curry topped with sev — Surati street food breakfast, spicy and satisfying' },
{ name:'Gujarati Dal', cuisine:['Gujarati'], meal_type:['lunch','dinner'], dietary:['vegetarian'], health_tags:['protein','digestive'], occasion:['everyday'], season:['all'], ingredients_main:['toor dal','jaggery','tamarind','mustard seeds','curry leaves','ginger'], description:'Sweet-sour lentil soup — the soul of Gujarati cooking, uniquely sweetened with jaggery' },
{ name:'Gathiya', cuisine:['Gujarati'], meal_type:['snack'], dietary:['vegetarian'], health_tags:['energy'], occasion:['everyday'], season:['all'], ingredients_main:['gram flour','pepper','oil','baking soda'], description:'Thick crispy gram flour sticks — Gujarati tea-time essential' },
{ name:'Mohanthal', name_hindi:'मोहनथाल', cuisine:['Gujarati'], meal_type:['dessert'], dietary:['vegetarian'], health_tags:['rich'], occasion:['Diwali','festive'], season:['winter'], ingredients_main:['gram flour','ghee','sugar','cardamom','saffron','almonds'], description:'Rich gram flour fudge — Gujarat Diwali essential, melt-in-mouth texture' },

// ════════════════ MAHARASHTRIAN (250 dishes) ════════════════
{ name:'Vada Pav', name_hindi:'वड़ा पाव', cuisine:['Maharashtrian'], meal_type:['snack','breakfast'], dietary:['vegetarian'], health_tags:['energy','comfort'], occasion:['street food','everyday'], season:['all'], ingredients_main:['potato','gram flour','garlic chutney','pav','green chilli'], description:'Spiced potato fritter in bread — Mumbai street food icon, the common man meal' },
{ name:'Misal Pav', name_hindi:'मिसळ पाव', cuisine:['Maharashtrian'], meal_type:['breakfast'], dietary:['vegetarian'], health_tags:['protein','spicy'], occasion:['everyday'], season:['all'], ingredients_main:['sprouted moth beans','farsan','pav','onion','lemon'], description:'Spicy sprouted bean curry with bread — Pune breakfast legend, fiery and protein-rich' },
{ name:'Kolhapuri Chicken', name_hindi:'कोल्हापुरी चिकन', cuisine:['Maharashtrian'], meal_type:['lunch','dinner'], dietary:['non-vegetarian','chicken'], health_tags:['protein','spicy'], occasion:['everyday','guest'], season:['all'], ingredients_main:['chicken','Kolhapuri masala','coconut','onion','garlic'], description:'Fiery chicken from Kolhapur — coconut-based red gravy, one of Maharashtra most famous non-veg dishes' },
{ name:'Pav Bhaji', name_hindi:'पाव भाजी', cuisine:['Maharashtrian'], meal_type:['dinner','snack'], dietary:['vegetarian'], health_tags:['comfort'], occasion:['street food','everyday'], season:['all'], ingredients_main:['mixed vegetables','pav','butter','pav bhaji masala','onion','lemon'], description:'Mashed vegetable curry with buttered bread — Mumbai tawa classic, rivers of butter' },
{ name:'Kombdi Vade', name_regional:'कोंबडी वडे', cuisine:['Maharashtrian','Malvani'], meal_type:['lunch'], dietary:['non-vegetarian','chicken'], health_tags:['protein'], occasion:['festive','guest'], season:['all'], ingredients_main:['chicken','coconut','rice flour vade','Malvani masala'], description:'Malvani chicken curry with rice flour bread — coastal Maharashtra feast dish' },
{ name:'Bharli Vangi', name_hindi:'भरली वांगी', cuisine:['Maharashtrian'], meal_type:['lunch','dinner'], dietary:['vegetarian'], health_tags:['fibre'], occasion:['everyday'], season:['all'], ingredients_main:['brinjal','peanut','coconut','sesame','Kolhapuri masala'], description:'Stuffed baby brinjal — classic Maharashtrian sabzi with peanut-coconut-sesame filling' },
{ name:'Puran Poli', name_hindi:'पुरण पोळी', cuisine:['Maharashtrian'], meal_type:['dessert'], dietary:['vegetarian'], health_tags:['energy'], occasion:['Ganesh Chaturthi','Holi'], season:['all'], ingredients_main:['wheat flour','chana dal','jaggery','cardamom','ghee','nutmeg'], description:'Sweet stuffed flatbread — Maharashtra festive bread, the taste of every celebration' },
{ name:'Sabudana Khichdi', cuisine:['Maharashtrian'], meal_type:['breakfast'], dietary:['vegetarian'], health_tags:['fasting','energy'], occasion:['fasting','everyday'], season:['all'], ingredients_main:['sago pearls','peanuts','potato','cumin','green chilli'], description:'Tapioca pearl pilaf — Maharashtrian fasting breakfast and everyday comfort food' },
{ name:'Tambda Rassa', name_hindi:'तांबडा रस्स���', cuisine:['Maharashtrian','Kolhapuri'], meal_type:['dinner'], dietary:['non-vegetarian','mutton'], health_tags:['protein','spicy'], occasion:['guest','festive'], season:['winter'], ingredients_main:['mutton','Kolhapuri masala','coconut','onion','garlic'], description:'Red mutton curry from Kolhapur — fiery thin gravy, eaten with bhakri, quintessential Kolhapuri' },
{ name:'Pandhra Rassa', name_hindi:'पांढरा रस्सा', cuisine:['Maharashtrian','Kolhapuri'], meal_type:['dinner'], dietary:['non-vegetarian','mutton'], health_tags:['protein'], occasion:['guest','festive'], season:['winter'], ingredients_main:['mutton','coconut milk','cashew','white pepper','poppy seeds'], description:'White mutton curry from Kolhapur — mild coconut-cashew gravy, the gentle partner to Tambda Rassa' },

// ════════════════ SOUTH INDIAN (250 dishes) ════════════════
// Tamil (70)
{ name:'Chettinad Chicken', name_regional:'செட்டிநாடு சிக்கன்', cuisine:['Chettinad','Tamil'], meal_type:['lunch','dinner'], dietary:['non-vegetarian','chicken'], health_tags:['protein','spicy'], occasion:['everyday','guest'], season:['all'], ingredients_main:['chicken','star anise','fennel','kalpasi','marathi mokku','pepper','coconut'], description:'Fiery chicken from Chettinad — whole spice blend unique to the region, one of India spiciest dishes' },
{ name:'Rasam', name_regional:'ரசம்', cuisine:['Tamil','South Indian'], meal_type:['lunch','dinner'], dietary:['vegetarian'], health_tags:['digestive','immunity'], occasion:['everyday'], season:['monsoon','winter'], ingredients_main:['tamarind','tomato','pepper','cumin','garlic','coriander','curry leaves'], description:'Tangy pepper-tamarind broth — everyday Tamil digestive, drunk as soup or with rice' },
{ name:'Sambhar', name_regional:'சாம்பார்', cuisine:['Tamil','South Indian'], meal_type:['lunch','breakfast'], dietary:['vegetarian'], health_tags:['protein','fibre'], occasion:['everyday'], season:['all'], ingredients_main:['toor dal','tamarind','vegetables','sambhar powder','mustard seeds','curry leaves'], description:'Lentil-vegetable stew — the backbone of South Indian cuisine, served with rice, idli, or dosa' },
{ name:'Bisi Bele Bath', name_regional:'ಬಿಸಿ ಬೇಳೆ ಬಾತ್', cuisine:['Karnataka','South Indian'], meal_type:['lunch'], dietary:['vegetarian'], health_tags:['protein','comfort'], occasion:['everyday'], season:['all'], ingredients_main:['rice','toor dal','bisi bele bath powder','vegetables','tamarind','ghee'], description:'Hot lentil rice from Karnataka — spiced one-pot comfort food, finished with ghee' },
{ name:'Thayir Sadam', name_regional:'தயிர் சாதம்', cuisine:['Tamil','South Indian'], meal_type:['lunch'], dietary:['vegetarian'], health_tags:['probiotic','cooling'], occasion:['everyday'], season:['summer'], ingredients_main:['rice','yogurt','mustard seeds','ginger','curry leaves','green chilli'], description:'Curd rice — Tamil everyday finisher, cooling and probiotic, the last course of every meal' },
// Kerala (60)
{ name:'Kerala Karimeen Pollichathu', name_regional:'കരിമീൻ പൊള്ളിച്ചത്', cuisine:['Kerala'], meal_type:['lunch','dinner'], dietary:['non-vegetarian','fish'], health_tags:['protein','omega-3'], occasion:['everyday','guest'], season:['all'], ingredients_main:['pearl spot fish','coconut','shallots','curry leaves','banana leaf'], description:'Pearl spot fish grilled in banana leaf — Kerala backwater speciality, smoky and succulent' },
{ name:'Appam Kadala Curry', name_regional:'അപ്പം കടല കറി', cuisine:['Kerala'], meal_type:['breakfast'], dietary:['vegetarian'], health_tags:['probiotic'], occasion:['everyday'], season:['all'], ingredients_main:['rice flour','coconut milk','toddy','black chickpea','coconut'], description:'Lacy rice pancake with black chickpea curry — quintessential Kerala breakfast' },
{ name:'Kerala Fish Moilee', name_regional:'മീൻ മോലി', cuisine:['Kerala'], meal_type:['lunch','dinner'], dietary:['non-vegetarian','fish'], health_tags:['protein','omega-3'], occasion:['everyday'], season:['all'], ingredients_main:['fish','coconut milk','shallots','green chilli','turmeric','curry leaves'], description:'Fish in light coconut milk sauce — Kerala Christian home cooking, delicate and aromatic' },
{ name:'Avial', name_regional:'അവിയൽ', cuisine:['Kerala'], meal_type:['lunch'], dietary:['vegetarian'], health_tags:['fibre'], occasion:['Onam','everyday'], season:['all'], ingredients_main:['mixed vegetables','coconut','yogurt','curry leaves','coconut oil'], description:'Mixed vegetables in coconut-yogurt sauce — essential dish of Kerala Onam Sadya feast' },
{ name:'Kerala Meen Curry', cuisine:['Kerala'], meal_type:['lunch','dinner'], dietary:['non-vegetarian','fish'], health_tags:['protein','omega-3'], occasion:['everyday'], season:['all'], ingredients_main:['fish','kokum','coconut','shallots','red chilli','curry leaves'], description:'Sour fish curry with kokum — everyday Kerala coastal home cooking' },
// Andhra/Telangana (70)
{ name:'Hyderabadi Dum Biryani', name_hindi:'हैदराबादी दम बिर्यान���', cuisine:['Hyderabadi','Telangana'], meal_type:['lunch','dinner'], dietary:['non-vegetarian','chicken'], health_tags:['protein','energy'], occasion:['party','wedding','everyday'], season:['all'], ingredients_main:['chicken','basmati rice','saffron','fried onion','yogurt','whole spices','mint'], description:'Layered chicken and rice sealed with dough — Hyderabad royal biryani, slow-cooked dum style' },
{ name:'Gongura Mamsam', name_regional:'గోంగూర మాంసం', cuisine:['Andhra','Telugu'], meal_type:['lunch','dinner'], dietary:['non-vegetarian','mutton'], health_tags:['protein','iron'], occasion:['everyday'], season:['all'], ingredients_main:['mutton','gongura leaves','onion','garlic','red chilli'], description:'Mutton with sorrel leaves — tangy Andhra signature dish, bold and sour' },
{ name:'Pesarattu', name_regional:'పెసరట్టు', cuisine:['Andhra','Telugu'], meal_type:['breakfast'], dietary:['vegetarian'], health_tags:['protein','iron'], occasion:['everyday'], season:['all'], ingredients_main:['whole moong','rice','ginger','green chilli','cumin'], description:'Green gram dosa — protein-rich Andhra breakfast, served with allam chutney' },
{ name:'Andhra Chicken Fry', cuisine:['Andhra'], meal_type:['snack','dinner'], dietary:['non-vegetarian','chicken'], health_tags:['protein','spicy'], occasion:['everyday','party'], season:['all'], ingredients_main:['chicken','red chilli','curry leaves','garlic','ginger'], description:'Fiery dry chicken fry — Andhra spice level at its peak, crispy and addictive' },
{ name:'Pappu Pulusu', name_regional:'పప్పు పులుసు', cuisine:['Andhra','Telugu'], meal_type:['lunch'], dietary:['vegetarian'], health_tags:['protein'], occasion:['everyday'], season:['all'], ingredients_main:['toor dal','tamarind','tomato','green chilli','mustard seeds','curry leaves'], description:'Tangy lentil stew from Andhra — everyday comfort dal with tamarind tang' },

// ════════════════ BENGALI (200 dishes) ═════��══════════
{ name:'Sorshe Ilish', name_hindi:'सरसों इलिश', name_regional:'সর্ষে ইলিশ', cuisine:['Bengali'], meal_type:['lunch','dinner'], dietary:['non-vegetarian','fish'], health_tags:['protein','omega-3'], occasion:['everyday','festive'], season:['monsoon'], ingredients_main:['hilsa fish','mustard paste','mustard oil','green chilli','turmeric'], description:'Hilsa in mustard sauce — the king of Bengali fish dishes, peak season during monsoon' },
{ name:'Kosha Mangsho', name_regional:'কষা মাংস', cuisine:['Bengali'], meal_type:['lunch','dinner'], dietary:['non-vegetarian','mutton'], health_tags:['protein','iron'], occasion:['Sunday','festive'], season:['winter'], ingredients_main:['mutton','onion','ginger-garlic','yogurt','whole spices','mustard oil'], description:'Slow-cooked spiced mutton — Bengali Sunday staple, dark and intensely flavoured' },
{ name:'Macher Jhol', name_regional:'মাছের ঝোল', cuisine:['Bengali'], meal_type:['lunch'], dietary:['non-vegetarian','fish'], health_tags:['protein','light'], occasion:['everyday'], season:['all'], ingredients_main:['rohu fish','potato','tomato','turmeric','mustard oil','nigella seeds'], description:'Light fish curry — everyday Bengali comfort, thin turmeric broth with fish and potato' },
{ name:'Shukto', name_regional:'শুক্তো', cuisine:['Bengali'], meal_type:['lunch'], dietary:['vegetarian'], health_tags:['bitter','digestive'], occasion:['everyday'], season:['summer'], ingredients_main:['bitter gourd','raw banana','sweet potato','drumstick','poppy seeds','milk'], description:'Mixed vegetable bitter preparation — first course of Bengali lunch, aids digestion' },
{ name:'Luchi Alur Dom', name_regional:'লুচি আলুর দম', cuisine:['Bengali'], meal_type:['breakfast','lunch'], dietary:['vegetarian'], health_tags:['energy'], occasion:['Sunday','festive'], season:['all'], ingredients_main:['maida','potato','tomato','ghee','ginger','whole spices'], description:'Deep-fried bread with spiced potato — Bengali Sunday breakfast and festive favourite' },
{ name:'Chingri Malai Curry', name_regional:'চিংড়ি মালাই কারি', cuisine:['Bengali'], meal_type:['lunch','dinner'], dietary:['non-vegetarian','fish'], health_tags:['protein'], occasion:['guest','festive'], season:['all'], ingredients_main:['prawns','coconut milk','turmeric','green chilli','mustard oil','sugar'], description:'Prawns in coconut milk — Bengali celebration dish, delicate and creamy' },
{ name:'Mishti Doi', name_regional:'মিষ্টি দই', cuisine:['Bengali'], meal_type:['dessert'], dietary:['vegetarian'], health_tags:['probiotic','calcium'], occasion:['everyday','festive'], season:['all'], ingredients_main:['milk','jaggery','yogurt culture'], description:'Sweetened set yogurt — Bengali signature dessert, caramelised jaggery flavour in clay pot' },
{ name:'Rasgulla', name_regional:'রসগোল্লা', cuisine:['Bengali'], meal_type:['dessert'], dietary:['vegetarian'], health_tags:['light'], occasion:['festive','everyday'], season:['all'], ingredients_main:['chenna','sugar syrup','cardamom','rose water'], description:'Spongy cottage cheese balls in sugar syrup — Bengal gift to the world, light and bouncy' },
{ name:'Patishapta', name_regional:'পাটিসাপটা', cuisine:['Bengali'], meal_type:['dessert'], dietary:['vegetarian'], health_tags:['celebration'], occasion:['Makar Sankranti','winter'], season:['winter'], ingredients_main:['rice flour','coconut','jaggery','milk','khoya'], description:'Stuffed crepe with coconut-jaggery filling — Bengali winter dessert for Poush Parbon' },
{ name:'Doi Maach', name_regional:'দই মাছ', cuisine:['Bengali'], meal_type:['lunch'], dietary:['non-vegetarian','fish'], health_tags:['protein','probiotic'], occasion:['everyday'], season:['all'], ingredients_main:['fish','yogurt','mustard oil','turmeric','green chilli','sugar'], description:'Fish in yogurt gravy — Bengali comfort dish, mild and creamy with a touch of sweetness' },

// ═���══════════════ PUNJABI / NORTH INDIAN (250 dishes) ════════���═══════
{ name:'Butter Chicken', name_hindi:'बटर चिकन', cuisine:['Punjabi','Mughlai'], meal_type:['dinner','lunch'], dietary:['non-vegetarian','chicken'], health_tags:['protein'], occasion:['everyday','party'], season:['all'], ingredients_main:['chicken','butter','cream','tomato','kasuri methi','ginger-garlic'], description:'Creamy tomato chicken — Delhi invention, now India most famous dish globally' },
{ name:'Sarson Ka Saag Makki di Roti', name_hindi:'सरसों का साग मक्की दी रोटी', cuisine:['Punjabi'], meal_type:['lunch','dinner'], dietary:['vegetarian'], health_tags:['iron','fibre','seasonal'], occasion:['winter'], season:['winter'], ingredients_main:['mustard greens','spinach','cornmeal','ghee','jaggery','onion'], description:'Mustard greens with corn flatbread — Punjab winter icon, eaten with a dollop of white butter' },
{ name:'Amritsari Chole', name_hindi:'अमृतसरी छोले', cuisine:['Punjabi'], meal_type:['breakfast','lunch'], dietary:['vegetarian'], health_tags:['protein','fibre'], occasion:['everyday'], season:['all'], ingredients_main:['chickpeas','tea leaves','onion','ginger','amchur','chole masala'], description:'Amritsar-style dark chickpea curry — cooked with tea for colour, tangy and robust' },
{ name:'Amritsari Kulcha', name_hindi:'अमृतसरी कुलचा', cuisine:['Punjabi'], meal_type:['breakfast','lunch'], dietary:['vegetarian'], health_tags:['energy'], occasion:['everyday','street food'], season:['all'], ingredients_main:['maida','potato','paneer','onion','coriander','butter'], description:'Stuffed tandoori bread from Amritsar — flaky, buttery, filled with spiced potato and paneer' },
{ name:'Rajma Chawal', name_hindi:'राजमा चावल', cuisine:['Punjabi'], meal_type:['lunch'], dietary:['vegetarian'], health_tags:['protein','iron','fibre'], occasion:['everyday'], season:['all'], ingredients_main:['kidney beans','rice','onion','tomato','ginger-garlic','spices'], description:'Kidney bean curry with rice — Monday lunch in every Punjabi household, comfort at its peak' },
{ name:'Dal Makhani', name_hindi:'दाल मखनी', cuisine:['Punjabi'], meal_type:['dinner','lunch'], dietary:['vegetarian'], health_tags:['protein','iron'], occasion:['everyday','festive'], season:['winter'], ingredients_main:['black urad dal','butter','cream','tomato','garlic','kasuri methi'], description:'Slow-cooked black lentils in butter — 24-hour simmered Punjab classic, rich and velvety' },
{ name:'Chicken Tikka', name_hindi:'चिकन टिक्का', cuisine:['Punjabi'], meal_type:['snack','dinner'], dietary:['non-vegetarian','chicken'], health_tags:['protein'], occasion:['party','everyday'], season:['all'], ingredients_main:['chicken','yogurt','lemon','tikka masala','capsicum','onion'], description:'Tandoori grilled chicken pieces — Punjabi appetiser, smoky and charred' },
{ name:'Tandoori Chicken', name_hindi:'तंदूरी चिकन', cuisine:['Punjabi'], meal_type:['dinner','snack'], dietary:['non-vegetarian','chicken'], health_tags:['protein'], occasion:['party','everyday'], season:['all'], ingredients_main:['chicken','yogurt','Kashmiri chilli','lemon','ginger-garlic'], description:'Whole marinated chicken roasted in tandoor — the original Punjabi classic, red and smoky' },
{ name:'Palak Paneer', name_hindi:'पालक पनीर', cuisine:['Punjabi'], meal_type:['lunch','dinner'], dietary:['vegetarian'], health_tags:['iron','calcium','protein'], occasion:['everyday'], season:['winter'], ingredients_main:['spinach','paneer','onion','garlic','cream','cumin'], description:'Spinach-cottage cheese curry — North Indian restaurant staple, iron meets calcium' },

// ════════════════ MUGHLAI / LUCKNOWI / AWADHI (150 dishes) ════════════════
{ name:'Lucknowi Galouti Kebab', name_hindi:'ल���नवी गलौटी कबाब', cuisine:['Awadhi','Lucknowi'], meal_type:['snack','dinner'], dietary:['non-vegetarian','mutton'], health_tags:['protein'], occasion:['party','guest'], season:['all'], ingredients_main:['minced mutton','raw papaya','cardamom','mace','rose water','ghee'], description:'Melt-in-mouth mutton kebab — invented for a toothless Nawab, 160+ spices in legend' },
{ name:'Kakori Kebab', cuisine:['Awadhi','Lucknowi'], meal_type:['snack','dinner'], dietary:['non-vegetarian','mutton'], health_tags:['protein'], occasion:['party'], season:['all'], ingredients_main:['minced mutton','raw papaya','saffron','mace','cardamom','ghee'], description:'Seekh kebab from Kakori village — finer than galouti, silky texture, Lucknow pride' },
{ name:'Shami Kebab', name_hindi:'शामी कबाब', cuisine:['Mughlai','Lucknowi'], meal_type:['snack','dinner'], dietary:['non-vegetarian','mutton'], health_tags:['protein'], occasion:['everyday','party'], season:['all'], ingredients_main:['mutton mince','chana dal','onion','mint','egg','whole spices'], description:'Pan-fried lentil-meat patties — Mughlai classic, crispy outside, soft inside' },
{ name:'Lucknowi Biryani', cuisine:['Awadhi','Lucknowi'], meal_type:['lunch','dinner'], dietary:['non-vegetarian','chicken'], health_tags:['protein','energy'], occasion:['party','wedding'], season:['all'], ingredients_main:['chicken','basmati rice','saffron','kewra water','fried onion','whole spices'], description:'Pukki biryani — rice and meat cooked separately then layered, Lucknow style, fragrant with kewra' },
{ name:'Nihari', name_hindi:'निहारी', cuisine:['Mughlai','Lucknowi'], meal_type:['breakfast','dinner'], dietary:['non-vegetarian','mutton'], health_tags:['protein','iron'], occasion:['weekend','festive'], season:['winter'], ingredients_main:['mutton shanks','wheat flour','ginger','green chilli','lime','fried onion'], description:'Slow-cooked bone marrow stew — Old Delhi breakfast of kings, eaten with naan at dawn' },
{ name:'Haleem', name_hindi:'हलीम', cuisine:['Hyderabadi','Mughlai'], meal_type:['dinner'], dietary:['non-vegetarian','mutton'], health_tags:['protein','energy'], occasion:['Ramadan','winter'], season:['winter'], ingredients_main:['mutton','wheat','barley','lentils','ghee','fried onion','lime'], description:'Slow-cooked meat and grain stew — Hyderabadi Ramadan staple, thick and nourishing' },
{ name:'Mughlai Paratha', name_hindi:'मुगलई पराठा', cuisine:['Mughlai','Bengali'], meal_type:['breakfast','dinner'], dietary:['non-vegetarian','egg'], health_tags:['protein','energy'], occasion:['weekend'], season:['all'], ingredients_main:['maida','egg','onion','green chilli','ghee'], description:'Egg-stuffed fried bread — Kolkata street food with Mughlai roots, rich and flaky' },
{ name:'Korma', name_hindi:'कोरम���', cuisine:['Mughlai'], meal_type:['dinner'], dietary:['non-vegetarian','chicken'], health_tags:['protein','rich'], occasion:['party','wedding'], season:['all'], ingredients_main:['chicken','cashew','yogurt','cream','saffron','cardamom','mace'], description:'Rich nut-yogurt gravy — Mughlai banquet dish, mild and aromatic' },
{ name:'Sheermal', cuisine:['Awadhi','Lucknowi'], meal_type:['dinner'], dietary:['vegetarian'], health_tags:['energy'], occasion:['festive'], season:['all'], ingredients_main:['maida','milk','saffron','sugar','ghee','cardamom'], description:'Saffron-laced sweet bread — baked in tandoor, Lucknow Nawabi bread, fragrant and rich' },

// ════════════════ COASTAL: GOAN / MANGALOREAN / KONKANI (150 dishes) ════════════════
{ name:'Goan Vindaloo', name_regional:'Vindalho', cuisine:['Goan'], meal_type:['lunch','dinner'], dietary:['non-vegetarian','pork'], health_tags:['protein','spicy'], occasion:['Christmas','everyday'], season:['all'], ingredients_main:['pork','vinegar','Kashmiri chilli','garlic','ginger','whole spices'], description:'Pork in vinegar-chilli sauce — Portuguese-Goan hybrid, tangy-hot, Christmas essential' },
{ name:'Goan Xacuti', name_regional:'Xacuti', cuisine:['Goan'], meal_type:['lunch','dinner'], dietary:['non-vegetarian','chicken'], health_tags:['protein'], occasion:['everyday','festive'], season:['all'], ingredients_main:['chicken','coconut','poppy seeds','star anise','clove','onion'], description:'Chicken in complex coconut-spice gravy — Goan classic with 20+ spice blend' },
{ name:'Goan Fish Curry Rice', cuisine:['Goan'], meal_type:['lunch'], dietary:['non-vegetarian','fish'], health_tags:['protein','omega-3'], occasion:['everyday'], season:['all'], ingredients_main:['fish','coconut','kokum','tamarind','red chilli','rice'], description:'Fish curry with rice — the daily Goan meal, sour-spicy coconut gravy with steamed rice' },
{ name:'Sorpotel', name_regional:'Sorpotel', cuisine:['Goan'], meal_type:['lunch','dinner'], dietary:['non-vegetarian','pork'], health_tags:['protein'], occasion:['Christmas','Easter'], season:['winter'], ingredients_main:['pork','liver','vinegar','toddy','red chilli','whole spices'], description:'Spicy pork offal stew — Goan Catholic festival essential, improves with reheating' },
{ name:'Bebinca', name_regional:'Bebinca', cuisine:['Goan'], meal_type:['dessert'], dietary:['vegetarian'], health_tags:['rich'], occasion:['Christmas','wedding'], season:['all'], ingredients_main:['coconut milk','egg yolk','sugar','ghee','nutmeg','maida'], description:'Seven-layer Goan pudding — each layer baked individually, Christmas dessert queen' },
{ name:'Mangalorean Kori Roti', name_regional:'ಕೋರಿ ರೊಟ್ಟಿ', cuisine:['Mangalorean'], meal_type:['lunch','dinner'], dietary:['non-vegetarian','chicken'], health_tags:['protein','spicy'], occasion:['everyday','festive'], season:['all'], ingredients_main:['chicken','coconut','rice roti','byadgi chilli','tamarind','onion'], description:'Chicken curry with crispy rice wafers — Mangalore signature, fiery red curry soaked into roti' },
{ name:'Kane Fry', name_regional:'ಕಣೆ ಫ್ರೈ', cuisine:['Mangalorean'], meal_type:['snack','dinner'], dietary:['non-vegetarian','fish'], health_tags:['protein','omega-3'], occasion:['everyday'], season:['all'], ingredients_main:['ladyfish','semolina','turmeric','red chilli','salt'], description:'Crispy pan-fried ladyfish — Mangalore coast staple, simple and addictive' },
{ name:'Neer Dosa', name_regional:'ನೀರ ದೋಸೆ', cuisine:['Mangalorean'], meal_type:['breakfast'], dietary:['vegetarian'], health_tags:['light'], occasion:['everyday'], season:['all'], ingredients_main:['rice','coconut','water'], description:'Paper-thin water rice crepe — Mangalore delicacy, lacy and translucent, served with chutney' },
{ name:'Konkani Sol Kadhi', cuisine:['Konkani','Goan'], meal_type:['lunch'], dietary:['vegetarian'], health_tags:['digestive','cooling'], occasion:['everyday'], season:['summer'], ingredients_main:['kokum','coconut milk','garlic','green chilli','coriander'], description:'Pink kokum-coconut drink — Konkani digestive served after meals, cooling and tangy' },

// ════════════════ KASHMIRI (100 dishes) ═══��════════════
{ name:'Rogan Josh', name_hindi:'रोगन जोश', cuisine:['Kashmiri'], meal_type:['lunch','dinner'], dietary:['non-vegetarian','mutton'], health_tags:['protein','iron'], occasion:['festive','Wazwan','everyday'], season:['winter'], ingredients_main:['mutton','Kashmiri chilli','fennel','yogurt','saffron','dry ginger'], description:'Slow-cooked lamb in aromatic gravy — Kashmiri Wazwan cornerstone, red from chilli not tomato' },
{ name:'Gushtaba', name_regional:'گوشتابہ', cuisine:['Kashmiri'], meal_type:['dinner'], dietary:['non-vegetarian','mutton'], health_tags:['protein'], occasion:['Wazwan','wedding'], season:['winter'], ingredients_main:['minced mutton','yogurt','saffron','fennel','dry ginger','cream'], description:'Giant mutton meatballs in yogurt — the final dish of Kashmiri Wazwan feast, mild and royal' },
{ name:'Dum Aloo Kashmiri', name_hindi:'दम आलू कश्मीरी', cuisine:['Kashmiri'], meal_type:['lunch','dinner'], dietary:['vegetarian'], health_tags:['comfort'], occasion:['everyday'], season:['winter'], ingredients_main:['baby potato','yogurt','fennel','dry ginger','Kashmiri chilli','saffron'], description:'Slow-cooked baby potatoes in yogurt gravy — Kashmiri vegetarian pride, mild and aromatic' },
{ name:'Yakhni', name_regional:'یخنی', cuisine:['Kashmiri'], meal_type:['dinner'], dietary:['non-vegetarian','mutton'], health_tags:['protein','light'], occasion:['Wazwan','everyday'], season:['winter'], ingredients_main:['mutton','yogurt','fennel','dry ginger','saffron','mint'], description:'Mutton in yogurt broth — delicate Kashmiri preparation, fennel-scented and comforting' },
{ name:'Haak', name_regional:'ہاک', cuisine:['Kashmiri'], meal_type:['lunch','dinner'], dietary:['vegetarian'], health_tags:['iron','fibre'], occasion:['everyday'], season:['winter'], ingredients_main:['collard greens','mustard oil','hing','dry red chilli','water'], description:'Kashmiri collard greens — everyday Pandit vegetable, simple and nourishing with mustard oil' },
{ name:'Modur Pulao', name_regional:'مودور پلاؤ', cuisine:['Kashmiri'], meal_type:['lunch'], dietary:['vegetarian'], health_tags:['energy','celebration'], occasion:['Wazwan','wedding'], season:['all'], ingredients_main:['basmati rice','saffron','sugar','ghee','dry fruits','cinnamon'], description:'Sweet saffron rice — Kashmiri celebration pulao, golden and fragrant with dry fruits' },
{ name:'Tabak Maaz', cuisine:['Kashmiri'], meal_type:['snack','dinner'], dietary:['non-vegetarian','mutton'], health_tags:['protein'], occasion:['Wazwan','festive'], season:['winter'], ingredients_main:['mutton ribs','milk','fennel','dry ginger','ghee'], description:'Crispy fried lamb ribs — first boiled in milk-spice, then deep-fried, Wazwan appetiser' },
{ name:'Kashmiri Rajma', cuisine:['Kashmiri'], meal_type:['lunch'], dietary:['vegetarian'], health_tags:['protein'], occasion:['everyday'], season:['all'], ingredients_main:['Kashmiri rajma','onion','ginger','fennel','dry ginger','mustard oil'], description:'Small red kidney beans — Kashmiri style with fennel and dry ginger, different from Punjabi rajma' },

// ���═══════════════ SINDHI (100 dishes) ════════════════
{ name:'Sindhi Kadhi', name_hindi:'सिंधी कढ़ी', cuisine:['Sindhi'], meal_type:['lunch'], dietary:['vegetarian'], health_tags:['digestive','comfort'], occasion:['everyday'], season:['all'], ingredients_main:['gram flour','okra','drumstick','cluster beans','tamarind','onion'], description:'Thick gram flour vegetable stew — Sindhi Sunday staple, tangy and loaded with vegetables' },
{ name:'Dal Pakwan', name_hindi:'दाल पकवान', cuisine:['Sindhi'], meal_type:['breakfast'], dietary:['vegetarian'], health_tags:['protein','energy'], occasion:['Sunday','festive'], season:['all'], ingredients_main:['chana dal','maida','cumin','onion','green chilli','coriander'], description:'Spiced lentils with crispy fried bread — quintessential Sindhi Sunday breakfast' },
{ name:'Sai Bhaji', name_hindi:'साई भाजी', cuisine:['Sindhi'], meal_type:['lunch'], dietary:['vegetarian'], health_tags:['iron','fibre'], occasion:['everyday'], season:['all'], ingredients_main:['spinach','dill','chana dal','potato','onion','tomato'], description:'Greens and lentil one-pot from Sindh — the most nutritious Sindhi everyday dish' },
{ name:'Sindhi Biryani', cuisine:['Sindhi'], meal_type:['lunch','dinner'], dietary:['non-vegetarian','mutton'], health_tags:['protein','energy'], occasion:['party','festive'], season:['all'], ingredients_main:['mutton','basmati rice','fried onion','yogurt','potato','plum','whole spices'], description:'Spicy mutton biryani with potato and plum — Sindhi celebration rice, bolder than Hyderabadi' },
{ name:'Seyal Mani', cuisine:['Sindhi'], meal_type:['breakfast'], dietary:['vegetarian'], health_tags:['quick'], occasion:['everyday'], season:['all'], ingredients_main:['leftover roti','tomato','onion','green chilli','cumin','coriander'], description:'Leftover bread cooked with tomato — Sindhi zero-waste breakfast, tangy and quick' },

// ═══════════��════ PARSI (75 dishes) ════════════════
{ name:'Dhansak', name_hindi:'धनसाक', cuisine:['Parsi'], meal_type:['lunch'], dietary:['non-vegetarian','mutton'], health_tags:['protein','fibre'], occasion:['Sunday','memorial'], season:['all'], ingredients_main:['mutton','mixed dals','vegetables','fenugreek','tamarind','jaggery'], description:'Lentil-mutton stew — Parsi Sunday ritual dish, sweet-sour-spicy, served with caramelised brown rice' },
{ name:'Patra ni Machhi', name_hindi:'पतरा नी मच्छी', cuisine:['Parsi'], meal_type:['dinner','lunch'], dietary:['non-vegetarian','fish'], health_tags:['protein','omega-3'], occasion:['wedding','festive'], season:['all'], ingredients_main:['pomfret','coconut chutney','banana leaf','coriander','mint','lemon'], description:'Fish steamed in banana leaf with green chutney — Parsi wedding essential, delicate and aromatic' },
{ name:'Salli Boti', name_hindi:'सल्ली बोटी', cuisine:['Parsi'], meal_type:['dinner'], dietary:['non-vegetarian','mutton'], health_tags:['protein'], occasion:['party','festive'], season:['all'], ingredients_main:['mutton','potato straw','onion','tomato','vinegar','jaggery'], description:'Mutton curry topped with crispy potato straws — sweet-sour Parsi classic' },
{ name:'Akuri', name_hindi:'आकुरी', cuisine:['Parsi'], meal_type:['breakfast'], dietary:['non-vegetarian','egg'], health_tags:['protein'], occasion:['everyday'], season:['all'], ingredients_main:['eggs','onion','tomato','green chilli','coriander','butter'], description:'Parsi spiced scrambled eggs — softer and richer than bhurji, Irani cafe breakfast' },
{ name:'Lagan nu Custard', cuisine:['Parsi'], meal_type:['dessert'], dietary:['non-vegetarian','egg'], health_tags:['calcium'], occasion:['wedding'], season:['all'], ingredients_main:['milk','eggs','sugar','nutmeg','cardamom','charoli'], description:'Baked wedding custard — caramelised Parsi wedding dessert, rich with nutmeg' },
{ name:'Berry Pulao', cuisine:['Parsi'], meal_type:['lunch'], dietary:['non-vegetarian','mutton'], health_tags:['protein','energy'], occasion:['festive','wedding'], season:['all'], ingredients_main:['mutton','basmati rice','barberries','fried onion','saffron','whole spices'], description:'Lamb rice with dried barberries — Parsi celebration pulao, sweet-tart berry contrast' },

// ════════════════ CHETTINAD (75 dishes) ════════════════
{ name:'Chicken Chettinad', name_regional:'செட்டிநாடு கோழி', cuisine:['Chettinad'], meal_type:['lunch','dinner'], dietary:['non-vegetarian','chicken'], health_tags:['protein','spicy'], occasion:['everyday','guest'], season:['all'], ingredients_main:['chicken','star anise','fennel','kalpasi','pepper','coconut','curry leaves'], description:'Fiery chicken with rare Chettinad spices — kalpasi and marathi mokku give it unique depth' },
{ name:'Chettinad Prawn Masala', cuisine:['Chettinad'], meal_type:['lunch','dinner'], dietary:['non-vegetarian','fish'], health_tags:['protein','omega-3'], occasion:['everyday'], season:['all'], ingredients_main:['prawns','coconut','pepper','fennel','curry leaves','tamarind'], description:'Spicy prawn curry with whole spices — Chettinad seafood at its finest' },
{ name:'Kuzhi Paniyaram', name_regional:'குழி பணியாரம்', cuisine:['Chettinad','Tamil'], meal_type:['breakfast','snack'], dietary:['vegetarian'], health_tags:['probiotic'], occasion:['everyday'], season:['all'], ingredients_main:['rice batter','urad dal','onion','coconut','curry leaves'], description:'Savoury fermented rice-lentil balls — made in special pan, crispy outside, soft inside' },
{ name:'Athirasam', name_regional:'அதிரசம��', cuisine:['Chettinad','Tamil'], meal_type:['dessert'], dietary:['vegetarian'], health_tags:['energy'], occasion:['Diwali','festive'], season:['all'], ingredients_main:['rice flour','jaggery','cardamom','ghee'], description:'Jaggery rice doughnut — ancient Tamil Diwali sweet, chewy and deeply flavoured' },

// ════════════════ ODIA (75 dishes) ════════════════
{ name:'Dalma', name_regional:'ଡାଲମା', cuisine:['Odia'], meal_type:['lunch'], dietary:['vegetarian'], health_tags:['protein','fibre'], occasion:['everyday','Jagannath temple'], season:['all'], ingredients_main:['chana dal','raw banana','raw papaya','pumpkin','coconut','panch phutana'], description:'Lentils with mixed vegetables — Odisha temple food, sattvic and wholesome' },
{ name:'Pakhala Bhata', name_regional:'ପଖାଳ ଭାତ', cuisine:['Odia'], meal_type:['lunch'], dietary:['vegetarian'], health_tags:['probiotic','cooling'], occasion:['summer','everyday'], season:['summer'], ingredients_main:['rice','water','yogurt','mustard','curry leaves','green chilli'], description:'Fermented water rice — Odisha summer staple, cooling and probiotic, eaten with fried vegetables' },
{ name:'Chhena Poda', name_regional:'ଛେନା ପୋଡ଼', cuisine:['Odia'], meal_type:['dessert'], dietary:['vegetarian'], health_tags:['calcium'], occasion:['festive','everyday'], season:['all'], ingredients_main:['chenna','sugar','cardamom','raisins','cashew'], description:'Baked cottage cheese cake — Odisha signature dessert, caramelised and dense' },
{ name:'Santula', name_regional:'ସନ୍ତୁଳା', cuisine:['Odia'], meal_type:['lunch'], dietary:['vegetarian'], health_tags:['light','fibre'], occasion:['everyday'], season:['all'], ingredients_main:['mixed vegetables','panch phutana','turmeric','coconut'], description:'Steamed mixed vegetables — simple Odia preparation, no oil, sattvic temple food' },
{ name:'Machha Besara', cuisine:['Odia'], meal_type:['lunch','dinner'], dietary:['non-vegetarian','fish'], health_tags:['protein','omega-3'], occasion:['everyday'], season:['all'], ingredients_main:['fish','mustard paste','turmeric','green chilli','mustard oil'], description:'Fish in mustard gravy — Odia everyday fish preparation, yellow and pungent' },

// ════════════════ ASSAMESE / NORTHEAST (75 dishes) ════════��═══════
{ name:'Masor Tenga', name_regional:'মাছৰ টেঙা', cuisine:['Assamese'], meal_type:['lunch'], dietary:['non-vegetarian','fish'], health_tags:['protein','light'], occasion:['everyday'], season:['all'], ingredients_main:['fish','tomato','lemon','elephant apple','mustard oil','turmeric'], description:'Sour fish curry — Assam everyday fish dish, light tangy broth with elephant apple or lemon' },
{ name:'Khar', name_regional:'খাৰ', cuisine:['Assamese'], meal_type:['lunch'], dietary:['vegetarian'], health_tags:['digestive','alkaline'], occasion:['everyday'], season:['all'], ingredients_main:['raw papaya','khar alkali','mustard oil','turmeric'], description:'Alkaline vegetable preparation — unique Assamese first course, made with burnt banana peel alkali' },
{ name:'Assamese Pitha', name_regional:'পিঠা', cuisine:['Assamese'], meal_type:['breakfast','dessert'], dietary:['vegetarian'], health_tags:['energy'], occasion:['Bihu','festive'], season:['winter'], ingredients_main:['rice flour','coconut','jaggery','sesame','ghee'], description:'Rice flour cakes — Assamese Bihu festival essential, multiple varieties (til pitha, ghila pitha)' },
{ name:'Ou Tenga Maas', cuisine:['Assamese'], meal_type:['dinner'], dietary:['non-vegetarian','fish'], health_tags:['protein'], occasion:['everyday'], season:['summer'], ingredients_main:['fish','elephant apple','mustard seeds','green chilli','mustard oil'], description:'Fish with elephant apple — sour Assamese preparation, unique to the Northeast' },
{ name:'Duck Curry Assamese', cuisine:['Assamese'], meal_type:['dinner'], dietary:['non-vegetarian','chicken'], health_tags:['protein'], occasion:['Bihu','festive'], season:['winter'], ingredients_main:['duck','ash gourd','sesame','garlic','ginger','mustard oil'], description:'Duck with ash gourd — Assamese Bihu feast dish, rich and gamey' },
{ name:'Aloo Pitika', name_regional:'আলু পিটিকা', cuisine:['Assamese'], meal_type:['lunch'], dietary:['vegetarian'], health_tags:['comfort'], occasion:['everyday'], season:['all'], ingredients_main:['potato','mustard oil','onion','green chilli','coriander'], description:'Mashed potato with mustard oil — Assamese comfort side dish, simple and satisfying' },
];

// Merge all cuisine files into single export
export const DISH_DATA: DishSeed[] = [
  ...JAIN_DISH_DATA,
  ...GUJARATI_DISHES,
  ...MAHARASHTRIAN_DISHES,
  ...MALVANI_DISHES,
  ...MANGALOREAN_DISHES,
  ...GOAN_DISHES,
  ...FASTING_DISHES,
  ...PUNJABI_DISHES,
  ...RAJASTHANI_DISHES,
  ...NON_JAIN_DISHES,
];
