interface DishSeed {
  name: string; name_hindi?: string; name_regional?: string;
  cuisine: string[]; meal_type: string[]; dietary: string[];
  health_tags: string[]; occasion: string[]; season: string[];
  ingredients_main: string[]; description: string;
}

export const PUNJABI_DISHES: DishSeed[] = [
// ═══ Non-Veg Mains (60) ═══
{ name:'Murgh Makhani', name_hindi:'मुर्ग़ मखनी', cuisine:['Punjabi','Mughlai'], meal_type:['dinner'], dietary:['non-vegetarian','chicken'], health_tags:['protein','rich'], occasion:['everyday','party'], season:['all'], ingredients_main:['chicken','butter','cream','tomato','kasuri methi','ginger-garlic','honey'], description:'The original butter chicken from Daryaganj Delhi — invented at Moti Mahal in the 1950s, smoky tandoori chicken in butter-tomato sauce' },
{ name:'Achari Murgh', name_hindi:'अचारी मुर्ग़', cuisine:['Punjabi'], meal_type:['dinner'], dietary:['non-vegetarian','chicken'], health_tags:['protein'], occasion:['everyday'], season:['all'], ingredients_main:['chicken','pickle spices','mustard seeds','fennel','onion seeds','fenugreek seeds','yogurt'], description:'Pickle-spiced chicken — tangy five-seed masala, the pickle spice blend gives it a unique sour-hot punch' },
{ name:'Dahi Wala Murgh', name_hindi:'दही वाला मुर्ग़', cuisine:['Punjabi'], meal_type:['dinner'], dietary:['non-vegetarian','chicken'], health_tags:['protein','probiotic'], occasion:['everyday'], season:['all'], ingredients_main:['chicken','yogurt','onion','ginger-garlic','green chilli','coriander'], description:'Yogurt chicken — mild creamy chicken simmered in spiced yogurt, North Indian home-style comfort' },
{ name:'Methi Murgh', name_hindi:'मेथी मुर्ग़', cuisine:['Punjabi'], meal_type:['dinner'], dietary:['non-vegetarian','chicken'], health_tags:['protein','iron'], occasion:['everyday'], season:['winter'], ingredients_main:['chicken','fresh fenugreek leaves','onion','tomato','ginger-garlic','cream'], description:'Fenugreek chicken — bitter-sweet methi leaves balance the rich gravy, Punjab winter non-veg staple' },
{ name:'Palak Murgh', name_hindi:'पालक मुर्ग़', cuisine:['Punjabi'], meal_type:['dinner'], dietary:['non-vegetarian','chicken'], health_tags:['protein','iron'], occasion:['everyday'], season:['winter'], ingredients_main:['chicken','spinach','onion','ginger-garlic','green chilli','cream'], description:'Spinach chicken — the non-veg version of palak paneer, iron-rich, green and creamy, winter dinner' },
{ name:'Mutton Kadhai', name_hindi:'मटन कड़ाही', cuisine:['Punjabi'], meal_type:['dinner'], dietary:['non-vegetarian','mutton'], health_tags:['protein','iron'], occasion:['weekend','guest'], season:['winter'], ingredients_main:['mutton','capsicum','tomato','onion','kadhai masala','coriander seeds'], description:'Wok-tossed mutton with bell peppers — Punjabi dhaba-style, coarsely ground spices, served sizzling in iron kadhai' },
{ name:'Mutton Korma Punjabi', name_hindi:'मटन कोरमा', cuisine:['Punjabi','Mughlai'], meal_type:['dinner'], dietary:['non-vegetarian','mutton'], health_tags:['protein','rich'], occasion:['party','wedding'], season:['winter'], ingredients_main:['mutton','cashew','yogurt','cream','saffron','cardamom','mace'], description:'Rich mutton in nut-yogurt sauce — Punjabi wedding feast dish, mild and aromatic, cream and cashew base' },
{ name:'Keema Matar', name_hindi:'कीमा मटर', cuisine:['Punjabi','Mughlai'], meal_type:['dinner'], dietary:['non-vegetarian','mutton'], health_tags:['protein','iron'], occasion:['everyday'], season:['winter'], ingredients_main:['mutton mince','green peas','onion','ginger-garlic','garam masala','coriander'], description:'Minced meat with peas — everyday Punjabi-Mughlai non-veg, quick to cook, great with roti or naan' },
{ name:'Keema Pav', name_hindi:'कीमा पाव', cuisine:['Punjabi','Mumbai'], meal_type:['dinner','snack'], dietary:['non-vegetarian','mutton'], health_tags:['protein'], occasion:['everyday','street food'], season:['all'], ingredients_main:['mutton mince','pav bread','onion','ginger-garlic','green chilli','coriander'], description:'Spiced mince with bread — Irani café staple, dry keema scooped up with soft pav' },
{ name:'Brain Masala', name_hindi:'भेजा मसाला', cuisine:['Punjabi','Mughlai'], meal_type:['dinner'], dietary:['non-vegetarian','mutton'], health_tags:['protein','revival'], occasion:['weekend','guest'], season:['winter'], ingredients_main:['goat brain','onion','ginger-garlic','green chilli','garam masala','coriander'], description:'Goat brain curry — old Lahori delicacy, creamy and rich, revival dish being rediscovered in Delhi' },
{ name:'Paya Punjabi', name_hindi:'पाया', cuisine:['Punjabi','Mughlai'], meal_type:['breakfast','dinner'], dietary:['non-vegetarian','mutton'], health_tags:['protein','collagen'], occasion:['winter','weekend'], season:['winter'], ingredients_main:['goat trotters','onion','ginger-garlic','whole spices','coriander','naan'], description:'Goat trotter stew — old Delhi winter breakfast, slow-cooked overnight, eaten with naan at dawn' },
{ name:'Amritsari Fish Fry', name_hindi:'अमृतसरी फिश फ्राई', cuisine:['Punjabi'], meal_type:['snack','dinner'], dietary:['non-vegetarian','fish'], health_tags:['protein','omega-3'], occasion:['everyday','party'], season:['all'], ingredients_main:['fish','gram flour','ajwain','chaat masala','lemon','garlic'], description:'Crispy battered fish from Amritsar — ajwain-laced gram flour coating, the best street fish in India' },
{ name:'Tawa Macchi', name_hindi:'तवा मछली', cuisine:['Punjabi'], meal_type:['dinner'], dietary:['non-vegetarian','fish'], health_tags:['protein','omega-3'], occasion:['everyday'], season:['all'], ingredients_main:['fish steaks','onion','capsicum','tomato','ginger-garlic','spices'], description:'Griddle-cooked fish — Punjabi tawa preparation, fish steaks seared with onion-capsicum on flat iron griddle' },
{ name:'Tandoori Chicken', name_hindi:'तंदूरी चिकन', cuisine:['Punjabi'], meal_type:['dinner','snack'], dietary:['non-vegetarian','chicken'], health_tags:['protein'], occasion:['party','everyday'], season:['all'], ingredients_main:['whole chicken','yogurt','Kashmiri chilli','lemon','ginger-garlic','tandoori masala'], description:'Whole marinated chicken roasted in clay oven — the original Peshawar-Punjabi classic, red, smoky, iconic' },
{ name:'Seekh Kebab', name_hindi:'सीख कबाब', cuisine:['Punjabi','Mughlai'], meal_type:['snack','dinner'], dietary:['non-vegetarian','mutton'], health_tags:['protein'], occasion:['party','street food'], season:['all'], ingredients_main:['mutton mince','onion','green chilli','coriander','garam masala','egg'], description:'Minced meat skewers grilled on seekh — street food from Old Delhi to Amritsar, smoky and juicy' },
{ name:'Reshmi Kebab', name_hindi:'रेशमी कबाब', cuisine:['Mughlai','Punjabi'], meal_type:['snack','dinner'], dietary:['non-vegetarian','chicken'], health_tags:['protein'], occasion:['party'], season:['all'], ingredients_main:['chicken mince','cream','cashew','egg','cardamom','mace','white pepper'], description:'Silky chicken kebab — cream and cashew make these meltingly soft, Mughlai party appetiser' },
{ name:'Hariyali Kebab', name_hindi:'हरियाली कबाब', cuisine:['Punjabi'], meal_type:['snack'], dietary:['non-vegetarian','chicken'], health_tags:['protein','iron'], occasion:['party'], season:['all'], ingredients_main:['chicken','spinach','coriander','mint','green chilli','yogurt','ginger'], description:'Green herb chicken kebab — marinated in spinach-mint-coriander paste, vivid green, fresh and herby' },
{ name:'Dahi ke Kebab', name_hindi:'दही के कबाब', cuisine:['Lucknowi','Punjabi'], meal_type:['snack'], dietary:['vegetarian'], health_tags:['protein','probiotic'], occasion:['party'], season:['all'], ingredients_main:['hung curd','paneer','cashew','raisins','breadcrumbs','cardamom'], description:'Yogurt patties — Lucknowi vegetarian kebab, crispy outside with creamy curd centre, melt-in-mouth' },
// ═══ Veg Mains (50) ═══
{ name:'Sarson da Saag', name_hindi:'सरसों दा साग', cuisine:['Punjabi'], meal_type:['lunch','dinner'], dietary:['vegetarian'], health_tags:['iron','fibre','seasonal'], occasion:['winter'], season:['winter'], ingredients_main:['mustard greens','spinach','butter','cornmeal','ginger','green chilli','ghee'], description:'Mustard greens mash — Punjab winter soul food, slow-cooked greens with a lump of white butter, eaten with makki di roti' },
{ name:'Makki di Roti', name_hindi:'मक्की दी रोटी', cuisine:['Punjabi'], meal_type:['lunch','dinner'], dietary:['vegetarian'], health_tags:['fibre','energy'], occasion:['winter'], season:['winter'], ingredients_main:['cornmeal','ghee'], description:'Corn flatbread — inseparable partner of sarson da saag, hand-shaped thick golden disc, Punjab winter identity' },
{ name:'Pindi Chole', name_hindi:'पिंडी छोले', cuisine:['Punjabi'], meal_type:['lunch','breakfast'], dietary:['vegetarian'], health_tags:['protein','fibre'], occasion:['everyday'], season:['all'], ingredients_main:['chickpeas','tea leaves','onion','ginger','pomegranate seeds','anardana','chole masala'], description:'Rawalpindi-style dark chickpeas — cooked with tea bags for colour, tangier and dryer than regular chole' },
{ name:'Kadhi Pakora', name_hindi:'कढ़ी पकोड़ा', cuisine:['Punjabi'], meal_type:['lunch'], dietary:['vegetarian'], health_tags:['probiotic','comfort'], occasion:['everyday'], season:['monsoon'], ingredients_main:['yogurt','gram flour','onion pakora','turmeric','fenugreek seeds','mustard seeds'], description:'Yogurt curry with onion fritters — North Indian comfort food, tangy kadhi with crispy pakode floating in it' },
{ name:'Langar ki Dal', name_hindi:'लंगर की दाल', cuisine:['Punjabi'], meal_type:['lunch'], dietary:['vegetarian'], health_tags:['protein','sacred'], occasion:['everyday','Gurudwara'], season:['all'], ingredients_main:['chana dal','urad dal','butter','onion','ginger-garlic','tomato','ghee'], description:'Sikh temple dal — the taste of langar, slow-cooked overnight in massive pots, served to all regardless of caste or creed' },
{ name:'Kadah Prasad', name_hindi:'कड़ा प्रसाद', cuisine:['Punjabi'], meal_type:['dessert'], dietary:['vegetarian'], health_tags:['energy','sacred'], occasion:['Gurudwara','festive'], season:['all'], ingredients_main:['wheat flour','ghee','sugar','water'], description:'Sikh sacred halwa — equal parts atta, ghee, sugar, water, cooked at every Gurudwara, served warm as prasad' },
{ name:'Malai Kofta', name_hindi:'मलाई कोफ़्ता', cuisine:['Punjabi','Mughlai'], meal_type:['dinner'], dietary:['vegetarian'], health_tags:['rich','protein'], occasion:['party','wedding'], season:['all'], ingredients_main:['paneer','potato','cashew','cream','tomato','cardamom','saffron'], description:'Paneer-potato dumplings in cashew-cream gravy — North Indian party showpiece, rich and royal' },
{ name:'Navratan Korma', name_hindi:'नवरत्न कोरमा', cuisine:['Mughlai','Punjabi'], meal_type:['dinner'], dietary:['vegetarian'], health_tags:['rich','varied'], occasion:['party','wedding'], season:['all'], ingredients_main:['mixed vegetables','paneer','cashew','cream','saffron','raisins','cardamom'], description:'Nine-gem vegetable korma — Mughlai wedding vegetarian, nine types of vegetables and fruits in cream sauce' },
{ name:'Dum Aloo Punjabi', name_hindi:'दम आलू', cuisine:['Punjabi'], meal_type:['dinner','lunch'], dietary:['vegetarian'], health_tags:['comfort'], occasion:['everyday'], season:['winter'], ingredients_main:['baby potato','yogurt','onion','ginger-garlic','Kashmiri chilli','cream'], description:'Slow-cooked baby potatoes in spiced gravy — Punjabi dum aloo, onion-tomato base, richer than Kashmiri version' },
{ name:'Bharwa Bhindi', name_hindi:'भरवां भिंडी', cuisine:['Punjabi'], meal_type:['lunch','dinner'], dietary:['vegetarian'], health_tags:['fibre'], occasion:['everyday'], season:['summer'], ingredients_main:['okra','amchur','coriander','cumin','fennel','red chilli','turmeric'], description:'Stuffed okra — slit okra packed with dry spice mix, pan-fried until crispy, summer Punjabi sabzi' },
{ name:'Baingan Bharta', name_hindi:'बैंगन भर्ता', cuisine:['Punjabi'], meal_type:['dinner'], dietary:['vegetarian'], health_tags:['fibre'], occasion:['everyday'], season:['winter'], ingredients_main:['aubergine','onion','tomato','garlic','green chilli','coriander','mustard oil'], description:'Smoky mashed aubergine — roasted whole on flame, mashed with onion-tomato, the smoky flavour is everything' },
// ═══ Parathas (15) ═══
{ name:'Aloo Paratha', name_hindi:'आलू पराठा', cuisine:['Punjabi'], meal_type:['breakfast'], dietary:['vegetarian'], health_tags:['energy','comfort'], occasion:['everyday'], season:['winter'], ingredients_main:['wheat flour','potato','green chilli','cumin','coriander','ghee'], description:'Potato stuffed flatbread — Punjab breakfast king, served with butter, pickle, and curd, every dhaba serves this' },
{ name:'Gobi Paratha', name_hindi:'गोभी पराठा', cuisine:['Punjabi'], meal_type:['breakfast'], dietary:['vegetarian'], health_tags:['fibre'], occasion:['everyday'], season:['winter'], ingredients_main:['wheat flour','cauliflower','green chilli','ginger','coriander','ghee'], description:'Cauliflower stuffed flatbread — winter breakfast when gobhi is abundant, spiced with ginger and chilli' },
{ name:'Mooli Paratha', name_hindi:'मूली पराठा', cuisine:['Punjabi'], meal_type:['breakfast'], dietary:['vegetarian'], health_tags:['fibre','digestive'], occasion:['everyday'], season:['winter'], ingredients_main:['wheat flour','radish','green chilli','coriander','ajwain','ghee'], description:'Radish stuffed flatbread — winter Punjab breakfast, peppery mooli filling, served with butter and nimbu achaar' },
{ name:'Paneer Paratha Punjabi', name_hindi:'पनीर पराठा', cuisine:['Punjabi'], meal_type:['breakfast'], dietary:['vegetarian'], health_tags:['protein','calcium'], occasion:['weekend'], season:['winter'], ingredients_main:['wheat flour','paneer','green chilli','cumin','coriander','ghee'], description:'Cottage cheese stuffed flatbread — richer weekend breakfast, crumbled paneer spiced with cumin and chilli' },
{ name:'Onion Paratha', name_hindi:'प्याज़ पराठा', cuisine:['Punjabi'], meal_type:['breakfast'], dietary:['vegetarian'], health_tags:['energy'], occasion:['everyday'], season:['all'], ingredients_main:['wheat flour','onion','green chilli','ajwain','coriander','ghee'], description:'Onion stuffed flatbread — the quickest paratha, raw onion filling cooks inside the hot dough' },
{ name:'Methi Paratha', name_hindi:'मेथी पराठा', cuisine:['Punjabi'], meal_type:['breakfast'], dietary:['vegetarian'], health_tags:['iron'], occasion:['everyday'], season:['winter'], ingredients_main:['wheat flour','fenugreek leaves','green chilli','cumin','ghee'], description:'Fenugreek flatbread — winter iron boost, fresh methi kneaded into the dough, fragrant and earthy' },
{ name:'Laccha Paratha', name_hindi:'लच्छा पराठा', cuisine:['Punjabi'], meal_type:['lunch','dinner'], dietary:['vegetarian'], health_tags:['energy'], occasion:['restaurant','party'], season:['all'], ingredients_main:['wheat flour','ghee','oil','salt'], description:'Layered flaky flatbread — pulled into thin layers before cooking, crispy and flaky, restaurant-style' },
{ name:'Mixed Veg Paratha', cuisine:['Punjabi'], meal_type:['breakfast','lunchbox'], dietary:['vegetarian'], health_tags:['fibre'], occasion:['everyday','lunchbox'], season:['all'], ingredients_main:['wheat flour','carrot','capsicum','cabbage','green chilli','cumin','ghee'], description:'Mixed vegetable paratha — grated vegetables in dough, great for kids lunchbox, colourful and nutritious' },
// ═══ Street Food Delhi / Punjab (30) ═══
{ name:'Golgappa', name_hindi:'गोलगप्पे', cuisine:['Punjabi','Delhi'], meal_type:['snack'], dietary:['vegetarian'], health_tags:['light'], occasion:['street food','evening'], season:['all'], ingredients_main:['semolina puris','potato','chickpea','tamarind water','mint water','black salt'], description:'Hollow puris with tangy water — Delhi street food obsession, pani puri of the North, cold spicy water shots' },
{ name:'Dahi Puri Delhi', cuisine:['Delhi','Punjabi'], meal_type:['snack'], dietary:['vegetarian'], health_tags:['probiotic'], occasion:['street food'], season:['all'], ingredients_main:['semolina puris','potato','yogurt','tamarind chutney','sev','pomegranate'], description:'Puris filled with yogurt — Delhi chaat variant, creamy yogurt with sweet tamarind and crunchy sev' },
{ name:'Papdi Chaat Delhi', cuisine:['Delhi','Punjabi'], meal_type:['snack'], dietary:['vegetarian'], health_tags:['light'], occasion:['street food','evening'], season:['all'], ingredients_main:['papdi wafers','potato','chickpea','yogurt','tamarind chutney','green chutney','sev'], description:'Crispy wafer chaat — Delhi Chandni Chowk speciality, layers of papdi, curd, chutneys, and sev' },
{ name:'Aloo Tikki Chaat', name_hindi:'आलू टिक्की चाट', cuisine:['Delhi','Punjabi'], meal_type:['snack'], dietary:['vegetarian'], health_tags:['comfort'], occasion:['street food','evening'], season:['winter'], ingredients_main:['potato patties','chickpea curry','yogurt','tamarind chutney','green chutney','sev'], description:'Potato patty chaat — Delhi street food, crispy tikkis topped with chole, curd, and chutneys' },
{ name:'Raj Kachori', name_hindi:'राज कचौरी', cuisine:['Delhi','Rajasthani'], meal_type:['snack'], dietary:['vegetarian'], health_tags:['royal'], occasion:['street food','party'], season:['all'], ingredients_main:['large kachori shell','potato','sprouts','yogurt','tamarind chutney','sev','pomegranate'], description:'King-sized stuffed kachori — giant crispy shell cracked open and filled with curd-chutney-sprouts, royal street food' },
{ name:'Dahi Bhalle Delhi', name_hindi:'दही भल्ले', cuisine:['Delhi','Punjabi'], meal_type:['snack'], dietary:['vegetarian'], health_tags:['probiotic'], occasion:['street food','festive'], season:['all'], ingredients_main:['urad dal','yogurt','tamarind chutney','red chilli','cumin','raisins'], description:'Lentil dumplings in spiced yogurt — Old Delhi chaat, bhalle soaked until soft, drowning in cold curd' },
{ name:'Ram Ladoo', name_hindi:'राम लड्डू', cuisine:['Delhi'], meal_type:['snack'], dietary:['vegetarian'], health_tags:['protein'], occasion:['street food'], season:['all'], ingredients_main:['moong dal','radish','green chutney','green chilli'], description:'Fried moong dal balls — Delhi-only street food, tiny golden balls served with shredded radish and green chutney' },
{ name:'Chole Kulche Delhi', name_hindi:'छोले कुल्चे', cuisine:['Delhi'], meal_type:['lunch','street food'], dietary:['vegetarian'], health_tags:['protein'], occasion:['street food','everyday'], season:['all'], ingredients_main:['chickpeas','kulcha bread','onion','green chilli','lemon','chole masala'], description:'Chickpea with leavened bread — Delhi lunch staple, spicier than Amritsari chole, served on roadside carts' },
{ name:'Tikki Chole', name_hindi:'टिक्की छोले', cuisine:['Delhi'], meal_type:['snack','lunch'], dietary:['vegetarian'], health_tags:['protein','energy'], occasion:['street food'], season:['all'], ingredients_main:['potato patties','chickpea curry','onion','green chutney','lemon'], description:'Potato patties with chickpea curry — Delhi street fusion, crispy tikkis drowned in spicy chole' },
{ name:'Daulat ki Chaat', name_hindi:'दौलत की चाट', cuisine:['Delhi'], meal_type:['dessert','snack'], dietary:['vegetarian'], health_tags:['light','seasonal','revival'], occasion:['winter','street food'], season:['winter'], ingredients_main:['full-cream milk foam','sugar','pistachios','saffron','cardamom'], description:'Milk cloud dessert — Old Delhi winter-only delicacy, milk foam set overnight in dew, lighter than air, vanishes by 10am' },
{ name:'Kulfi Falooda', name_hindi:'कुल्फी फ़ालूदा', cuisine:['Punjabi','Mughlai'], meal_type:['dessert'], dietary:['vegetarian'], health_tags:['celebration'], occasion:['summer','party'], season:['summer'], ingredients_main:['kulfi','falooda sev','rose syrup','basil seeds','milk','pistachios'], description:'Indian ice cream with noodles — dense kulfi over rose-milk falooda, summer celebration dessert' },
{ name:'Rabdi Jalebi', name_hindi:'रबड़ी जलेबी', cuisine:['Punjabi'], meal_type:['dessert'], dietary:['vegetarian'], health_tags:['rich','celebration'], occasion:['festive','wedding'], season:['winter'], ingredients_main:['maida','sugar syrup','saffron','thick reduced milk','pistachios'], description:'Hot jalebi with cold rabdi — the ultimate North Indian sweet combo, crispy spirals dipped in thick cold rabdi' },
// ═══ Himachal / Uttarakhand / Pahari (20) ═══
{ name:'Siddu', name_regional:'सिड्डू', cuisine:['Himachali'], meal_type:['lunch'], dietary:['vegetarian'], health_tags:['energy','seasonal'], occasion:['winter'], season:['winter'], ingredients_main:['wheat flour','poppy seed paste','walnuts','ghee','yeast'], description:'Steamed stuffed bread from Himachal — poppy seed or walnut filling, steamed in layers, eaten with ghee in snow-bound winters' },
{ name:'Babru', cuisine:['Himachali'], meal_type:['snack','breakfast'], dietary:['vegetarian'], health_tags:['energy'], occasion:['festive'], season:['all'], ingredients_main:['wheat flour','urad dal','hing','ginger','oil'], description:'Deep-fried stuffed bread from Himachal — black dal filling, puri-like, served during festivals and fairs' },
{ name:'Madra', name_regional:'मदरा', cuisine:['Himachali'], meal_type:['lunch'], dietary:['vegetarian'], health_tags:['protein','festive'], occasion:['wedding','festive'], season:['all'], ingredients_main:['chickpea','yogurt','ghee','cardamom','clove','cinnamon','bay leaf'], description:'Himachali chickpea yogurt curry — Dham feast essential, slow-cooked in yogurt with whole spices, the pride of Chamba' },
{ name:'Kullu Trout Fry', cuisine:['Himachali'], meal_type:['dinner'], dietary:['non-vegetarian','fish'], health_tags:['protein','omega-3'], occasion:['everyday'], season:['all'], ingredients_main:['rainbow trout','turmeric','red chilli','lemon','mustard oil'], description:'Pan-fried Kullu river trout — Himalayan freshwater fish, simply spiced, served along the Beas river valley' },
{ name:'Kaale Chane ka Khatta', cuisine:['Himachali'], meal_type:['lunch'], dietary:['vegetarian'], health_tags:['protein'], occasion:['festive','everyday'], season:['all'], ingredients_main:['black chickpea','tamarind','jaggery','ginger','whole spices','ghee'], description:'Sour black chickpea curry from Himachal — Dham feast component, sweet-sour with tamarind and jaggery' },
{ name:'Kafuli', name_regional:'काफुली', cuisine:['Uttarakhandi'], meal_type:['lunch'], dietary:['vegetarian'], health_tags:['iron','fibre'], occasion:['everyday'], season:['winter'], ingredients_main:['spinach','fenugreek','rice paste','ghee','cumin','green chilli'], description:'Garhwali green curry — spinach and fenugreek thickened with rice paste, Uttarakhand mountain winter food' },
{ name:'Chainsoo', name_regional:'चैंसू', cuisine:['Uttarakhandi'], meal_type:['lunch'], dietary:['vegetarian'], health_tags:['protein'], occasion:['everyday'], season:['all'], ingredients_main:['black gram dal','garlic','ginger','cumin','ghee'], description:'Roasted black gram dal from Garhwal — urad dal dry-roasted before cooking for deep nutty flavour, Uttarakhand identity dish' },
{ name:'Phaanu', name_regional:'फाणु', cuisine:['Uttarakhandi'], meal_type:['lunch'], dietary:['vegetarian'], health_tags:['protein'], occasion:['everyday'], season:['all'], ingredients_main:['mixed lentils','garlic','ginger','cumin','ghee','jakhiya seeds'], description:'Mixed lentil paste from Garhwal — soaked dal ground and slow-cooked, thick and earthy, mountain protein staple' },
{ name:'Dubke', cuisine:['Uttarakhandi'], meal_type:['lunch'], dietary:['vegetarian'], health_tags:['protein'], occasion:['everyday'], season:['all'], ingredients_main:['chana dal','garlic','cumin','turmeric','jakhiya seeds','ghee'], description:'Garhwali yellow lentil curry — tempered with jakhiya (Himalayan wild mustard), unique mountain flavour' },
// ═══ Haryana (10) ═══
{ name:'Bajre ki Khichdi Haryana', cuisine:['Haryanvi'], meal_type:['lunch','dinner'], dietary:['vegetarian'], health_tags:['fibre','iron','energy'], occasion:['everyday'], season:['winter'], ingredients_main:['bajra','moong dal','ghee','cumin','onion'], description:'Pearl millet khichdi — Haryana winter staple, eaten with a large dollop of ghee and jaggery, sustaining farm food' },
{ name:'Kachri ki Sabzi', cuisine:['Haryanvi','Rajasthani'], meal_type:['lunch'], dietary:['vegetarian'], health_tags:['fibre','desert food'], occasion:['everyday'], season:['summer'], ingredients_main:['dried kachri','mustard oil','cumin','red chilli','hing'], description:'Dried wild melon vegetable — desert vegetable from Haryana-Rajasthan border, tangy and unique, zero water needed' },
{ name:'Bathua Saag', name_hindi:'बथुआ साग', cuisine:['Haryanvi','Punjabi'], meal_type:['lunch'], dietary:['vegetarian'], health_tags:['iron','seasonal'], occasion:['winter'], season:['winter'], ingredients_main:['bathua leaves','onion','garlic','green chilli','makki ka atta','ghee'], description:'Chenopodium greens — Haryana winter saag, iron-rich wild green cooked with cornmeal, lesser known sister of sarson' },
{ name:'Methi Saag Haryana', cuisine:['Haryanvi'], meal_type:['lunch'], dietary:['vegetarian'], health_tags:['iron'], occasion:['winter'], season:['winter'], ingredients_main:['fenugreek leaves','onion','garlic','makki atta','ghee','green chilli'], description:'Fenugreek greens — Haryana winter preparation, bitter-sweet methi cooked with cornmeal, eaten with bajra roti' },
];
