interface DishSeed { name: string; name_hindi?: string; name_regional?: string; cuisine: string[]; meal_type: string[]; dietary: string[]; health_tags: string[]; occasion: string[]; season: string[]; ingredients_main: string[]; description: string; }

export const SINDHI_DISHES: DishSeed[] = [
// ═══ EVERYDAY SINDHI (40) ═══
{ name:'Sindhi Kadhi', name_hindi:'सिंधी कढ़ी', cuisine:['Sindhi'], meal_type:['lunch'], dietary:['vegetarian'], health_tags:['digestive','comfort'], occasion:['everyday','Sunday'], season:['all'], ingredients_main:['gram flour','tamarind','okra','drumstick','cluster beans','potato','onion','tomato'], description:'The defining Sindhi dish — unlike Punjabi kadhi, this uses NO yoghurt, tamarind gives the tang, loaded with vegetables, Sunday staple in every Sindhi home' },
{ name:'Dal Pakwan Sindhi', name_hindi:'दाल पकवान', cuisine:['Sindhi'], meal_type:['breakfast'], dietary:['vegetarian'], health_tags:['protein','energy'], occasion:['Sunday','festive','everyday'], season:['all'], ingredients_main:['chana dal','maida','cumin','onion','green chilli','coriander','oil'], description:'The iconic Sindhi Sunday breakfast — spiced chana dal with crispy fried maida wafers, every Sindhi worldwide eats this on Sunday morning' },
{ name:'Sai Bhaji Sindhi', name_hindi:'साई भाजी', cuisine:['Sindhi'], meal_type:['lunch'], dietary:['vegetarian'], health_tags:['iron','fibre','protein'], occasion:['everyday'], season:['all'], ingredients_main:['spinach','dill','chana dal','potato','onion','tomato','fenugreek'], description:'Greens and lentil one-pot — the most nutritious Sindhi dish, seven greens with dal, mashed together, served with rice' },
{ name:'Bhuga Chaavar', name_hindi:'भुगा चावल', cuisine:['Sindhi'], meal_type:['lunch'], dietary:['vegetarian'], health_tags:['comfort','energy'], occasion:['everyday'], season:['all'], ingredients_main:['rice','onion','cumin','whole spices','ghee','sugar'], description:'Caramelised onion rice — Sindhi daily rice, onions fried dark and sweet, the caramel notes make it distinctive from regular pulao' },
{ name:'Sindhi Biryani', cuisine:['Sindhi'], meal_type:['lunch','dinner'], dietary:['non-vegetarian','mutton'], health_tags:['protein','energy'], occasion:['party','festive','wedding'], season:['all'], ingredients_main:['mutton','basmati rice','fried onion','yogurt','potato','dried plum','whole spices','mint'], description:'Sindhi celebration rice — includes potato and dried plum (aloo bukhara), bolder and spicier than Hyderabadi, Sindhi identity dish at every wedding' },
{ name:'Koki Sindhi', name_hindi:'कोकी', cuisine:['Sindhi'], meal_type:['breakfast'], dietary:['vegetarian'], health_tags:['fibre','energy'], occasion:['everyday'], season:['all'], ingredients_main:['wheat flour','onion','green chilli','cumin','coriander','pomegranate seeds','oil'], description:'Thick Sindhi flatbread — studded with onion and spices, cooked on low flame until crispy, Sindhi breakfast identity alongside chai' },
{ name:'Sindhi Curry', cuisine:['Sindhi'], meal_type:['lunch'], dietary:['vegetarian'], health_tags:['comfort'], occasion:['everyday'], season:['all'], ingredients_main:['potato','tomato','gram flour','tamarind','cluster beans','okra','onion'], description:'Everyday Sindhi vegetable curry — lighter than kadhi, tamarind-gram flour base with whatever vegetables are in season' },
{ name:'Seyal Maani', name_hindi:'सेयल माणी', cuisine:['Sindhi'], meal_type:['breakfast','lunch'], dietary:['vegetarian'], health_tags:['quick','zero-waste'], occasion:['everyday'], season:['all'], ingredients_main:['leftover roti','tomato','onion','green chilli','cumin','coriander'], description:'Leftover bread in tomato — Sindhi zero-waste genius, stale roti simmered in spiced tomato sauce, tangy and quick' },
{ name:'Seyal Murgi', cuisine:['Sindhi'], meal_type:['dinner'], dietary:['non-vegetarian','chicken'], health_tags:['protein'], occasion:['everyday'], season:['all'], ingredients_main:['chicken','tomato','onion','ginger-garlic','green chilli','cumin','coriander'], description:'Sindhi-style chicken in tomato — same seyal technique applied to chicken, tomato-forward gravy, everyday Sindhi non-veg' },
{ name:'Seyal Gosht', cuisine:['Sindhi'], meal_type:['dinner'], dietary:['non-vegetarian','mutton'], health_tags:['protein','iron'], occasion:['weekend'], season:['winter'], ingredients_main:['mutton','tomato','onion','ginger-garlic','whole spices','cumin'], description:'Sindhi mutton in tomato — slow-cooked seyal style, tomato breaks down into rich gravy, weekend special' },
{ name:'Teevan Sindhi', name_hindi:'तीवन', cuisine:['Sindhi'], meal_type:['dinner'], dietary:['non-vegetarian','mutton'], health_tags:['protein','iron'], occasion:['festive','guest'], season:['winter'], ingredients_main:['mutton','onion','yogurt','whole spices','ginger-garlic','ghee'], description:'Sindhi slow-cooked mutton — the celebratory mutton curry, richer than seyal, yogurt-based, hours of slow cooking' },
{ name:'Aloo Tuk', name_hindi:'आलू टुक', cuisine:['Sindhi'], meal_type:['snack','lunch'], dietary:['vegetarian'], health_tags:['comfort','crispy'], occasion:['everyday'], season:['all'], ingredients_main:['potato','red chilli','amchur','cumin','oil'], description:'Twice-fried potatoes — boiled, smashed, fried until super crispy, the Sindhi potato signature, crunchy and spiced' },
{ name:'Bhee Sindhi', name_hindi:'भी', cuisine:['Sindhi'], meal_type:['lunch'], dietary:['vegetarian'], health_tags:['fibre'], occasion:['everyday','festive'], season:['winter'], ingredients_main:['lotus stem','onion','tomato','cumin','coriander','amchur'], description:'Lotus stem curry — Sindhis love lotus stem (bhee/kamal kakdi), sliced rounds in tangy masala, crunchy texture' },
{ name:'Bhee Aloo', cuisine:['Sindhi'], meal_type:['lunch'], dietary:['vegetarian'], health_tags:['fibre','comfort'], occasion:['everyday'], season:['winter'], ingredients_main:['lotus stem','potato','onion','tomato','cumin','amchur'], description:'Lotus stem with potato — everyday Sindhi combination, the crunch of bhee with soft potato, simple and satisfying' },
{ name:'Dal Chawal Palida', cuisine:['Sindhi'], meal_type:['lunch'], dietary:['vegetarian'], health_tags:['protein','comfort'], occasion:['everyday'], season:['all'], ingredients_main:['moong dal','rice','gram flour','tamarind','turmeric','cumin'], description:'The Sindhi three-component meal — dal over rice with palida (tamarind-gram flour soup) on the side, everyday comfort' },
// ═══ SINDHI SNACKS (15) ═══
{ name:'Sindhi Besan Papdi', cuisine:['Sindhi'], meal_type:['snack'], dietary:['vegetarian'], health_tags:['crispy'], occasion:['everyday','Diwali'], season:['all'], ingredients_main:['gram flour','cumin','pepper','ajwain','oil'], description:'Crispy gram flour crackers — Sindhi namkeen essential, spiced and fried thin, Diwali snack box must-have' },
{ name:'Thadal Sindhi', name_hindi:'ठंडल', cuisine:['Sindhi'], meal_type:['snack'], dietary:['vegetarian'], health_tags:['cooling'], occasion:['summer','Cheti Chand'], season:['summer'], ingredients_main:['almonds','melon seeds','fennel','rose petals','sugar','milk','pepper'], description:'Sindhi cooling drink — like Rajasthani thandai but with more fennel, served at Cheti Chand (Sindhi New Year), summer essential' },
{ name:'Sindhi Kachori', cuisine:['Sindhi'], meal_type:['snack','breakfast'], dietary:['vegetarian'], health_tags:['energy'], occasion:['everyday','festive'], season:['all'], ingredients_main:['maida','moong dal','cumin','fennel','green chilli','oil'], description:'Sindhi lentil pastry — smaller and crunchier than Rajasthani kachori, moong dal filling, street breakfast with chutney' },
{ name:'Tosha Sindhi', cuisine:['Sindhi'], meal_type:['dessert','snack'], dietary:['vegetarian'], health_tags:['energy'], occasion:['festive'], season:['all'], ingredients_main:['maida','ghee','sugar syrup','cardamom','saffron'], description:'Deep-fried sweet — Sindhi festival sweet, layered pastry soaked in syrup, similar to jalebi but flatter and crunchier' },
{ name:'Lolo Sindhi', name_hindi:'लोलो', cuisine:['Sindhi'], meal_type:['breakfast','dessert'], dietary:['vegetarian'], health_tags:['energy'], occasion:['festive','everyday'], season:['all'], ingredients_main:['wheat flour','jaggery','ghee','cardamom'], description:'Sweet Sindhi flatbread — jaggery kneaded into dough, cooked on tawa with ghee, breakfast sweet or festival bread' },
{ name:'Mitho Lolo', cuisine:['Sindhi'], meal_type:['dessert'], dietary:['vegetarian'], health_tags:['energy','celebration'], occasion:['wedding','festive'], season:['all'], ingredients_main:['wheat flour','sugar','ghee','cardamom','almonds'], description:'Sweet ceremonial bread — richer version of lolo for weddings and festivals, more ghee and dry fruits, Sindhi celebration bread' },
// ═══ SINDHI FESTIVE (10) ═══
{ name:'Sindhi Tahiri', name_hindi:'सिंधी ताहिरी', cuisine:['Sindhi'], meal_type:['lunch','dessert'], dietary:['vegetarian'], health_tags:['energy','celebration'], occasion:['Cheti Chand','festive'], season:['all'], ingredients_main:['rice','jaggery','ghee','cardamom','clove','cashew','raisins'], description:'Sweet rice — Sindhi Cheti Chand celebration rice, jaggery-sweetened with whole spices, the Sindhi New Year must-have' },
{ name:'Sindhi Seviyan', cuisine:['Sindhi'], meal_type:['dessert'], dietary:['vegetarian'], health_tags:['comfort'], occasion:['Eid','festive'], season:['all'], ingredients_main:['vermicelli','milk','sugar','ghee','cardamom','almonds','raisins'], description:'Sweet vermicelli — Sindhi celebration dessert, shared across Hindu and Muslim Sindhi communities' },
{ name:'Sindhi Kheer', cuisine:['Sindhi'], meal_type:['dessert'], dietary:['vegetarian'], health_tags:['calcium','comfort'], occasion:['festive'], season:['all'], ingredients_main:['rice','milk','sugar','cardamom','saffron','almonds'], description:'Sindhi rice pudding — slow-simmered, thicker than North Indian version, saffron-heavy, festival offering' },
];
