interface DishSeed {
  name: string; name_hindi?: string; name_regional?: string;
  cuisine: string[]; meal_type: string[]; dietary: string[];
  health_tags: string[]; occasion: string[]; season: string[];
  ingredients_main: string[]; description: string;
}

export const MUGHLAI_DISHES: DishSeed[] = [
// ═══ KEBABS (30) ═══
{ name:'Galouti Kebab Lucknowi', name_hindi:'गलौटी कबाब', cuisine:['Awadhi','Lucknowi'], meal_type:['snack','dinner'], dietary:['non-vegetarian','mutton'], health_tags:['protein'], occasion:['party','guest'], season:['all'], ingredients_main:['minced mutton','raw papaya','cardamom','mace','rose water','ghee','nutmeg'], description:'Melt-in-mouth mutton kebab — invented for toothless Nawab Asad-ud-Daula, 160+ spices in legend, the softest kebab in existence' },
{ name:'Kakori Kebab', cuisine:['Awadhi','Lucknowi'], meal_type:['snack','dinner'], dietary:['non-vegetarian','mutton'], health_tags:['protein'], occasion:['party'], season:['all'], ingredients_main:['minced mutton','raw papaya','saffron','mace','cardamom','kewra water','ghee'], description:'Seekh from Kakori village — finer even than galouti, silky smooth on the seekh, Lucknow pride, named after the village' },
{ name:'Shami Kebab', name_hindi:'शामी कबाब', cuisine:['Mughlai','Lucknowi'], meal_type:['snack','dinner'], dietary:['non-vegetarian','mutton'], health_tags:['protein'], occasion:['everyday','party','Eid'], season:['all'], ingredients_main:['mutton mince','chana dal','onion','mint','egg','whole spices','ginger'], description:'Pan-fried lentil-meat patties — the most made kebab in Indian Muslim homes, crispy outside, soft inside, Eid table essential' },
{ name:'Boti Kebab', name_hindi:'बोटी कबाब', cuisine:['Mughlai'], meal_type:['snack','dinner'], dietary:['non-vegetarian','mutton'], health_tags:['protein','iron'], occasion:['party','festive'], season:['all'], ingredients_main:['mutton cubes','yogurt','red chilli','ginger-garlic','lemon','whole spices'], description:'Grilled mutton cubes — bone-in pieces marinated and tandoored, Old Delhi Jama Masjid style' },
{ name:'Chapli Kebab', name_hindi:'चपली कबाब', cuisine:['Mughlai'], meal_type:['snack','dinner'], dietary:['non-vegetarian','mutton'], health_tags:['protein'], occasion:['everyday'], season:['all'], ingredients_main:['mutton mince','tomato','onion','pomegranate seeds','coriander seeds','green chilli'], description:'Flat minced meat patty — Peshawari origin, spread flat like a chappal (slipper), coarser than shami, more rustic' },
{ name:'Pathar ka Gosht', name_hindi:'पत्थर का गोश्त', cuisine:['Mughlai','Hyderabad'], meal_type:['dinner'], dietary:['non-vegetarian','mutton'], health_tags:['protein','revival'], occasion:['party','guest'], season:['all'], ingredients_main:['mutton steaks','garlic','ginger','lime','pepper','oil'], description:'Stone-cooked mutton — meat seared on heated stone slab, Hyderabadi Nizam tradition, revival in HNI kitchens' },
{ name:'Burra Kebab', cuisine:['Mughlai'], meal_type:['dinner'], dietary:['non-vegetarian','mutton'], health_tags:['protein'], occasion:['party'], season:['all'], ingredients_main:['mutton chops','yogurt','saffron','cardamom','mace','ginger-garlic'], description:'Large mutton chop kebab — whole chops marinated and tandoored, impressive presentation, Mughal banquet meat' },
{ name:'Kalmi Kebab', name_hindi:'कलमी कबाब', cuisine:['Mughlai'], meal_type:['snack','dinner'], dietary:['non-vegetarian','chicken'], health_tags:['protein'], occasion:['party'], season:['all'], ingredients_main:['chicken drumsticks','yogurt','cream','cardamom','mace','saffron','charcoal'], description:'Creamy chicken drumstick kebab — cream-marinated and tandoored, finished with dhungar smoking over charcoal' },
{ name:'Tangdi Kebab', name_hindi:'टांगड़ी कबाब', cuisine:['Mughlai'], meal_type:['snack','dinner'], dietary:['non-vegetarian','chicken'], health_tags:['protein'], occasion:['party','everyday'], season:['all'], ingredients_main:['chicken legs','yogurt','red chilli paste','ginger-garlic','lemon','ajwain'], description:'Chicken leg kebab — whole drumsticks marinated red, tandoored until charred, the party appetiser king' },
{ name:'Gilawat ke Kebab', cuisine:['Awadhi','Lucknowi'], meal_type:['snack'], dietary:['non-vegetarian','mutton'], health_tags:['protein','revival'], occasion:['party'], season:['all'], ingredients_main:['minced mutton','raw papaya','cardamom','mace','kewra','ittar','ghee'], description:'Lucknow aristocrat kebab — even softer than galouti, perfumed with ittar (attar), the ultimate Nawabi indulgence' },
{ name:'Pasanda Kebab', cuisine:['Mughlai'], meal_type:['dinner'], dietary:['non-vegetarian','mutton'], health_tags:['protein'], occasion:['party'], season:['all'], ingredients_main:['mutton fillets','yogurt','cashew','cream','saffron','cardamom'], description:'Stuffed mutton escalope — thin mutton slices stuffed with nuts, rolled and grilled, Mughal court elegance' },
{ name:'Nargisi Kofta', name_hindi:'नर्गिसी कोफ़्ता', cuisine:['Mughlai','Lucknowi'], meal_type:['dinner'], dietary:['non-vegetarian','mutton'], health_tags:['protein'], occasion:['party','wedding','Eid'], season:['all'], ingredients_main:['mutton mince','hard-boiled egg','onion','ginger-garlic','garam masala','cream'], description:'Scotch egg Mughlai — boiled egg wrapped in spiced mince, fried and simmered in gravy, Eid-wedding centrepiece' },
// ═══ BIRYANIS & PULAOS (20) ═══
{ name:'Lucknowi Dum Biryani', cuisine:['Awadhi','Lucknowi'], meal_type:['lunch','dinner'], dietary:['non-vegetarian','mutton'], health_tags:['protein','energy'], occasion:['Eid','wedding','party'], season:['all'], ingredients_main:['mutton','basmati rice','saffron','kewra water','fried onion','whole spices','yogurt'], description:'Lucknow pukki biryani — meat and rice cooked SEPARATELY then layered, kewra-scented, milder than Hyderabadi, Awadhi elegance' },
{ name:'Delhi Biryani', cuisine:['Mughlai','Delhi'], meal_type:['lunch','dinner'], dietary:['non-vegetarian','mutton'], health_tags:['protein','energy'], occasion:['Eid','party'], season:['all'], ingredients_main:['mutton','basmati rice','saffron','fried onion','yogurt','whole spices','mint'], description:'Old Delhi Mughlai biryani — bolder spice than Lucknowi, more generous with meat, Jama Masjid area tradition' },
{ name:'Yakhni Pulao', name_hindi:'यखनी पुलाव', cuisine:['Awadhi','Lucknowi'], meal_type:['lunch'], dietary:['non-vegetarian','mutton'], health_tags:['protein','light'], occasion:['everyday','Eid'], season:['all'], ingredients_main:['mutton','basmati rice','yogurt','whole spices','saffron','kewra water'], description:'Mutton broth rice — rice cooked in yakhni (meat stock), lighter than biryani, fragrant with whole spices, Lucknow everyday' },
{ name:'Mutton Pulao Mughlai', cuisine:['Mughlai'], meal_type:['lunch'], dietary:['non-vegetarian','mutton'], health_tags:['protein','energy'], occasion:['everyday','Eid'], season:['all'], ingredients_main:['mutton','basmati rice','whole spices','fried onion','ghee','saffron'], description:'Simple Mughlai meat rice — less layered than biryani, meat and rice cooked together, everyday Mughlai home food' },
{ name:'Zarda Pulao', name_hindi:'ज़र्दा पुलाव', cuisine:['Mughlai'], meal_type:['dessert','lunch'], dietary:['vegetarian'], health_tags:['energy','celebration'], occasion:['Eid','wedding'], season:['all'], ingredients_main:['basmati rice','sugar','saffron','ghee','cardamom','dry fruits','rose water','kewra'], description:'Sweet saffron rice — golden celebratory rice, Eid and Mughlai wedding essential, fragrant with rose and kewra' },
{ name:'Moti Pulao', name_hindi:'मोती पुलाव', cuisine:['Awadhi','Lucknowi'], meal_type:['dinner'], dietary:['vegetarian'], health_tags:['rich','revival'], occasion:['wedding','guest'], season:['all'], ingredients_main:['basmati rice','paneer balls','ghee','saffron','cardamom','kewra water'], description:'Pearl rice — small paneer balls (moti) studded in fragrant rice, Lucknow Nawabi vegetarian show-stopper, being revived' },
{ name:'Rampur Biryani', cuisine:['Rampur'], meal_type:['lunch','dinner'], dietary:['non-vegetarian','mutton'], health_tags:['protein','revival'], occasion:['festive','Eid'], season:['all'], ingredients_main:['mutton','basmati rice','ittar','saffron','kewra','whole spices','ghee'], description:'Rampur Nawab biryani — perfumed with ittar, distinct from Lucknow and Hyderabad, a nearly lost tradition being revived' },
// ═══ KORMAS & GRAVIES (25) ═══
{ name:'Mutton Korma Mughlai', name_hindi:'मटन कोरमा', cuisine:['Mughlai'], meal_type:['dinner'], dietary:['non-vegetarian','mutton'], health_tags:['protein','rich'], occasion:['Eid','wedding','guest'], season:['winter'], ingredients_main:['mutton','yogurt','cashew','cream','saffron','cardamom','mace','kewra'], description:'Royal mutton in nut-cream sauce — the Mughal banquet centrepiece, slow-braised until tender, cream-cashew-saffron richness' },
{ name:'Chicken Korma Mughlai', cuisine:['Mughlai'], meal_type:['dinner'], dietary:['non-vegetarian','chicken'], health_tags:['protein'], occasion:['party','guest'], season:['all'], ingredients_main:['chicken','yogurt','cashew','cream','cardamom','mace','saffron'], description:'Chicken in Mughlai cream sauce — milder than mutton korma, the default Mughlai party chicken, aromatic with whole spices' },
{ name:'Rezala', name_hindi:'रेज़ाला', cuisine:['Mughlai'], meal_type:['dinner'], dietary:['non-vegetarian','mutton'], health_tags:['protein','revival'], occasion:['Eid','wedding'], season:['winter'], ingredients_main:['mutton','yogurt','white pepper','ghee','poppy seeds','cardamom','rose water'], description:'White mutton curry — no chilli, white from yogurt-poppy seed base, delicate and aromatic, Nawabi court dish being revived' },
{ name:'Dum ka Murgh', name_hindi:'दम का मुर्ग़', cuisine:['Mughlai','Lucknowi'], meal_type:['dinner'], dietary:['non-vegetarian','chicken'], health_tags:['protein'], occasion:['party','Eid'], season:['all'], ingredients_main:['whole chicken','yogurt','saffron','whole spices','kewra','fried onion','ghee'], description:'Whole chicken on dum — sealed pot slow-cooking, the chicken steams in its own juices with Mughlai aromatics' },
{ name:'Murgh Musallam', name_hindi:'मुर्ग़ मुसल्लम', cuisine:['Mughlai'], meal_type:['dinner'], dietary:['non-vegetarian','chicken'], health_tags:['protein','celebration'], occasion:['wedding','Eid'], season:['all'], ingredients_main:['whole chicken','boiled eggs','cashew','cream','saffron','whole spices','ghee'], description:'Whole stuffed chicken — the ultimate Mughlai presentation, stuffed with eggs, in rich cream sauce, Eid and wedding grandeur' },
{ name:'Shahi Murgh', cuisine:['Mughlai'], meal_type:['dinner'], dietary:['non-vegetarian','chicken'], health_tags:['protein','rich'], occasion:['party'], season:['all'], ingredients_main:['chicken','cashew','cream','almonds','saffron','cardamom','mace'], description:'Royal chicken — cream-nut gravy, Mughlai richness at full volume, every spice measured, saffron threads visible' },
{ name:'Nihari Lucknowi', name_hindi:'निहारी', cuisine:['Mughlai','Lucknowi'], meal_type:['breakfast','dinner'], dietary:['non-vegetarian','mutton'], health_tags:['protein','iron','energy'], occasion:['winter','Ramadan'], season:['winter'], ingredients_main:['mutton shanks','wheat flour','ginger','green chilli','lime','fried onion'], description:'Slow-cooked bone marrow stew — eaten at dawn in Old Lucknow, overnight slow-cook extracts every bit of flavour from bones' },
{ name:'Nalli Nihari', name_hindi:'नल्ली निहारी', cuisine:['Mughlai','Delhi'], meal_type:['breakfast','dinner'], dietary:['non-vegetarian','mutton'], health_tags:['protein','collagen'], occasion:['winter','Eid'], season:['winter'], ingredients_main:['mutton shank with bone','wheat flour','ginger','whole spices','lime','coriander'], description:'Bone marrow nihari — the marrow oozes out of cracked bones, Delhi Jama Masjid area dawn food, rich collagen' },
// ═══ BREADS (10) ═══
{ name:'Sheermal Lucknowi', name_hindi:'शीरमाल', cuisine:['Awadhi','Lucknowi'], meal_type:['dinner'], dietary:['vegetarian'], health_tags:['energy'], occasion:['festive','Eid'], season:['all'], ingredients_main:['maida','milk','saffron','sugar','ghee','cardamom','yeast'], description:'Saffron-laced sweet bread — baked in tandoor, Lucknow Nawabi bread, fragrant yellow from saffron, pairs with korma' },
{ name:'Warqi Paratha', name_hindi:'वर्क़ी पराठा', cuisine:['Mughlai','Lucknowi'], meal_type:['dinner'], dietary:['vegetarian'], health_tags:['energy'], occasion:['festive'], season:['all'], ingredients_main:['maida','ghee','salt'], description:'Layered flaky bread — paper-thin layers separated by ghee, Mughlai version of laccha paratha, more delicate' },
{ name:'Roomali Roti', name_hindi:'रूमाली रोटी', cuisine:['Mughlai'], meal_type:['dinner'], dietary:['vegetarian'], health_tags:['light'], occasion:['restaurant','party'], season:['all'], ingredients_main:['maida','wheat flour','oil','milk'], description:'Handkerchief-thin bread — tossed in the air like pizza to stretch, so thin you can see through it, folded like a handkerchief' },
{ name:'Bakarkhani', name_hindi:'बाक़रख़ानी', cuisine:['Mughlai','Lucknowi'], meal_type:['breakfast','dinner'], dietary:['vegetarian'], health_tags:['energy','revival'], occasion:['Eid'], season:['all'], ingredients_main:['maida','ghee','milk','sugar','saffron','sesame','poppy seeds'], description:'Thick flaky biscuit bread — Mughal-era bread being revived, semi-sweet, layered and baked, Eid morning with nihari' },
{ name:'Taftan', name_hindi:'ताफ़तान', cuisine:['Mughlai'], meal_type:['dinner'], dietary:['vegetarian'], health_tags:['energy'], occasion:['Eid','party'], season:['all'], ingredients_main:['maida','milk','yogurt','saffron','sugar','ghee','egg'], description:'Saffron leavened bread — softer than naan, slightly sweet, baked in tandoor, Mughlai feast bread' },
// ═══ DESSERTS & DRINKS (20) ═══
{ name:'Shahi Tukda', name_hindi:'शाही टुकड़ा', cuisine:['Mughlai','Lucknowi'], meal_type:['dessert'], dietary:['vegetarian'], health_tags:['rich'], occasion:['Eid','wedding'], season:['all'], ingredients_main:['bread','ghee','sugar syrup','milk','saffron','cardamom','pistachios','almonds'], description:'Royal bread pudding — fried bread soaked in saffron milk and syrup, Lucknow Eid dessert, each layer adds richness' },
{ name:'Phirni Mughlai', name_hindi:'फ़िरनी', cuisine:['Mughlai'], meal_type:['dessert'], dietary:['vegetarian'], health_tags:['comfort'], occasion:['Eid','everyday'], season:['all'], ingredients_main:['ground rice','milk','sugar','cardamom','saffron','pistachios'], description:'Ground rice pudding in clay cup — set cold, the clay absorbs moisture giving perfect texture, Mughlai Eid essential' },
{ name:'Badam Halwa', name_hindi:'बादाम हलवा', cuisine:['Mughlai'], meal_type:['dessert'], dietary:['vegetarian'], health_tags:['protein','rich'], occasion:['festive','winter'], season:['winter'], ingredients_main:['almonds','ghee','sugar','saffron','cardamom','milk'], description:'Almond fudge — blanched almonds ground and slow-cooked in ghee, intensely rich, Mughlai winter sweet' },
{ name:'Lauz', name_hindi:'लौज़', cuisine:['Mughlai','Lucknowi'], meal_type:['dessert'], dietary:['vegetarian'], health_tags:['protein','revival'], occasion:['festive'], season:['all'], ingredients_main:['almonds','sugar','rose water','cardamom','silver leaf'], description:'Almond marzipan sweet — Lucknowi confection, ground almonds set with sugar, cut into diamonds, being revived' },
{ name:'Sohan Halwa', name_hindi:'सोहन हलवा', cuisine:['Mughlai'], meal_type:['dessert'], dietary:['vegetarian'], health_tags:['energy'], occasion:['festive'], season:['all'], ingredients_main:['wheat flour','ghee','sugar','milk','saffron','almonds','pistachios'], description:'Dense layered fudge — Mughlai tradition, slow-cooked until it sets into chewy layers, Ajmer and Multan famous' },
{ name:'Khubani ka Meetha', name_hindi:'खुबानी का मीठा', cuisine:['Mughlai','Hyderabad'], meal_type:['dessert'], dietary:['vegetarian'], health_tags:['celebration'], occasion:['Eid','wedding'], season:['all'], ingredients_main:['dried apricots','sugar','cream','almonds','cardamom'], description:'Stewed apricot dessert — Hyderabadi Nizam sweet, dried apricots slow-cooked until silky, topped with cream and ice cream' },
{ name:'Kulfi Malai', name_hindi:'मलाई कुल्फ़ी', cuisine:['Mughlai'], meal_type:['dessert'], dietary:['vegetarian'], health_tags:['calcium'], occasion:['summer','everyday'], season:['summer'], ingredients_main:['milk','sugar','cardamom','saffron','pistachios','almonds'], description:'Dense Indian ice cream — slow-reduced milk frozen in moulds, denser than Western ice cream, no air whipped in' },
{ name:'Falooda Mughlai', name_hindi:'फ़ालूदा', cuisine:['Mughlai'], meal_type:['dessert'], dietary:['vegetarian'], health_tags:['cooling'], occasion:['summer'], season:['summer'], ingredients_main:['falooda sev','rose syrup','basil seeds','milk','ice cream','pistachios'], description:'Rose milk dessert drink — layers of falooda noodles, rose syrup, basil seeds, milk and ice cream, Mughlai summer indulgence' },
{ name:'Thandai Mughlai', name_hindi:'ठंडाई', cuisine:['Mughlai'], meal_type:['snack'], dietary:['vegetarian'], health_tags:['cooling','festive'], occasion:['Holi','summer'], season:['summer'], ingredients_main:['milk','almonds','cashew','fennel','melon seeds','saffron','rose petals','black pepper'], description:'Spiced nut milk — Holi and Shivratri drink, stone-ground nut paste in cold milk, traditionally with bhang on Holi' },
{ name:'Kewra Sharbat', cuisine:['Awadhi','Lucknowi'], meal_type:['snack'], dietary:['vegetarian'], health_tags:['cooling','revival'], occasion:['summer','Eid'], season:['summer'], ingredients_main:['kewra water','sugar','lime','ice'], description:'Pandanus flower water — Lucknow summer cooler, delicate floral fragrance, served at Nawabi iftars, being revived' },
{ name:'Rose Sharbat Mughlai', cuisine:['Mughlai'], meal_type:['snack'], dietary:['vegetarian'], health_tags:['cooling'], occasion:['summer','wedding'], season:['summer'], ingredients_main:['rose water','sugar','lime','basil seeds','ice'], description:'Rose water drink — Mughlai summer essential, pink and fragrant, served at every Muslim wedding and Eid gathering' },
];
