/**
 * Seed script: 150+ authentic Indian dishes for RAG.
 * Run via: npx ts-node scripts/seed-dishes.ts
 * OR import dishData from this file and insert via Supabase client.
 */

interface DishSeed {
  name: string;
  name_hindi?: string;
  name_regional?: string;
  cuisine: string[];
  meal_type: string[];
  dietary: string[];
  health_tags: string[];
  occasion: string[];
  season: string[];
  ingredients_main: string[];
  description: string;
}

export const DISH_DATA: DishSeed[] = [
  // ─── BREAKFAST (30) ─────────────────────────────────────────────────────
  { name:'Poha', name_hindi:'पोहा', cuisine:['Maharashtrian','Gujarati'], meal_type:['breakfast'], dietary:['vegetarian'], health_tags:['light','iron'], occasion:['everyday'], season:['all'], ingredients_main:['flattened rice','onion','peanuts','turmeric','mustard seeds'], description:'Light beaten rice with peanuts and turmeric' },
  { name:'Upma', name_hindi:'उपमा', cuisine:['South Indian','Maharashtrian'], meal_type:['breakfast'], dietary:['vegetarian'], health_tags:['light','fibre'], occasion:['everyday'], season:['all'], ingredients_main:['semolina','mustard seeds','curry leaves','vegetables'], description:'Semolina porridge with vegetables' },
  { name:'Idli Sambhar', name_hindi:'इडली सांभर', cuisine:['South Indian','Tamil'], meal_type:['breakfast'], dietary:['vegetarian'], health_tags:['protein','probiotic'], occasion:['everyday'], season:['all'], ingredients_main:['rice batter','urad dal','toor dal','vegetables'], description:'Steamed rice cakes with lentil soup' },
  { name:'Masala Dosa', name_hindi:'मसाला डोसा', cuisine:['South Indian','Kerala'], meal_type:['breakfast'], dietary:['vegetarian'], health_tags:['probiotic','iron'], occasion:['everyday','weekend'], season:['all'], ingredients_main:['rice batter','potato','onion','mustard seeds'], description:'Crispy rice crepe with spiced potato filling' },
  { name:'Methi Thepla', name_hindi:'मेथी थेपला', cuisine:['Gujarati'], meal_type:['breakfast'], dietary:['vegetarian'], health_tags:['iron','fibre'], occasion:['everyday','travel'], season:['winter'], ingredients_main:['wheat flour','fenugreek leaves','yogurt','spices'], description:'Fenugreek flatbread from Gujarat' },
  { name:'Aloo Paratha', name_hindi:'आलू पराठा', cuisine:['Punjabi'], meal_type:['breakfast'], dietary:['vegetarian'], health_tags:['energy','carbs'], occasion:['everyday'], season:['winter'], ingredients_main:['wheat flour','potato','green chilli','cumin'], description:'Stuffed potato flatbread with butter' },
  { name:'Sabudana Khichdi', name_hindi:'साबूदाणा खिचडी', cuisine:['Maharashtrian'], meal_type:['breakfast'], dietary:['vegetarian'], health_tags:['fasting','energy'], occasion:['fasting','everyday'], season:['all'], ingredients_main:['sago pearls','peanuts','potato','cumin'], description:'Tapioca pearl pilaf for fasting days' },
  { name:'Puri Bhaji', name_hindi:'पूरी भाजी', cuisine:['Maharashtrian','Punjabi'], meal_type:['breakfast'], dietary:['vegetarian'], health_tags:['energy'], occasion:['weekend','festival'], season:['all'], ingredients_main:['wheat flour','potato','oil','spices'], description:'Deep-fried bread with spiced potato curry' },
  { name:'Chole Bhature', name_hindi:'छोले भटूरे', cuisine:['Punjabi'], meal_type:['breakfast','lunch'], dietary:['vegetarian'], health_tags:['protein','energy'], occasion:['weekend','festival'], season:['winter'], ingredients_main:['chickpeas','maida','yogurt','spices'], description:'Spiced chickpea curry with fried bread' },
  { name:'Rava Dosa', name_hindi:'रवा डोसा', cuisine:['South Indian'], meal_type:['breakfast'], dietary:['vegetarian'], health_tags:['light'], occasion:['everyday'], season:['all'], ingredients_main:['semolina','rice flour','cashew','cumin'], description:'Crispy semolina crepe' },
  { name:'Moong Dal Cheela', name_hindi:'मूंग दाल चीला', cuisine:['Rajasthani','Punjabi'], meal_type:['breakfast'], dietary:['vegetarian'], health_tags:['protein','light'], occasion:['everyday'], season:['all'], ingredients_main:['moong dal','ginger','green chilli','cumin'], description:'Savoury moong lentil pancake' },
  { name:'Appam with Stew', name_hindi:'अप्पम', name_regional:'Appam', cuisine:['Kerala'], meal_type:['breakfast'], dietary:['vegetarian'], health_tags:['probiotic'], occasion:['everyday'], season:['all'], ingredients_main:['rice flour','coconut milk','yeast','vegetables'], description:'Lacy rice pancake with coconut vegetable stew' },
  { name:'Puttu Kadala', name_regional:'Puttu', cuisine:['Kerala'], meal_type:['breakfast'], dietary:['vegetarian'], health_tags:['fibre','protein'], occasion:['everyday'], season:['all'], ingredients_main:['rice flour','coconut','black chickpea'], description:'Steamed rice cylinders with black chickpea curry' },
  { name:'Kanda Bhaji', name_hindi:'कांदा भजी', cuisine:['Maharashtrian'], meal_type:['breakfast','snack'], dietary:['vegetarian'], health_tags:['comfort'], occasion:['rainy day'], season:['monsoon'], ingredients_main:['onion','gram flour','spices','oil'], description:'Crispy onion fritters' },
  { name:'Gobi Paratha', name_hindi:'गोभी पराठा', cuisine:['Punjabi'], meal_type:['breakfast'], dietary:['vegetarian'], health_tags:['fibre'], occasion:['everyday'], season:['winter'], ingredients_main:['wheat flour','cauliflower','green chilli','spices'], description:'Cauliflower stuffed flatbread' },
  { name:'Pesarattu', name_regional:'Pesarattu', cuisine:['Telugu','Andhra'], meal_type:['breakfast'], dietary:['vegetarian'], health_tags:['protein','iron'], occasion:['everyday'], season:['all'], ingredients_main:['whole moong','rice','ginger','green chilli'], description:'Green gram dosa from Andhra' },
  { name:'Misal Pav', name_hindi:'मिसळ पाव', cuisine:['Maharashtrian'], meal_type:['breakfast'], dietary:['vegetarian'], health_tags:['protein','spicy'], occasion:['everyday'], season:['all'], ingredients_main:['sprouted moth beans','farsan','pav','onion'], description:'Spicy sprouted bean curry with bread' },
  { name:'Anda Bhurji', name_hindi:'अंडा भुर्जी', cuisine:['Maharashtrian','Punjabi'], meal_type:['breakfast'], dietary:['non-vegetarian','egg'], health_tags:['protein'], occasion:['everyday'], season:['all'], ingredients_main:['eggs','onion','tomato','green chilli'], description:'Spiced scrambled eggs Indian style' },
  { name:'Pongal', name_regional:'Ven Pongal', cuisine:['Tamil','South Indian'], meal_type:['breakfast'], dietary:['vegetarian'], health_tags:['comfort','protein'], occasion:['everyday','festival'], season:['all'], ingredients_main:['rice','moong dal','pepper','ghee','cashew'], description:'Comforting rice-lentil porridge with ghee' },
  { name:'Paneer Paratha', name_hindi:'पनीर पराठा', cuisine:['Punjabi'], meal_type:['breakfast'], dietary:['vegetarian'], health_tags:['protein','calcium'], occasion:['weekend'], season:['winter'], ingredients_main:['wheat flour','paneer','green chilli','spices'], description:'Cottage cheese stuffed flatbread' },

  // ─── LUNCH (50) ─────────────────────────────────────────────────────────
  { name:'Dal Makhani', name_hindi:'दाल मखनी', cuisine:['Punjabi','Mughlai'], meal_type:['lunch','dinner'], dietary:['vegetarian'], health_tags:['protein','iron'], occasion:['everyday','festival'], season:['winter'], ingredients_main:['black urad dal','butter','cream','tomato','spices'], description:'Slow-cooked black lentils in butter gravy' },
  { name:'Rajma Chawal', name_hindi:'राजमा चावल', cuisine:['Punjabi'], meal_type:['lunch'], dietary:['vegetarian'], health_tags:['protein','iron','fibre'], occasion:['everyday'], season:['all'], ingredients_main:['kidney beans','rice','onion','tomato','spices'], description:'Kidney bean curry with steamed rice' },
  { name:'Palak Paneer', name_hindi:'पालक पनीर', cuisine:['Punjabi'], meal_type:['lunch','dinner'], dietary:['vegetarian'], health_tags:['iron','calcium','protein'], occasion:['everyday'], season:['winter'], ingredients_main:['spinach','paneer','onion','garlic','cream'], description:'Spinach and cottage cheese curry' },
  { name:'Kadhi Chawal', name_hindi:'कढ़ी चावल', cuisine:['Punjabi','Rajasthani','Gujarati'], meal_type:['lunch'], dietary:['vegetarian'], health_tags:['probiotic','light'], occasion:['everyday'], season:['monsoon'], ingredients_main:['yogurt','gram flour','rice','turmeric'], description:'Yogurt-gram flour curry with rice' },
  { name:'Bhindi Masala', name_hindi:'भिंडी मसाला', cuisine:['Punjabi','Maharashtrian'], meal_type:['lunch','dinner'], dietary:['vegetarian'], health_tags:['fibre'], occasion:['everyday'], season:['summer'], ingredients_main:['okra','onion','tomato','spices'], description:'Spiced okra dry fry' },
  { name:'Aloo Gobi', name_hindi:'आलू गोभी', cuisine:['Punjabi'], meal_type:['lunch','dinner'], dietary:['vegetarian'], health_tags:['fibre','vitamin C'], occasion:['everyday'], season:['winter'], ingredients_main:['potato','cauliflower','turmeric','cumin'], description:'Potato and cauliflower dry curry' },
  { name:'Chole Masala', name_hindi:'छोले मसाला', cuisine:['Punjabi'], meal_type:['lunch'], dietary:['vegetarian'], health_tags:['protein','fibre'], occasion:['everyday'], season:['all'], ingredients_main:['chickpeas','onion','tomato','chole masala'], description:'Spiced chickpea curry' },
  { name:'Pav Bhaji', name_hindi:'पाव भाजी', cuisine:['Maharashtrian'], meal_type:['lunch','dinner'], dietary:['vegetarian'], health_tags:['comfort'], occasion:['everyday','street food'], season:['all'], ingredients_main:['mixed vegetables','pav bread','butter','spices'], description:'Mashed vegetable curry with buttered bread' },
  { name:'Sambhar Rice', name_hindi:'सांभर राइस', cuisine:['South Indian','Tamil'], meal_type:['lunch'], dietary:['vegetarian'], health_tags:['protein','fibre'], occasion:['everyday'], season:['all'], ingredients_main:['toor dal','vegetables','tamarind','rice','sambhar powder'], description:'Lentil-vegetable stew with rice' },
  { name:'Rasam Rice', name_hindi:'रसम चावल', cuisine:['South Indian','Tamil'], meal_type:['lunch'], dietary:['vegetarian'], health_tags:['digestive','immunity'], occasion:['everyday'], season:['monsoon','winter'], ingredients_main:['tamarind','tomato','pepper','cumin','rice'], description:'Tangy pepper-tamarind soup with rice' },
  { name:'Baingan Bharta', name_hindi:'बैंगन भर्ता', cuisine:['Punjabi'], meal_type:['lunch','dinner'], dietary:['vegetarian'], health_tags:['fibre'], occasion:['everyday'], season:['winter'], ingredients_main:['aubergine','onion','tomato','green chilli'], description:'Smoky mashed aubergine' },
  { name:'Jeera Rice with Dal Tadka', name_hindi:'जीरा राइस दाल तड़का', cuisine:['Punjabi','Gujarati'], meal_type:['lunch'], dietary:['vegetarian'], health_tags:['protein','comfort'], occasion:['everyday'], season:['all'], ingredients_main:['rice','cumin','toor dal','ghee','garlic'], description:'Cumin rice with tempered lentils' },
  { name:'Matar Paneer', name_hindi:'मटर पनीर', cuisine:['Punjabi','Mughlai'], meal_type:['lunch','dinner'], dietary:['vegetarian'], health_tags:['protein','calcium'], occasion:['everyday'], season:['winter'], ingredients_main:['green peas','paneer','onion','tomato','cream'], description:'Cottage cheese and peas in tomato gravy' },
  { name:'Undhiyu', name_hindi:'उंधियू', name_regional:'Undhiyu', cuisine:['Gujarati'], meal_type:['lunch'], dietary:['vegetarian'], health_tags:['fibre','seasonal'], occasion:['winter','festival'], season:['winter'], ingredients_main:['surti papdi','purple yam','brinjal','methi muthiya'], description:'Mixed winter vegetable casserole from Gujarat' },
  { name:'Varan Bhaat', name_hindi:'वरण भात', cuisine:['Maharashtrian'], meal_type:['lunch'], dietary:['vegetarian'], health_tags:['comfort','protein'], occasion:['everyday'], season:['all'], ingredients_main:['toor dal','rice','ghee','turmeric'], description:'Plain dal-rice, Maharashtrian comfort staple' },
  { name:'Chicken Curry', name_hindi:'चिकन करी', cuisine:['Punjabi','Mughlai'], meal_type:['lunch','dinner'], dietary:['non-vegetarian','chicken'], health_tags:['protein'], occasion:['everyday'], season:['all'], ingredients_main:['chicken','onion','tomato','ginger-garlic','spices'], description:'Home-style chicken curry' },
  { name:'Butter Chicken', name_hindi:'बटर चिकन', cuisine:['Punjabi','Mughlai'], meal_type:['lunch','dinner'], dietary:['non-vegetarian','chicken'], health_tags:['protein'], occasion:['weekend','party'], season:['all'], ingredients_main:['chicken','butter','cream','tomato','kasuri methi'], description:'Creamy tomato chicken — iconic Punjabi dish' },
  { name:'Goan Fish Curry', name_regional:'Xitt Kodi', cuisine:['Goan'], meal_type:['lunch','dinner'], dietary:['non-vegetarian','fish'], health_tags:['protein','omega-3'], occasion:['everyday'], season:['all'], ingredients_main:['fish','coconut','tamarind','kokum','red chilli'], description:'Tangy coconut fish curry from Goa' },
  { name:'Mutton Rogan Josh', name_hindi:'मटन रोगन जोश', cuisine:['Kashmiri','Mughlai'], meal_type:['lunch','dinner'], dietary:['non-vegetarian','mutton'], health_tags:['protein','iron'], occasion:['weekend','festival'], season:['winter'], ingredients_main:['mutton','Kashmiri chilli','fennel','yogurt','saffron'], description:'Kashmiri slow-cooked lamb in aromatic gravy' },
  { name:'Egg Curry', name_hindi:'अंडा करी', cuisine:['Bengali','South Indian'], meal_type:['lunch','dinner'], dietary:['non-vegetarian','egg'], health_tags:['protein'], occasion:['everyday'], season:['all'], ingredients_main:['eggs','onion','tomato','spices'], description:'Boiled eggs in spiced onion-tomato gravy' },
  { name:'Macher Jhol', name_hindi:'माछेर झोल', name_regional:'Macher Jhol', cuisine:['Bengali'], meal_type:['lunch'], dietary:['non-vegetarian','fish'], health_tags:['protein','omega-3'], occasion:['everyday'], season:['all'], ingredients_main:['rohu fish','potato','tomato','turmeric','mustard oil'], description:'Bengali light fish curry' },
  { name:'Kosha Mangsho', name_regional:'Kosha Mangsho', cuisine:['Bengali'], meal_type:['lunch','dinner'], dietary:['non-vegetarian','mutton'], health_tags:['protein','iron'], occasion:['weekend','festival'], season:['winter'], ingredients_main:['mutton','onion','yogurt','whole spices','mustard oil'], description:'Bengali slow-cooked spiced mutton' },
  { name:'Prawn Masala', name_hindi:'प्रॉन मसाला', cuisine:['Goan','Mangalorean','Kerala'], meal_type:['lunch','dinner'], dietary:['non-vegetarian','fish'], health_tags:['protein','omega-3'], occasion:['everyday'], season:['all'], ingredients_main:['prawns','coconut','onion','tomato','curry leaves'], description:'Spiced prawn curry in coconut gravy' },
  { name:'Keema Matar', name_hindi:'कीमा मटर', cuisine:['Mughlai','Punjabi'], meal_type:['lunch','dinner'], dietary:['non-vegetarian','mutton'], health_tags:['protein','iron'], occasion:['everyday'], season:['winter'], ingredients_main:['minced mutton','green peas','onion','ginger-garlic'], description:'Minced meat with green peas' },
  { name:'Chicken Biryani', name_hindi:'चिकन बिर्यानी', cuisine:['Hyderabadi','Mughlai'], meal_type:['lunch','dinner'], dietary:['non-vegetarian','chicken'], health_tags:['protein','energy'], occasion:['weekend','party','festival'], season:['all'], ingredients_main:['chicken','basmati rice','saffron','fried onion','whole spices'], description:'Layered chicken and rice, Hyderabadi style' },
  { name:'Veg Biryani', name_hindi:'वेज बिर्यानी', cuisine:['Hyderabadi'], meal_type:['lunch','dinner'], dietary:['vegetarian'], health_tags:['energy'], occasion:['weekend','party'], season:['all'], ingredients_main:['basmati rice','mixed vegetables','saffron','fried onion','whole spices'], description:'Aromatic vegetable layered rice' },
  { name:'Dal Fry', name_hindi:'दाल फ्राई', cuisine:['Punjabi'], meal_type:['lunch','dinner'], dietary:['vegetarian'], health_tags:['protein','iron'], occasion:['everyday'], season:['all'], ingredients_main:['toor dal','onion','tomato','cumin','ghee'], description:'Tempered yellow lentils' },
  { name:'Aloo Matar', name_hindi:'आलू मटर', cuisine:['Punjabi'], meal_type:['lunch','dinner'], dietary:['vegetarian'], health_tags:['energy'], occasion:['everyday'], season:['winter'], ingredients_main:['potato','green peas','onion','tomato','spices'], description:'Potato and peas curry' },
  { name:'Tinda Masala', name_hindi:'टिंडा मसाला', cuisine:['Punjabi','Sindhi'], meal_type:['lunch'], dietary:['vegetarian'], health_tags:['light','fibre'], occasion:['everyday'], season:['summer'], ingredients_main:['tinda','onion','tomato','spices'], description:'Apple gourd in spiced gravy' },
  { name:'Lauki Chana Dal', name_hindi:'लौकी चना दाल', cuisine:['Punjabi','Rajasthani'], meal_type:['lunch'], dietary:['vegetarian'], health_tags:['light','diabetic-friendly'], occasion:['everyday'], season:['summer'], ingredients_main:['bottle gourd','chana dal','tomato','cumin'], description:'Bottle gourd with split gram lentils' },

  // ─── DINNER (40) ────────────────────────────────────────────────────────
  { name:'Paneer Butter Masala', name_hindi:'पनीर बटर मसाला', cuisine:['Punjabi','Mughlai'], meal_type:['dinner','lunch'], dietary:['vegetarian'], health_tags:['protein','calcium'], occasion:['weekend','party'], season:['all'], ingredients_main:['paneer','butter','cream','tomato','kasuri methi'], description:'Rich tomato-cream cottage cheese curry' },
  { name:'Malvani Fish Curry', name_regional:'Malvani', cuisine:['Malvani','Maharashtrian'], meal_type:['dinner','lunch'], dietary:['non-vegetarian','fish'], health_tags:['protein','omega-3'], occasion:['everyday'], season:['all'], ingredients_main:['fish','coconut','kokum','red chilli','coriander'], description:'Spicy Konkan coast fish curry' },
  { name:'Kali Mirch Chicken', name_hindi:'काली मिर्च चिकन', cuisine:['Mughlai'], meal_type:['dinner'], dietary:['non-vegetarian','chicken'], health_tags:['protein'], occasion:['everyday'], season:['winter'], ingredients_main:['chicken','black pepper','yogurt','cream'], description:'Black pepper chicken in creamy sauce' },
  { name:'Dal Palak', name_hindi:'दाल पालक', cuisine:['Punjabi'], meal_type:['dinner','lunch'], dietary:['vegetarian'], health_tags:['iron','protein'], occasion:['everyday'], season:['winter'], ingredients_main:['toor dal','spinach','garlic','cumin','ghee'], description:'Lentils with spinach' },
  { name:'Paneer Tikka Masala', name_hindi:'पनीर टिक्का मसाला', cuisine:['Punjabi'], meal_type:['dinner'], dietary:['vegetarian'], health_tags:['protein','calcium'], occasion:['weekend'], season:['all'], ingredients_main:['paneer','bell pepper','onion','yogurt','spices'], description:'Grilled paneer cubes in spiced gravy' },
  { name:'Chicken Tikka Masala', name_hindi:'चिकन टिक्का मसाला', cuisine:['Punjabi','Mughlai'], meal_type:['dinner'], dietary:['non-vegetarian','chicken'], health_tags:['protein'], occasion:['weekend','party'], season:['all'], ingredients_main:['chicken','yogurt','bell pepper','tomato','cream'], description:'Grilled chicken in rich masala gravy' },
  { name:'Lamb Korma', name_hindi:'लैम्ब कोरमा', cuisine:['Mughlai'], meal_type:['dinner'], dietary:['non-vegetarian','mutton'], health_tags:['protein'], occasion:['party','festival'], season:['winter'], ingredients_main:['lamb','cashew','yogurt','saffron','cream'], description:'Lamb in rich cashew-yogurt sauce' },
  { name:'Shahi Paneer', name_hindi:'शाही पनीर', cuisine:['Mughlai'], meal_type:['dinner'], dietary:['vegetarian'], health_tags:['protein','calcium'], occasion:['party','festival'], season:['all'], ingredients_main:['paneer','cashew','cream','saffron','spices'], description:'Royal cottage cheese in cashew cream' },
  { name:'Methi Matar Malai', name_hindi:'मेथी मटर मलाई', cuisine:['Punjabi','Mughlai'], meal_type:['dinner'], dietary:['vegetarian'], health_tags:['iron','protein'], occasion:['everyday'], season:['winter'], ingredients_main:['fenugreek leaves','green peas','cream','cashew'], description:'Fenugreek and peas in creamy sauce' },
  { name:'Fish Fry', name_hindi:'फिश फ्राई', cuisine:['Goan','Bengali','Mangalorean'], meal_type:['dinner','snack'], dietary:['non-vegetarian','fish'], health_tags:['protein','omega-3'], occasion:['everyday'], season:['all'], ingredients_main:['fish','semolina','turmeric','chilli','lemon'], description:'Crispy pan-fried spiced fish' },
  { name:'Tawa Chicken', name_hindi:'तवा चिकन', cuisine:['Maharashtrian','Punjabi'], meal_type:['dinner'], dietary:['non-vegetarian','chicken'], health_tags:['protein'], occasion:['everyday'], season:['all'], ingredients_main:['chicken','onion','bell pepper','spices'], description:'Griddle-cooked spicy chicken' },
  { name:'Dum Aloo', name_hindi:'दम आलू', cuisine:['Kashmiri','Punjabi'], meal_type:['dinner','lunch'], dietary:['vegetarian'], health_tags:['comfort'], occasion:['everyday'], season:['winter'], ingredients_main:['baby potato','yogurt','fennel','ginger','Kashmiri chilli'], description:'Slow-cooked baby potatoes in spiced gravy' },
  { name:'Chana Masala', name_hindi:'चना मसाला', cuisine:['Punjabi'], meal_type:['dinner','lunch'], dietary:['vegetarian'], health_tags:['protein','fibre'], occasion:['everyday'], season:['all'], ingredients_main:['chickpeas','onion','tomato','amchur','spices'], description:'Tangy spiced chickpea curry' },
  { name:'Mixed Veg Sabzi', name_hindi:'मिक्स वेज सब्ज़ी', cuisine:['Punjabi'], meal_type:['dinner','lunch'], dietary:['vegetarian'], health_tags:['fibre','vitamins'], occasion:['everyday'], season:['all'], ingredients_main:['mixed vegetables','onion','tomato','spices'], description:'Medley of seasonal vegetables' },

  // ─── SNACK (15) ─────────────────────────────────────────────────────────
  { name:'Samosa', name_hindi:'समोसा', cuisine:['Punjabi','Rajasthani'], meal_type:['snack'], dietary:['vegetarian'], health_tags:['comfort'], occasion:['everyday','tea time'], season:['all'], ingredients_main:['potato','peas','maida','cumin','oil'], description:'Crispy pastry triangle with spiced potato filling' },
  { name:'Pakora', name_hindi:'पकोड़ा', cuisine:['Punjabi','Rajasthani'], meal_type:['snack'], dietary:['vegetarian'], health_tags:['comfort'], occasion:['rainy day','tea time'], season:['monsoon'], ingredients_main:['gram flour','onion','spinach','spices','oil'], description:'Assorted vegetable fritters' },
  { name:'Vada Pav', name_hindi:'वड़ा पाव', cuisine:['Maharashtrian'], meal_type:['snack'], dietary:['vegetarian'], health_tags:['energy'], occasion:['street food','everyday'], season:['all'], ingredients_main:['potato','gram flour','pav','garlic chutney'], description:'Mumbai spiced potato fritter in bread roll' },
  { name:'Dhokla', name_hindi:'ढोकला', cuisine:['Gujarati'], meal_type:['snack','breakfast'], dietary:['vegetarian'], health_tags:['light','probiotic'], occasion:['everyday','tea time'], season:['all'], ingredients_main:['gram flour','yogurt','mustard seeds','curry leaves'], description:'Steamed savoury gram flour cake' },
  { name:'Khandvi', name_hindi:'खांडवी', cuisine:['Gujarati'], meal_type:['snack'], dietary:['vegetarian'], health_tags:['light'], occasion:['festival','tea time'], season:['all'], ingredients_main:['gram flour','yogurt','coconut','mustard seeds'], description:'Rolled gram flour savoury from Gujarat' },
  { name:'Pani Puri', name_hindi:'पानी पूरी', cuisine:['Maharashtrian','Gujarati'], meal_type:['snack'], dietary:['vegetarian'], health_tags:['light'], occasion:['street food'], season:['summer'], ingredients_main:['semolina puris','potato','chickpea','tamarind water','mint water'], description:'Hollow crispy puris with tangy water' },
  { name:'Bhel Puri', name_hindi:'भेल पूरी', cuisine:['Maharashtrian'], meal_type:['snack'], dietary:['vegetarian'], health_tags:['light'], occasion:['street food','evening'], season:['all'], ingredients_main:['puffed rice','sev','onion','coriander','tamarind chutney'], description:'Mumbai puffed rice chaat' },
  { name:'Dahi Vada', name_hindi:'दही वड़ा', cuisine:['Punjabi','Maharashtrian'], meal_type:['snack'], dietary:['vegetarian'], health_tags:['probiotic'], occasion:['festival','everyday'], season:['summer'], ingredients_main:['urad dal','yogurt','tamarind chutney','cumin'], description:'Lentil dumplings in spiced yogurt' },
  { name:'Masala Chai', name_hindi:'मसाला चाय', cuisine:['Punjabi','Gujarati','Maharashtrian'], meal_type:['snack'], dietary:['vegetarian'], health_tags:['antioxidant','comfort'], occasion:['everyday','tea time'], season:['all'], ingredients_main:['tea leaves','milk','ginger','cardamom','sugar'], description:'Indian spiced tea' },
  { name:'Aloo Tikki', name_hindi:'आलू टिक्की', cuisine:['Punjabi'], meal_type:['snack'], dietary:['vegetarian'], health_tags:['comfort'], occasion:['street food','tea time'], season:['winter'], ingredients_main:['potato','green peas','spices','oil'], description:'Crispy spiced potato patties' },

  // ─── DESSERT (15) ───────────────────────────────────────────────────────
  { name:'Gulab Jamun', name_hindi:'गुलाब जामुन', cuisine:['Mughlai','Punjabi'], meal_type:['dessert'], dietary:['vegetarian'], health_tags:['celebration'], occasion:['festival','party'], season:['all'], ingredients_main:['khoya','maida','sugar syrup','cardamom','rose water'], description:'Soft dumplings soaked in rose-scented sugar syrup' },
  { name:'Kheer', name_hindi:'खीर', cuisine:['Punjabi','Bengali'], meal_type:['dessert'], dietary:['vegetarian'], health_tags:['calcium','comfort'], occasion:['festival','everyday'], season:['all'], ingredients_main:['rice','milk','sugar','cardamom','almonds'], description:'Creamy rice pudding with nuts' },
  { name:'Jalebi', name_hindi:'जलेबी', cuisine:['Rajasthani','Mughlai'], meal_type:['dessert','breakfast'], dietary:['vegetarian'], health_tags:['energy'], occasion:['festival'], season:['winter'], ingredients_main:['maida','sugar syrup','saffron','ghee'], description:'Crispy spirals soaked in saffron syrup' },
  { name:'Gajar Halwa', name_hindi:'गाजर का हलवा', cuisine:['Punjabi'], meal_type:['dessert'], dietary:['vegetarian'], health_tags:['vitamin A','comfort'], occasion:['winter','festival'], season:['winter'], ingredients_main:['carrot','milk','sugar','ghee','nuts'], description:'Slow-cooked carrot fudge with nuts' },
  { name:'Rasmalai', name_hindi:'रसमलाई', cuisine:['Bengali'], meal_type:['dessert'], dietary:['vegetarian'], health_tags:['calcium'], occasion:['festival','party'], season:['all'], ingredients_main:['chenna','milk','sugar','cardamom','saffron'], description:'Soft paneer dumplings in sweet saffron milk' },
  { name:'Shrikhand', name_hindi:'श्रीखंड', cuisine:['Maharashtrian','Gujarati'], meal_type:['dessert'], dietary:['vegetarian'], health_tags:['probiotic','calcium'], occasion:['festival','everyday'], season:['summer'], ingredients_main:['hung curd','sugar','saffron','cardamom','nuts'], description:'Sweetened strained yogurt with saffron' },
  { name:'Modak', name_hindi:'मोदक', cuisine:['Maharashtrian'], meal_type:['dessert'], dietary:['vegetarian'], health_tags:['celebration'], occasion:['Ganesh Chaturthi'], season:['monsoon'], ingredients_main:['rice flour','coconut','jaggery','cardamom'], description:'Sweet coconut-jaggery dumplings for Ganesh festival' },
  { name:'Payasam', name_regional:'Payasam', cuisine:['Kerala','South Indian'], meal_type:['dessert'], dietary:['vegetarian'], health_tags:['comfort'], occasion:['festival','Onam'], season:['all'], ingredients_main:['vermicelli','milk','sugar','ghee','cashew'], description:'South Indian sweet milk pudding' },
  { name:'Malpua', name_hindi:'मालपुआ', cuisine:['Bengali','Rajasthani'], meal_type:['dessert'], dietary:['vegetarian'], health_tags:['energy'], occasion:['festival'], season:['winter'], ingredients_main:['maida','milk','sugar syrup','fennel','cardamom'], description:'Sweet fried pancakes in sugar syrup' },
  { name:'Basundi', name_hindi:'बासुंदी', cuisine:['Maharashtrian','Gujarati'], meal_type:['dessert'], dietary:['vegetarian'], health_tags:['calcium'], occasion:['festival'], season:['all'], ingredients_main:['milk','sugar','cardamom','saffron','nuts'], description:'Thick sweetened reduced milk' },
];
