interface DishSeed {
  name: string; name_hindi?: string; name_regional?: string;
  cuisine: string[]; meal_type: string[]; dietary: string[];
  health_tags: string[]; occasion: string[]; season: string[];
  ingredients_main: string[]; description: string;
}

// ═══════════ MALVANI (100+) ═══════════
export const MALVANI_DISHES: DishSeed[] = [
{ name:'Malvani Chicken Curry', name_regional:'मालवणी कोंबडी', cuisine:['Malvani'], meal_type:['lunch','dinner'], dietary:['non-vegetarian','chicken'], health_tags:['protein','spicy'], occasion:['everyday','guest'], season:['all'], ingredients_main:['chicken','Malvani masala','coconut','kokum','onion','garlic'], description:'Konkan coast chicken — the Malvani masala is roasted fresh, coconut-kokum base, served with ukdide tandool (red rice)' },
{ name:'Malvani Fish Curry', name_regional:'मालवणी मासळ्याची आमटी', cuisine:['Malvani'], meal_type:['lunch'], dietary:['non-vegetarian','fish'], health_tags:['protein','omega-3'], occasion:['everyday'], season:['all'], ingredients_main:['fish','coconut','kokum','Malvani masala','garlic','tamarind'], description:'Everyday Malvani fish — coconut-kokum red gravy, the daily lunch in every Sindhudurg household, served with rice' },
{ name:'Malvani Mutton Curry', cuisine:['Malvani'], meal_type:['dinner'], dietary:['non-vegetarian','mutton'], health_tags:['protein','iron'], occasion:['festive','guest'], season:['winter'], ingredients_main:['mutton','Malvani masala','coconut','onion','garlic','kokum'], description:'Konkan mutton — slow-cooked in Malvani spice paste, richer and heavier than the chicken version, weekend special' },
{ name:'Malvani Prawns Masala', name_regional:'कोळंबी मसाला', cuisine:['Malvani'], meal_type:['lunch','dinner'], dietary:['non-vegetarian','fish'], health_tags:['protein','omega-3'], occasion:['everyday'], season:['all'], ingredients_main:['prawns','coconut','Malvani masala','kokum','onion','garlic'], description:'Prawns in Malvani red coconut gravy — quick and flavourful, 20-minute coastal home cooking' },
{ name:'Tisrya Masala Malvani', cuisine:['Malvani'], meal_type:['dinner'], dietary:['non-vegetarian','fish'], health_tags:['protein','iron'], occasion:['guest','monsoon'], season:['monsoon'], ingredients_main:['clams','coconut','garlic','ginger','kokum','red chilli'], description:'Clam masala Malvan style — tiny clams in thick coconut gravy, monsoon seasonal when clams are freshest' },
{ name:'Kube Masala', cuisine:['Malvani'], meal_type:['dinner'], dietary:['non-vegetarian','fish'], health_tags:['protein'], occasion:['guest'], season:['all'], ingredients_main:['oysters','coconut','Malvani masala','garlic','kokum'], description:'Oyster masala — rare Malvani coastal delicacy, oysters in spiced coconut gravy, Vengurla speciality' },
{ name:'Bombil Rassa Malvani', cuisine:['Malvani'], meal_type:['lunch'], dietary:['non-vegetarian','fish'], health_tags:['protein'], occasion:['everyday'], season:['all'], ingredients_main:['Bombay duck','coconut','kokum','garlic','red chilli','turmeric'], description:'Bombay duck in thin Malvani gravy — delicate fish in sour red rassa, Sindhudurg style' },
{ name:'Surmai Fry Malvani', cuisine:['Malvani'], meal_type:['dinner','snack'], dietary:['non-vegetarian','fish'], health_tags:['protein','omega-3'], occasion:['everyday'], season:['all'], ingredients_main:['kingfish','Malvani masala','semolina','turmeric','lemon','oil'], description:'Pan-fried kingfish steaks — Malvani-marinated with the house masala, crispy semolina coating' },
{ name:'Kombdi Vade Malvani', name_regional:'कोंबडी वडे', cuisine:['Malvani'], meal_type:['lunch'], dietary:['non-vegetarian','chicken'], health_tags:['protein','festive'], occasion:['festive','wedding'], season:['all'], ingredients_main:['chicken','Malvani masala','coconut','rice flour','onion','garlic'], description:'Chicken curry with rice flour bread — Malvani feast centrepiece, the vade are crispy rice flour discs soaking up the gravy' },
{ name:'Ukdide Tandool', cuisine:['Malvani'], meal_type:['lunch','dinner'], dietary:['vegetarian'], health_tags:['fibre'], occasion:['everyday'], season:['all'], ingredients_main:['red rice','water','salt'], description:'Boiled red rice — the Malvani daily carb, parboiled red variety unique to Konkan coast, nuttier than white rice' },
{ name:'Malvani Vade', cuisine:['Malvani'], meal_type:['lunch','breakfast'], dietary:['vegetarian'], health_tags:['energy'], occasion:['everyday','festive'], season:['all'], ingredients_main:['rice flour','urad dal','cumin','salt','oil'], description:'Crispy rice flour puri — Malvani bread, crunchier than wheat puri, the vessel for soaking up fish curry' },
{ name:'Malvani Amboli', cuisine:['Malvani'], meal_type:['breakfast'], dietary:['vegetarian'], health_tags:['probiotic'], occasion:['everyday'], season:['all'], ingredients_main:['rice flour','urad dal','coconut','cumin'], description:'Fermented rice pancake — Malvan breakfast, thick and spongy, naturally sour from overnight fermentation' },
{ name:'Sol Kadhi Malvani', cuisine:['Malvani'], meal_type:['lunch'], dietary:['vegetarian'], health_tags:['digestive','cooling'], occasion:['everyday'], season:['summer'], ingredients_main:['kokum','coconut milk','garlic','green chilli','cumin','coriander'], description:'Pink kokum-coconut digestive — Malvani after-meal drink, cooling and tangy, essential summer accompaniment' },
{ name:'Malvani Dal', cuisine:['Malvani'], meal_type:['lunch','dinner'], dietary:['vegetarian'], health_tags:['protein'], occasion:['everyday'], season:['all'], ingredients_main:['toor dal','kokum','coconut','garlic','mustard seeds','curry leaves'], description:'Coconut-kokum lentils — Malvani everyday dal, tangier than Maharashtrian varan, coconut adds richness' },
{ name:'Kaju Curry Malvani', cuisine:['Malvani'], meal_type:['lunch'], dietary:['vegetarian'], health_tags:['protein','rich'], occasion:['festive','guest'], season:['all'], ingredients_main:['cashew','coconut','Malvani masala','kokum','onion'], description:'Cashew nut curry — vegetarian Malvani festive dish, whole cashews in coconut-kokum gravy, rich and creamy' },
{ name:'Phansachi Bhaji', cuisine:['Malvani'], meal_type:['lunch'], dietary:['vegetarian'], health_tags:['fibre'], occasion:['summer'], season:['summer'], ingredients_main:['raw jackfruit','coconut','Malvani masala','onion','garlic'], description:'Raw jackfruit curry — summer seasonal Malvani sabzi, meaty jackfruit in spiced coconut gravy' },
{ name:'Kelphulachi Bhaji', cuisine:['Malvani'], meal_type:['lunch'], dietary:['vegetarian'], health_tags:['fibre','revival'], occasion:['everyday'], season:['monsoon'], ingredients_main:['banana flower','coconut','mustard seeds','turmeric','green chilli'], description:'Banana flower sabzi — forgotten Malvani vegetable being rediscovered, subtle flavour, monsoon seasonal' },
{ name:'Patholi', cuisine:['Malvani'], meal_type:['dessert'], dietary:['vegetarian'], health_tags:['celebration'], occasion:['Ganesh Chaturthi','Nag Panchami'], season:['monsoon'], ingredients_main:['rice flour','coconut','jaggery','cardamom','turmeric leaves'], description:'Sweet rice in turmeric leaves — steamed Malvani sweet wrapped in haldi leaves, monsoon festival special' },
{ name:'Narali Bhat Malvani', cuisine:['Malvani'], meal_type:['dessert'], dietary:['vegetarian'], health_tags:['energy'], occasion:['Narali Purnima'], season:['monsoon'], ingredients_main:['rice','coconut','jaggery','ghee','cardamom','cashew'], description:'Coconut sweet rice — Narali Purnima offering in Malvan, fishermen pray before monsoon fishing resumes' },
{ name:'Aappe Malvani', cuisine:['Malvani'], meal_type:['breakfast','snack'], dietary:['vegetarian'], health_tags:['probiotic'], occasion:['everyday'], season:['all'], ingredients_main:['rice flour','urad dal','coconut','jaggery'], description:'Sweet rice balls — Malvani round dumplings made in aappe mould, slightly sweet, festival and everyday' },
{ name:'Rava Fried Fish Malvani', cuisine:['Malvani'], meal_type:['snack','dinner'], dietary:['non-vegetarian','fish'], health_tags:['protein'], occasion:['everyday','party'], season:['all'], ingredients_main:['fish','semolina','Malvani masala','lemon','turmeric','oil'], description:'Semolina-crusted fried fish — Malvani party appetiser, thick crispy rava coating with red masala underneath' },
{ name:'Tawa Fish Malvani', cuisine:['Malvani'], meal_type:['dinner'], dietary:['non-vegetarian','fish'], health_tags:['protein','omega-3'], occasion:['everyday'], season:['all'], ingredients_main:['pomfret','Malvani masala','lemon','oil'], description:'Griddle-cooked whole pomfret — Malvani tawa style, whole fish seared with masala paste, smoky and charred' },
];

// ═══════════ MANGALOREAN (100+) ═══════════
export const MANGALOREAN_DISHES: DishSeed[] = [
{ name:'Kori Rotti', name_regional:'ಕೋರಿ ರೊಟ್ಟಿ', cuisine:['Mangalorean'], meal_type:['lunch','dinner'], dietary:['non-vegetarian','chicken'], health_tags:['protein','spicy'], occasion:['everyday','festive'], season:['all'], ingredients_main:['chicken','coconut','byadgi chilli','rice rotti','onion','tamarind'], description:'Chicken curry with crispy rice wafers — Mangalore signature, fiery red coconut curry poured over brittle rice rotti' },
{ name:'Chicken Ghee Roast', name_regional:'ಚಿಕನ್ ಘೀ ರೋಸ್ಟ್', cuisine:['Mangalorean'], meal_type:['dinner'], dietary:['non-vegetarian','chicken'], health_tags:['protein','rich'], occasion:['party','guest'], season:['all'], ingredients_main:['chicken','ghee','byadgi chilli','Kashmiri chilli','garlic','tamarind','coconut'], description:'Ghee-roasted chicken — Mangalore Bunt community invention, deeply red, roasted in ghee until caramelised' },
{ name:'Kane Fry', name_regional:'ಕಣೆ ಫ್ರೈ', cuisine:['Mangalorean'], meal_type:['snack','dinner'], dietary:['non-vegetarian','fish'], health_tags:['protein','omega-3'], occasion:['everyday'], season:['all'], ingredients_main:['ladyfish','semolina','turmeric','red chilli','salt','oil'], description:'Crispy fried ladyfish — Mangalore coast everyday fish, simple semolina coating, best eaten hot off the pan' },
{ name:'Bangude Masala Fry', cuisine:['Mangalorean'], meal_type:['dinner','snack'], dietary:['non-vegetarian','fish'], health_tags:['protein','omega-3'], occasion:['everyday'], season:['all'], ingredients_main:['mackerel','red chilli paste','tamarind','turmeric','oil'], description:'Masala-fried mackerel — Mangalorean daily fish, marinated in red chilli paste, pan-fried crispy' },
{ name:'Prawn Gassi', name_regional:'ಯೆಟ್ಟಿ ಗಸ್ಸಿ', cuisine:['Mangalorean'], meal_type:['lunch','dinner'], dietary:['non-vegetarian','fish'], health_tags:['protein','omega-3'], occasion:['everyday'], season:['all'], ingredients_main:['prawns','coconut','byadgi chilli','tamarind','onion','curry leaves'], description:'Prawns in coconut curry — Mangalore everyday gassi, thick red coconut gravy, the default seafood preparation' },
{ name:'Mutton Gassi', cuisine:['Mangalorean'], meal_type:['dinner'], dietary:['non-vegetarian','mutton'], health_tags:['protein','iron'], occasion:['weekend','festive'], season:['all'], ingredients_main:['mutton','coconut','byadgi chilli','whole spices','onion','tamarind'], description:'Mutton in Mangalorean spiced coconut gravy — richer than prawn gassi, weekend special' },
{ name:'Chicken Sukka', name_regional:'ಕೋರಿ ಸುಕ್ಕ', cuisine:['Mangalorean'], meal_type:['dinner'], dietary:['non-vegetarian','chicken'], health_tags:['protein'], occasion:['everyday','party'], season:['all'], ingredients_main:['chicken','coconut','byadgi chilli','pepper','curry leaves','onion'], description:'Dry chicken with roasted coconut — Mangalorean sukka (dry) style, crunchy coconut bits, bold spice' },
{ name:'Clam Sukka', cuisine:['Mangalorean'], meal_type:['dinner'], dietary:['non-vegetarian','fish'], health_tags:['protein','iron'], occasion:['monsoon'], season:['monsoon'], ingredients_main:['clams','coconut','red chilli','garlic','curry leaves'], description:'Dry clams with roasted coconut — monsoon Mangalorean preparation, tiny clams tossed in dry masala' },
{ name:'Crab Masala Mangalorean', cuisine:['Mangalorean'], meal_type:['dinner'], dietary:['non-vegetarian','fish'], health_tags:['protein'], occasion:['guest','festive'], season:['all'], ingredients_main:['crab','coconut','byadgi chilli','onion','garlic','tamarind'], description:'Whole crab in red coconut curry — messy, hands-on Mangalorean feast, cracking shells at the table' },
{ name:'Neer Dosa', name_regional:'ನೀರ ದೋಸೆ', cuisine:['Mangalorean'], meal_type:['breakfast'], dietary:['vegetarian'], health_tags:['light'], occasion:['everyday'], season:['all'], ingredients_main:['rice','coconut','water'], description:'Paper-thin water rice crepe — translucent Mangalorean delicacy, no fermentation needed, just rice and coconut' },
{ name:'Pathrode', name_regional:'ಪತ್ರೊಡೆ', cuisine:['Mangalorean'], meal_type:['snack','breakfast'], dietary:['vegetarian'], health_tags:['iron','fibre'], occasion:['everyday','monsoon'], season:['monsoon'], ingredients_main:['colocasia leaves','rice flour','coconut','jaggery','tamarind','red chilli'], description:'Spiced colocasia leaf rolls — Mangalorean version of patra, rice-coconut paste spread on leaves, steamed and sliced' },
{ name:'Dalitoy', name_regional:'ಡಾಲಿತೊಯ್', cuisine:['Mangalorean','GSB'], meal_type:['lunch','dinner'], dietary:['vegetarian'], health_tags:['protein','light'], occasion:['everyday'], season:['all'], ingredients_main:['toor dal','coconut','kokum','curry leaves','hing','ghee'], description:'GSB Brahmin dal — simplest Mangalorean lentil, thin consistency, kokum tang, everyday Saraswat comfort' },
{ name:'Kuvale Gassi', cuisine:['Mangalorean'], meal_type:['lunch'], dietary:['vegetarian'], health_tags:['fibre'], occasion:['everyday'], season:['summer'], ingredients_main:['ash gourd','coconut','byadgi chilli','tamarind','curry leaves'], description:'Ash gourd in coconut curry — Mangalorean vegetable gassi, mild and cooling, summer preparation' },
{ name:'Breadfruit Curry Mangalorean', cuisine:['Mangalorean'], meal_type:['lunch'], dietary:['vegetarian'], health_tags:['fibre','energy'], occasion:['everyday'], season:['monsoon'], ingredients_main:['breadfruit','coconut','red chilli','tamarind','curry leaves'], description:'Breadfruit in coconut gravy — seasonal Mangalorean preparation, starchy and filling, monsoon when breadfruit ripens' },
{ name:'Akki Rotti', name_regional:'ಅಕ್ಕಿ ರೊಟ್ಟಿ', cuisine:['Mangalorean','Karnataka'], meal_type:['breakfast'], dietary:['vegetarian'], health_tags:['fibre'], occasion:['everyday'], season:['all'], ingredients_main:['rice flour','onion','coconut','cumin','curry leaves','green chilli'], description:'Rice flour flatbread — Karnataka-Mangalore breakfast, studded with onion and coconut, crispy edges' },
{ name:'Mangalorean Biryani', cuisine:['Mangalorean'], meal_type:['lunch','dinner'], dietary:['non-vegetarian','chicken'], health_tags:['protein','energy'], occasion:['party','wedding'], season:['all'], ingredients_main:['chicken','basmati rice','coconut milk','fried onion','mint','whole spices'], description:'Mangalore biryani — coconut milk-based, different from Hyderabadi, milder and creamier' },
{ name:'Beary Biryani', cuisine:['Mangalorean'], meal_type:['lunch','dinner'], dietary:['non-vegetarian','chicken'], health_tags:['protein'], occasion:['wedding','Eid'], season:['all'], ingredients_main:['chicken','basmati rice','fried onion','mint','ghee','rose water','whole spices'], description:'Muslim Beary community biryani — Mangalore festive rice, rose water scented, Eid and wedding celebration' },
{ name:'Mangalorean Pork Bafat', cuisine:['Mangalorean'], meal_type:['dinner'], dietary:['non-vegetarian','pork'], health_tags:['protein'], occasion:['Christmas','Easter'], season:['winter'], ingredients_main:['pork','bafat powder','vinegar','onion','garlic','ginger'], description:'Mangalorean Catholic pork curry — bafat spice blend is unique to Mangalorean Christians, Christmas essential' },
{ name:'Ros Omelette Mangalorean', cuisine:['Mangalorean'], meal_type:['breakfast','snack'], dietary:['non-vegetarian','egg'], health_tags:['protein'], occasion:['street food','everyday'], season:['all'], ingredients_main:['eggs','onion','green chilli','red curry','pav'], description:'Omelette drenched in red curry — Mangalore street food legend, fluffy omelette swimming in spicy ros gravy with pav' },
{ name:'Sannas', cuisine:['Mangalorean'], meal_type:['breakfast','dinner'], dietary:['vegetarian'], health_tags:['probiotic'], occasion:['Christmas','everyday'], season:['all'], ingredients_main:['rice flour','coconut','toddy','sugar'], description:'Steamed rice cakes — Mangalorean Catholic bread, fermented with toddy, fluffy and slightly sweet, eaten with curry' },
{ name:'Alle Belle', cuisine:['Mangalorean'], meal_type:['dessert','snack'], dietary:['vegetarian'], health_tags:['energy'], occasion:['Christmas'], season:['all'], ingredients_main:['maida','coconut','jaggery','cardamom','ghee'], description:'Coconut-jaggery crepe — Mangalorean Catholic sweet, thin crepe rolled with coconut filling, Christmas treat' },
];

// ═══════════ GOAN (100+) ═══════════
export const GOAN_DISHES: DishSeed[] = [
{ name:'Goan Fish Curry Rice', name_regional:'Xitt Kodi', cuisine:['Goan'], meal_type:['lunch'], dietary:['non-vegetarian','fish'], health_tags:['protein','omega-3'], occasion:['everyday'], season:['all'], ingredients_main:['fish','coconut','kokum','red chilli','turmeric','tamarind','rice'], description:'The daily Goan meal — sour-spicy coconut fish curry over steamed rice, eaten in every Goan home regardless of religion' },
{ name:'Goan Prawn Curry', cuisine:['Goan'], meal_type:['lunch','dinner'], dietary:['non-vegetarian','fish'], health_tags:['protein','omega-3'], occasion:['everyday'], season:['all'], ingredients_main:['prawns','coconut','kokum','red chilli','turmeric','onion'], description:'Prawns in Goan coconut gravy — richer than fish curry, served for dinner when guests visit' },
{ name:'Chicken Xacuti', name_regional:'Xacuti', cuisine:['Goan'], meal_type:['lunch','dinner'], dietary:['non-vegetarian','chicken'], health_tags:['protein'], occasion:['everyday','festive'], season:['all'], ingredients_main:['chicken','coconut','poppy seeds','star anise','clove','onion','nutmeg'], description:'Chicken in complex spice gravy — Goan Hindu/Catholic shared dish, 20+ spice xacuti masala roasted fresh' },
{ name:'Chicken Cafreal', name_regional:'Cafreal', cuisine:['Goan'], meal_type:['dinner'], dietary:['non-vegetarian','chicken'], health_tags:['protein'], occasion:['party','Christmas'], season:['all'], ingredients_main:['chicken','coriander','green chilli','garlic','ginger','lime','cumin'], description:'Green masala chicken — Portuguese-Goan, bright green from coriander-chilli paste, pan-fried until charred' },
{ name:'Goan Vindaloo', name_regional:'Vindalho', cuisine:['Goan'], meal_type:['lunch','dinner'], dietary:['non-vegetarian','pork'], health_tags:['protein','spicy'], occasion:['Christmas','everyday'], season:['all'], ingredients_main:['pork','vinegar','Kashmiri chilli','garlic','ginger','whole spices','jaggery'], description:'The real Vindaloo — Portuguese-origin, vinegar-chilli-garlic marinated pork, NOT the British curry house version' },
{ name:'Goan Pork Ribs', cuisine:['Goan'], meal_type:['dinner'], dietary:['non-vegetarian','pork'], health_tags:['protein'], occasion:['Christmas','party'], season:['all'], ingredients_main:['pork ribs','vinegar','garlic','toddy','red chilli','whole spices'], description:'Slow-cooked Goan pork ribs — falling-off-the-bone tender, vinegar-marinated, Christmas Eve dinner' },
{ name:'Sorpotel', name_regional:'Sorpotel', cuisine:['Goan'], meal_type:['dinner'], dietary:['non-vegetarian','pork'], health_tags:['protein'], occasion:['Christmas','Easter'], season:['winter'], ingredients_main:['pork','liver','vinegar','toddy','red chilli','whole spices','onion'], description:'Pork and liver stew — Catholic Goan festival dish, improves over 3 days of reheating, Christmas feast essential' },
{ name:'Chourico Pulao', cuisine:['Goan'], meal_type:['lunch'], dietary:['non-vegetarian','pork'], health_tags:['protein','energy'], occasion:['festive','everyday'], season:['all'], ingredients_main:['Goan sausage','basmati rice','onion','garlic','vinegar','red chilli'], description:'Goan sausage rice — spiced chouriço cooked with rice, the one-pot Goan comfort meal' },
{ name:'Recheado Pomfret', name_regional:'Recheado', cuisine:['Goan'], meal_type:['dinner'], dietary:['non-vegetarian','fish'], health_tags:['protein','omega-3'], occasion:['party','guest'], season:['all'], ingredients_main:['pomfret','recheado masala','vinegar','garlic','ginger','red chilli'], description:'Stuffed whole pomfret — bright red recheado paste inside, pan-fried, Goan dinner party centrepiece' },
{ name:'Bangda Recheado', cuisine:['Goan'], meal_type:['dinner'], dietary:['non-vegetarian','fish'], health_tags:['protein','omega-3'], occasion:['everyday'], season:['all'], ingredients_main:['mackerel','recheado masala','vinegar','oil'], description:'Mackerel with recheado paste — everyday Goan fish, cheaper than pomfret but equally delicious with the red paste' },
{ name:'Ambot Tik', name_regional:'Ambot Tik', cuisine:['Goan'], meal_type:['lunch'], dietary:['non-vegetarian','fish'], health_tags:['protein'], occasion:['everyday'], season:['all'], ingredients_main:['shark','Kashmiri chilli','tamarind','onion','garlic','kokum'], description:'Sour-spicy shark curry — Goan Catholic preparation, tangy tamarind-kokum gravy, sharp and intense' },
{ name:'Goan Caldine', cuisine:['Goan'], meal_type:['lunch','dinner'], dietary:['non-vegetarian','fish'], health_tags:['protein','light'], occasion:['everyday'], season:['all'], ingredients_main:['fish','coconut milk','turmeric','green chilli','onion','ginger'], description:'Mild yellow coconut fish curry — the gentler Goan curry, turmeric-coconut milk base, comfort for the unwell' },
{ name:'Goan Prawn Balchao', name_regional:'Balchão', cuisine:['Goan'], meal_type:['condiment','dinner'], dietary:['non-vegetarian','fish'], health_tags:['protein'], occasion:['everyday'], season:['all'], ingredients_main:['dried prawns','vinegar','red chilli','garlic','sugar','onion'], description:'Prawn pickle-curry hybrid — spicy, sweet, sour Goan preservation technique, lasts for months, a condiment and main dish' },
{ name:'Kismur', cuisine:['Goan'], meal_type:['snack','condiment'], dietary:['non-vegetarian','fish'], health_tags:['protein'], occasion:['everyday'], season:['all'], ingredients_main:['dried prawns','coconut','onion','green chilli','lime'], description:'Dried prawn salad — Goan cold salad, shredded dried prawns with coconut and onion, unique texture and flavour' },
{ name:'Goan Saraswat Fish Curry', cuisine:['Goan'], meal_type:['lunch'], dietary:['non-vegetarian','fish'], health_tags:['protein','omega-3'], occasion:['everyday'], season:['all'], ingredients_main:['fish','coconut','kokum','green chilli','hing','curry leaves'], description:'GSB Saraswat fish curry — Goan Hindu version, no onion-garlic, kokum and hing for flavour, subtler than Catholic curry' },
{ name:'Bebinca', name_regional:'Bebinca', cuisine:['Goan'], meal_type:['dessert'], dietary:['vegetarian'], health_tags:['rich','celebration'], occasion:['Christmas','wedding'], season:['all'], ingredients_main:['coconut milk','egg yolk','sugar','ghee','nutmeg','maida'], description:'Seven-layer Goan pudding — each layer baked individually under fire, Christmas dessert queen, hours to make' },
{ name:'Dodol', cuisine:['Goan'], meal_type:['dessert'], dietary:['vegetarian'], health_tags:['energy'], occasion:['Christmas'], season:['all'], ingredients_main:['rice flour','coconut milk','jaggery','cashew','cardamom'], description:'Dense coconut-jaggery fudge — Goan Christmas sweet, takes 6+ hours of continuous stirring' },
{ name:'Neureos', cuisine:['Goan'], meal_type:['dessert'], dietary:['vegetarian'], health_tags:['celebration'], occasion:['Christmas','Diwali'], season:['all'], ingredients_main:['maida','coconut','sugar','semolina','cardamom','ghee'], description:'Goan sweet pastry — crescent-shaped fried dumpling with coconut-semolina filling, Diwali and Christmas' },
{ name:'Bolinhas', cuisine:['Goan'], meal_type:['dessert','snack'], dietary:['vegetarian'], health_tags:['energy'], occasion:['Christmas'], season:['all'], ingredients_main:['coconut','semolina','sugar','ghee','cardamom','cashew'], description:'Coconut cookies — Goan Christmas baking tradition, crumbly coconut-semolina rounds' },
{ name:'Goan Poi', cuisine:['Goan'], meal_type:['breakfast'], dietary:['vegetarian'], health_tags:['energy'], occasion:['everyday'], season:['all'], ingredients_main:['wheat flour','toddy','sugar','salt'], description:'Goan crusty bread — fermented with palm toddy, the daily bread of Goa, eaten with curry or xacuti' },
{ name:'Sanna Kodi', cuisine:['Goan'], meal_type:['breakfast','dinner'], dietary:['non-vegetarian','chicken'], health_tags:['protein'], occasion:['everyday'], season:['all'], ingredients_main:['rice flour','coconut','toddy','chicken','coconut','red chilli'], description:'Steamed rice cakes with chicken curry — Goan breakfast or dinner, fluffy sannas soaking up spicy kodi' },
{ name:'Ros Omelette Goan', cuisine:['Goan'], meal_type:['breakfast','snack'], dietary:['non-vegetarian','egg'], health_tags:['protein'], occasion:['street food'], season:['all'], ingredients_main:['eggs','onion','green chilli','red curry','pav'], description:'Omelette in red curry with bread — Goan street food, fluffy omelette swimming in coconut-chilli ros' },
{ name:'Tambdi Bhaji', cuisine:['Goan'], meal_type:['lunch'], dietary:['vegetarian'], health_tags:['iron'], occasion:['everyday'], season:['monsoon'], ingredients_main:['red amaranth','garlic','coconut','onion'], description:'Red amaranth leaves — Goan monsoon green, cooked with coconut and garlic, iron-rich, eaten with rice' },
{ name:'Valache Birde', cuisine:['Goan'], meal_type:['lunch'], dietary:['vegetarian'], health_tags:['protein','fibre'], occasion:['everyday'], season:['monsoon'], ingredients_main:['field beans','coconut','red chilli','tamarind','onion'], description:'Field bean curry — Goan monsoon preparation, earthy and filling, served with rice' },
{ name:'Goan Dal', cuisine:['Goan'], meal_type:['lunch','dinner'], dietary:['vegetarian'], health_tags:['protein'], occasion:['everyday'], season:['all'], ingredients_main:['toor dal','kokum','coconut','garlic','cumin','mustard seeds'], description:'Goan-style lentils — kokum and coconut distinguish it from North Indian dal, everyday accompaniment' },
{ name:'Butter Garlic Crab Goan', cuisine:['Goan'], meal_type:['dinner'], dietary:['non-vegetarian','fish'], health_tags:['protein'], occasion:['party','guest'], season:['all'], ingredients_main:['crab','butter','garlic','pepper','lime','coriander'], description:'Butter-garlic crab — Goan beach shack classic, whole crabs tossed in butter-garlic-pepper, messy and magnificent' },
{ name:'Goan Mackerel Recheado', cuisine:['Goan'], meal_type:['dinner'], dietary:['non-vegetarian','fish'], health_tags:['protein','omega-3'], occasion:['everyday'], season:['all'], ingredients_main:['mackerel','recheado masala','vinegar','oil'], description:'Whole mackerel with red masala — everyday Goan fish, slit and stuffed with recheado paste, pan-fried' },
{ name:'Tisreo Masala Goan', cuisine:['Goan'], meal_type:['dinner'], dietary:['non-vegetarian','fish'], health_tags:['protein','iron'], occasion:['monsoon'], season:['monsoon'], ingredients_main:['clams','coconut','garlic','red chilli','onion','kokum'], description:'Goan clam masala — monsoon when clams are abundant, coconut-kokum gravy, eaten with poi bread' },
{ name:'Goan Chicken Piri Piri', cuisine:['Goan'], meal_type:['dinner','snack'], dietary:['non-vegetarian','chicken'], health_tags:['protein','spicy'], occasion:['party'], season:['all'], ingredients_main:['chicken','piri piri sauce','garlic','lime','butter','red chilli'], description:'Portuguese-Goan spicy chicken — piri piri chilli marinade, grilled or pan-fried, sharp lime-chilli heat' },
];
