import { PDFDocument, rgb, StandardFonts } from 'pdf-lib';

function truncate(text, max) {
  if (!text) return '';
  return text.length > max ? text.substring(0, max - 1) + '\u2026' : text;
}

export default async function handler(req, res) {
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'POST, OPTIONS');
  res.setHeader('Access-Control-Allow-Headers', 'Content-Type');
  if (req.method === 'OPTIONS') { res.status(200).end(); return; }
  if (req.method !== 'POST') { res.status(405).json({ error: 'Method not allowed' }); return; }

  try {
    const { type, familyName, dateRange, content, language } = req.body;

    const labels = {
      en: { ingredients: 'INGREDIENTS', method: 'METHOD' },
      hi: { ingredients: 'सामग्री', method: 'विधि' },
      mr: { ingredients: 'साहित्य', method: 'कृती' },
      gu: { ingredients: 'સામગ્રી', method: 'પ્રક્રિયા' },
      ta: { ingredients: 'பொருட்கள்', method: 'முறை' },
      ml: { ingredients: 'ചേരുവകൾ', method: 'രീതി' },
    };
    const L = labels[language] || labels['en'];

    const pdfDoc = await PDFDocument.create();
    const boldFont = await pdfDoc.embedFont(StandardFonts.HelveticaBold);
    const regularFont = await pdfDoc.embedFont(StandardFonts.Helvetica);

    function addPage() {
      const page = pdfDoc.addPage([595, 842]);
      const { width, height } = page.getSize();

      // Navy header rectangle
      page.drawRectangle({ x: 0, y: height - 60, width, height: 60, color: rgb(0.102, 0.227, 0.361) });

      // Title
      page.drawText(`My Maharaj ${type || 'Document'}`, {
        x: 20, y: height - 24, size: 13, font: boldFont, color: rgb(1, 1, 1)
      });

      // Subtitle (family + date)
      if (familyName || dateRange) {
        page.drawText(truncate(`for ${familyName || ''} \u2014 ${dateRange || ''}`, 80), {
          x: 20, y: height - 44, size: 9, font: regularFont, color: rgb(0.788, 0.635, 0.153)
        });
      }

      // Footer
      page.drawText('Generated by My Maharaj | my-maharaj.vercel.app', {
        x: 20, y: 18, size: 7, font: regularFont, color: rgb(0.6, 0.6, 0.6)
      });

      return { page, width, height };
    }

    let { page, height } = addPage();
    let yPosition = height - 76;
    const lineH = 17;

    function ensureSpace(lines = 1) {
      if (yPosition - (lines * lineH) < 40) {
        const added = addPage();
        page = added.page;
        height = added.height;
        yPosition = height - 76;
      }
    }

    // ── Meal Plan ──────────────────────────────────────────────────────────
    if (type === 'Meal Plan' && content?.days) {
      for (const day of content.days) {
        ensureSpace(2);
        page.drawText(truncate(`${day.dayName}, ${day.date}`, 60), {
          x: 20, y: yPosition, size: 11, font: boldFont, color: rgb(0.102, 0.227, 0.361)
        });
        yPosition -= lineH;

        const meals = (day.meals || []).filter(m => m.dish && m.dish.trim());
        for (const meal of meals) {
          ensureSpace(1);
          page.drawText(truncate(`  ${meal.label}: ${meal.dish}`, 80), {
            x: 20, y: yPosition, size: 9, font: regularFont, color: rgb(0.2, 0.2, 0.2)
          });
          yPosition -= lineH - 4;
        }
        yPosition -= 8;
      }
    }

    // ── Shopping List ──────────────────────────────────────────────────────
    if (type === 'Shopping List' && content?.categories) {
      for (const category of content.categories) {
        ensureSpace(2);
        page.drawText(category.name || '', {
          x: 20, y: yPosition, size: 11, font: boldFont, color: rgb(0.102, 0.42, 0.36)
        });
        yPosition -= lineH;

        const items = category.items || [];
        for (const item of items) {
          ensureSpace(1);
          const qty = item.quantity ? `${item.quantity}${item.unit ? ' ' + item.unit : ''}` : '';
          const label = qty ? `${qty} ${item.name}` : item.name;
          page.drawText(truncate(`  \u2022 ${label}`, 75), {
            x: 20, y: yPosition, size: 9, font: regularFont, color: rgb(0.2, 0.2, 0.2)
          });
          yPosition -= lineH - 4;
        }
        yPosition -= 8;
      }
    }

    // ── Recipe ─────────────────────────────────────────────────────────────
    if (type === 'Recipe') {
      ensureSpace(2);
      page.drawText(truncate(content?.recipeName || 'Recipe', 60), {
        x: 20, y: yPosition, size: 14, font: boldFont, color: rgb(0.102, 0.227, 0.361)
      });
      yPosition -= lineH * 1.8;

      if (content?.ingredients?.length) {
        ensureSpace(2);
        page.drawText(L.ingredients, {
          x: 20, y: yPosition, size: 10, font: boldFont, color: rgb(0.102, 0.42, 0.36)
        });
        yPosition -= lineH;

        for (const ing of content.ingredients) {
          ensureSpace(1);
          const text = typeof ing === 'string' ? ing : `${ing.quantity || ''} ${ing.unit || ''} ${ing.item || ''}`.trim();
          page.drawText(truncate(`  \u2022 ${text}`, 80), {
            x: 20, y: yPosition, size: 9, font: regularFont, color: rgb(0.2, 0.2, 0.2)
          });
          yPosition -= lineH - 4;
        }
        yPosition -= 8;
      }

      if (content?.method?.length) {
        ensureSpace(2);
        page.drawText(L.method, {
          x: 20, y: yPosition, size: 10, font: boldFont, color: rgb(0.102, 0.42, 0.36)
        });
        yPosition -= lineH;

        content.method.forEach((step, i) => {
          ensureSpace(1);
          page.drawText(truncate(`${i + 1}. ${step}`, 80), {
            x: 20, y: yPosition, size: 9, font: regularFont, color: rgb(0.2, 0.2, 0.2)
          });
          yPosition -= lineH;
        });
      }

      if (content?.maharajNote) {
        ensureSpace(2);
        yPosition -= 6;
        page.drawText(truncate(`Maharaj\u2019s tip: ${content.maharajNote}`, 80), {
          x: 20, y: yPosition, size: 9, font: regularFont, color: rgb(0.56, 0.42, 0.08)
        });
      }
    }

    const pdfBytes = await pdfDoc.save();
    const safeType = (type || 'document').toLowerCase().replace(/\s+/g, '-');

    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader('Content-Disposition', `attachment; filename="${safeType}.pdf"`);
    res.status(200).send(Buffer.from(pdfBytes));
  } catch (err) {
    console.error('PDF generation error:', err);
    res.status(500).json({ error: 'PDF generation failed', detail: String(err) });
  }
}
