import type { VercelRequest, VercelResponse } from '@vercel/node';

export default function handler(req: VercelRequest, res: VercelResponse) {
  if (req.method !== 'POST') {
    return res.status(405).json({ error: 'Method not allowed' });
  }

  const { menu, eventDetails, shoppingList } = req.body;
  const html = generateOutdoorHTML(menu, eventDetails, shoppingList);

  res.setHeader('Content-Type', 'text/html');
  res.setHeader('Content-Disposition', 'inline; filename=outdoor-menu.html');
  res.status(200).send(html);
}

function generateOutdoorHTML(menu: any, eventDetails: any, shoppingList: any[]) {
  const { eventType, guests, foodType, budget, setup, weather, includeAlcohol } = eventDetails;

  const renderItems = (items: any[]) => (items || []).map((item: any) => `
    <div class="item"><div class="item-name">${item.name}</div><div class="item-desc">${item.description}</div></div>
  `).join('');

  const renderShopCategories = (cats: any[]) => (cats || []).map((cat: any) => `
    <div class="shop-section">
      <div class="shop-section-title">${cat.title}</div>
      <div class="shop-grid">${(cat.items || []).map((item: string) => `<span class="shop-chip">${item}</span>`).join('')}</div>
    </div>
  `).join('');

  const renderTips = (tips: string[]) => (tips || []).map((t: string) => `<div class="tip-item">&bull; ${t}</div>`).join('');

  const qrSvg = `<svg width="50" height="50" viewBox="0 0 52 52" xmlns="http://www.w3.org/2000/svg"><rect width="52" height="52" fill="white"/><rect x="2" y="2" width="20" height="20" rx="2" fill="#1A6B3C"/><rect x="5" y="5" width="14" height="14" rx="1" fill="white"/><rect x="8" y="8" width="8" height="8" fill="#1A6B3C"/><rect x="30" y="2" width="20" height="20" rx="2" fill="#1A6B3C"/><rect x="33" y="5" width="14" height="14" rx="1" fill="white"/><rect x="36" y="8" width="8" height="8" fill="#1A6B3C"/><rect x="2" y="30" width="20" height="20" rx="2" fill="#1A6B3C"/><rect x="5" y="33" width="14" height="14" rx="1" fill="white"/><rect x="8" y="36" width="8" height="8" fill="#1A6B3C"/></svg>`;

  const headerBlock = `<div class="header"><div class="spacer"></div><div class="header-center"><div class="logo-box"><span class="logo-text">My Maharaj</span></div><div class="logo-sub">by Blue Flute Consulting LLC-FZ</div><div class="website">www.bluefluteconsulting.com</div></div><div class="qr-box">${qrSvg}<div class="qr-label">Scan to visit</div></div></div>`;

  const footerBlock = `<div class="footer"><div class="footer-l">Generated by My Maharaj &middot; my-maharaj.vercel.app &middot; Strictly for personal use</div><div class="footer-r">Blue Flute Consulting LLC-FZ</div></div>`;

  return `<!DOCTYPE html><html><head><meta charset="UTF-8"><title>Outdoor Catering Menu — My Maharaj</title>
<style>
*{margin:0;padding:0;box-sizing:border-box}body{font-family:Arial,sans-serif;background:#F0FDF4}
@media print{.page{page-break-after:always}.page:last-child{page-break-after:avoid}.no-print{display:none}}
.page{width:210mm;min-height:297mm;margin:0 auto 20px;background:#F0FDF4;display:flex;flex-direction:column}
.header{background:#1A6B3C;padding:16px 24px;display:flex;align-items:flex-start;justify-content:space-between}.header-center{flex:1;text-align:center}
.logo-box{display:inline-block;background:white;border-radius:8px;padding:4px 16px;margin-bottom:4px}.logo-text{font-size:18px;font-weight:bold;color:#1A6B3C}
.logo-sub{font-size:9px;color:rgba(255,255,255,0.6);margin-top:2px}.website{font-size:10px;color:#C9A227;font-weight:bold;margin-top:3px}.spacer{width:60px;flex-shrink:0}
.qr-box{width:60px;height:60px;background:white;border-radius:6px;display:flex;flex-direction:column;align-items:center;justify-content:center;flex-shrink:0;padding:4px}.qr-label{font-size:7px;color:#1A6B3C;font-weight:bold;text-align:center;margin-top:2px}
.event-bar{background:#C9A227;padding:10px 24px;text-align:center}.event-title{font-size:18px;font-weight:bold;color:#1B2A0C}.event-meta{font-size:11px;color:#412402;margin-top:2px}
.body{padding:16px 24px;flex:1}.two-col{display:grid;grid-template-columns:1fr 1fr;gap:14px}
.card{background:rgba(255,255,255,0.88);border:0.5px solid rgba(26,107,60,0.12);border-radius:10px;overflow:hidden;margin-bottom:10px}
.card-header{background:#1A6B3C;padding:5px 12px;font-size:11px;font-weight:bold;color:white;letter-spacing:0.4px}.card-body{padding:8px 12px}
.item{padding:4px 0;border-bottom:0.5px solid rgba(26,107,60,0.08)}.item:last-child{border-bottom:none}.item-name{font-size:12px;font-weight:bold;color:#1A6B3C}.item-desc{font-size:10px;color:#555;margin-top:1px;line-height:1.4}
.tips-card{background:rgba(255,251,235,0.9);border:0.5px solid rgba(201,162,39,0.3);border-radius:10px;padding:12px;margin-top:10px}.tips-title{font-size:11px;font-weight:bold;color:#92400E;margin-bottom:6px}.tip-item{font-size:10px;color:#78350F;line-height:1.6;margin-bottom:2px}
.footer{background:#1A6B3C;padding:8px 24px;display:flex;justify-content:space-between;align-items:center;margin-top:auto}.footer-l{font-size:9px;color:rgba(255,255,255,0.5)}.footer-r{font-size:9px;color:#C9A227;font-weight:bold}
.shop-body{padding:20px 24px;flex:1}.shop-section{margin-bottom:14px}.shop-section-title{font-size:11px;font-weight:bold;color:#1A6B3C;letter-spacing:0.5px;margin-bottom:8px;padding-bottom:4px;border-bottom:1.5px solid #1A6B3C}
.shop-grid{display:flex;flex-wrap:wrap;gap:6px}.shop-chip{background:white;border:0.5px solid rgba(26,107,60,0.15);border-radius:20px;padding:4px 12px;font-size:11px;color:#1A6B3C}
.note-box{background:rgba(201,162,39,0.1);border:0.5px solid rgba(201,162,39,0.3);border-radius:8px;padding:10px 14px;margin-top:16px}.note-txt{font-size:11px;color:#854F0B;line-height:1.6}
.print-btn{display:block;margin:20px auto;padding:12px 40px;background:#1A6B3C;color:white;border:none;border-radius:10px;font-size:15px;font-weight:bold;cursor:pointer}
</style>
<script>window.onload=function(){window.print();}</script>
</head><body>
<button class="print-btn no-print" onclick="window.print()">Print / Save as PDF</button>
<div class="page">
${headerBlock}
<div class="event-bar"><div class="event-title">${eventType} Menu</div><div class="event-meta">${guests} guests &middot; ${foodType} &middot; ${setup} &middot; AED ${budget}/head${includeAlcohol ? ' &middot; Alcoholic available' : ''} &middot; ${weather}</div></div>
<div class="body"><div class="two-col">
<div><div class="card"><div class="card-header">Starters</div><div class="card-body">${renderItems(menu.starters)}</div></div><div class="card"><div class="card-header">Main Course</div><div class="card-body">${renderItems(menu.main_course)}</div></div></div>
<div><div class="card"><div class="card-header">Desserts</div><div class="card-body">${renderItems(menu.desserts)}</div></div><div class="card"><div class="card-header">Beverages</div><div class="card-body">${renderItems(menu.beverages)}<div class="item"><div class="item-name">Mineral Water</div><div class="item-desc">Still and sparkling — essential for outdoors</div></div></div></div></div>
</div>${menu.packing_tips?.length ? `<div class="tips-card"><div class="tips-title">Packing &amp; Serving Tips</div>${renderTips(menu.packing_tips)}</div>` : ''}</div>
${footerBlock}
</div>
<div class="page">
${headerBlock}
<div class="event-bar"><div class="event-title">Shopping List</div><div class="event-meta">${eventType} &middot; ${guests} guests &middot; AED ${budget}/head</div></div>
<div class="shop-body">${renderShopCategories(shoppingList)}<div class="note-box"><div class="note-txt">Tip from Maharaj: For outdoor events, pack food in insulated containers. Buy ice packs separately. Fresh produce should be prepped the morning of the event.</div></div></div>
${footerBlock}
</div>
</body></html>`;
}
