const { createClient } = require('@supabase/supabase-js');

module.exports = async function handler(req, res) {
  if (req.method !== 'POST') return res.status(405).end();

  const { title, content, language } = req.body;
  const days = content?.days ?? [];

  const html = `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>My Maharaj Meal Plan</title>
<style>
  @media print { .no-print { display: none; } body { margin: 0; } }
  body { font-family: system-ui, -apple-system, 'Segoe UI', sans-serif; margin: 0; padding: 20px; background: #fff; color: #1b3a5c; }
  .header { background: #1b3a5c; color: white; padding: 16px 20px; margin-bottom: 20px; border-radius: 8px; }
  .header h1 { margin: 0; font-size: 20px; font-weight: 600; }
  .header p { margin: 4px 0 0; font-size: 13px; color: rgba(255,255,255,0.7); }
  .print-btn { background: #1a6b5c; color: white; border: none; padding: 10px 24px; border-radius: 8px; font-size: 14px; cursor: pointer; margin-bottom: 20px; }
  table { width: 100%; border-collapse: collapse; font-size: 13px; }
  th { background: #1b3a5c; color: white; padding: 10px 12px; text-align: left; font-weight: 500; }
  td { padding: 8px 12px; border-bottom: 0.5px solid #e0e0e0; vertical-align: top; }
  tr:nth-child(even) td { background: #f8f9fa; }
  .day-header td { background: #c9a227; color: #1a1a1a; font-weight: 600; font-size: 13px; }
  .meal-label { font-size: 10px; color: #888; text-transform: uppercase; letter-spacing: 0.5px; display: block; margin-bottom: 2px; }
  .meal-dish { font-size: 13px; color: #1b3a5c; }
  .footer { margin-top: 20px; font-size: 11px; color: #aaa; text-align: center; }
</style>
</head>
<body>
<div class="header">
  <h1>My Maharaj Meal Plan</h1>
  <p>for Your Family</p>
</div>
<button class="print-btn no-print" onclick="window.print()">Print / Save as PDF</button>
<table>
  <thead>
    <tr>
      <th style="width:12%">Day</th>
      <th style="width:16%">Breakfast</th>
      <th style="width:18%">Lunch</th>
      <th style="width:18%">Dinner</th>
      <th style="width:18%">Supporting</th>
      <th style="width:18%">Evening</th>
    </tr>
  </thead>
  <tbody>
    ${days.map(day => {
      const meals = day.meals || [];
      const get = (label) => meals.find(m => m.label?.toLowerCase().includes(label.toLowerCase()))?.dish || '';
      const breakfast = get('Breakfast');
      const lunchCurries = meals.filter(m => m.label?.toLowerCase().includes('lunch curry')).map(m => m.dish).filter(Boolean).join(' + ');
      const dinnerCurries = meals.filter(m => m.label?.toLowerCase().includes('dinner curry')).map(m => m.dish).filter(Boolean).join(' + ');
      const lunchVeg = get('Lunch Veg');
      const lunchRaita = get('Lunch Raita');
      const lunchBread = get('Lunch Bread');
      const lunchRice = get('Lunch Rice');
      const dinnerVeg = get('Dinner Veg');
      const dinnerRaita = get('Dinner Raita');
      const dinnerBread = get('Dinner Bread');
      const dinnerRice = get('Dinner Rice');
      const snack = get('Snack');
      return `
        <tr class="day-header"><td colspan="6">${day.dayName || ''}</td></tr>
        <tr>
          <td></td>
          <td><span class="meal-label">Breakfast</span><span class="meal-dish">${breakfast}</span></td>
          <td><span class="meal-label">Curry</span><span class="meal-dish">${lunchCurries}</span></td>
          <td><span class="meal-label">Curry</span><span class="meal-dish">${dinnerCurries}</span></td>
          <td>
            <span class="meal-label">Veg</span><span class="meal-dish">${lunchVeg}</span><br>
            <span class="meal-label" style="margin-top:4px">Raita</span><span class="meal-dish">${lunchRaita}</span><br>
            <span class="meal-label" style="margin-top:4px">Bread</span><span class="meal-dish">${lunchBread}</span><br>
            <span class="meal-label" style="margin-top:4px">Rice</span><span class="meal-dish">${lunchRice}</span>
          </td>
          <td><span class="meal-label">Snack</span><span class="meal-dish">${snack}</span></td>
        </tr>`;
    }).join('')}
  </tbody>
</table>
<div class="footer">Generated by My Maharaj · Blue Flute Consulting LLC-FZ · Dubai</div>
</body>
</html>`;

  res.setHeader('Content-Type', 'text/html; charset=utf-8');
  return res.send(html);
};
