import type { VercelRequest, VercelResponse } from '@vercel/node';

export default async function handler(req: VercelRequest, res: VercelResponse) {
  if (req.method !== 'POST') return res.status(405).end();

  const { email, planData, weekLabel } = req.body;

  try {
    // Resend integration — requires RESEND_API_KEY env var
    const { Resend } = await import('resend');
    const resend = new Resend(process.env.RESEND_API_KEY);

    const html = generateWeeklyPlanHTML(planData, weekLabel);

    await resend.emails.send({
      from: 'Maharaj <maharaj@bluefluteconsulting.com>',
      to: email,
      subject: `Your Weekly Meal Plan — ${weekLabel}`,
      html,
    });

    return res.status(200).json({ success: true });
  } catch (err) {
    console.error('[SendWeeklyPDF] Error:', err);
    return res.status(500).json({ error: String(err) });
  }
}

function generateWeeklyPlanHTML(planData: any[], weekLabel: string) {
  const dayHeaders = (planData || []).map((d: any) => `<th>${d.day?.substring(0, 3) || ''}<br>${d.date || ''}</th>`).join('');
  const mealRow = (slot: string) => (planData || []).map((d: any) => `<td>${d[slot]?.options?.[0]?.name || '-'}</td>`).join('');

  return `<!DOCTYPE html><html><head><meta charset="UTF-8"><title>Weekly Meal Plan — My Maharaj</title>
<style>body{font-family:Arial,sans-serif;background:#F0F4F8;margin:0;padding:20px}
.header{background:#1B3A5C;padding:20px;text-align:center;border-radius:12px 12px 0 0}
.logo{background:white;display:inline-block;padding:6px 20px;border-radius:8px;font-size:20px;font-weight:bold;color:#1B3A5C}
.website{color:#C9A227;font-size:12px;margin-top:6px}
.week-bar{background:#C9A227;padding:10px;text-align:center;font-size:16px;font-weight:bold;color:#1B2A0C}
table{width:100%;border-collapse:collapse;background:white}
th{background:#1B3A5C;color:white;padding:10px;text-align:center;font-size:13px}
td{padding:10px;text-align:center;border:1px solid #E5E7EB;font-size:12px}
tr:nth-child(even){background:#F8F9FA}
.footer{background:#1B3A5C;padding:10px 20px;display:flex;justify-content:space-between;border-radius:0 0 12px 12px}
.footer-l{color:rgba(255,255,255,0.5);font-size:10px}.footer-r{color:#C9A227;font-size:10px;font-weight:bold}
</style></head><body>
<div class="header"><div class="logo">My Maharaj</div><div class="website">www.bluefluteconsulting.com</div></div>
<div class="week-bar">Weekly Meal Plan — ${weekLabel}</div>
<table><tr><th>Meal</th>${dayHeaders}</tr>
<tr><td><strong>Breakfast</strong></td>${mealRow('breakfast')}</tr>
<tr><td><strong>Lunch</strong></td>${mealRow('lunch')}</tr>
<tr><td><strong>Snack</strong></td>${mealRow('snack')}</tr>
<tr><td><strong>Dinner</strong></td>${mealRow('dinner')}</tr></table>
<div class="footer"><span class="footer-l">Generated by My Maharaj &middot; my-maharaj.vercel.app</span><span class="footer-r">Blue Flute Consulting LLC-FZ</span></div>
</body></html>`;
}
